///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Overview

== Overview

A typical Coherence deployment contains custom application code that runs with Coherence.
To run custom application code in a `Coherence` resource that code needs to be packaged into an image that the
deployment will use.

=== Building and Deploying Applications

[PILLARS]
====
[CARD]
.Build Custom Application Images
[link=docs/applications/020_build_application.adoc]
--
Building custom Coherence application images for use with the Coherence Operator.
--

[CARD]
.Deploy Custom Application Images
[link=docs/applications/030_deploy_application.adoc]
--
Deploying custom application images using the Coherence Operator.
--
====

=== Configuring Applications

There are many settings in a `Coherence` resource that control the behaviour of Coherence, the JVM and
the application code. Some of the application specific settings are shown below:

[PILLARS]
====
[CARD]
.Setting the Classpath
[link=docs/jvm/020_classpath.adoc]
--
Setting a custom classpath for the application.
--

[CARD]
.Setting a Main Class
[link=docs/applications/040_application_main.adoc]
--
Setting a custom main class to run.
--

[CARD]
.Setting Application Arguments
[link=docs/applications/050_application_args.adoc]
--
Setting arguments to pass to the main class.
--

[CARD]
.Working Directory
[link=docs/applications/060_application_working_dir.adoc]
--
Setting the application's working directory.
--
====
