///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Build Application Images

== Build Custom Application Images

To deploy a Coherence application using the operator the application code must be packaged into an image that the
Coherence container in the Pods will run. This image can be any image that contains a JVM as well as the application's
jar files, including obviously `coherence.jar`.

There are many ways to build an image for a Java application so it would be of little value to document the exact steps
for one of them here that might turn out to be used by very few people. One of the simplest ways to build a Java image
is to use https://github.com/GoogleContainerTools/jib/blob/master/README.md[JIB].
The Operator supports JIB images automatically but any image that meets the requirements of having a JVM and `coherence.jar`
will be supported. Any version of Java which works with the version of `coherence.jar` in the image will be suitable.
This can be a JRE, it does not need to be a full JDK.

At a bare minimum the directories in an image might look like this example
(obviously there would be more O/S related files and more JVM files, but they are not relevant for the example):
[source]
----
/
|-- app
|    |-- libs                      <1>
|         |-- application.jar
|         |-- coherence.jar
|-- usr
     |-- bin
     |    |-- java                 <2>
     |
     |-- lib
          |-- jvm
               |-- java-11-openjdk <3>
----
<1> The `/app/libs` directory contains the application jar files. This will be the classpath used to run the application.
<2> The `/usr/bin/java` file is the Java executable and on the `PATH` in the image (this would be a link to the actual
Java executable location, in this example to `/usr/lib/jvm/java-11-openjdk/bin/java`.
<3> The `/usr/lib/jvm/java-11-openjdk/` is the actual JVM install location.

=== Image `EntryPoint` - What Does the Operator Run?

The image does not need to have an `EntryPoint` or command specified, it does not need to actually be executable.
If the image does have an `EntryPoint`, it will just be ignored.

The Coherence Operator actually injects its own `runner` executable into the container which the container runs and which
in turn builds the Java command line to execute. The `runner` process looks at arguments and environment variables configured
for the Coherence container and from these constructs a Java comamnd line that it then executes.

The default command might look something like this:
[source,bash]
----
java -cp `/app/resources:/app/classes:/app/libs/*` \
    <JVM args> \
    <System Properties> \
    com.tangosol.net.DefaultCacheServer
----
The `runner` will work out the JVM's classpath, args and system properties to add to the command line
and execute the main class `com.tangosol.net.DefaultCacheServer`.
All these are configurable in the `Coherence` resource spec.

=== Optional `CLASSPATH` Environment Variable

If the `CLASSPATH` environment variable has been set in an image that classpath will be used when running the Coherence
container. Other elements may also be added to the classpath depending on the configuration of the `Coherence` resource.

=== Setting the Classpath

An application image contains `.jar` files (at least `coherence.jar`), possibly Java class files, also possibly
other ad-hoc files, all of which need to be on the application's classpath.
There are certain classpath values that the operator supports out of the box without needing any extra configuration,
but for occasions where the location of files in the image does not match the defaults a classpath can be specified.

Images built with https://github.com/GoogleContainerTools/jib/blob/master/README.md[JIB]
have a default classpath of `/app/resources:/app/classes:/app/libs/*`.
When the Coherence container starts if the directories `/app/resources`, `/app/classes` or `/app/libs/` exist in the
image they will automatically be added to the classpath of the JVM. In this way the Operator supports standard JIB
images without requiring additional configuration.

If the image is not a JIB image, or is a JIB image without the standard classpath but one or more of the
`/app/resources`, `/app/classes` or `/app/libs/` directories exist they will still be added to the classpath.
This may be desired or in some cases it may cause issues. It is possible to disable automatically adding these
directories in the `Coherence` resource spec by setting the `jvm.useJibClasspath` field to `false` (the default
value of the field is `true`).

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    useJibClasspath: false  # <1>
----
<1> The `useJibClasspath` is set to `false`. Even if any of the the `/app/resources`, `/app/classes` or `/app/libs/`
directories exist in the image they will not be added to the classpath.

If the image is not a JIB image, or is a JIB image without the standard classpath, then additional classpath entries
can be configured as described in the <<jvm/020_classpath.adoc,setting the classpath>> documentation.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    classpath:          # <1>
      - "/data/libs/*"  # <2>
      - "/data/config"
----
<1> The `jvm.classpath` field will be used to add additional items to the classpath, the field is a list of strings.
<2> Each entry in the `jvm.classpath` will be appended to the classpath exactly as it is declared, so in this case
the classpath will be `/data/libs/*:/data/config`


=== Optional `JAVA_HOME` Environment Variable

The `JAVA_HOME` environment variable does not have to be set in the image. If it is set the JVM at that location will
be used to run the application. If it is not set then the `java` executable *must* be on the `PATH` in the image.


=== Optional `COHERENCE_HOME` Environment Variable

The `COHERENCE_HOME` environment variable does not have to be set in an image.
Typically, all the jar files, including `coherence.jar` would be packaged into a single directory which is then used as
the classpath.
It is possible to run official Coherence images published by Oracle, which have `COHERENCE_HOME` set, which is then used
by the Operator to set the classpath.

If the `COHERENCE_HOME` environment variable is set in an image the following entries will be added to the end of the
classpath:

* `$COHERENCE_HOME/lib/coherence.jar`
* `$COHERENCE_HOME/conf`

=== Additional Data Volumes

If the application requires access to external storage volumes in Kubernetes it is possible to add additional `Volumes`
and `VolumeMappings` to the Pod and containers.

There are three ways to add additional volumes:

* ConfigMaps - easily add a `ConfigMap` volume and volume mapping see: <<other/050_configmap_volumes.adoc,Add ConfigMap Volumes>>
* Secrets - easily add a `Secret` volume and volume mapping see: <<other/060_secret_volumes.adoc,Add Secret Volumes>>
* Volumes - easily add any additional volume and volume mapping see: <<other/070_add_volumes.adoc,Add Volumes>>

Both of `ConfigMaps` and `Secrets` have been treated as a special case because they are quite commonly used to provide
configurations to Pods, so the `Coherence` spec provides a simpler way to declare them than for ad-hoc `Volumes`.

