///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2024, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Deploy Coherence Applications
:description: Coherence Operator Documentation - Deploy Coherence Applications
:keywords: oracle coherence, kubernetes, operator, documentation, Deploy Coherence Applications

== Deploy Coherence Applications

Once a custom application image has been built (as described in <<docs/applications/020_build_application.adoc,Build Custom Application Images>>)
a `Coherence` resource can be configured to use that image.


=== Specify the Image to Use

To specify the image to use set the `image` field in the `Coherence` spec to the name of the image.

For example if there was an application image called `catalogue:1.0.0` it can be specified like this:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: test
spec:
  image: catalogue:1.0.0  # <1>
----
<1> The `catalogue:1.0.0` will be used in the `coherence` container in the deployment's Pods.

The example above would assume that the `catalogue:1.0.0` has a JVM on the `PATH` and all the required `.jar` files,
or Java classes, in the default classpath locations used by the Operator.

=== Image Pull Secrets

If your image needs to be pulled from a private registry you may need to provide
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/[image pull secrets] for this.

For example, supposing the application image is `repo.acme.com/catalogue:1.0.0` and that `repo.acme.com` is a private registry; we might a `Secret` to the k8s namespace named `repo-acme-com-secrets`. We can then specify that these secrets are used in the `Coherence` resource by setting the `imagePullSecrets` fields. The `imagePullSecrets` field is a list of secret names, the same format as that used when specifying secrets for a Pod spec.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: test
spec:
  image: repo.acme.com/catalogue:1.0.0  # <1>
  imagePullSecrets:
    - name: repo-acme-com-secrets       # <2>
----

<1> The `repo.acme.com/catalogue:1.0.0` image will be used for the application image
<2> The `Secret` named `repo-acme-com-secrets` will be used to pull images.

Multiple secrets can be specified in the case where different images used by different containers are pulled from different registries.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: test
spec:
  image: repo.acme.com/catalogue:1.0.0
  imagePullSecrets:
    - name: repo-acme-com-secrets               # <1>
    - name: oracle-container-registry-secrets
----

<1> The example above has two image pull secrets, `repo-acme-com-secrets` and `oracle-container-registry-secrets`


=== More Application Configuration

Additional configuration can be added to specify other application settings, these include:

* setting the <<docs/jvm/020_classpath.adoc,classpath>>
* specifying the <<docs/applications/040_application_main.adoc,application main>>
* specifying <<docs/applications/050_application_args.adoc,application arguments>>
* specifying the <<docs/applications/060_application_working_dir.adoc,working directory>>
