///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Set the Application Main

== Set the Application Main

The Coherence container in the deployment's Pods will, by default, run `com.tangosol.net.DefaultCacheServer` as the Java main class.
It is possible to change this when running a custom application that requires a different main.

The name of the main is set in the `application.main` field in the `CoherenceDeployment` spec.

For example, if the deployment is using a custom image `catalogue:1.0.0` that requires a custom main class
called `com.acme.Catalogue` the `CoherenceDeployment` would look like this:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceDeployment
metadata:
  name: test
spec:
  image: catalogue:1.0.0
  application:
    main: com.acme.Catalogue # <1>
----
<1> The `com.acme.Catalogue` will be run as the main class.

The example would be equivalent to the Coherence container running:
[source,bash]
----
$ java com.acme.Catalogue
----
