///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Set the Application Main
:description: Coherence Operator Documentation - Set the Application Main
:keywords: oracle coherence, kubernetes, operator, documentation, set application main

== Set the Application Main

The Coherence container in the deployment's Pods will, by default, run `com.tangosol.net.DefaultCacheServer` as the Java main class.
It is possible to change this when running a custom application that requires a different main.

The name of the main is set in the `application.main` field in the `Coherence` spec.

For example, if the deployment is using a custom image `catalogue:1.0.0` that requires a custom main class
called `com.acme.Catalogue` the `Coherence` resource would look like this:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: test
spec:
  image: catalogue:1.0.0
  application:
    main: com.acme.Catalogue # <1>
----
<1> The `com.acme.Catalogue` will be run as the main class.

The example would be equivalent to the Coherence container running:
[source,bash]
----
$ java com.acme.Catalogue
----
