///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Packaging Applications

Whilst it is simple to deploy a Coherence cluster into Kubernetes in most cases there is also a requirement to add
application code and configuration to the Coherence JVMs class path.

== Packaging Applications

//// TBD... step by step guide to building a Coherence Java server side application,
//// packaging it into an image and deploying it using the operator.