///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Coherence Operator Development

The Coherence Operator is a Go based project built using the
https://github.com/operator-framework/operator-sdk[Operator SDK].

== Coherence Operator Development

=== Development Prerequisites

The following prerequisites are required to build and test the operator (the prerequisites to just run the operator
are obviously a sub-set of these).

* https://github.com/operator-framework/operator-sdk/tree/v0.11.0[operator-sdk] version *v0.11.0*
* https://git-scm.com/downloads[git]
* https://golang.org/dl/[go] version v1.12+.
* https://www.mercurial-scm.org/downloads[mercurial] version 3.9+
* https://docs.docker.com/install/[docker] version 17.03+.
* https://kubernetes.io/docs/tasks/tools/install-kubectl/[kubectl] version v1.11.3+.
* Access to a Kubernetes v1.11.3+ cluster.

* http://jdk.java.net/[Java 8+ JDK]
* https://maven.apache.org[Maven] version 3.5+
* Access to a Maven repository containing Oracle Coherence 12.2.1.4 (for the exact GAV see the
`pom.xml` file in the `java/` directory)

* Optional: https://github.com/go-delve/delve/tree/master/Documentation/installation[delve]
version 1.2.0+ (for local debugging with `operator-sdk up local --enable-delve`).

* This project uses `make` for building, which should already be installed on most systems

NOTE: This project currently uses the Operator SDK v0.11.0 so make sure you install the correct version of
the Operator SDK CLI.

NOTE: As stated above this project requires K8s v1.11.3+ so if using Docker on MacOS you need at least version 2.1.0.0


=== Project Structure

The project also contains a Java sub-project that is used to create Coherence utilities that the Operator relies on
to work correctly with Coherence clusters that it is managing.

This project was initially generated using the Operator SDK and this dictates the structure of the project
which means that files and directories should not be moved arbitrarily.

=== Operator SDK Files
The following should not be moved:

|===
|File |Description

|`bin/` |scripts used in the Operator Docker image
|`build/Dockerfile` |the `Dockerfile` used by the Operator SDK to build the Docker image
|`cmd/manager/main.go` |The Operator `main` generated by the Operator SDK
|`deploy/` |Yaml files generated and maintained by the Operator SDK
|`deploy/crds` |The CRD files generated and maintained by the Operator SDK
|`helm-charts/` |The Helm charts used by the Operator
|`pkg/apis` |The API `struct` code generated by the Operator SDK and used to generate the CRD files
|`pkg/controller` |The controller code generated by the Operator SDK
|`watches.yaml` |The Helm Operator configuration generated by the Operator SDK
|`local-watches.yaml` |The Helm Operator configuration used when running the operator locally
|===

