///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= High Level Design

== High Level Design

The Coherence Operator has been built using the https://github.com/operator-framework/operator-sdk[Operator SDK] and
hence the design is based on how the framework works.

=== Custom Resource Definitions (CRDs)
In Kubernetes a CRD is a yaml (or json) file that defines the structure of a custom resource. When building operators
using the Operator SDK the yaml files are not edited directly, they are generated from the Go structs in the source code.
The Coherence Operator has three CRDs:

* CoherenceCluster
* CoherenceRole
* CoherenceInternal

==== CoherenceCluster CRD
The CoherenceCluster CRD is the main CRD that defines what a Coherence cluster looks like. This is the CRD that a customer
creates and manges through the normal kubernetes commands and APIs. A CoherenceCluster is made up of one or more roles.
Each role defines a sub-set of the members of a Coherence cluster (or all of the members in the case of a cluster with a
single role).

The yaml for the CoherenceCluster CRD is in the file `deploy/crds/coherence.oracle.com_coherenceclusters_crd.yaml`. This yaml
is generated by the Operator SDK from the `CoherenceCluster` struct in the `pkg/apis/coherence/v1/coherencecluster_types.go`
source file.

==== CoherenceRole CRD
The CoherenceRole CRD is a definition of a role within a CoherenceCluster. A role is a sub-set of the members of a
cluster that all share the same configuration. A customer should not interact directly with a CoherenceRole other
than when scaling (for example using `kubectl scale` commands).

The reason that a cluster is split into roles represented by a different CRD is to allow more fine grained control over
different parts of the cluster, especially for operations such as scaling. By having a separate CRD for a role allows
a customer to update or scale each role individually.

The yaml for the CoherenceRole CRD is in the file `deploy/crds/coherence.oracle.com_coherenceroles_crd.yaml`. This yaml
is generated by the Operator SDK from the `CoherenceRole` struct in the `pkg/apis/coherence/v1/coherencerole_types.go`
source file.

==== CoherenceInternal CRD
The CoherenceInternal CRD is (as the name suggests) entirely internal to the Coherence Operator and a customer should
not interact with it at all. The CoherenceInternal CRD is a representation of the values file used to install the
Coherence Helm chart.

The yaml for the CoherenceInternal CRD is in the file `deploy/crds/coherence.oracle.com_coherenceinternals_crd.yaml`. This yaml
is generated by the Operator SDK from the `CoherenceInternal` struct in the `pkg/apis/coherence/v1/coherenceinternal_types.go`
source file.

=== Modifying CRDs
To modify the contents of a CRD (for example to add a new field) the corresponding Go struct needs to be updated.
For backwards compatibility between released versions we should ensure that we do not delete fields. After any of the
structs have been modified the new CRD files need to be generated, this is done by running the Operator SDK generator
using the Makefile. If the generate step is not run the code will not work properly.

[source,bash]
----
make generate
----
