///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Debugging

== Debugging the Coherence Operator

Assuming that you have an IDE capable of debugging Go and have
https://github.com/go-delve/delve/tree/master/Documentation/installation[delve] installed you can debug the operator.
When debugging an instance of the operator is run locally so functionality that will only work when the operator is
deployed into k8s cannot be properly debugged.

To start an instance of the operator that can be debugged use the make target `run-debug`, for example:
[source,bash]
----
make run-debug
----
This will start the operator and listen for a debugger to connect on the default delve port `2345`.
The operator will connect to whichever k8s cluster the current environment is configured to point to.

=== Stopping the Debug Session
To stop the local operator just use CTRL-Z or CTRL-C. Sometimes processes can be left around even after exiting in
this way. To make sure all of the processes are dead you can run the kill script:
[source,bash]
----
make debug-stop
----

=== Debugging Tests
To debug the operator while running a particular tests first start the debugger as described above.
Then use the debug make test target to execute the test.

For example to debug the `TestMinimalCoherenceCluster` test first start the debug session:
[source,bash]
----
make run-debug
----
Then execute the test with the `debug-e2e-local-test` make target:
[source,bash]
----
make debug-e2e-local-test GO_TEST_FLAGS='-run=^TestMinimalCoherenceCluster$$'
----

