///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Building the Docs

The Coherence Operator documentation can be built directly from `make` commands.

== Building the Coherence Operator Documentation

The Coherence Operator documentation is written in https://asciidoctor.org[Ascii Doc] format and is built with tools
provided by our friends over in the http://helidon.io[Helidon] team.

The documentation source is under the `docs/` directory.

=== Build

To build the documentation run

[source,bash]
----
make docs
----

This will build the documentation into the directory `build/_output/docs`

=== View

To see the results of local changes to the documentation it is possible to run a local web-server that will allow the docs
to be viewed in a browser.

[source,bash]
----
make server-docs
----

This will start a local web-server on http://localhost:8080[]
This is useful to see changes in real time as documentation is edited and re-built.
The server does no need to be restarted between documentation builds.

NOTE: The local web-server requires Python
