= Useful Info

== Useful Info

=== Labeling Your K8s Node

For local testing, for example in Docker Desktop it is useful to add the zone label to your local K8s node with
the fault domain that is then used by the Coherence Pods to set their `site` property.

For example, if your local node is called `docker-desktop` you can use the following command to set
the zone name to `twilight-zone`:
[source,bash]
----
kubectl label node docker-desktop failure-domain.beta.kubernetes.io/zone=twilight-zone
----
With this label set all Coherence Pods installed by the Coherence Operator on that node will be
running in the `twilight-zone`.


=== Kubernetes Dashboard

Assuming that you have the https://github.com/kubernetes/dashboard[Kubernetes Dashboard] then you can easily
start the local proxy and display the required login token by running:
[source,bash]
----
./hack/kube-dash.sh
----
This will display the authentication token, the local k8s dashboard URL and then start `kubectl proxy`.

=== Stuck CoherenceInternal Resources
Sometimes a CoherenceInternal resource becomes stuck in k8s. This is because the operator adds finalizers to the
resources causing k8s to be unable to delete them. The simplest way to delete them is to use the `kubectl patch`
command to remove the finalizer.

For example, if there was a CoherenceInternal resource called `test-role` in namespace `testing` then
the following command could be used.
[source,bash]
----
kubectl -n testing patch coherenceinternal/test-role \
  -p '{"metadata":{"finalizers": []}}' \
  --type=merge;
----

Alternatively there is a make target that wil clean up and remove all CoherenceCLuster, CoherenceRole and CoherenceInternal
resources from the test namespace.
[source,bash]
----
make delete-coherence-clusters
----
