# Copyright 2019, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "coherence.fullname" . }}-scripts
  labels:
{{- include "coherence.release_labels" . | indent 4 }}
    component: coherence-scripts
data:
{{- range $path, $fileContents := .Files.Glob "scripts/*" }}
{{- $scriptName := regexReplaceAll "(^.*/)(.*)$" $path "${2}" }}
  {{ $scriptName }}: |
{{ $.Files.Get $path | printf "%s" | indent 4}}
{{- end }}
