///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Overview

== Overview

There are a number of miscellaneous configuration settings that can be added to containers and `Pods`
controlled by the Coherence Operator.

[PILLARS]
====
[CARD]
.Environment Variables
[link=other/020_environment.adoc]
--
Adding environment variables to the Coherence container.
--

[CARD]
.Pod Labels
[link=other/030_labels.adoc]
--
Adding Pod labels.
--

[CARD]
.Pod Annotations
[link=other/040_annotations.adoc]
--
Adding Pod annotations.
--
====

=== Containers

[PILLARS]
====
[CARD]
.Add Containers
[link=other/080_add_containers.adoc]
--
Adding side-car containers and init-containers.
--
====

=== Volumes

[PILLARS]
====
[CARD]
.Add Volumes
[link=other/070_add_volumes.adoc]
--
Adding Volumes and volume mounts.
--

[CARD]
.Add ConfigMap Volumes
[link=other/050_configmap_volumes.adoc]
--
Adding Volumes and volume mounts using ConfigMaps.
--

[CARD]
.Add Secret Volumes
[link=other/060_secret_volumes.adoc]
--
Adding Volumes and volume mounts using Secrets.
--
====

=== Pod Scheduling

[PILLARS]
====
[CARD]
.Pod Scheduling
[link=other/090_pod_scheduling.adoc]
--
Taints, Tolerations and node selectors.
--

[CARD]
.Resources
[link=other/100_resources.adoc]
--
Configuring Coherence container resource constraints.
--
====


