///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2025, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Pod & Container SecurityContext
:description: Coherence Operator Documentation - Pod & Container SecurityContexts
:keywords: oracle coherence, kubernetes, operator, pod sercurtyContext, container sercurtyContext

== Pod & Container SecurityContext

Kubernetes allows you to configure a https://kubernetes.io/docs/tasks/configure-pod-container/security-context/[Security Context] for both Pods and Containers. The Coherence CRD exposes both of these to allow you to set the security context configuration for the Coherence Pods and for the Coherence containers withing the Pods.

For more details see the Kubernetes https://kubernetes.io/docs/tasks/configure-pod-container/security-context/[Security Context] documentation.

=== The Default Security Context

The Coherence Operator configures a default security context for the Coherence Pods is none is specified in the `Coherence` resource yaml.
The default security context looks like this:
[source,yaml]
----
securityContext:
  runAsNonRoot: true
  runAsUser: 1000650000
  runAsGroup: 1000650000
  fsGroup: 1000650000
  fsGroupChangePolicy: "OnRootMismatch"
----

It is possible to change the values used for the default security context by specifying them when the Operator is installed.
See the <<config,Configure The Default Security Context>> section below.

It is possible to override this as described below.

=== Setting the Pod Security Context

To specify security settings for a Pod, include the `securityContext` field in the Coherence resource specification.
The securityContext field is a https://{k8s-doc-link}/#podsecuritycontext-v1-core[PodSecurityContext] object. The security settings that you specify for a Pod apply to all Containers in the Pod. Here is a configuration file for a Pod that has a securityContext:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: test
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
----

=== Setting the Coherence Container Security Context

To specify security settings for the Coherence container within the Pods, include the `containerSecurityContext` field in the Container manifest. The `containerSecurityContext` field is a https://{k8s-doc-link}/#securitycontext-v1-core[SecurityContext] object.
Security settings that you specify in the `containerSecurityContext` field apply only to the individual Coherence container and the Operator init-container, and they override settings made at the Pod level in the `securityContext` field when there is overlap. Container settings do not affect the Pod's Volumes.

Here is the configuration file for a Coherence resource that has both the Pod and the container security context:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: test
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containerSecurityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: false
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
----

[#config]
=== Configure The Default Security Context

As already mentioned above the default security context created by the operator looks like this:

[source,yaml]
----
securityContext:
  runAsNonRoot: true
  runAsUser: 1000650000
  runAsGroup: 1000650000
  fsGroup: 1000650000
  fsGroupChangePolicy: "OnRootMismatch"
----

The default values used for `runAsUser`, `runAsGroup` and `fsGroup` can be configured using the Operator's configuration file.

When the Operator is installed using the default installation it will read an optional configuration file from
an optional `ConfigMap`. The `ConfigMap` must be created in the same namespace as the operator is running and
should be named `coherence-operator`. The config map should contain a yaml file named `coherence-operator.yaml`.

[IMPORTANT]
====
The `coherence-operator` config map MUST be created before the Operator is installed, even if the yaml file
that it contains is empty.

The Operator will watch the config file for changes, so if the `ConfigMap` is updated after the Operator is started,
the changes will take effect. If the `ConfigMap` does not exist when the Operator is started then the config file
cannot be mounted for the Operator to watch.
====


==== Disable The Default Security Context

To disable the creation of a default Pod security context for Coherence Pods, create a configuration file
name `coherence-operator.yaml` with the following contents.

[source]
.coherence-operator.yaml
----
coherenceSecurityContext:
  enabled: false
----

Create the `ConfigMap` using the configuration file in the same namespace that the operator will be installed into.
For example, if the operator is to be installed into a namespace named `coherence` the `ConfigMap` can be created
using the following command:

[source,bash]
----
kubectl -n coherence create configmap coherence-operator \
  --from-file=coherence-operator.yaml
----

With the `coherenceSecurityContext.enabled` field set to false, the Operator will not apply a default security context
to the Coherence Pods. This may be useful in environments such as OpenShift which already apply a default security
configuration to Pods.

==== Change The Default Security Context

In the configuration file, any field under the `coherenceSecurityContext` section will be applied to
the default security context and override the operators default values.

For example, a `ConfigMap` could be created with the following file:

[source]
.coherence-operator.yaml
----
coherenceSecurityContext:
  runAsUser: 1000
----

This will override the `runAsUser` field to be set to `1000` resulting in a default security context as shown below:

[source,yaml]
----
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000650000
  fsGroup: 1000650000
  fsGroupChangePolicy: "OnRootMismatch"
----

If the config file contains an empty value, this will result in the corresponding value being unset in the
security context.
This is useful for unsetting fields that the operator has default values for such as `runAsUser`, `runAsGroup`,
`runAsNonRoot`, `fsGroup` and `fsGroupChangePolicy`.


For example, the default `runAsUser` value is `1000650000`.
The configuration file can be created with a `runAsUser` field with no value as shown below

[source]
.coherence-operator.yaml
----
coherenceSecurityContext:
  runAsUser:
----

This will result in a security context with the `runAsUser` unset.

[source,yaml]
----
securityContext:
  runAsNonRoot: true
  runAsUser:
  runAsGroup: 1000650000
  fsGroup: 1000650000
  fsGroupChangePolicy: "OnRootMismatch"
----

