///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Configure Additional Containers

== Configure Additional Containers

Additional containers and init-containers can easily be added to a `Coherence` resource Pod.
There are two types of container that can be added, init-containers and normal containers.
An example use case for this would be to add something like a Fluentd side-car container to ship logs to Elasticsearch.

NOTE: A note about Volumes: +
The Operator created a number of volumes and volume mounts by default. These default volume mounts will be added
to *all* containers in the `Pod` including containers added as described here. +
Any additional volumes and volume mounts added to the `Coherence` resource spec will also be added *all* containers.

=== Add a Container

To add a container to the `Pods` specify the container in the `sideCars` list in the `Coherence` CRD spec.

See the <<docs/logging/020_logging.adoc,Logging Documentation>> for a bigger example of adding a side-car container.

For example:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  sideCars:
    - name: fluentd                   # <1>
      image: "fluent/fluentd:v1.3.3"
----
<1> An additional container named `fluentd` has been added to the CRD spec.

The containers will added to the `sideCars` will be added to the `Pods` exactly as configured.
Any configuration that is valid in a Kubernetes
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#container-v1-core[Container Spec]
may be added to an entry in `sideCars`


=== Add an Init-Container

Just like normal containers above, additional init-containers can also be added to the `Pods`.
To add an init-container to the `Pods` specify the container in the `initContainers` list in the `Coherence` CRD spec.
As with containers, for init-containers any configuration that is valid in a Kubernetes
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#container-v1-core[Container Spec]
may be added to an entry in `initContainers`

For example:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  initContainers:
    - name: setup                   # <1>
      image: "app-setup:1.0.0"
----
<1> An additional init-container named `setup` has been added to the CRD spec with an image named `app-setup:1.0.0`.


