///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2024, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Container Resource Limits

== Container Resource Limits

When creating a `Coherence` resource you can optionally specify how much CPU and memory (RAM) each Coherence Container
is allowed to consume. The container resources are specified in the `resources` section of the `Coherence` spec;
the format is exactly the same as documented in the Kubernetes documentation
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/[Managing Compute Resources for Containers].

WARNING: When setting resource limits, in particular memory limits, for a container it is important to ensure that the
Coherence JVM is properly configured so that it does not consume more memory than the limits. If the JVM attempts to
consume more memory than the resource limits allow the `Pod` can be killed by Kubernetes.
See <<docs/jvm/050_memory.adoc,Configuring the JVM Memory>> for details on the different memory settings.

For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: test-cluster
spec:
  resources:           # <1>
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
----
<1> The `coherence` container in the `Pods` will have requests of 0.25 cpu and 64MiB of memory,
and limits of 0.5 cpu and 128MiB of memory.


== InitContainer Resource Limits

The Coherence Operator adds an init-container to the Pods that it manages. This init container does nothing more
than copy some files and ensure some directories exist. In terms of resource use it is extremely light.
Some customers have expressed a desire to still be able to set limits fo this init container, so this is possible
using the `spec.initResources` field.

For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: test-cluster
spec:
  initResources:           # <1>
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
----
<1> The `coherence-k8s-utils` init-container in the `Pods` will have requests of 0.25 cpu and 64MiB of memory,
and limits of 0.5 cpu and 128MiB of memory.

These resources only applies to the init-container that the Operator creates, any other init-containers added in the
`spec.initContainers` section should have their own resources configured.
