# options for analysis running
run:
  # include test files or not, default is true
  tests: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - gocritic
    - gofmt

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on data files.
    - path: pkg/data
      linters:
        - gofmt
    # Exclude some linters from running on tests files.
    - path: test\.go
      linters:
        - gosec
        - bodyclose
