# options for analysis running
version: "2"

run:
  # include test files or not, default is true
  tests: true

formatters:
  enable:
    - gofmt
  exclusions:
    generated: disable
    paths:
      - data/

linters:
  settings:
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/gomeg
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - gocritic

  exclusions:
    presets:
      - common-false-positives
    paths:
      - utils/docgen/main.go
      - utils/linkcheck/main.go
    rules:
      - path: _test\.go
        linters:
          - gosec
          - bodyclose
          - errcheck
      - path: test/
        linters:
          - staticcheck
        text: "ST1001:"
      - path: pkg/fakes/
        linters:
          - staticcheck
        text: "ST1001:"
