///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Logging
:keywords: oracle coherence, kubernetes, operator, Logging

== Logging

[PILLARS]
====
[CARD]
.Enabling Log Capture
[link=logging/020_logging.adoc]
--
Capturing and viewing Coherence cluster Logs.
--

[CARD]
.Using Your Own Elasticsearch
[link=logging/030_own.adoc]
--
Pushing logs to your own Elasticsearch instance.
--

[CARD]
.Kibana Dashboards
[link=logging/040_dashboards.adoc]
--
Details on the Kibana Dashboards available..
--

====

