///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Log Capture with Fluentd

== Log Capture with Fluentd

There are many ways to capture container logs in Kubernetes, one possibility that this guide will cover is using
a Fluentd side-car container to ship log files to Elasticsearch.
This is a common pattern and one the the `Coherence` CRD makes simple by allowing easy injection of additional containers.

NOTE: This guide is going to assume that the default logging related configurations provided by the operator will
be used. For example, Coherence will be configured to use Java util logging for logs, and the default logging configuration
file will be used. Whilst these things are not pre-requisites for shipping logs to Elasticsearch they are required
to make the examples below work.

To be able to send Coherence logs to Elasticsearch there are some steps that must be completed:

* Configure Coherence to log to files
* Add a `Volume` and `VolumeMount` to be used for log files
* Add the Fluentd side-car container

=== Configure Coherence to Log to Files

Coherence will log to the console by default so to be able to ship logs to Elasticsearch it needs to be configured
to write to log files. One way to do this is to add a Java Util Logging configuration file and then to configure
Coherence to use the JDK logger.

In the `jvm.args` section of the `Coherence` CRD the system properties should be added to set the configuration file used by Java util logging and to configure Coherence logging.
See the Coherence https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/develop-applications/operational-configuration-elements.html[Logging Config]
documentation for more details.

There are alternative ways to configure the Java util logger besides using a configuration file, just as there are
alternative logging frameworks that Coherence can be configured to use to produce log files.
This example is going to use Java util logging as that is the simplest to demonstrate without requiring any additional
logging libraries.

==== Operator Provided Logging Configuration File

Whilst any valid Java util logging configuration file may be used, the Coherence Operator injects a default logging
configuration file into the `coherence` container that can be used to configure the logger to write
logs to files under the `/logs` directory. The log files will have the name `coherence-%g.log`, where `%g` is the
log file generation created as logs get rotated.

This file will be injected into the container at `/coherence-operator/utils/logging/logging.properties`
and will look something like this:
[source]
----
com.oracle.coherence.handlers=java.util.logging.ConsoleHandler,java.util.logging.FileHandler

com.oracle.coherence.level=FINEST

java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.ConsoleHandler.level=FINEST

java.util.logging.FileHandler.pattern=/logs/coherence-%g.log
java.util.logging.FileHandler.limit=10485760
java.util.logging.FileHandler.count=50
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter

java.util.logging.SimpleFormatter.format=%5$s%6$s%n
----

To configure Cohrence and the logger some system properties need to be added to the `jvm.args` field
of the `Coherence` CRD spec:

For example:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: cluster-one
spec:
  jvm:
    args:
      - "-Dcoherence.log=jdk"                                                                   # <1>
      - "-Dcoherence.log.logger=com.oracle.coherence"                                           # <2>
      - "-Djava.util.logging.config.file=/coherence-operator/utils/logging/logging.properties"  # <3>
----
<1> Coherence has been configured to use the Java util logging.
<2> The Coherence logger name has been set to `com.oracle.coherence`, which matches the logging configuration file.
<3> The Java util logging configuration file is set to the file injected by the Operator.


==== Log Files Volume

The logging configuration above configures Coherence to write logs to the `/logs` directory.
For this location to be accessible to both the `coherence` container and to the `fluentd` container it needs to be
created as a `Volume` in the `Pod` and mounted to both containers.
As this `Volume` can be ephemeral and is typically not required to live longer than the `Pod` the simplest type of
`Volume` to use is an `emptyDir` volume source.

For example:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: cluster-one
spec:
  jvm:
    args:
      - "-Dcoherence.log=jdk"
      - "-Dcoherence.log.logger=com.oracle.coherence"
      - "-Djava.util.logging.config.file=/coherence-operator/utils/logging/logging.properties"
  volumes:
    - name: logs           # <1>
      emptyDir: {}
  volumeMounts:
    - name: logs           # <2>
      mountPath: /logs
----
<1> An additional empty-dir `Volume` named `logs` has been added to the `Coherence` spec.
<2> The `logs` volume will be mounted at `/logs` in all containers in the `Pod`.



=== Add the Fluentd Side-Car

With Coherence configured to write to log files, and those log files visible to other containers in the `Pod` the
Fluentd side-car container can be added.

The example yaml below shows a `Coherence` resource with the additional Fluentd container added.
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: cluster-one
spec:
  jvm:
    args:
      - "-Dcoherence.log=jdk"
      - "-Dcoherence.log.logger=com.oracle.coherence"
      - "-Djava.util.logging.config.file=/coherence-operator/utils/logging/logging.properties"
  volumes:
    - name: logs           # <1>
      emptyDir: {}
  volumeMounts:
    - name: logs           # <2>
      mountPath: /logs
  sideCars:
    - name: fluentd                                                                    # <1>
      image: "fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch-1.3"
      args:
        - "-c"
        - "/etc/fluent.conf"
      env:
        - name: "FLUENTD_CONF"                                                         # <2>
          value: "fluentd-coherence.conf"
        - name: "FLUENT_ELASTICSEARCH_SED_DISABLE"                                     # <3>
          value: "true"
  configMapVolumes:
    - name: "efk-config"                                                               # <4>
      mountPath: "/fluentd/etc/fluentd-coherence.conf"
      subPath: "fluentd-coherence.conf"
----
<1> The `fluentd` container has been added to the `sideCars` list. This will create another container
in the `Pod` exactly as configured.
<2> The `FLUENTD_CONF` environment variable has been set to the name of the configuration file that Fluentd should use.
The standard Fluentd behaviour is to locate this file in the `/fluentd/etc/` directory.
<3> The `FLUENT_ELASTICSEARCH_SED_DISABLE` environment variable has been set to work around a known issue https://github.com/fluent/fluentd-kubernetes-daemonset#disable-sed-execution-on-elasticsearch-image[here].
<4> An additional volume has been added from a `ConfigMap` named `efk-config`, that contains the Fluentd configuration to use.
This will be mounted to the `fluentd` container at `/fluentd/etc/fluentd-coherence.conf`, which corresponds to the
name of the file set in the `FLUENTD_CONF` environment variable.

NOTE: There is no need to add a `/logs` volume mount to the `fluentd` container. The operator will mount the `logs`
`Volume` to *all* containers in the `Pod`.

In the example above the Fluentd configuration has been provided from a `ConfigMap`. It could just as easily have come from a
`Secret` or some other external `Volume` mount, or it could have been baked into the Fluentd image to be used.

==== The Fluentd Configuration File

The `ConfigMap` used to provide the Fluentd configuration might look something like this:
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: efk-config                              # <1>
  labels:
    component: coherence-efk-config
data:
  fluentd-coherence.conf: |
    # Ignore fluentd messages
    <match fluent.**>
      @type null
    </match>

    # Coherence Logs
    <source>                                    # <2>
      @type tail
      path /logs/coherence-*.log
      pos_file /tmp/cohrence.log.pos
      read_from_head true
      tag coherence-cluster
      multiline_flush_interval 20s
      <parse>
       @type multiline
       format_firstline /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}/
       format1 /^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3})\/(?<uptime>[0-9\.]+) (?<product>.+) <(?<level>[^\s]+)> \(thread=(?<thread>.+), member=(?<member>.+)\):[\S\s](?<log>.*)/
      </parse>
    </source>

    <filter coherence-cluster>                  # <3>
     @type record_transformer
     <record>
       cluster "#{ENV['COH_CLUSTER_NAME']}"
       role "#{ENV['COH_ROLE']}"
       host "#{ENV['HOSTNAME']}"
       pod-uid "#{ENV['COH_POD_UID']}"
     </record>
    </filter>

    <match coherence-cluster>                   # <4>
      @type elasticsearch
      hosts "http://elasticsearch-master:9200"
      logstash_format true
      logstash_prefix coherence-cluster
    </match>
----
<1> The name of the `ConfigMap` is `efk-config` to match the name specified in the `Coherence` CRD spec.
<2> The `source` section is configured to match log files with the name `/logs/coherence-*.log`, which is the name that
Coherence logging has been configured to use. The pattern in the `source` section is a Fluentd pattern that matches the
standard Coherence log message format.
<3> A `filter` section will add additional fields to the log message. These come from the environment variables that
the Operator will inject into all containers in the Pod. In this case the Coherence cluster name, the Coherence role name,
the Pod host name and Pod UID.
<4> The final section tells Fluentd how to ship the logs to Elasticsearch, in this case to the endpoint `http://elasticsearch-master:9200`

There are many ways to configure Fluentd, the example above is just one way and is in fact taken from one of the Operator's functional tests.

With the `efk-config` `ConfigMap` created in the same namespace as the `Coherence` resource the Coherence logs from the
containers will now be shipped to Elasticsearch.
