///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Overview

== Overview

The Coherence Operator allows full control over the configuration of the JVM used to run the Coherence application.
The `jvm` section of the `CoherenceDeployment` spec has a number of fields to easily configure specific aspects of the
JVM as well as a catch-all `jvm.args` list that allows any arbitrary argument to be passed to the JVM.

=== Guides to JVM Settings

[PILLARS]
====
[CARD]
.Classpath
[link=jvm_settings/020_classpath.adoc]
--
Default classpath settings and options for setting a custom classpath.
--

[CARD]
.JVM Arguments
[link=jvm_settings/030_jvm_args.adoc]
--
Adding arbitrary JVM arguments.
--

[CARD]
.Garbage Collection
[link=jvm_settings/040_gc.adoc]
--
Configuring the garbage collector.
--

[CARD]
.Memory Settings
[link=jvm_settings/050_memory.adoc]
--
Configuring the heap size and other memory settings.
--

[CARD]
.Logging
[link=jvm_settings/060_logging.adoc]
--
Configuring Java util logging.
--
====

[PILLARS]
====
[CARD]
.Debugger
[link=jvm_settings/070_debugger.adoc]
--
Using debugger settings.
--

[CARD]
.Flight Recorder
[link=jvm_settings/080_flight_recorder.adoc]
--
Using Flight Recorder.
--

[CARD]
.JMX
[link=jvm_settings/090_jmx.adoc]
--
Using JMX.
--

[CARD]
.Use Container Limits
[link=jvm_settings/100_container_limits.adoc]
--
Configuring the JVM to respect container resource limits.
--
====
