///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Java Util Logging

== Java Util Logging Configuration

Coherence is configured to use Java util logging as its logger in the `Pods` that are started from the `Coherence`
resource. A default Java util logging configuration file will be injected into the `Pod` by the operator that configures
the Coherence logger to log to rolling log files in a `/logs` directory.

The Java util logging configuration file can be overridden using the `jvm.loggingConfig` field in the CRD.
The value should point to a file either in the image being run or loaded from a volume such as a `ConfigMap`.

For example:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    loggingConfig: storage-logging.properties # <1>
----
<1> The logging configuration file is set to `storage-logging.properties`.

