///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Diagnostic Tools
:keywords: oracle coherence, kubernetes, operator, Diagnostic Tools

== Diagnostic Tools

[PILLARS]
====
[CARD]
.Generating Heap Dumps
[link=diagnostics/020_heapdump.adoc]
--
Produce and extract a heap dump.
--

[CARD]
.Using Java Flight Recorder
[link=diagnostics/030_jfr.adoc]
--
Produce and extract a Java Flight Recorder (JFR) file.
--

[CARD]
.Coherence Reporter
[link=diagnostics/040_reporter.adoc]
--
Manage and use the Reporter.
--

[CARD]
.Accessing the Coherence Console
[link=diagnostics/050_console.adoc]
--
Access the Coherence Console.
--

[CARD]
.Accessing CohQL
[link=diagnostics/060_cohql.adoc]
--
Access the CohQL client.
--

====

