FROM scratch

COPY lib/*.jar  /files/lib/
COPY config/    /files/config/
COPY logging/   /files/logging/
COPY runner     /files/runner
COPY op-test    /files/op-test
COPY utils-init /files/utils-init
