#
# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
# Example 2
# Adds a separate proxy role
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: example-cluster-storage
spec:
  cluster: example-cluster
  jvm:
    memory:
      heapSize: 512m
    args:
      - "-Dcoherence.metrics.legacy.names=false"
      - "-Dcoherence.metrics.mp.names=true"
  ports:
    - name: metrics
      port: 9612
      serviceMonitor:
        enabled: true
  coherence:
    cacheConfig: storage-cache-config.xml
    metrics:
      enabled: true
  image: deployment-example:3.1.1
  imagePullPolicy: Always
  replicas: 3
---
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: example-cluster-proxy
spec:
  cluster: example-cluster
  jvm:
    memory:
      heapSize: 512m
    args:
      - "-Dcoherence.metrics.legacy.names=false"
      - "-Dcoherence.metrics.mp.names=true"
  ports:
    - name: metrics
      port: 9612
      serviceMonitor:
        enabled: true
    - name: proxy
      port: 20000
  coherence:
    cacheConfig: proxy-cache-config.xml
    storageEnabled: false
    metrics:
      enabled: true
  image: deployment-example:3.1.1
  imagePullPolicy: Always
  replicas: 1
