#
# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
# Example 3
# Adds a separate application node running helidon app
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: example-cluster-storage
spec:
  cluster: example-cluster
  jvm:
    memory:
      heapSize: 512m
    args:
      - "-Dcoherence.metrics.legacy.names=false"
  ports:
    - name: metrics
      port: 9612
      serviceMonitor:
        enabled: true
  coherence:
    cacheConfig: storage-cache-config.xml
    metrics:
      enabled: true
  image: deployment-example:3.0.3
  imagePullPolicy: Always
  replicas: 3
---
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: example-cluster-proxy
spec:
  cluster: example-cluster
  jvm:
    memory:
      heapSize: 512m
    args:
      - "-Dcoherence.metrics.legacy.names=false"
  ports:
    - name: metrics
      port: 9612
      serviceMonitor:
        enabled: true
    - name: proxy
      port: 20000
  coherence:
    cacheConfig: proxy-cache-config.xml
    storageEnabled: false
    metrics:
      enabled: true
  image: deployment-example:3.0.3
  imagePullPolicy: Always
  replicas: 1
---
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: example-cluster-rest
spec:
  cluster: example-cluster
  jvm:
    memory:
      heapSize: 512m
    args:
      - "-Dcoherence.metrics.legacy.names=false"
  ports:
    - name: metrics
      port: 9612
      serviceMonitor:
        enabled: true
    - name: http
      port: 8080
  coherence:
    cacheConfig: storage-cache-config.xml
    storageEnabled: false
    metrics:
      enabled: true
  image: deployment-example:3.0.3
  imagePullPolicy: Always
  application:
    main: com.oracle.coherence.examples.Main
  replicas: 1
