apiVersion: v1
kind: Service
metadata:
  name: storage-sts
  labels:
    coherence.oracle.com/cluster: test-cluster
    coherence.oracle.com/deployment: storage
    coherence.oracle.com/component: statefulset-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: tcp-coherence
    port: 7
    protocol: TCP
    targetPort: 7
  publishNotReadyAddresses: true
  selector:
    coherence.oracle.com/cluster: test-cluster
    coherence.oracle.com/deployment: storage
---
apiVersion: v1
kind: Service
metadata:
  name: storage-wka
  labels:
    coherence.oracle.com/cluster: test-cluster
    coherence.oracle.com/deployment: storage
    coherence.oracle.com/component: wka-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: tcp-coherence
    port: 7
    protocol: TCP
    targetPort: 7
  publishNotReadyAddresses: true
  selector:
    coherence.oracle.com/cluster: test-cluster
    coherence.oracle.com/deployment: storage
---
apiVersion: v1
kind: Service
metadata:
  name: storage-extend
  labels:
    coherence.oracle.com/cluster: test-cluster
    coherence.oracle.com/deployment: storage
    coherence.oracle.com/component: extend-service
spec:
  type: ClusterIP
  ports:
  - name: tcp-coherence
    port: 20000
    protocol: TCP
    targetPort: extend
  selector:
    coherence.oracle.com/cluster: test-cluster
    coherence.oracle.com/deployment: storage
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage
  labels:
    coherence.oracle.com/cluster: test-cluster
    coherence.oracle.com/deployment: storage
    coherence.oracle.com/component: statefulset
spec:
  selector:
    matchLabels:
      coherence.oracle.com/cluster: test-cluster
      coherence.oracle.com/deployment: storage
  serviceName: storage-sts
  replicas: 3
  template:
    metadata:
      labels:
        coherence.oracle.com/cluster: test-cluster
        coherence.oracle.com/deployment: storage
    spec:
      volumes:
        - name: tls
          secret:
            secretName: coherence-tls
      containers:
        - name: coherence
          image: simple-coherence:1.0.0
          volumeMounts:
            - mountPath: /certs
              name: tls
          command:
            - java
          args:
            - "--class-path"
            - "@/app/jib-classpath-file"
            - -Xms1800m
            - -Xmx1800m
            - "@/app/jib-main-class-file"
          env:
            - name: COHERENCE_CLUSTER
              value: storage
            - name: COHERENCE_WKA
              value: storage-wka
            - name: COHERENCE_CACHECONFIG
              value: test-cache-config.xml
            - name: COHERENCE_EXTEND_SOCKET_PROVIDER
              value: extend-tls
            - name: COHERENCE_EXTEND_KEYSTORE
              value: file:/certs/server.jks
            - name: COHERENCE_IDENTITY_PASSWORD_FILE
              value: /certs/server-password.txt
            - name: COHERENCE_KEY_PASSWORD_FILE
              value: /certs/server-key-password.txt
            - name: COHERENCE_EXTEND_TRUSTSTORE
              value: file:/certs/trust.jks
            - name: COHERENCE_TRUST_PASSWORD_FILE
              value: /certs/trust-password.txt
          ports:
            - name: extend
              containerPort: 20000


