apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: setup-env
spec:
  description: Environment setup.
  params:
   - name: docker-config-name
     description: The name of the Docker config json file.
     type: string
     default: ".dockerconfigjson"
  workspaces:
    - name: shared-data
      description: |
        This workspace contains the cloned repo files, so they can be read by the
        next task.
    - name: dockerconfig
      description: Includes a docker `config.json`
  results:
    - name: BUILD_ARCH
      description: The build architecture.
  steps:
    - name: setup-env
      image: container-registry.oracle.com/os/oraclelinux:9-slim
      env:
      script: |
        set -e
        cp $(workspaces.dockerconfig.path)/$(params.docker-config-name) $(workspaces.shared-data.path)/config.json
        UNAME_M=$(uname -m)
        if [ "$UNAME_M" = "arm64" ]
        then
          BUILD_ARCH=arm64
        elif [ "$UNAME_M" = "aarch" ]
        then
          BUILD_ARCH=arm64
        else
          BUILD_ARCH=amd64
        fi
        echo -n "$BUILD_ARCH" | tee "$(results.BUILD_ARCH.path)"
