///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Overview

The `Coherence` resource has a number of fields to configure the behaviour of `Coherence`,
these fields are in the `spec.coherence` section of the CRD.

== Configuring Coherence

The `Coherence` CRD has specific fields to configure the most common Coherence settings.
Any other settings can be configured by adding system properties to the <<jvm/010_overview.adoc,JVM Settings>>.

The following Coherence features can be directly specified in the `Coherence` spec.

* <<coherence/020_cluster_name.adoc,Cluster Name>>
* <<coherence/030_cache_config.adoc,Cache Configuration File>>
* <<coherence/040_override_file.adoc,Operational Configuration File>> (aka, the override file)
* <<coherence/050_storage_enabled.adoc,Storage Enabled>> or disabled deployments
* <<coherence/060_log_level.adoc,Log Level>>
* <<coherence/070_wka.adoc,Well Known Addressing>> and cluster discovery
* <<coherence/080_persistence.adoc,Persistence>>
* <<management/010_overview.adoc,Management over REST>>
* <<metrics/010_overview.adoc,Metrics>>

NOTE: The Coherence settings in the `Coherence` CRD spec typically set system property values that will
be passed through to the Coherence JVM command line, which in turn configure Coherence.
This is the same behaviour that would occur when running Coherence outside of containers.
Whether these system properties actually apply or not depends on the application code. For example,
it is simple to override the Coherence operational configuration file in a jar file deployed as part of an
application's image in such a way that will cause all the normal Coherence system properties to be ignored.
If that is done then the Coherence settings discussed in this documentation will not apply. +
For example, adding a `tangosol-coherence-override.xml` file to a jar on the application's classpath that contains
an overridden `<configurable-cache-factory-config>` section with a hard coded cache configuration file name would
mean that the `Coherence` CRD `spec.coherence.cacheConfig` field, that sets the `coherence.cacheconfig` system
property, would be ignored. +
It is, therefore, entirely at the application developer's discretion whether they use the fields of the `Coherence` CRD
to configure Coherence, or they put those settings into configuration files, either hard coded into jar files or
picked up at runtime from files mapped from Kubernetes volumes, config maps, secrets, etc.

