///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Cache Configuration File

== Set the Cache Configuration File Name

The name of the Coherence cache configuration file that the Coherence processes in a `Coherence` resource will
use can be set with the `spec.coherence.cacheConfig` field. By setting this field the `coherence.cacheconfig` system
property will be set in the Coherence JVM.

When the `spec.coherence.cacheConfig` is blank or not specified, Coherence use its default behaviour to find the
cache configuration file to use. Typically, this is to use the first occurrence of `coherence-cache-config.xml` that is
found on the classpath
(consult the https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/develop-applications/understanding-configuration.html#GUID-360B798E-2120-44A9-8B09-1FDD9AB40EB5[Coherence documentation]
for an explanation of the default behaviour).

To set a specific cache configuration file to use set the `spec.coherence.cacheConfig` field, for example:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  coherence:
    cacheConfig: storage-cache-config.xml # <1>
----

<1> The `spec.coherence.cacheConfig` field has been set to `storage-cache-config.xml` which will effectively pass
`-Dcoherence.cacheconfig=storage-cache-config.xml` to the JVM command line.

