///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Storage Enabled or Disabled

== Storage Enabled or Disabled Deployments
Partitioned cache services that manage Coherence caches are configured as storage enabled or storage disabled.
Whilst it is possible to configure individual services to be storage enabled or disabled in the cache configuration file
and have a mixture of modes in a single JVM, typically all the services in a JVM share the same mode by setting the
`coherence.distributed.localstorage` system property to `true` for storage enabled members and to `false` for
storage disabled members. The `Coherence` CRD allows this property to be set by specifying the
`spec.coherence.storageEnabled` field to either true or false. The default value when nothing is specified is `true`.

[source,yaml]
.storage enabled
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  coherence:
    storageEnabled: true  #<1>
----

<1> The `Coherence` resource specifically sets `coherence.distributed.localstorage` to `true`


[source,yaml]
.storage disabled
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  coherence:
    storageEnabled: false  #<1>
----

<1> The `Coherence` resource specifically sets `coherence.distributed.localstorage` to `false`

