///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Management Over ReST
:keywords: oracle coherence, kubernetes, operator, Management, ReST

== Management over ReST

[PILLARS]
====
[CARD]
.Enabling
[link=management/020_enabling.adoc]
--
Enabling Management Over ReST.
--

[CARD]
.Using JVisualVM
[link=management/030_visualvm.adoc]
--
Access Management Over ReST using JVisualVM plugin.
--

[CARD]
.Enabling SSL
[link=management/040_ssl.adoc]
--
Enable SSL with Management over ReST.
--

[CARD]
.Modifying MBeans
[link=management/050_mbeans.adoc]
--
Modifying writable Coherence MBeans.
--

====

