///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Management Over ReST
:keywords: oracle coherence, kubernetes, operator, Management, ReST

== Management

[PILLARS]
====
[CARD]
.Management Over ReST
[link=management/020_management_over_rest.adoc]
--
Management Over ReST.
--

[CARD]
.Using VisualVM
[link=management/040_visualvm.adoc]
--
Access the Coherence cluster via VisualVM.
--

====

== Diagnostics

[PILLARS]
====
[CARD]
.Generating Heap Dumps
[link=management/030_heapdump.adoc]
--
Produce and extract a heap dump.
--

[CARD]
.Accessing the Console
[link=management/050_console.adoc]
--
Accessing the Coherence Console.
--

[CARD]
.Accessing CohQL
[link=management/060_cohql.adoc]
--
Accessing the CohQL client.
--

====
