///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2025 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= The Coherence CLI
:description: Coherence Operator Documentation - Coherence CLI
:keywords: oracle coherence, kubernetes, operator, coherence-cli, cli

== The Coherence CLI

If Coherence Management over REST is enabled, it is possible to use the
https://github.com/oracle/coherence-cli[Coherence CLI]
to access management information. The Operator enables Coherence Management over REST by default, so unless it
has specifically been disabled, the CLI can be used.

See the https://oracle.github.io/coherence-cli/docs/latest[Coherence CLI Documentation]
for more information on how to use the CLI.

The Coherence CLI is automatically added to Coherence Pods by the Operator, so it is available as an executable
that can be run using `kubectl exec`.
At start-up of a Coherence container a default Coherence CLI configuration is created so that the CLI
knows about the local cluster member.


=== Using the CLI in Pods

The Operator installs the CLI at the location `/coherence-operator/utils/cohctl`.
Most official Coherence images are distroless images so they do not have a shell that can be used to create a session and execute commands. Each `cohctl` command will need to be executed as a separate `kubectl exec` command.

Once a Pod is running is it simple to use the CLI.
For example, the yaml below will create a simple three member cluster.

[source]
.minimal.yaml
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
    replicas: 3
----

The cluster name is `storage` and there will be three Pods created, `storage-0`, `storage-1` and `storage-2`.

To list the services running in the `storage-0` Pod the following command can be run:

[source,bash]
----
kubectl exec storage-0 -c coherence -- /coherence-operator/utils/cohctl get services
----

The `-c coherence` option tells `kubectl` to exec the command in the `coherence` container.
By default this is the only container that will be running in the Pod, so the option could be omitted.
If the option is omitted, `kubectl` will display a warning to say it assumes you mean the `coherence` container.

Everything after the `--` is the command to run in the Pod. In this case we execute:
[source,bash]
----
/coherence-operator/utils/cohctl get services
----
which runs the Coherence CLI binary at `/coherence-operator/utils/cohctl` with the command `get services`.

The output displayed by the command will look something like this:

[source,bash]
----
Using cluster connection 'default' from current context.

SERVICE NAME            TYPE              MEMBERS  STATUS HA  STORAGE  PARTITIONS
"$GRPC:GrpcProxy"       Proxy                   3  n/a             -1          -1
"$SYS:Concurrent"       DistributedCache        3  NODE-SAFE        3         257
"$SYS:ConcurrentProxy"  Proxy                   3  n/a             -1          -1
"$SYS:Config"           DistributedCache        3  NODE-SAFE        3         257
"$SYS:HealthHttpProxy"  Proxy                   3  n/a             -1          -1
"$SYS:SystemProxy"      Proxy                   3  n/a             -1          -1
ManagementHttpProxy     Proxy                   3  n/a             -1          -1
MetricsHttpProxy        Proxy                   3  n/a             -1          -1
PartitionedCache        DistributedCache        3  NODE-SAFE        3         257
PartitionedTopic        PagedTopic              3  NODE-SAFE        3         257
Proxy                   Proxy                   3  n/a             -1          -1
----

The exact output will vary depending on the version of Coherence and the configurations being used.

More CLI commands can be run by changing the CLI commands specified after `/coherence-operator/utils/cohctl`.

For example, to list all the members of the cluster:

[source,bash]
----
kubectl exec storage-0 -c coherence -- /coherence-operator/utils/cohctl get members
----

=== Disabling CLI Access

There may be certain circumstances in which you wish to disable the use of the CLI in your cluster.
To do this, add the `CLI_DISABLED` env variable to you config and set to `true`.

[source]
.minimal.yaml
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
    replicas: 3
    env:
     - name: "CLI_DISABLED"
       value: "true"
----

If you try to run the CLI you will get the following message:

[source]
----
cohctl has been disabled from running in the Coherence Operator
----
