///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Generating Heap Dumps

TBC

== Produce and extract a heap dump

// We will produce a heap dump on OOM error by default see clusters/080_jvm.adoc

// see this article https://danlebrero.com/2018/11/20/how-to-do-java-jvm-heapdump-in-kubernetes/
// for some ideas on handling heap dumps. We do not support the side-car thing but the notes about
// emptyDir{} which is our default setting are interesting.
