///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Generating Heap Dumps

Some of the debugging techniques described in https://docs.oracle.com/en/middleware/fusion-middleware/coherence/12.2.1.4/develop-applications/debugging-coherence.html[Debugging in Coherence]
require the creation of files, such as log files and JVM heap dumps, for analysis. You can also create and extract these files in the Coherence Operator.

== Produce and extract a heap dump

This example shows how to collect a .hprof file for a heap dump.

A single-command technique is also included at the end of this sample.

NOTE: Coherence Pods are configured to  produce a heap dump on OOM error by default. See
<<clusters/080_jvm.adoc, Configure The JVM>> for more information.

NOTE: You cal also trigger a heap dump via the https://docs.oracle.com/en/middleware/fusion-middleware/coherence/12.2.1.4/rest-reference/op-management-coherence-cluster-members-memberidentifier-dumpheap-post.html[Management over REST API].

=== 1. Install a Coherence Cluster

Deploy a simple `CoherenceCluster` resource with a single role like this:
[source,yaml]
.heapdump-cluster.yaml
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: heapdump-cluster
spec:
  role: storage        
  replicas: 3
----

NOTE: Add an `imagePullSecrets` entry if required to pull images from a private repository.

[source,bash]
----
kubectl create -n <namespace> -f  heapdump-cluster.yaml

coherencecluster.coherence.oracle.com/heapdump-cluster created

kubectl -n <namespace> get pod -l coherenceCluster=heapdump-cluster

NAME                         READY   STATUS    RESTARTS   AGE
heapdump-cluster-storage-0   1/1     Running   0          59s
heapdump-cluster-storage-1   1/1     Running   0          59s
heapdump-cluster-storage-2   1/1     Running   0          59s
----

=== 2. Obtain the PID of the Coherence process

Obtain the PID of the Coherence process. Generally, the PID is 1. You can also use jps to get the actual PID.

[source,bash]
----
kubectl exec -it -n coherence-example heapdump-cluster-storage-0 -- bash

$  jps
1 Main
153 Jps
----

NOTE: The process with `Main` is the main process that calls `DefaultCacheServer` to start a cluster node.

=== 3. Use the jcmd command to extract the heap dump

[source,bash]
----
$ rm -f /tmp/heap.hprof
$ /usr/java/default/bin/jcmd 1 GC.heap_dump /tmp/heap.hprof
$ exit
----

=== 4. Copy the heap dump to local machine

[source,bash]
----
kubectl cp <namespace>/heapdump-cluster-storage-0:/tmp/heap.hprof heap.hprof

tar: Removing leading `/' from member names

ls -l heap.hprof

-rw-r--r--  1 user  staff  21113314 15 Oct 08:50 heap.hprof
----

NOTE: Depending upon whether the Kubernetes cluster is local or remote, this might take some time.

=== 5. Single command usage

Assuming that the Coherence PID is 1, you can use this repeatable single-command technique to extract the heap dump:

[source,bash]
----
(kubectl exec heapdump-cluster-storage-0 -n <namespace>  -- /bin/bash -c \
  "rm -f /tmp/heap.hprof; /usr/java/default/bin/jcmd 1 GC.heap_dump /tmp/heap.hprof; cat /tmp/heap.hprof > /dev/stderr" ) 2> heap.hprof
----

=== 6. Clean Up

After running the above the Coherence cluster can be removed using `kubectl`:

[source,bash]
----
kubectl -n <namespace> delete -f heapdump-cluster.yaml
----
