///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Using VisualVM

https://visualvm.github.io/[VisualVM] is a visual tool integrating commandline JDK tools and lightweight profiling capabilities.
Designed for both development and production time use.

== Access the Coherence cluster via VisualVM

Coherence management is implemented using Java Management Extensions (JMX). JMX is a Java standard
for managing and monitoring Java applications and services. VisualVM and other JMX tools can be used to
manage and monitor Coherence Clusters via JMX.

This example shows how to connect to a cluster via VisualVM over JMXMP.

Please see <<020_manegement_over_rest.adoc,Management over ReST>> for how to connect
to a cluster via the VisualVM plugin using ReST.

NOTE: See the https://docs.oracle.com/en/middleware/fusion-middleware/coherence/12.2.1.4/manage/introduction-oracle-coherence-management.html[Coherence Management Documentation]
for more information on JMX and Management.