{{/* Copyright 2019, Oracle Corporation and/or its affiliates.  All rights reserved. */}}
{{/* Licensed under the Universal Permissive License v 1.0 as shown at               */}}
{{/* http://oss.oracle.com/licenses/upl.                                             */}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "coherence-operator.fullname" . }}
  labels:
{{- include "coherence-operator.release_labels" . | indent 4 }}
    component: "coherence-operator"
    name: coherence-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      coherenceOperatorCluster: {{ template "coherence-operator.fullname" . }}
      component: "coherence-operator"
  template:
    metadata:
      labels:
        coherenceOperatorCluster: {{ template "coherence-operator.fullname" . }}
        app: {{ template "coherence-operator.name" . }}
        release: {{ .Release.Name }}
        component: "coherence-operator"
        name: coherence-operator
    spec:
{{- if .Values.serviceAccount}}
  {{- if not ((eq .Values.serviceAccount "default")) }}
      serviceAccountName: {{ .Values.serviceAccount }}
  {{- end }}
{{- end }}
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end }}
# ---------------------------------------------------------------------------
# Node scheduling
# ---------------------------------------------------------------------------
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
# ---------------------------------------------------------------------------
#  Container: coherence-operator
# ---------------------------------------------------------------------------
        - name: {{ .Chart.Name }}
          image: {{ .Values.coherenceOperator.image }}
          imagePullPolicy: {{ .Values.coherenceOperator.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: HELM_COHERENCE_IMAGE
              value: {{ .Values.coherenceOperator.defaultCoherenceImage | quote }}
            - name: UTILS_IMAGE
              value: {{ .Values.coherenceOperator.defaultCoherenceUtilsImage | quote }}
          ports:
            - name: "rest"
              containerPort: 8000
            - name: "metrics"
              containerPort: 8383
            - name: "oper-metrics"
              containerPort: 8686
# ---------------------------------------------------------------------------
#         environment variables
# ---------------------------------------------------------------------------
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "coherence-operator"
{{- if .Values.statusHARetry }}
            - name: STATUS_HA_RETRY
              value: {{ .Values.statusHARetry | quote }}
{{- end }}
