# --------------------------------------------------------------------
# This is the Cluster Role binding required by the Coherence Operator
# to self-manage its CRDs and Web-Hooks.
# --------------------------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-install-rolebinding
  labels:
    app.kubernetes.io/name: coherence-operator
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-install-role
subjects:
- kind: ServiceAccount
  name: service-account
  namespace: default
