# Copyright 2019, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

{{- $releaseName := .Release.Name -}}
{{- $releaseNamespace := .Release.Namespace -}}
{{- $serviceAccount := .Values.serviceAccount }}
{{- if .Values.serviceAccount }}
  {{- if not ((eq .Values.serviceAccount "default")) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  labels:
    {{- include "coherence-operator.release_labels" . | indent 4 }}
    component: coherence-operator-service-account
---
  {{- end }}
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $releaseNamespace }}-coherence-operator-cluster-role
  labels:
    release: {{ $releaseName }}
    component: coherence-operator-cluster-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
{{- if .Values.logCaptureEnabled }}
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $releaseNamespace }}-coherence-operator-cluster-role-binding
  labels:
    release: {{ $releaseName }}
    component: coherence-operator-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $releaseNamespace }}-coherence-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccount }}
    namespace: {{ $releaseNamespace }}
{{- if .Values.logCaptureEnabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $releaseNamespace }}-coherence-operator-secrets-cluster-role
  labels:
    release: {{ $releaseName }}
    component: coherence-operator-secrets-cluster-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "update"]
---
  {{- if .Values.targetNamespaces }}
    {{- range .Values.targetNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coherence-operator-secrets-role-binding
  namespace: {{ . | quote }}
  labels:
    release: {{ $releaseName }}
    component: coherence-operator-secrets-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $releaseNamespace }}-coherence-operator-secrets-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccount }}
    namespace: {{ $releaseNamespace }}
---
    {{- end }}
  {{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $releaseNamespace }}-coherence-operator-secrets-cluster-role-binding
  labels:
    release: {{ $releaseName }}
    component: coherence-operator-secrets-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $releaseNamespace }}-coherence-operator-secrets-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccount }}
    namespace: {{ $releaseNamespace }}
  {{- end }}
{{- end }}
