{
 "title": "Coherence Alerts Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "README",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>This dashboard is purely used to generate useful alerts because of a limitation in Grafana that<br/>\ndoes not currently allow for using alerts when using template variables.\n<br/>\nThese items on this dashboard are not meant to be used for general monitoring.</h3></center>"
  },
  {
   "title": "Recent Departures (last 5 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(delta(vendor_Coherence_Cluster_MembersDepartureCount[5m]))",
     "legendFormat": "Recent Cluster Departures"
    }
   ]
  },
  {
   "title": "Total Heap % Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(vendor_Coherence_Memory_HeapMemoryUsage_used / vendor_Coherence_Memory_HeapMemoryUsage_max) by(cluster) * 100",
     "legendFormat": "Cluster Name;:{{cluster}}"
    }
   ]
  },
  {
   "title": "Free Physical Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(vendor_Coherence_OS_FreePhysicalMemorySize / vendor_Coherence_OS_TotalPhysicalMemorySize)  by (machine) * 100",
     "legendFormat": "Free Physical Memory: {{machine}}"
    }
   ]
  },
  {
   "title": "Unbalanced Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(avg(vendor_Coherence_Service_PartitionsUnbalanced{type=~\"DistributedCache|FederatedCache\"}) by(name) > 0)",
     "legendFormat": "Endangered Services"
    }
   ]
  },
  {
   "title": "Endangered  Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(vendor_Coherence_PartitionAssignment_HAStatusCode <= 1)",
     "legendFormat": "Endangered Services"
    }
   ]
  },
  {
   "title": "Recent Guardian Recoveries  (last 5 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(delta(vendor_Coherence_Node_GuardRecoverCount[5m]))",
     "legendFormat": "Recent Guardian Recoveries"
    }
   ]
  },
  {
   "title": "Recent Guardian Terminations  (last 5 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(delta(vendor_Coherence_Node_GuardTerminateCount[5m]))",
     "legendFormat": "Recent Guardian Terminations"
    }
   ]
  },
  {
   "title": "Cluster Storage Members",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(vendor_Coherence_Cluster_Size)"
    }
   ]
  },
  {
   "title": "Federation Errors (last 5 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(delta(vendor_Coherence_Federation_DestinationStatus[5m]))",
     "legendFormat": "Recent Federation Errors"
    }
   ]
  },
  {
   "title": "Outgoing Byte Backlog",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_ConnectionManager_OutgoingByteBacklog",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}