{
 "title": "Coherence Cache Details Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor_Coherence_Cluster_Size, cluster)"
   },
   {
    "name": "ServiceName",
    "label": "Service Name",
    "query": "label_values(vendor_Coherence_Service_Member_Count{cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "CacheName",
    "label": "Cache Name",
    "query": "label_values(vendor_Coherence_Cache_Units_Bytes{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName'}, name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Cache Details - $ServiceName / $CacheName</h3></center>"
  },
  {
   "title": "Cache Size",
   "type": "singlestat",
   "description": "The size of number of entries in the cache.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Cache_Size{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName',name=~\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "Cache Memory",
   "type": "singlestat",
   "description": "Indicates memory utilized by the cache entries. \nNote: If the unit-calculator is not BINARY or the service is not a DistributedCache service, then the details may be incorrect.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Cache_Units_Bytes{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName',name=~\"$CacheName\"}) "
    }
   ]
  },
  {
   "title": "Index Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_StorageManager_IndexTotalUnits{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName',cache=~\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "Total Non-Optimized Queries",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_StorageManager_NonOptimizedQueryCount{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName',cache=~\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "Total Non-Optimized Query Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_StorageManager_NonOptimizedQueryTotalMillis{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName',cache=~\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "Max Query Duration",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(vendor_Coherence_StorageManager_MaxQueryDurationMillis{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName',cache=~\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "Cache And Index Memory for $CacheName",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Cache_Units_Bytes{cluster=~\"$ClusterName\",tier=\"back\",name=~\"$CacheName\"})",
     "legendFormat": "Cache Memory"
    },
    {
     "expr": "sum(vendor_Coherence_StorageManager_IndexTotalUnits{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', cache=~\"$CacheName\"})",
     "legendFormat": "Index Memory"
    }
   ]
  },
  {
   "title": "Cache Evictions for $CacheName",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_StorageManager_EvictionCount{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', cache=~\"$CacheName\"}) - sum(vendor_Coherence_StorageManager_EvictionCount{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', cache=~\"$CacheName\"} offset $__interval) ",
     "legendFormat": "Evictions"
    }
   ]
  },
  {
   "title": "Back Cache and Access Counts for Cache $CacheName",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Cache_Size{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Units_Bytes{cluster=~\"$ClusterName\",tier=\"back\",name=~\"$CacheName\"}) by(member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Total_Gets{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Total_Puts{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Hits{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Prunes{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Misses{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Hits{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"back\"}) by (member) / (sum(vendor_Coherence_Cache_Hits{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"back\"}) by (member) + sum(vendor_Coherence_Cache_Misses{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"back\"}) by (member) ) "
    }
   ]
  },
  {
   "title": "Back Cache and Access Times for Cache $CacheName",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Cache_Total_Gets_Millis{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Total_Puts_Millis{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Hits_Millis{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Prunes_Millis{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Misses_Millis{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Storage_Max_Query_Duration_Millis{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', cache=~\"$CacheName\"}) by (member)"
    }
   ]
  },
  {
   "title": "Cache Storage Details for Cache $CacheName",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Storage_Listener_Registrations{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Storage_Eviction_Count{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Storage_Non_Optimized_Query_Count{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Storage_Optimized_Query_Count{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Storage_Index_Total_Units{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_StorageManager_NonOptimizedQueryTotal_Millis{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_StorageManager_MaxQueryDurationMillis{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_StorageManager_EvictionCount{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_StorageManager_LocksPending{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_StorageManager_LocksGranted{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', cache=~\"$CacheName\"}) by (member)"
    }
   ]
  },
  {
   "title": "Front Cache and Access Counts for Cache $CacheName",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Cache_Size{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"front\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Total_gets{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"front\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Total_Puts{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"front\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Hits{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"front\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Misses{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"front\"}) by (member)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Hits{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"front\"}) by (member) / (sum(vendor_Coherence_Cache_Hits{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"front\"}) by (member) + sum(vendor_Coherence_Cache_Misses{cluster=~\"$ClusterName\",coherence_service=~'$ServiceName', name=~\"$CacheName\", tier=\"front\"}) by (member) ) "
    }
   ]
  }
 ]
}