{
 "title": "Coherence Caches Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor_Coherence_Cluster_Size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor_Coherence_Cluster_Size{cluster=~\"$ClusterName\"}, version)"
   },
   {
    "name": "Services",
    "label": "Services",
    "query": "label_values(vendor_Coherence_Service_Request_Max_Duration{cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "Caches",
    "label": "Caches",
    "query": "label_values(vendor_Coherence_Cache_Size{cluster=~\"$ClusterName\"}, name) "
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Caches Summary - $ClusterName</h3></center>"
  },
  {
   "title": "Cache List",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Cache_Units_Bytes{cluster=~\"$ClusterName\",tier=\"back\"}) by (coherence_service, name)"
    },
    {
     "expr": "sum(vendor_Coherence_Cache_Size{cluster=~\"$ClusterName\",tier=\"back\"}) by (coherence_service, name)"
    }
   ]
  },
  {
   "title": "Cache Data Memory Usage",
   "type": "graph",
   "description": "Shows a graph of cache related memory used.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Cache_Units_Bytes{cluster=~\"$ClusterName\",tier=\"back\"})",
     "legendFormat": "Cache Memory"
    },
    {
     "expr": "sum(vendor_Coherence_Storage_Manager_Index_Total_units{cluster=~\"$ClusterName\"})",
     "legendFormat": "Index Memory"
    }
   ]
  },
  {
   "title": "Cache Index Size",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Storage_Manager_Index_Total_Units{cluster=~\"$ClusterName\"}) by (coherence_service, cache )"
    }
   ]
  },
  {
   "title": "Total Cache Evictions",
   "type": "graph",
   "description": "Shows a graph of total cache evictions across all caches and members.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Storage_Manager_Eviction_Count{cluster=~\"$ClusterName\"}) - sum(vendor_Coherence_Storage_Manager_Eviction_Count{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Total Evictions"
    }
   ]
  }
 ]
}