{
 "title": "Coherence Dashboard Main",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor_Coherence_Cluster_Size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor_Coherence_Cluster_Size{cluster=~\"$ClusterName\"}, version)"
   },
   {
    "name": "Services",
    "label": "Services",
    "query": "label_values(vendor_Coherence_Service_RequestMaxDuration{cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "Caches",
    "label": "Caches",
    "query": "label_values(vendor_Coherence_Cache_Size{cluster=~\"$ClusterName\"}, name) "
   },
   { "name": "TopLimit", "label": "Top N Limit", "query": "1,3,5,10,15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Cluster Overview - $CoherenceVersion</h3></center>"
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    { "title": "Current Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 } },
    { "title": "Recent Alert State Changes", "type": "alertlist", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 } }
   ]
  },
  {
   "title": "Cluster Overview - $ClusterName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Cluster Members",
   "type": "singlestat",
   "description": "Shows the number of cluster members.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vendor_Coherence_Cluster_Size{cluster=~\"$ClusterName\"})  "
    }
   ]
  },
  {
   "title": "Recent Departures",
   "type": "singlestat",
   "description": "Recent member departures.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(delta(vendor_Coherence_Cluster_MembersDepartureCount{cluster=~\"$ClusterName\"}[5m])) >= 0"
    }
   ]
  },
  {
   "title": "Endangered Services",
   "type": "singlestat",
   "description": "The number of services with endangered partitions.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vendor_Coherence_PartitionAssignment_HAStatusCode{cluster=~\"$ClusterName\"} <= 1)"
    }
   ]
  },
  {
   "title": "Used Cluster Heap",
   "type": "singlestat",
   "description": "Total used cluster heap across all members after GC.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\"})"
    }
   ]
  },
  {
   "title": "Total Cluster Heap",
   "type": "singlestat",
   "description": "Total available cluster heap across all members.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Max{cluster=~\"$ClusterName\"})"
    }
   ]
  },
  {
   "title": "Total Heap Memory Usage %",
   "type": "singlestat",
   "description": "Percentage of heap memory used across all members.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\"}) / sum(vendor_Coherence_Memory_HeapAfterGC_Max{cluster=~\"$ClusterName\"}) * 100  "
    }
   ]
  },
  {
   "title": "Cluster Memory Details",
   "type": "graph",
   "description": "Total and used cluster memory (after GC) across all members (storage enabled and disabled). Please see tables and graphs directly below for breakdown by Role.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\"})",
     "legendFormat": "Used Cluster Memory"
    },
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Max{cluster=~\"$ClusterName\"})",
     "legendFormat": "Total Cluster Memory"
    }
   ]
  },
  {
   "title": "Current Load Averages",
   "type": "graph",
   "description": "Show the current load average across all machines.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(vendor_Coherence_OS_SystemLoadAverage{cluster=~\"$ClusterName\"}) by (machine)",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Total Heap Used By Role",
   "type": "table",
   "description": "Total heap usage summarized by role.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg(count(vendor_Coherence_Memory_HeapAfterGC_Max{cluster=~\"$ClusterName\"}) by (role, name)) by (role)"
    },
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\"}) by (role)"
    },
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Max{cluster=~\"$ClusterName\"}) by (role)"
    },
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\"}) by (role) / sum(vendor_Coherence_Memory_HeapAfterGC_Max{cluster=~\"$ClusterName\"}) by (role)  \n"
    }
   ]
  },
  {
   "title": "Memory Usage % by Role",
   "type": "graph",
   "description": "Memory usage percentage by member role.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\"}) by (role) / sum(vendor_Coherence_Memory_HeapAfterGC_Max{cluster=~\"$ClusterName\"}) by (role)  \n",
     "legendFormat": "Role: {{role}}"
    }
   ]
  },
  {
   "title": "Top $TopLimit Machines -  Physical Memory",
   "type": "table",
   "description": "The top  $TopLimit Members that have the lowest physical memory % available.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "bottomk($TopLimit, avg(vendor_Coherence_OS_FreePhysicalMemorySize{cluster=~\"$ClusterName\"}/ vendor_Coherence_OS_TotalPhysicalMemorySize{cluster=~\"$ClusterName\"}) by (machine))"
    }
   ]
  },
  {
   "title": "Top $TopLimit Loaded Members  - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the highest CPU Load % over the current time range.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "topk($TopLimit, sum(avg_over_time(vendor_Coherence_OS_ProcessCpuLoad{cluster=~\"$ClusterName\"}[$__range] )) by (member))"
    }
   ]
  },
  {
   "title": "Top $TopLimit Members - Heap Used % - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the highest heap memory % used over the current time range.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "topk($TopLimit, avg(avg_over_time(vendor_Coherence_Memory_HeapMemoryUsage_used{cluster=~\"$ClusterName\"}[$__range]) / avg_over_time(vendor_Coherence_Memory_HeapMemoryUsage_max{cluster=~\"$ClusterName\"}[$__range])) by (member))"
    }
   ]
  },
  {
   "title": "Top $TopLimit Members - Total GC Time -  Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the greatest  Total GC Time over the current time range.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": " topk($TopLimit,sum(delta(vendor_Coherence_GC_CollectionTime{cluster=~\"$ClusterName\"}[$__range])) by (member)) > 0"
    }
   ]
  },
  {
   "title": "Top $TopLimit Members - Task Count -  Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the greatest change in the Task Count over the current time range.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": " topk($TopLimit,sum(delta(vendor_Coherence_Service_TaskCount{cluster=~\"$ClusterName\"}[$__range])) by (member)) > 0"
    }
   ]
  },
  {
   "title": "Top $TopLimit Services - Task Count - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Services  that have the greatest change in the Task Count over the current time range.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": " topk($TopLimit,sum(delta(vendor_Coherence_Service_TaskCount{cluster=~\"$ClusterName\"}[$__range])) by (name)) > 0"
    }
   ]
  },
  {
   "title": "Task Backlog By Member",
   "type": "graph",
   "description": "Total task backlog per member.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Service_TaskBacklog{cluster=~\"$ClusterName\"}) by (member) > 0",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Task Backlog By Service",
   "type": "graph",
   "description": "Total task backlog by service.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Service_TaskBacklog{cluster=~\"$ClusterName\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Proxy Outgoing Byte Backlog by Service",
   "type": "graph",
   "description": "Total Proxy Outgoing Byte Backlog by Service",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_ConnectionManager_OutgoingByteBacklog{cluster=~\"$ClusterName\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current Suspect Services - Unbalanced Partitions",
   "type": "table",
   "description": "Services that  have unbalanced partitions.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "avg(vendor_Coherence_Service_PartitionsUnbalanced{cluster=~\"$ClusterName\", type=~\"DistributedCache|FederatedCache\"}) by(name) > 0"
    }
   ]
  },
  {
   "title": "Top $TopLimit Members - Network -  Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the greatest change in sent and received messages over the current time range.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "topk($TopLimit, sum(vendor_Coherence_Node_PacketsSent{cluster=~\"$ClusterName\"} + vendor_Coherence_Node_PacketsReceived{cluster=~\"$ClusterName\"}  - vendor_Coherence_Node_PacketsSent{cluster=~\"$ClusterName\"} offset $__range -   vendor_Coherence_Node_PacketsReceived{cluster=~\"$ClusterName\"} offset $__range) by (member))"
    }
   ]
  },
  {
   "title": "Current Top  $TopLimit Cache Max Query Times",
   "type": "table",
   "description": "The current top $TopLimit caches, services and member with the highest Max Query Time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "topk($TopLimit, sum(vendor_Coherence_StorageManager_MaxQueryDurationMilis{cluster=~\"$ClusterName\"}) by (member, service, cache)) > 0"
    }
   ]
  },
  {
   "title": "Current Top $TopLimit Non-Optimized Queries",
   "type": "table",
   "description": "The current top $TopLimit nodes with the highest number of Non-Optimized Queries.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "topk($TopLimit, sum(vendor_Coherence_StorageManager_NonOptimizedQueryCount{cluster=~\"$ClusterName\"}) by (member, service, cache))> 0"
    }
   ]
  },
  {
   "title": "Guardian Recoveries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Node_GuardRecoverCount{cluster=~\"$ClusterName\"} - vendor_Coherence_Node_GuardRecoverCount{cluster=~\"$ClusterName\"} offset $__interval > 0",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Guardian Terminations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Node_GuardTerminateCount{cluster=~\"$ClusterName\"} - vendor_Coherence_Node_GuardTerminateCount{cluster=~\"$ClusterName\"}  offset $__interval > 0",
     "legendFormat": "{{member}}"
    }
   ]
  }
 ]
}