{
 "title": "Coherence Federation Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor_Coherence_Cluster_Size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor_Coherence_Cluster_Size{cluster=~\"$ClusterName\"}, version)"
   },
   { "name": "TopLimit", "label": "Top N Limit", "query": "1,3,5,10,15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Federation Summary - $ClusterName</h3></center>"
  },
  {
   "title": "Destinations",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "count(vendor_Coherence_Federation_Destination_TotalMsgSent {cluster=~\"$ClusterName\"})by (coherence_service, name, participant_type)"
    },
    {
     "expr": "avg(vendor_Coherence_Federation_Destination_Status {cluster=~\"$ClusterName\"}) by (coherence_service, name, participant_type)"
    }
   ]
  },
  {
   "title": "Origins",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "count(vendor_Coherence_Federation_Origin_TotalMsgReceived {cluster=~\"$ClusterName\"}) by (coherence_service, name)"
    }
   ]
  },
  {
   "title": "Entries Sent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Destination_TotalEntriesSent {cluster=~\"$ClusterName\"})"
    }
   ]
  },
  {
   "title": "Records Sent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Destination_TotalRecordsSent {cluster=~\"$ClusterName\"})"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Destination_TotalMsgSent {cluster=~\"$ClusterName\"})"
    }
   ]
  },
  {
   "title": "Entries Received",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Origin_TotalEntriesReceived {cluster=~\"$ClusterName\"})"
    }
   ]
  },
  {
   "title": "Records Received",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Origin_TotalRecordsReceived {cluster=~\"$ClusterName\"})"
    }
   ]
  },
  {
   "title": "Messages Received",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Origin_TotalMsgReceived {cluster=~\"$ClusterName\"})"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Destination_TotalBytesSent {cluster=~\"$ClusterName\"}) - sum(vendor_Coherence_Federation_Destination_TotalBytesSent {cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Destination: {{name}}"
    }
   ]
  },
  {
   "title": "Total Bytes Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Origin_TotalBytesReceived{cluster=~\"$ClusterName\"}) - sum(vendor_Coherence_Federation_Origin_TotalBytesReceived {cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Origin: {{name}}"
    }
   ]
  },
  {
   "title": "Total Messages Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Destination_TotalMsgSent {cluster=~\"$ClusterName\"}) - sum(vendor_Coherence_Federation_Destination_TotalMsgSent {cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Destination: {{name}}"
    }
   ]
  },
  {
   "title": "Total Messages Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Origin_TotalMsgReceived {cluster=~\"$ClusterName\"}) - sum(vendor_Coherence_Federation_Origin_TotalMsgReceived {cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Origin: {{name}}"
    }
   ]
  },
  {
   "title": "Total Records Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Destination_TotalRecordsSent{cluster=~\"$ClusterName\"}) - sum(vendor_Coherence_Federation_Destination_TotalRecordsSent {cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Destination: {{name}}"
    }
   ]
  },
  {
   "title": "Total Records Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Origin_TotalRecordsReceived{cluster=~\"$ClusterName\"}) - sum(vendor_Coherence_Federation_Origin_TotalRecordsReceived {cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Origin: {{name}}"
    }
   ]
  },
  {
   "title": "Total Entries Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Destination_TotalEntriesSent {cluster=~\"$ClusterName\"}) - sum(vendor_Coherence_Federation_Destination_TotalEntriesSent {cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Destination: {{name}}"
    }
   ]
  },
  {
   "title": "Total Entries Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Origin_TotalEntriesReceived {cluster=~\"$ClusterName\"}) - sum(vendor_Coherence_Federation_Origin_TotalEntriesReceived {cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Origin: {{name}}"
    }
   ]
  }
 ]
}