{
 "title": "Coherence Federation Details Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor_Coherence_Cluster_Size, cluster)"
   },
   {
    "name": "Destination",
    "label": "Destination",
    "query": "label_values(vendor_Coherence_Federation_Destination_TotalBytesSent {cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "ServiceName",
    "label": "Service Name",
    "query": "label_values(vendor_Coherence_Federation_Destination_TotalBytesSent {cluster=~\"$ClusterName\",name=~\"$Destination\"}, coherence_service)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Federation Details - $ServiceName, Destiniation - $Destination</h3></center>"
  },
  {
   "title": "Destinations",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Destination_TotalBytesSent {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'})by (coherence_service, name, participant_type, nodeId)"
    },
    {
     "expr": "sum(vendor_Coherence_Federation_Destination_TotalEntriesSent {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'})by (coherence_service, name, participant_type, nodeId)"
    },
    {
     "expr": "sum(vendor_Coherence_Federation_Destination_TotalMsgSent {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'})by (coherence_service, name, participant_type, nodeId)"
    },
    {
     "expr": "sum(vendor_Coherence_Federation_Destination_TotalRecordsSent {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'})by (coherence_service, name, participant_type, nodeId)"
    },
    {
     "expr": "sum(vendor_Coherence_Federation_Destination_ReplicateAllTotalTimeMillis{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'})by (coherence_service, name, participant_type, nodeId)"
    },
    {
     "expr": "avg(vendor_Coherence_Federation_Destination_Status{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'})by (coherence_service, name, participant_type, nodeId)"
    }
   ]
  },
  {
   "title": "Data Sent  per Member",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Federation_Destination_TotalBytesSent{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'} - vendor_Coherence_Federation_Destination_TotalBytesSent{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'} offset $__interval ",
     "legendFormat": "Node: {{nodeId}}"
    }
   ]
  },
  {
   "title": "Entries Sent per Member",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Federation_Destination_TotalEntriesSent{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'} - vendor_Coherence_Federation_Destination_TotalEntriesSent{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'} offset $__interval ",
     "legendFormat": "Node: {{nodeId}}"
    }
   ]
  },
  {
   "title": "Entries Sent per Member",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Federation_Destination_TotalRecordsSent{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'} - vendor_Coherence_Federation_Destination_TotalRecordsSent{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'} offset $__interval ",
     "legendFormat": "Node: {{nodeId}}"
    }
   ]
  },
  {
   "title": "Errors and Un-Acked Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Federation_Destination_TotalErrorResponses{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'} - vendor_Coherence_Federation_Destination_TotalErrorResponses{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'} offset $__interval ",
     "legendFormat": "Error Responses Node: {{nodeId}}"
    },
    {
     "expr": "sum(vendor_Coherence_Federation_Destination_TotalMsgUnacked{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'}) by (nodeId)",
     "legendFormat": "Message Unacked Node: {{nodeId}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "content": "<center><h3>Federation Details - $ServiceName, Origin - $Destination</h3></center>"
  },
  {
   "title": "Origins",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Origin_TotalBytesReceived {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'})by (coherence_service, name, nodeId)"
    },
    {
     "expr": "sum(vendor_Coherence_Federation_Origin_TotalEntriesReceived {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'})by (coherence_service, name, nodeId)"
    },
    {
     "expr": "sum(vendor_Coherence_Federation_Origin_TotalRecordsReceived {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'})by (coherence_service, name, nodeId)"
    },
    {
     "expr": "sum(vendor_Coherence_Federation_Origin_TotalMsgReceived {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'})by (coherence_service, name, nodeId)"
    }
   ]
  },
  {
   "title": "Origins Member Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Origin_TotalBytesReceived {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'})by (coherence_service, name, nodeId, member)"
    },
    {
     "expr": "sum(vendor_Coherence_Federation_Origin_TotalMsgUnacked {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'})by (coherence_service, name, nodeId, member)"
    }
   ]
  },
  {
   "title": "Origins Un-Acked Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Federation_Destination_TotalMsgUnacked{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~'$ServiceName'}) by (nodeId)",
     "legendFormat": "Message Unacked Node: {{nodeId}}"
    }
   ]
  }
 ]
}