{
 "title": "Coherence gRPC Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor_Coherence_Cluster_Size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor_Coherence_Cluster_Size{cluster=~\"$ClusterName\"}, version)"
   },
   {
    "name": "Services",
    "label": "Services",
    "query": "label_values(vendor_Coherence_Service_RequestMaxDuration{cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "Caches",
    "label": "Caches",
    "query": "label_values(vendor_Coherence_Cache_Size{cluster=~\"$ClusterName\"}, name) "
   },
   { "name": "TopLimit", "label": "Top N Limit", "query": "1,3,10,15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>gRPC Summary - $ClusterName</h3></center>"
  },
  {
   "title": "Total gRPC Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_events_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_aggregate_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_invoke_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_invokeAll_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_isEmpty_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_keySet_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_entrySet_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_values_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_nextEntrySetPage_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_nextKeySetPage_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsKey_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsValue_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsEntry_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_put_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_get_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_remove_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_replace_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_putAll_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_getAll_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_removeMapping_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_replaceMapping_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_size_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_clear_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_destroy_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_truncate_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_addIndex_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_removeIndex_total{cluster=~\"$ClusterName\"}\n) "
    }
   ]
  },
  {
   "title": "Total Cache Wide Operations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_size_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_clear_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_destroy_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_truncate_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_addIndex_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_removeIndex_total{cluster=~\"$ClusterName\"})"
    }
   ]
  },
  {
   "title": "Total Mutations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_put_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_get_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_remove_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_replace_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_putAll_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_getAll_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_removeMapping_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_replaceMapping_total{cluster=~\"$ClusterName\"}  ) "
    }
   ]
  },
  {
   "title": "Total Queries/ Data Access",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_isEmpty_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_keySet_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_entrySet_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_values_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_nextEntrySetPage_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_nextKeySetPage_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsKey_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsValue_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsEntry_total{cluster=~\"$ClusterName\"} ) "
    }
   ]
  },
  {
   "title": "Total Invocations/ Aggregations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_aggregate_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_invoke_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_invokeAll_total{cluster=~\"$ClusterName\"} ) "
    }
   ]
  },
  {
   "title": "Total events",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_events_total{cluster=~\"$ClusterName\"} ) "
    }
   ]
  },
  {
   "title": "gRPC Request Count by Category - All Members",
   "type": "table",
   "description": "Shows the total gRPC Requests for the various request categories.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_size_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_clear_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_destroy_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_truncate_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_addIndex_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_removeIndex_total{cluster=~\"$ClusterName\"}) by (member, node_id ,machine, role)"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_put_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_get_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_remove_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_replace_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_putAll_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_getAll_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_removeMapping_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_replaceMapping_total{cluster=~\"$ClusterName\"}  ) by (member, node_id ,machine, role)"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_isEmpty_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_keySet_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_entrySet_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_values_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_nextEntrySetPage_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_nextKeySetPage_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsKey_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsValue_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsEntry_total{cluster=~\"$ClusterName\"}  ) by (member, node_id ,machine, role)"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_aggregate_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_invoke_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_invokeAll_total{cluster=~\"$ClusterName\"} ) by (member, node_id ,machine, role)"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_events_total) by (member, node_id ,machine, role)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "content": "<center><h3>Cache Wide Operations</h3></center>"
  },
  {
   "title": "Cache Wide Operations Count - All Members",
   "type": "graph",
   "description": "Shows the number of cache wide operations such as  size, clear, destroy, truncate, add index and remove index.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_size_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_size_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Size"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_clear_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_clear_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Clear"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_destroy_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_destroy_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Destroy"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_truncate_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_truncate_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Truncate"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_addIndex_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_addIndex_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Add Index"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_removeIndex_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_removeIndex_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Remove Index"
    }
   ]
  },
  {
   "title": "Cache Wide Operations - Rate per Second - All Members",
   "type": "graph",
   "description": "Shows the operation rate/ second over  the last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_size_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Size"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_clear_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Clear"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_destroy_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Destroy"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_truncate_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Truncate"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_addIndex_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Add Index"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_removeIndex_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Remove Index"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "content": "<center><h3>Mutations</h3></center>"
  },
  {
   "title": "Mutation Count - All Members",
   "type": "graph",
   "description": "Shows the number of mutations such as  put, get, remove, replace, getAll, putAll, removeMapping and replaceMapping.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_put_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_put_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Put"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_get_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_get_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_remove_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_remove_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Remove"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_replace_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_replace_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Replace"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_getAll_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_getAll_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Get All"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_putAll_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_putAll_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Put All"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_removeMapping_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_removeMapping_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Remove Mapping"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_replaceMapping_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_replaceMapping_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Replace Mapping"
    }
   ]
  },
  {
   "title": "Mutations - Rate per Second - All Members",
   "type": "graph",
   "description": "Shows the operation rate/ second over  the last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_put_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Put"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_get_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Get"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_remove_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Remove"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_replace_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Replace"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_putAll_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Put All"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_getAll_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Get All"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_removeMapping_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Remove Mapping"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_replaceMapping_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Replace Mapping"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 },
   "content": "<center><h3>Queries/ Data Access</h3></center>"
  },
  {
   "title": "Queries/ Data Access Count - All Members",
   "type": "graph",
   "description": "Shows the number of query or access operations such as  isEmpty, keySet, entrySet, values, nextEntrySet, nextKeySet, containsKey, containsValue and containsEntry.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_isEmpty_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_isEmpty_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Is Empty"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_keySet_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_keySet_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Key Set"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_entrySet_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_entrySet_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Entry Set"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_values_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_values_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Values"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_nextEntrySetPage_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_nextEntrySetPage_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Next Entry Set Page"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_nextKeySetPage_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_nextKeySetPage_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Next Key Set Page"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_containsKey_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsKey_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Contains Key"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_containsValue_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsValue_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Contains Value"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_containsEntry_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsEntry_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Contains Entry"
    }
   ]
  },
  {
   "title": "Queries/ Data Access Rate per Second - All Members",
   "type": "graph",
   "description": "Shows the operation rate/ second over  the last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_put_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Put"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_get_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Get"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_remove_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Remove"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_replace_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Replace"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_putAll_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Put All"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_getAll_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Get All"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_removeMapping_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Remove Mapping"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_replaceMapping_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Replace Mapping"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 44 },
   "content": "<center><h3>Invocations/ Aggregations</h3></center>"
  },
  {
   "title": "Invocations/ Aggregations Count - All Members",
   "type": "graph",
   "description": "Shows the number of event based operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_aggregate_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_aggregate_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Aggregate"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_invoke_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_invoke_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Invoke"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_invokeAll_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_invokeAll_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Invoke All"
    }
   ]
  },
  {
   "title": "Invocations/ Aggregations Rate per Second - All Members",
   "type": "graph",
   "description": "Shows the operation rate/ second over  the last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_aggregate_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Aggregate"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_invoke_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Invoke"
    },
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_invokeAll_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Invoke All"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 54 },
   "content": "<center><h3>Events</h3></center>"
  },
  {
   "title": "Event Count - All Members",
   "type": "graph",
   "description": "Shows the number of event based operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_events_total{cluster=~\"$ClusterName\"} -\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_events_total{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Events"
    }
   ]
  },
  {
   "title": "Event Rate per Second - All Members",
   "type": "graph",
   "description": "Shows the operation rate/ second over  the last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(application_com_oracle_coherence_grpc_proxy_NamedCacheService_events_one_min_rate_per_second{cluster=~\"$ClusterName\"})",
     "legendFormat": "Events"
    }
   ]
  }
 ]
}