{
 "title": "Coherence HTTP Servers Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor_Coherence_Cluster_Size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor_Coherence_Cluster_Size{cluster=~\"$ClusterName\"}, version)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>HTTP Servers Summary - $ClusterName</h3></center>"
  },
  {
   "title": "HTTP Servers List",
   "type": "table",
   "description": "Coherence based HTTP servers",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "count(vendor_Coherence_ConnectionManager_TotalRequestCount{cluster=~\"$ClusterName\",protocol=~\"http\"}) by (name) "
    },
    {
     "expr": "sum(vendor_Coherence_ConnectionManager_TotalRequestCount{cluster=~\"$ClusterName\",protocol=~\"http\"}) by (name) "
    },
    {
     "expr": "sum(vendor_Coherence_ConnectionManager_TotalErrorCount{cluster=~\"$ClusterName\",protocol=~\"http\"}) by (name) "
    },
    {
     "expr": "sum(vendor_Coherence_ConnectionManager_AverageRequestTime{cluster=~\"$ClusterName\",protocol=~\"http\"}) by (name) "
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "HTTP Requests for Coherence based HTTP servers",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_ConnectionManager_TotalRequestCount{cluster=~\"$ClusterName\",protocol=~\"http\"} - vendor_Coherence_ConnectionManager_TotalRequestCount{cluster=~\"$ClusterName\",protocol=~\"http\"} offset $__interval ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "graph",
   "description": "HTTP Response Codes for Coherence based HTTP servers",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_ConnectionManager_response_1xx_count{cluster=~\"$ClusterName\",protocol=~\"http\"}  - vendor_Coherence_ConnectionManager_response_1xx_count{cluster=~\"$ClusterName\",protocol=~\"http\"} offset $__interval ",
     "legendFormat": "{{name}} 100-199"
    },
    {
     "expr": "vendor_Coherence_ConnectionManager_response_2xx_count{cluster=~\"$ClusterName\",protocol=~\"http\"}  - vendor_Coherence_ConnectionManager_response_2xx_count{cluster=~\"$ClusterName\",protocol=~\"http\"} offset $__interval ",
     "legendFormat": "{{name}} 200-299"
    },
    {
     "expr": "vendor_Coherence_ConnectionManager_response_3xx_count{cluster=~\"$ClusterName\",protocol=~\"http\"}  - vendor_Coherence_ConnectionManager_response_3xx_count{cluster=~\"$ClusterName\",protocol=~\"http\"} offset $__interval ",
     "legendFormat": "{{name}} 300-399"
    },
    {
     "expr": "vendor_Coherence_ConnectionManager_response_4xx_count{cluster=~\"$ClusterName\",protocol=~\"http\"}  - vendor_Coherence_ConnectionManager_response_4xx_count{cluster=~\"$ClusterName\",protocol=~\"http\"} offset $__interval ",
     "legendFormat": "{{name}} 400-499"
    },
    {
     "expr": "vendor_Coherence_ConnectionManager_response_5xx_count{cluster=~\"$ClusterName\",protocol=~\"http\"}  - vendor_Coherence_ConnectionManager_response_5xx_count{cluster=~\"$ClusterName\",protocol=~\"http\"} offset $__interval ",
     "legendFormat": "{{name}} 500-599"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "content": "<center><h3>Microprofile HTTP Servers Summary - $ClusterName</h3></center>"
  },
  {
   "title": "HTTP Servers List",
   "type": "table",
   "description": "HTTP Servers for Microprofile based HTTP servers",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(vendor_requests_count_total{cluster=~\"$ClusterName\"}) by(member, role, namespace)"
    },
    {
     "expr": "sum(vendor_requests_meter_rate_per_second{cluster=~\"$ClusterName\"}) by(member, role, namespace)"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "HTTP Requests for Microprofile based HTTP servers",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_requests_count_total{cluster=~\"$ClusterName\"} - vendor_requests_count_total{cluster=~\"$ClusterName\"} offset $__interval) by(role)",
     "legendFormat": "Role: {{role}}"
    }
   ]
  }
 ]
}