{
 "title": "Coherence Kubernetes Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor_Coherence_Cluster_Size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor_Coherence_Cluster_Size{cluster=~\"$ClusterName\"}, version)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Kubernetes Summary - $ClusterName</h3></center>"
  },
  {
   "title": "Kubernetes Pod List",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "avg(vendor_Coherence_Cluster_Size{cluster=~\"$ClusterName\"}) by (pod, version, namespace)"
    }
   ]
  },
  {
   "title": "Pod Process CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(vendor_Coherence_OS_ProcessCpuLoad{cluster=~\"$ClusterName\"}) by (pod)",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Pod Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Memory_HeapMemoryUsage_used{cluster=~\"$ClusterName\"} ",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  }
 ]
}