{
 "title": "Coherence Member Details Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor_Coherence_Cluster_Size, cluster)"
   },
   {
    "name": "MemberName",
    "label": "Member Name",
    "query": "label_values(vendor_Coherence_Service_MemberCount{cluster=~\"$ClusterName\"}, member)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Member Details - $MemberName</h3></center>"
  },
  { "title": "Current  Details - $MemberName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Used Heap After GC",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\",member=~\"$MemberName\"})"
    }
   ]
  },
  {
   "title": "Max Heap",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "vendor_Coherence_Memory_HeapMemoryUsage_max{cluster=~\"$ClusterName\",member=~\"$MemberName\"}  "
    }
   ]
  },
  {
   "title": "Heap Used %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\",member=~\"$MemberName\"}) / sum(vendor_Coherence_Memory_HeapAfterGC_Max{cluster=~\"$ClusterName\",member=~\"$MemberName\"})  "
    }
   ]
  },
  {
   "title": "Publisher Success",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "vendor_Coherence_Node_PublisherSuccessRate{cluster=~\"$ClusterName\",member=~\"$MemberName\"} "
    }
   ]
  },
  {
   "title": "Receiver Success",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "vendor_Coherence_Node_ReceiverSuccessRate{cluster=~\"$ClusterName\",member=~\"$MemberName\"} "
    }
   ]
  },
  {
   "title": "Current Services Running on $MemberName",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {},
    {
     "expr": "sum(vendor_Coherence_Service_ThreadCount{cluster=~\"$ClusterName\",member=~\"$MemberName\"}) by (name) > 0"
    },
    {
     "expr": "sum(vendor_Coherence_Service_ThreadIdleCount{cluster=~\"$ClusterName\",member=~\"$MemberName\"}) by (name) > 0"
    },
    {
     "expr": "(sum(vendor_Coherence_Service_ThreadCount{cluster=~\"$ClusterName\",member=~\"$MemberName\"}) by (name) - sum(vendor_Coherence_Service_ThreadIdleCount{cluster=~\"$ClusterName\",member=~\"$MemberName\"}) by (name)) / (sum(vendor_Coherence_Service_ThreadCount{cluster=~\"$ClusterName\",member=~\"$MemberName\"}) by (name)) "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "content": "<center><h3>Memory and Garbage Collection</h3></center>"
  },
  {
   "title": "Heap Memory After GC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Max{cluster=~\"$ClusterName\", member=~\"$MemberName\"}) by (name) > 0",
     "legendFormat": "Max Heap: {{name}}"
    },
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\", member=~\"$MemberName\"}) by (name) > 0",
     "legendFormat": "Used  Heap After GC: {{name}}"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Memory_NonHeapMemoryUsage_used{cluster=~\"$ClusterName\", member=~\"$MemberName\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_Coherence_Memory_NonHeapMemoryUsage_committed{cluster=~\"$ClusterName\", member=~\"$MemberName\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_GC_CollectionCount{cluster=~\"$ClusterName\", member=~\"$MemberName\"} - vendor_Coherence_GC_CollectionCount{cluster=~\"$ClusterName\", member=~\"$MemberName\"} offset $__interval ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_GC_CollectionTime{cluster=~\"$ClusterName\", member=~\"$MemberName\"} - vendor_Coherence_GC_CollectionTime{cluster=~\"$ClusterName\", member=~\"$MemberName\"} offset $__interval ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "content": "<center><h3>Member Network Details</h3></center>"
  },
  {
   "title": "Packet Send Rate / Second",
   "type": "graph",
   "description": "The rate at which packets are being sent from this member.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(vendor_Coherence_Node_PacketsSent{cluster=~\"$ClusterName\", member=~\"$MemberName\"}[1m])  ",
     "legendFormat": "Packet Sent"
    }
   ]
  },
  {
   "title": "Packet Receive Rate / Second",
   "type": "graph",
   "description": "The rate at which packets are being received by this member.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(vendor_Coherence_Node_PacketsReceived{cluster=~\"$ClusterName\", member=~\"$MemberName\"}[1m])",
     "legendFormat": "Packets Received"
    }
   ]
  },
  {
   "title": "Publisher Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Node_PublisherSuccessRate{cluster=~\"$ClusterName\", member=~\"$MemberName\"}"
    }
   ]
  },
  {
   "title": "Receiver Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Node_ReceiverSuccessRate{cluster=~\"$ClusterName\", member=~\"$MemberName\"}"
    }
   ]
  },
  {
   "title": "Guardian Recoveries and Terminations",
   "type": "graph",
   "description": "The Guardian Recovery and Terminations over the current time range.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Node_GuardRecoverCount{cluster=~\"$ClusterName\", member=~\"$MemberName\"} - vendor_Coherence_Node_GuardRecoverCount{cluster=~\"$ClusterName\", member=~\"$MemberName\"} offset $__interval ",
     "legendFormat": "Guardian Recoveries"
    },
    {
     "expr": "vendor_Coherence_Node_GuardTerminateCount{cluster=~\"$ClusterName\", member=~\"$MemberName\"} - vendor_Coherence_Node_GuardTerminateCount{cluster=~\"$ClusterName\", member=~\"$MemberName\"} offset $__interval ",
     "legendFormat": "Guardian Terminations"
    }
   ]
  },
  {
   "title": "Send Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Node_SendQueueSize{cluster=~\"$ClusterName\", member=~\"$MemberName\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Microprofile HTTP Requests",
   "type": "graph",
   "description": "HTTP Requests for Microprofile based HTTP servers",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_requests_count_total{cluster=~\"$ClusterName\", member=~\"$MemberName\"} - vendor_requests_count_total{cluster=~\"$ClusterName\", member=~\"$MemberName\"} offset $__interval) by (member)",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "gRPC Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vendor_grpc_requests_count_total{cluster=~\"$ClusterName\", member=~\"$MemberName\"} - vendor_grpc_requests_count_totalionCount{cluster=~\"$ClusterName\", member=~\"$MemberName\"} offset $__interval",
     "legendFormat": "{{member}}"
    }
   ]
  }
 ]
}