{
 "title": "Coherence Proxy Server Detail Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor_Coherence_Cluster_Size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor_Coherence_Cluster_Size{cluster=~\"$ClusterName\"}, version)"
   },
   {
    "name": "ServiceName",
    "label": "Service Name",
    "query": "label_values(vendor_Coherence_ConnectionManager_TotalMessagesSent{cluster=~\"$ClusterName\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Proxy Servers Details - $ServiceName</h3></center>"
  },
  {
   "title": "Proxy Server Members for $ServiceName",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(vendor_Coherence_ConnectionManager_ConnectionCount{cluster=~\"$ClusterName\",name=~'$ServiceName'}) by (member, host_url)"
    },
    {
     "expr": "sum(vendor_Coherence_ConnectionManager_TotalMessagesReceived{cluster=~\"$ClusterName\",name=~'$ServiceName'}) by (member, host_url)"
    },
    {
     "expr": "sum(vendor_Coherence_ConnectionManager_TotalMessagesSent{cluster=~\"$ClusterName\",name=~'$ServiceName'}) by (member, host_url)"
    },
    {
     "expr": "sum(vendor_Coherence_ConnectionManager_TotalMessagesReceived {cluster=~\"$ClusterName\",name=~'$ServiceName'}) by (member, host_url)"
    },
    {
     "expr": "sum(vendor_Coherence_ConnectionManager_TotalBytesSent{cluster=~\"$ClusterName\",name=~'$ServiceName'}) by (member, host)"
    },
    {
     "expr": "sum(vendor_Coherence_ConnectionManager_OutgoingByteBacklog{cluster=~\"$ClusterName\",name=~'$ServiceName'}) by (member, host)"
    },
    {
     "expr": "sum(vendor_Coherence_ConnectionManager_UnauthorizedConnectionAttempts{cluster=~\"$ClusterName\",name=~'$ServiceName'}) by (member, host_url)"
    }
   ]
  },
  {
   "title": "Current Proxy Server Connections for $ServiceName",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(vendor_Coherence_ConnectionManager_ConnectionTimeMillis{cluster=~\"$ClusterName\",name=~'$ServiceName'}) by (remote_address, remote_port, member, nodeId)"
    }
   ]
  },
  {
   "title": "Outgoing Byte Backlog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_ConnectionManager_OutgoingByteBacklog{cluster=~\"$ClusterName\", name=~'$ServiceName', protocol=~\"tcp\"} > 0",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Outgoing Message Backlog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_ConnectionManager_OutgoingMessageBacklog{cluster=~\"$ClusterName\", name=~'$ServiceName'} > 0",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Total Bytes Sent/ sec - $ServiceName",
   "type": "graph",
   "description": "Total bytes sent (bytes/sec) of all Proxy Server members for $ServiceName.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_ConnectionManager_TotalBytesSent{cluster=~\"$ClusterName\",protocol=~\"tcp\", name=~'$ServiceName'} - vendor_Coherence_ConnectionManager_TotalBytesSent{cluster=~\"$ClusterName\",protocol=~\"tcp\", name=~'$ServiceName'} offset $__interval ",
     "legendFormat": "{{member}} Sent"
    }
   ]
  },
  {
   "title": "Total Bytes Received/ sec - $ServiceName",
   "type": "graph",
   "description": "Total bytes received (bytes/sec) of all Proxy Server members for $ServiceName.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_ConnectionManager_TotalMessagesReceived{cluster=~\"$ClusterName\",protocol=~\"tcp\"} - vendor_Coherence_ConnectionManager_TotalMessagesReceived{cluster=~\"$ClusterName\",protocol=~\"tcp\"} offset $__interval ",
     "legendFormat": "{{member}} Received"
    }
   ]
  }
 ]
}