apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: coherence-operator-catalog
  namespace: olm
spec:
  displayName: Oracle Coherence Operators
  image: IMAGE_NAME_PLACEHOLDER
  publisher: Oracle Corporation
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 60m
