apiVersion: v1
kind: ConfigMap
metadata:
  name: preflight
data:
  registry-config.json: |
    {
      "auths": {
        "default-route-openshift-image-registry.apps-crc.testing": {
          "auth": "Ym9ndXM6c2hhMjU2fkR1VmdQNndqLXNRd2xQaFVDVC1iS3gyTkhTREtQQ0Y1cGJETlVfcFBnaUU="
        }
      }
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: preflight
spec:
  template:
    spec:
      imagePullSecrets:
        - name: default-dockercfg-l28bp
      containers:
        - name: preflight
          image: "quay.io/opdev/preflight:stable"
          command:
            - preflight
            - check
            - container
            - --insecure
            - default-route-openshift-image-registry.apps-crc.testing/oracle/coherence-operator:3.4.3-arm64
          env:
            - name: PFLT_LOGLEVEL
              value: trace
            - name: PFLT_LOGFILE
              value: "/artifacts/preflight.log"
            - name: PFLT_ARTIFACTS
              value: "/artifacts"
            - name: PFLT_DOCKERCONFIG
              value: /registry-creds/registry-config.json
            - name: PFLT_CHANNEL
              value: "beta"
          volumeMounts:
            - name: "outputdir"
              mountPath: "/artifacts"
            - name: registry-config
              mountPath: /registry-creds
#            - name: "kubeconfig"
#              mountPath: "/creds"
      restartPolicy: Never
      volumes:
        - name: "outputdir"
          emptyDir:
            medium: ""
        - name: registry-config
          configMap:
            name: preflight
            optional: false
#        - name: kubeconfig
#          secret:
#            secretName: test-cluster-kubeconfig
#            optional: false
  backoffLimit: 2
