apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: coherence-client
    version: 1.0.0
spec:
  containers:
    - name: coherence
      image: coherence-client:1.0.0
      command:
        - /files/runner
        - sleep
        - "15m"
      env:
        - name: COHERENCE_CLIENT
          value: "grpc-fixed"
        - name: COHERENCE_GRPC_ADDRESS
          value: "storage-headless.coherence.svc"
        - name: COHERENCE_GRPC_PORT
          value: "1408"
