apiVersion: v1
kind: Service
metadata:
  name: storage-headless
spec:
  clusterIP: None
  selector:
    app: my-coherence-app
    version: 1.0.0
  ports:
    - name: coherence
      port: 7574
      targetPort: coherence
      appProtocol: tcp
    - name: coh-local
      port: 7575
      targetPort: coh-local
      appProtocol: tcp
    - name: extend-proxy
      port: 20000
      targetPort: extend-proxy
      appProtocol: tcp
    - name: grpc-proxy
      port: 1408
      targetPort: grpc-proxy
      appProtocol: grpc
    - name: management
      port: 30000
      targetPort: management
      appProtocol: http
    - name: metrics
      port: 9612
      targetPort: metrics
      appProtocol: http
