///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Add Secrets Volumes

Additional `Volumes` and `VolumeMounts` from `Secrets` can easily be added to a `Coherence` resource.

== Add Secrets Volumes

To add a `Secret` as an additional volume to the `Pods` of a Coherence deployment add entries to the
`secretVolumes` list in the CRD spec.
Each entry in the list has a mandatory `name` and `mountPath` field, all other fields are optional.
The `name` field is the name of the `Secret` to mount and is also used as the volume name.
The `mountPath` field is the path in the container to mount the volume to.

NOTE: Additional volumes added in this way (either `Secrets` shown here, or `Secrets` or plain `Volumes`) will be
added to all containers in the `Pod`.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  secretVolumes:
    - name: storage-config               # <1>
      mountPath: /home/coherence/config  # <2>
----
<1> The `Secret` named `storage-config` will be mounted to the `Pod` as an additional `Volume` named `storage-config`
<2> The `Secret` will be mounted at `/home/coherence/config` in the containers.

The yaml above would result in a `Pod` spec similar to the following (a lot of the `Pod` spec has been omitted to just
show the relevant volume information):
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: storage-0
spec:
  containers:
    - name: coherence
      volumeMounts:
        - name: storage-config
          mountPath: /home/coherence/config
  volumes:
    - name: storage-config
      secret:
        secretName: storage-config
----

As already stated, if the `Coherence` resource has additional containers the `Secret` will be mounted in all of them.

For example:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  additionalContainers:
    - name: fluentd
      image: "fluent/fluentd:v1.3.3"
  secretVolumes:
    - name: storage-config
      mountPath: /home/coherence/config
----

In this example the `storage-config` `Secret` will be mounted as a `Volume` and mounted to both the `coherence`
container and the `fluentd` container.
The yaml above would result in a `Pod` spec similar to the following (a lot of the `Pod` spec has been omitted to just
show the relevant volume information):

[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: storage-0
spec:
  containers:
    - name: coherence
      volumeMounts:
        - name: storage-config
          mountPath: /home/coherence/config
    - name: fluentd
      image: "fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch-1.3"
      volumeMounts:
        - name: storage-config
          mountPath: /home/coherence/config
  volumes:
    - name: storage-config
      secret:
        secretName: storage-config
----
