{
 "title": "Coherence Alerts Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "README",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>This dashboard is purely used to generate useful alerts because of a limitation in Grafana that<br/>\ndoes not currently allow for using alerts when using template variables.\n<br/>\nThese items on this dashboard are not meant to be used for general monitoring.</h3></center>"
  },
  {
   "title": "Recent Departures (last 5 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(delta(vendor:coherence_cluster_members_departure_count[5m]))",
     "legendFormat": "Recent Cluster Departures"
    }
   ]
  },
  {
   "title": "Total Heap % Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(vendor:coherence_memory_heap_memory_usage_used / vendor:coherence_memory_heap_memory_usage_max) by(cluster) * 100",
     "legendFormat": "Cluster Name;:{{cluster}}"
    }
   ]
  },
  {
   "title": "Free Physical Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(vendor:coherence_os_free_physical_memory_size / vendor:coherence_os_total_physical_memory_size)  by (machine) * 100",
     "legendFormat": "Free Physical Memory: {{machine}}"
    }
   ]
  },
  {
   "title": "Unbalanced Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(avg(vendor:coherence_service_partitions_unbalanced{type=~\"DistributedCache|FederatedCache\"}) by(name) > 0)",
     "legendFormat": "Endangered Services"
    }
   ]
  },
  {
   "title": "Endangered  Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(vendor:coherence_partition_assignment_ha_status_code <= 1)",
     "legendFormat": "Endangered Services"
    }
   ]
  },
  {
   "title": "Recent Guardian Recoveries  (last 5 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(delta(vendor:coherence_node_guard_recover_count[5m]))",
     "legendFormat": "Recent Guardian Recoveries"
    }
   ]
  },
  {
   "title": "Recent Guardian Terminations  (last 5 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(delta(vendor:coherence_node_guard_terminate_count[5m]))",
     "legendFormat": "Recent Guardian Terminations"
    }
   ]
  },
  {
   "title": "Cluster Storage Members",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(vendor:coherence_cluster_size)"
    }
   ]
  },
  {
   "title": "Federation Errors (last 5 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(delta(vendor:coherence_federation_destination_status[5m]))",
     "legendFormat": "Recent Federation Errors"
    }
   ]
  },
  {
   "title": "Outgoing Byte Backlog",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_connection_manager_outgoing_byte_backlog",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}