{
 "title": "Coherence Cache Store Details Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "ServiceName",
    "label": "Service Name",
    "query": "label_values(vendor:coherence_service_member_count{cluster=\"$ClusterName\"}, name)"
   },
   {
    "name": "CacheName",
    "label": "Cache Name",
    "query": "label_values(vendor:coherence_cache_units_bytes{cluster=\"$ClusterName\",coherence_service='$ServiceName'}, name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Cache Store Details - $ServiceName / $CacheName</h3></center>"
  },
  {
   "title": "Cache Size",
   "type": "singlestat",
   "description": "The size of number of entries in the cache.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_size{cluster=\"$ClusterName\",coherence_service='$ServiceName',name=\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "Total  Write Behind Queue Size",
   "type": "singlestat",
   "description": "Indicates the total size of all Write Behind Queues",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_queue_size{cluster=\"$ClusterName\",coherence_service='$ServiceName',name=\"$CacheName\"}) "
    }
   ]
  },
  {
   "title": "Total Store Writes",
   "type": "singlestat",
   "description": "Total store writes across all members",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_store_writes{cluster=\"$ClusterName\",coherence_service='$ServiceName',name=\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "Average Batch Size",
   "type": "singlestat",
   "description": "Average batch size across all members",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(vendor:coherence_cache_store_average_batch_size{cluster=\"$ClusterName\",coherence_service='$ServiceName',name=\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "Total Store Failures",
   "type": "singlestat",
   "description": "Total store failures across all members",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_store_failures{cluster=\"$ClusterName\",coherence_service='$ServiceName',cache=\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "Total Store Reads",
   "type": "singlestat",
   "description": "Total store reads across all members",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_store_reads{cluster=\"$ClusterName\",coherence_service='$ServiceName',name=\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "CacheStore Writes for $CacheName",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_store_writes{cluster=\"$ClusterName\",coherence_service='$ServiceName', name=\"$CacheName\"}) - \nsum(vendor:coherence_cache_store_writes{cluster=\"$ClusterName\",coherence_service='$ServiceName', name=\"$CacheName\"} offset $__interval)",
     "legendFormat": "Cache Store Wrutes"
    }
   ]
  },
  {
   "title": "CacheStore Reads for $CacheName",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_store_reads{cluster=\"$ClusterName\",coherence_service='$ServiceName', name=\"$CacheName\"}) - \nsum(vendor:coherence_cache_store_reads{cluster=\"$ClusterName\",coherence_service='$ServiceName', name=\"$CacheName\"} offset $__interval)",
     "legendFormat": "Cache Store Wrutes"
    }
   ]
  },
  {
   "title": "Member Cache Store Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg(vendor:coherence_cache_queue_size{cluster=\"$ClusterName\",coherence_service='$ServiceName', name=\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "avg(vendor:coherence_cache_store_writes{cluster=\"$ClusterName\",coherence_service='$ServiceName', name=\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "avg(vendor:coherence_cache_store_average_batch_size{cluster=\"$ClusterName\",coherence_service='$ServiceName', name=\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "avg(vendor:coherence_cache_store_write_millis{cluster=\"$ClusterName\",coherence_service='$ServiceName', name=\"$CacheName\", tier=\"back\"} / \n vendor:coherence_cache_store_writes{cluster=\"$ClusterName\",coherence_service='$ServiceName', name=\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "avg(vendor:coherence_cache_store_write_millis{cluster=\"$ClusterName\",coherence_service='$ServiceName', name=\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "avg(vendor:coherence_cache_store_reads{cluster=\"$ClusterName\",coherence_service='$ServiceName', name=\"$CacheName\", tier=\"back\"}) by (member)\n"
    },
    {
     "expr": "avg(vendor:coherence_cache_store_read_millis{cluster=\"$ClusterName\",coherence_service='$ServiceName', name=\"$CacheName\", tier=\"back\"} / \n  vendor:coherence_cache_store_reads{cluster=\"$ClusterName\",coherence_service='$ServiceName', name=\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "avg(vendor:coherence_cache_store_read_millis{cluster=\"$ClusterName\",coherence_service='$ServiceName', name=\"$CacheName\", tier=\"back\"}) by (member)"
    }
   ]
  }
 ]
}