{
 "title": "Coherence Caches Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(vendor:coherence_cluster_size, cluster)"
    }
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": {
     "query": "label_values(vendor:coherence_cluster_size{cluster=\"${ClusterName:raw}\"}, version)"
    }
   },
   {
    "name": "Services",
    "label": "Services",
    "query": {
     "query": "label_values(vendor:coherence_service_request_max_duration{cluster=\"${ClusterName:raw}\"}, name)"
    }
   },
   {
    "name": "Caches",
    "label": "Caches",
    "query": {
     "query": "label_values(vendor:coherence_cache_size{cluster=\"${ClusterName:raw}\"}, name) "
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>Caches Summary - $ClusterName</h3></center>"
   }
  },
  {
   "title": "Cache List",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_units_bytes{cluster=\"${ClusterName:raw}\",tier=\"back\"}) by (coherence_service, name)"
    },
    {
     "expr": "sum(vendor:coherence_cache_size{cluster=\"${ClusterName:raw}\",tier=\"back\"}) by (coherence_service, name)"
    }
   ]
  },
  {
   "title": "Cache Data Memory Usage",
   "type": "timeseries",
   "description": "Shows a graph of cache related memory used.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_units_bytes{cluster=\"${ClusterName:raw}\",tier=\"back\"})",
     "legendFormat": "Cache Memory"
    },
    {
     "expr": "sum(vendor:coherence_storage_manager_index_total_units{cluster=\"${ClusterName:raw}\"})",
     "legendFormat": "Index Memory"
    }
   ]
  },
  {
   "title": "Cache Index Size",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_storage_manager_index_total_units{cluster=\"${ClusterName:raw}\"}) by (coherence_service, cache )"
    }
   ]
  },
  {
   "title": "Total Cache Evictions",
   "type": "timeseries",
   "description": "Shows a graph of total cache evictions across all caches and members.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vendor:coherence_storage_manager_eviction_count{cluster=\"${ClusterName:raw}\"}) - sum(vendor:coherence_storage_manager_eviction_count{cluster=\"${ClusterName:raw}\"} offset $__interval) > 0",
     "legendFormat": "Total Evictions"
    }
   ]
  },
  {
   "title": "Total Events Dispatched",
   "type": "timeseries",
   "description": "Shows a graph of total cache evictions across all caches and members.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vendor:coherence_storage_manager_events_dispatched{cluster=\"${ClusterName:raw}\"}) - sum(vendor:coherence_storage_manager_events_dispatched{cluster=\"${ClusterName:raw}\"} offset $__interval) > 0",
     "legendFormat": "Total Events"
    }
   ]
  },
  {
   "title": "Total Events Dispatched By Service",
   "type": "timeseries",
   "description": "Shows a graph of total cache evictions across all caches and members.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vendor:coherence_storage_manager_events_dispatched{cluster=\"${ClusterName:raw}\"}) by (coherence_service) - sum(vendor:coherence_storage_manager_events_dispatched{cluster=\"${ClusterName:raw}\"} offset $__interval ) by (coherence_service) > 0",
     "legendFormat": "{{coherence_service}}"
    }
   ]
  },
  {
   "title": "Total Cache Prunes",
   "type": "timeseries",
   "description": "Shows a graph of total cache evictions across all caches and members.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_prunes{cluster=\"${ClusterName:raw}\",tier=\"back\"}) - sum(vendor:coherence_cache_prunes{cluster=\"${ClusterName:raw}\", tier=\"back\"} offset $__interval) > 0",
     "legendFormat": "Total Prunes"
    }
   ]
  },
  {
   "title": "Total Cache Prunes Millis",
   "type": "timeseries",
   "description": "Shows a graph of total cache evictions across all caches and members.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_prunes_millis{cluster=\"${ClusterName:raw}\",tier=\"back\"}) - sum(vendor:coherence_cache_prunes_millis{cluster=\"${ClusterName:raw}\", tier=\"back\"} offset $__interval) > 0",
     "legendFormat": "Total Prunes Millis"
    }
   ]
  }
 ]
}