{
 "title": "Coherence Executors Summary",
 "tags": [ "dashboard" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor:coherence_cluster_size{cluster=~\"$ClusterName\"}, version)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Executors Summary - $ClusterName</h3></center>"
  },
  {
   "title": "Executors List",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "count(vendor:coherence_executor_state_code{cluster=~\"$ClusterName\"}) by (name) "
    },
    {
     "expr": "sum(vendor:coherence_executor_tasks_in_progress_count{cluster=~\"$ClusterName\"}) by (name) "
    },
    {
     "expr": "sum(vendor:coherence_executor_tasks_completed_count{cluster=~\"$ClusterName\"}) by (name) "
    },
    {
     "expr": "sum(vendor:coherence_executor_tasks_rejected_count{cluster=~\"$ClusterName\"}) by (name) "
    }
   ]
  },
  {
   "title": "Tasks In Progress (All Executors)",
   "type": "graph",
   "description": "Total tasks in progress across all executors",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Task Count" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_executor_tasks_in_progress_count{cluster=~\"$ClusterName\"})",
     "legendFormat": "In Progress"
    }
   ]
  },
  {
   "title": "Completed/ Rejected Tasks (All Executors)",
   "type": "graph",
   "description": "Total completed and rejected tasks across all executors",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Task Count" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_executor_tasks_completed_count{cluster=~\"$ClusterName\"}) - sum(vendor:coherence_executor_tasks_completed_count{cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(vendor:coherence_executor_tasks_rejected_count{cluster=~\"$ClusterName\"}) - sum(vendor:coherence_executor_tasks_rejected_count{cluster=~\"$ClusterName\"} offset $__interval)  ",
     "legendFormat": "Rejected"
    }
   ]
  }
 ]
}