{
 "title": "Coherence Elastic Data Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(coherence_cluster_size, cluster)"
    }
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": {
     "query": "label_values(coherence_cluster_size{cluster=\"${ClusterName:raw}\"}, version)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>Elastic Data Summary - $ClusterName</h3></center>"
   }
  },
  {
   "title": "RAM Journal Files Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_journal_file_count{cluster=\"${ClusterName:raw}\",name=~\"RamJournalRM\"})"
    }
   ]
  },
  {
   "title": "Total RAM Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_journal_total_data_size{cluster=\"${ClusterName:raw}\",name=~\"RamJournalRM\"})"
    }
   ]
  },
  {
   "title": "Flash Journal Files Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_journal_file_count{cluster=\"${ClusterName:raw}\",name=~\"FlashJournalRM\"})"
    }
   ]
  },
  {
   "title": "Total Flash Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_journal_total_data_size{cluster=\"${ClusterName:raw}\",name=~\"FlashJournalRM\"})"
    }
   ]
  },
  {
   "title": "RAM Journal Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(coherence_journal_total_data_size{cluster=\"${ClusterName:raw}\",name=~\"RamJournalRM\"}) by (name)",
     "legendFormat": "Total Used RAM"
    }
   ]
  },
  {
   "title": "Flash Journal Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(coherence_journal_total_data_size{cluster=\"${ClusterName:raw}\",name=~\"FlashJournalRM\"}) by (name)",
     "legendFormat": "Total Used Flash"
    }
   ]
  },
  {
   "title": "RAM Journal Compactions - All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "coherence_journal_compaction_count{cluster=\"${ClusterName:raw}\",name=~\"RamJournalRM\"} - coherence_journal_compaction_count{cluster=\"${ClusterName:raw}\",name=~\"RamJournalRM\"} offset $__interval > 0",
     "legendFormat": "Compaction Count"
    },
    {
     "expr": "coherence_journal_exhaustive_compaction_count{cluster=\"${ClusterName:raw}\",name=~\"RamJournalRM\"}  - coherence_journal_exhaustive_compaction_count{cluster=\"${ClusterName:raw}\",name=~\"RamJournalRM\"} offset $__interval > 0",
     "legendFormat": "Exhaustive Compaction Count"
    }
   ]
  },
  {
   "title": "Flash Journal Compactions - All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "coherence_journal_compaction_count{cluster=\"${ClusterName:raw}\",name=~\"FlashJournalRM\"} - coherence_journal_compaction_count{cluster=\"${ClusterName:raw}\",name=~\"FlashJournalRM\"} offset $__interval > 0",
     "legendFormat": "Compaction Count"
    },
    {
     "expr": "coherence_journal_exhaustive_compaction_count{cluster=\"${ClusterName:raw}\",name=~\"FlashJournalRM\"}  - coherence_journal_exhaustive_compaction_count{cluster=\"${ClusterName:raw}\",name=~\"FlashJournalRM\"} offset $__interval > 0",
     "legendFormat": "Exhaustive Compaction Count"
    }
   ]
  }
 ]
}