{
 "title": "Coherence Executors Summary",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(coherence_cluster_size, cluster)"
    }
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": {
     "query": "label_values(coherence_cluster_size{cluster=\"${ClusterName:raw}\"}, version)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>Executors Summary - $ClusterName</h3></center>"
   }
  },
  {
   "title": "Executors List",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "count(coherence_executor_state_code{cluster=\"${ClusterName:raw}\"}) by (name) "
    },
    {
     "expr": "sum(coherence_executor_tasks_in_progress_count{cluster=\"${ClusterName:raw}\"}) by (name) "
    },
    {
     "expr": "sum(coherence_executor_tasks_completed_count{cluster=\"${ClusterName:raw}\"}) by (name) "
    },
    {
     "expr": "sum(coherence_executor_tasks_rejected_count{cluster=\"${ClusterName:raw}\"}) by (name) "
    }
   ]
  },
  {
   "title": "Tasks In Progress (All Executors)",
   "type": "timeseries",
   "description": "Total tasks in progress across all executors",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coherence_executor_tasks_in_progress_count{cluster=\"${ClusterName:raw}\"})",
     "legendFormat": "In Progress"
    }
   ]
  },
  {
   "title": "Completed/ Rejected Tasks (All Executors)",
   "type": "timeseries",
   "description": "Total completed and rejected tasks across all executors",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coherence_executor_tasks_completed_count{cluster=\"${ClusterName:raw}\"}) - sum(coherence_executor_tasks_completed_count{cluster=\"${ClusterName:raw}\"} offset $__interval) > 0",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(coherence_executor_tasks_rejected_count{cluster=\"${ClusterName:raw}\"}) - sum(coherence_executor_tasks_rejected_count{cluster=\"${ClusterName:raw}\"} offset $__interval) > 0",
     "legendFormat": "Rejected"
    }
   ]
  }
 ]
}