{
 "title": "Coherence Executor Details",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(coherence_cluster_size,namespace)"
    }
   },
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(coherence_cluster_size{namespace=~\"${Namespace:.*}\"}, cluster)"
    }
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": {
     "query": "label_values(coherence_cluster_size{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}, version)"
    }
   },
   {
    "name": "ExecutorName",
    "label": "Executor Name",
    "query": {
     "query": "label_values(coherence_executor_state_code{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>Executor Detail - $ExecutorName</h3></center>"
   }
  },
  {
   "title": "Executor Members",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "avg(coherence_executor_state_code{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",name=\"$ExecutorName\"}) by (machine, member, member_id, name)"
    }
   ]
  },
  {
   "title": "Tasks In Progress",
   "type": "timeseries",
   "description": "Total tasks in progress for this executor",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coherence_executor_tasks_in_progress_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",name=\"$ExecutorName\"})",
     "legendFormat": "In Progress"
    }
   ]
  },
  {
   "title": "Completed/ Rejected Tasks",
   "type": "timeseries",
   "description": "Total completed and rejected tasks for this executor",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coherence_executor_tasks_completed_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",name=\"$ExecutorName\"}) - sum(coherence_executor_tasks_completed_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",name=\"$ExecutorName\"} offset $__interval) > 0",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(coherence_executor_tasks_rejected_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",name=\"$ExecutorName\"}) -sum(coherence_executor_tasks_rejected_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",name=\"$ExecutorName\"} offset $__interval) > 0",
     "legendFormat": "Rejected"
    }
   ]
  }
 ]
}