{
 "title": "Coherence Executor Detail",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor:coherence_cluster_size{cluster=\"${ClusterName:raw}\"}, version)"
   },
   {
    "name": "ExecutorName",
    "label": "Executor Name",
    "query": "label_values(vendor:coherence_executor_state_code{cluster=\"${ClusterName:raw}\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Executor Detail - $ExecutorName</h3></center>"
  },
  {
   "title": "Executor Members",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "avg(vendor:coherence_executor_state_code{cluster=\"${ClusterName:raw}\",name=\"$ExecutorName\"}) by (machine, member, member_id, name)"
    }
   ]
  },
  {
   "title": "Tasks In Progress",
   "type": "graph",
   "description": "Total tasks in progress for this executor",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Task Count" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_executor_tasks_in_progress_count{cluster=\"${ClusterName:raw}\",name=\"$ExecutorName\"})",
     "legendFormat": "In Progress"
    }
   ]
  },
  {
   "title": "Completed/ Rejected Tasks",
   "type": "graph",
   "description": "Total completed and rejected tasks for this executor",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Task Count" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_executor_tasks_completed_count{cluster=\"${ClusterName:raw}\",name=\"$ExecutorName\"}) - sum(vendor:coherence_executor_tasks_completed_count{cluster=\"${ClusterName:raw}\",name=\"$ExecutorName\"} offset $__interval)",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(vendor:coherence_executor_tasks_rejected_count{cluster=\"${ClusterName:raw}\",name=\"$ExecutorName\"}) -sum(vendor:cohence_executor_tasks_rejected_count{cluster=\"${ClusterName:raw}\",name=\"$ExecutorName\"} offset $__interval)",
     "legendFormat": "Rejected"
    }
   ]
  }
 ]
}