{
 "title": "Coherence Federation Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(coherence_cluster_size,namespace)"
    }
   },
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(coherence_cluster_size{namespace=~\"${Namespace:.*}\"}, cluster)"
    }
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": {
     "query": "label_values(coherence_cluster_size{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}, version)"
    }
   },
   { "name": "TopLimit", "label": "Top N Limit", "query": "1,3,5,10,15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>Federation Summary - $ClusterName</h3></center>"
   }
  },
  {
   "title": "Destinations",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "count( coherence_federation_destination_total_msg_sent{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"})by (coherence_service, name, participant_type)"
    },
    {
     "expr": "avg(coherence_federation_destination_status {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) by (coherence_service, name, participant_type)"
    }
   ]
  },
  {
   "title": "Origins",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(coherence_federation_origin_total_msg_received {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) by (coherence_service, name)"
    }
   ]
  },
  {
   "title": "Current Envelope Size (All Services)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_cache_size{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", name=~\".*\\\\$Envelope\"})",
     "legendFormat": "Envelope Size"
    }
   ]
  },
  {
   "title": "Current RAM Journal Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_journal_total_data_size{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", name=\"RamJournalRM\"})",
     "legendFormat": "RAM Journal"
    }
   ]
  },
  {
   "title": "Current Flash Journal Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_journal_total_data_size{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", name=\"FlashJournalRM\"})",
     "legendFormat": "Flash Journal"
    }
   ]
  },
  {
   "title": "Entries Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_federation_destination_total_entries_sent {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"})"
    }
   ]
  },
  {
   "title": "Records Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_federation_destination_total_records_sent {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"})"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_federation_destination_total_msg_sent {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"})"
    }
   ]
  },
  {
   "title": "Entries Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_federation_origin_total_entries_received {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"})"
    }
   ]
  },
  {
   "title": "Records Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_federation_origin_total_records_received {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"})"
    }
   ]
  },
  {
   "title": "Messages Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_federation_origin_total_msg_received {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"})"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(coherence_federation_destination_total_bytes_sent{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) - sum(coherence_federation_destination_total_bytes_sent {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"} offset $__interval) ",
     "legendFormat": "Destination: {{name}}"
    }
   ]
  },
  {
   "title": "Total Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coherence_federation_origin_total_bytes_received {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) - sum(coherence_federation_origin_total_bytes_received {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"} offset $__interval)",
     "legendFormat": "Origin: {{name}}"
    }
   ]
  },
  {
   "title": "Total Messages Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coherence_federation_destination_total_msg_sent {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) - sum(coherence_federation_destination_total_msg_sent {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"} offset $__interval) ",
     "legendFormat": "Destination: {{name}}"
    }
   ]
  },
  {
   "title": "Total Messages Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coherence_federation_origin_total_msg_received {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"})  - sum(coherence_federation_origin_total_msg_received {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"} offset $__interval)",
     "legendFormat": "Origin: {{name}}"
    }
   ]
  },
  {
   "title": "Total Records Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coherence_federation_destination_total_records_sent {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) - sum(coherence_federation_destination_total_records_sent {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"} offset $__interval)",
     "legendFormat": "Destination: {{name}}"
    }
   ]
  },
  {
   "title": "Total Records Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coherence_federation_origin_total_records_received {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) - sum(coherence_federation_origin_total_records_received {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"} offset $__interval)",
     "legendFormat": "Origin: {{name}}"
    }
   ]
  },
  {
   "title": "Total Entries Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coherence_federation_destination_total_entries_sent {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) - sum(coherence_federation_destination_total_entries_sent {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"} offset $__interval)",
     "legendFormat": "Destination: {{name}}"
    }
   ]
  },
  {
   "title": "Total Entries Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coherence_federation_origin_total_entries_received {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) - sum(coherence_federation_origin_total_entries_received {namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"} offset $__interval)",
     "legendFormat": "Origin: {{name}}"
    }
   ]
  }
 ]
}