{
 "title": "Coherence gRPC Proxy Details Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(coherence_cluster_size, cluster)"
    }
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": {
     "query": "label_values(coherence_cluster_size{cluster=\"${ClusterName:raw}\"}, version)"
    }
   },
   {
    "name": "MemberName",
    "label": "Member Name",
    "query": {
     "query": "label_values(coherence_service_member_count{cluster=\"${ClusterName:raw}\"}, member)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>gRPC Proxy Details - $ClusterName / ${MemberName}</h3></center>"
   }
  },
  {
   "title": "Thread Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_grpc_named_cache_proxy_daemon_thread_count{member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"}) by (member)"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(coherence_grpc_connection_request_count{member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"}) by (member)"
    }
   ]
  },
  {
   "title": "Backlog",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_grpc_named_cache_proxy_task_backlog{member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_grpc_named_cache_proxy_error_request_count{member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"})"
    }
   ]
  },
  {
   "title": "gRpc Proxy Connections",
   "type": "table",
   "description": "Note: The gRPC proxy connections data stays visible for approx 5 minutes after the connection has terminated.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(coherence_grpc_connection_request_count{member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"}) by ( remote_address, uid)",
     "legendFormat": "Member"
    },
    {
     "expr": "sum(coherence_grpc_connection_request_rate{quantile=\"mean\", member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"}) by ( remote_address, uid)",
     "legendFormat": "Member"
    },
    {
     "expr": "sum(coherence_grpc_connection_request_rate{quantile=\"1min\", member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"}) by ( remote_address, uid)",
     "legendFormat": "Member"
    },
    {
     "expr": "sum(coherence_grpc_connection_request_rate{quantile=\"5min\", member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"}) by ( remote_address, uid)",
     "legendFormat": "Member"
    },
    {
     "expr": "sum(coherence_grpc_connection_request_rate{quantile=\"15min\", member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"}) by ( remote_address, uid)",
     "legendFormat": "Member"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(coherence_grpc_named_cache_proxy_request_count{member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"}) - sum(coherence_grpc_named_cache_proxy_request_count{member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"} offset $__interval) > 0",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(coherence_grpc_named_cache_proxy_responses_sent_count{member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"}) - sum(coherence_grpc_named_cache_proxy_responses_sent_count{member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"} offset $__interval) > 0",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Errors ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "coherence_grpc_named_cache_proxy_error_request_count{member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"} - coherence_grpc_named_cache_proxy_error_request_count{member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"} offset $__interval > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "coherence_grpc_named_cache_proxy_task_timeout_count{member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"} - coherence_grpc_named_cache_proxy_task_timeout_count{member=\"${MemberName}\",cluster=\"${ClusterName:raw}\"} offset $__interval > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}