{
 "title": "Coherence gRPC Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor_Coherence_Cluster_Size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor_Coherence_Cluster_Size{cluster=~\"$ClusterName\"}, version)"
   },
   {
    "name": "Services",
    "label": "Services",
    "query": "label_values(vendor_Coherence_Service_RequestMaxDuration{cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "Caches",
    "label": "Caches",
    "query": "label_values(vendor_Coherence_Cache_Size{cluster=~\"$ClusterName\"}, name) "
   },
   { "name": "TopLimit", "label": "Top N Limit", "query": "1,3,10,15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>gRPC Summary - $ClusterName</h3></center>"
  },
  {
   "title": "gRPC Request Count - All Members",
   "type": "table",
   "description": "Shows the total gRPC Requests for the various request categories.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_size_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_clear_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_destroy_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_truncate_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_addIndex_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_removeIndex_total{cluster=~\"$ClusterName\"}) by (member, node_id ,machine, role)"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_put_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_get_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_remove_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_replace_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_putAll_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_getAll_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_removeMapping_total{cluster=~\"$ClusterName\"} + \napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_replaceMapping_total{cluster=~\"$ClusterName\"}  ) by (member, node_id ,machine, role)"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_isEmpty_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_keySet_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_entrySet_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_values_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_nextEntrySetPage_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_nextKeySetPage_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsKey_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsValue_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_containsEntry_total{cluster=~\"$ClusterName\"}  ) by (member, node_id ,machine, role)"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_aggregate_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_invoke_total{cluster=~\"$ClusterName\"} +\napplication_com_oracle_coherence_grpc_proxy_NamedCacheService_invokeAll_total{cluster=~\"$ClusterName\"} ) by (member, node_id ,machine, role)"
    },
    {
     "expr": "sum(application_com_oracle_coherence_grpc_proxy_NamedCacheService_events_total) by (member, node_id ,machine, role)"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "HTTP Requests for Microprofile based HTTP servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_requests_count_total{cluster=~\"$ClusterName\"} - vendor_requests_count_total{cluster=~\"$ClusterName\"} offset $__interval) by(member)",
     "legendFormat": "Member: {{member}}"
    }
   ]
  },
  {
   "title": "Top $TopLimit Total GC Count  - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the highest Total GC Count over the current time range.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk($TopLimit, sum(delta(vendor_Coherence_GC_CollectionCount{cluster=~\"$ClusterName\"}[$__range] )) by (member))"
    }
   ]
  },
  {
   "title": "Heap Memory Usage After GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\"}) by (member)",
     "legendFormat": "Member: {{member}} ({{role}})"
    }
   ]
  },
  {
   "title": "Top $TopLimit Total GC Time  - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the highest Total GC Time over the current time range.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk($TopLimit, sum(delta(vendor_Coherence_GC_CollectionTime{cluster=~\"$ClusterName\"}[$__range])) by (member))"
    }
   ]
  },
  {
   "title": "Memory Usage % After GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\"}) by(member) / sum(vendor_Coherence_Memory_HeapMemoryUsage_max{cluster=~\"$ClusterName\"}) by (member) * 100",
     "legendFormat": "Member: {{member}}"
    }
   ]
  },
  {
   "title": "Receiver Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Node_ReceiverSuccessRate{cluster=~\"$ClusterName\"}",
     "legendFormat": "Member: {{member}}"
    }
   ]
  },
  {
   "title": "Publisher Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Node_PublisherSuccessRate{cluster=~\"$ClusterName\"}",
     "legendFormat": "Member: {{member}}"
    }
   ]
  },
  {
   "title": "Total gRPC Requests by Member",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "svendor_grpc_requests_count_total{cluster=~\"$ClusterName\"} - vendor_grpc_requests_count_total{cluster=~\"$ClusterName\"} offset $__interval",
     "legendFormat": "{{member}}"
    }
   ]
  }
 ]
}