{
 "title": "Coherence gRPC Proxy Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(vendor:coherence_cluster_size, cluster)"
    }
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": {
     "query": "label_values(vendor:coherence_cluster_size{cluster=\"${ClusterName:raw}\"}, version)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>gRPC Proxy Summary - $ClusterName</h3></center>"
   }
  },
  {
   "title": "gRpc Proxy List",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_grpc_named_cache_proxy_request_count{cluster=\"${ClusterName:raw}\"}) by (member, role, node_id)",
     "legendFormat": "Member"
    },
    {
     "expr": "sum(vendor:coherence_grpc_named_cache_proxy_responses_sent_count{cluster=\"${ClusterName:raw}\"}) by (member, role, node_id)",
     "legendFormat": "Member"
    },
    {
     "expr": "sum(vendor:coherence_grpc_named_cache_proxy_task_backlog{cluster=\"${ClusterName:raw}\"}) by (member, role, node_id)",
     "legendFormat": "Member"
    },
    {
     "expr": "sum(vendor:coherence_grpc_named_cache_proxy_error_request_count{cluster=\"${ClusterName:raw}\"}) by (member, role, node_id)",
     "legendFormat": "Member"
    }
   ]
  },
  {
   "title": "Requests - All Members",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_grpc_named_cache_proxy_request_count{cluster=\"${ClusterName:raw}\"}) - sum(vendor:coherence_grpc_named_cache_proxy_request_count{cluster=\"${ClusterName:raw}\"} offset $__interval)",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Responses - All Members",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_grpc_named_cache_proxy_responses_sent_count{cluster=\"${ClusterName:raw}\"}) - sum(vendor:coherence_grpc_named_cache_proxy_responses_sent_count{cluster=\"${ClusterName:raw}\"} offset $__interval)",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Requests - By Member",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_grpc_named_cache_proxy_request_count{cluster=\"${ClusterName:raw}\"} - vendor:coherence_grpc_named_cache_proxy_request_count{cluster=\"${ClusterName:raw}\"} offset $__interval",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Responses - By Members",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_grpc_named_cache_proxy_request_count{cluster=\"${ClusterName:raw}\"} - vendor:coherence_grpc_named_cache_proxy_request_count{cluster=\"${ClusterName:raw}\"} offset $__interval",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Errors - By Member",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_grpc_named_cache_proxy_error_request_count{cluster=\"${ClusterName:raw}\"} - vendor:coherence_grpc_named_cache_proxy_error_request_count{cluster=\"${ClusterName:raw}\"} offset $__interval",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Timeouts - By Member",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_grpc_named_cache_proxy_task_timeout_count{cluster=\"${ClusterName:raw}\"} - vendor:coherence_grpc_named_cache_proxy_task_timeout_count{cluster=\"${ClusterName:raw}\"} offset $__interval",
     "legendFormat": "{{member}}"
    }
   ]
  }
 ]
}