{
 "title": "Coherence HTTP Servers Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor:coherence_cluster_size{cluster=\"$ClusterName\"}, version)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>HTTP Servers Summary - $ClusterName</h3></center>"
  },
  {
   "title": "HTTP Servers List",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "count(vendor:coherence_connection_manager_total_request_count{cluster=\"$ClusterName\",protocol=~\"http\"}) by (name) "
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_total_request_count{cluster=\"$ClusterName\",protocol=~\"http\"}) by (name) "
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_total_error_count{cluster=\"$ClusterName\",protocol=~\"http\"}) by (name) "
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_average_request_time{cluster=\"$ClusterName\",protocol=~\"http\"}) by (name) "
    }
   ]
  },
  {
   "title": "HTTP Requests/ sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_connection_manager_total_request_count{cluster=\"$ClusterName\",protocol=~\"http\"} - vendor:coherence_connection_manager_total_request_count{cluster=\"$ClusterName\",protocol=~\"http\"} offset $__interval ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_connection_manager_response_1xx_count{cluster=\"$ClusterName\",protocol=~\"http\"} - vendor:coherence_connection_manager_response_1xx_count{cluster=\"$ClusterName\",protocol=~\"http\"} offset $__interval",
     "legendFormat": "{{name}} 100-199"
    },
    {
     "expr": "vendor:coherence_connection_manager_response_2xx_count{cluster=\"$ClusterName\",protocol=~\"http\"} - vendor:coherence_connection_manager_response_2xx_count{cluster=\"$ClusterName\",protocol=~\"http\"} offset $__interval ",
     "legendFormat": "{{name}} 200-299"
    },
    {
     "expr": "vendor:coherence_connection_manager_response_3xx_count{cluster=\"$ClusterName\",protocol=~\"http\"} - vendor:coherence_connection_manager_response_3xx_count{cluster=\"$ClusterName\",protocol=~\"http\"} offset $__interval",
     "legendFormat": "{{name}} 300-399"
    },
    {
     "expr": "vendor:coherence_connection_manager_response_4xx_count{cluster=\"$ClusterName\",protocol=~\"http\"} - vendor:coherence_connection_manager_response_4xx_count{cluster=\"$ClusterName\",protocol=~\"http\"} offset $__interval ",
     "legendFormat": "{{name}} 400-499"
    },
    {
     "expr": "vendor:coherence_connection_manager_response_5xx_count{cluster=\"$ClusterName\",protocol=~\"http\"} - vendor:coherence_connection_manager_response_5xx_count{cluster=\"$ClusterName\",protocol=~\"http\"} offset $__interval",
     "legendFormat": "{{name}} 500-599"
    }
   ]
  }
 ]
}