{
 "title": "Coherence Machines Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(vendor:coherence_cluster_size, cluster)"
    }
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": {
     "query": "label_values(vendor:coherence_cluster_size{cluster=\"${ClusterName:raw}\"}, version)"
    }
   },
   {
    "name": "Services",
    "label": "Services",
    "query": {
     "query": "label_values(vendor:coherence_service_request_max_duration{cluster=\"${ClusterName:raw}\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>Machines Summary - Version: $CoherenceVersion</h3></center>"
   }
  },
  {
   "title": "Current Cluster Machines",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "avg(vendor:coherence_os_available_processors{cluster=\"${ClusterName:raw}\"}) by (machine)"
    },
    {
     "expr": "avg(vendor:coherence_os_free_swap_space_size{cluster=\"${ClusterName:raw}\"}) by (machine)"
    },
    {
     "expr": "avg(vendor:coherence_os_total_physical_memory_size{cluster=\"${ClusterName:raw}\"}) by (machine)"
    },
    {
     "expr": "avg(vendor:coherence_os_free_physical_memory_size{cluster=\"${ClusterName:raw}\"}) by (machine)"
    },
    {
     "expr": "avg(vendor:coherence_os_free_physical_memory_size{cluster=\"${ClusterName:raw}\"}) by (machine) / avg(vendor:coherence_os_total_physical_memory_size{cluster=\"${ClusterName:raw}\"}) by (machine)"
    }
   ]
  },
  {
   "title": "Free Physical Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(vendor:coherence_os_free_physical_memory_size{cluster=\"${ClusterName:raw}\"}) by (machine)",
     "legendFormat": "{{machine}} - Available"
    },
    {
     "expr": "avg(vendor:coherence_os_total_physical_memory_size{cluster=\"${ClusterName:raw}\"}) by (machine)",
     "legendFormat": "{{machine}} - Total"
    }
   ]
  },
  {
   "title": "Load Averages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(vendor:coherence_os_system_load_average{cluster=\"${ClusterName:raw}\"}[1m])) by (machine)",
     "legendFormat": "{{machine}} - 1 Minute Avg"
    },
    {
     "expr": "avg(avg_over_time(vendor:coherence_os_system_load_average{cluster=\"${ClusterName:raw}\"}[5m])) by (machine)",
     "legendFormat": "{{machine}} - 5 Minutes Avg"
    },
    {
     "expr": "avg(avg_over_time(vendor:coherence_os_system_load_average{cluster=\"${ClusterName:raw}\"}[15m])) by (machine)",
     "legendFormat": "{{machine}} - 15 Minutes Avg"
    }
   ]
  }
 ]
}