{
 "title": "Coherence Member Details Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(coherence_cluster_size,namespace)"
    }
   },
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(coherence_cluster_size{namespace=~\"${Namespace:.*}\"}, cluster)"
    }
   },
   {
    "name": "MemberName",
    "label": "Member Name",
    "query": {
     "query": "label_values(coherence_service_member_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}, member)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>Member Details - $MemberName</h3></center>"
   }
  },
  { "title": "Current  Details - $MemberName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Used Heap After GC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_memory_heap_after_gc_used{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",member=\"$MemberName\"})"
    }
   ]
  },
  {
   "title": "Max Heap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coherence_memory_heap_memory_usage_max{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",member=\"$MemberName\"}  "
    }
   ]
  },
  {
   "title": "Heap Used %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_memory_heap_after_gc_used{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",member=\"$MemberName\"}) / sum(coherence_memory_heap_memory_usage_max{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",member=\"$MemberName\"})"
    }
   ]
  },
  {
   "title": "Publisher Success",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coherence_node_publisher_success_rate{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",member=\"$MemberName\"} "
    }
   ]
  },
  {
   "title": "Receiver Success",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coherence_node_receiver_success_rate{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",member=\"$MemberName\"} "
    }
   ]
  },
  {
   "title": "Current Services Running on $MemberName",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {},
    {
     "expr": "sum(coherence_service_thread_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",member=\"$MemberName\"}) by (name) > 0"
    },
    {
     "expr": "sum(coherence_service_thread_idle_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",member=\"$MemberName\"}) by (name) > 0"
    },
    {
     "expr": "(sum(coherence_service_thread_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",member=\"$MemberName\"}) by (name) - sum(coherence_service_thread_idle_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",member=\"$MemberName\"}) by (name)) / (sum(coherence_service_thread_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",member=\"$MemberName\"}) by (name)) "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "<center><h3>Memory and Garbage Collection</h3></center>"
   }
  },
  {
   "title": "Garbage Collection Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "coherence_gc_collection_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"} - coherence_gc_collection_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"} offset $__interval > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "coherence_gc_collection_time{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"} - coherence_gc_collection_time{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"} offset $__interval > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Heap Memory Used and After GC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "coherence_memory_heap_memory_usage_max{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"}",
     "legendFormat": "Max Heap"
    },
    {
     "expr": "sum(coherence_memory_heap_after_gc_used{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"})",
     "legendFormat": "Used After GC"
    },
    {
     "expr": "sum(coherence_memory_heap_memory_usage_used{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"})",
     "legendFormat": "Heap Used"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "coherence_memory_non_heap_memory_usage_used{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "coherence_memory_non_heap_memory_usage_committed{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "<center><h3>Member Network Details</h3></center>"
   }
  },
  {
   "title": "Packet Send Rate / Second",
   "type": "timeseries",
   "description": "The rate at which packets are being sent from this member.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(coherence_node_packets_sent{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"}[1m])  ",
     "legendFormat": "Packet Sent"
    }
   ]
  },
  {
   "title": "Packet Receive Rate / Second",
   "type": "timeseries",
   "description": "The rate at which packets are being received by this member.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(coherence_node_packets_received{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"}[1m])",
     "legendFormat": "Packets Received"
    }
   ]
  },
  {
   "title": "Publisher Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "coherence_node_publisher_success_rate{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"}"
    }
   ]
  },
  {
   "title": "Receiver Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "coherence_node_receiver_success_rate{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"}"
    }
   ]
  },
  {
   "title": "Guardian Recoveries and Terminations",
   "type": "timeseries",
   "description": "The Guardian Recovery and Terminations over the current time range.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "coherence_node_guard_recover_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"}  - coherence_node_guard_recover_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"} offset $__interval",
     "legendFormat": "Guardian Recoveries"
    },
    {
     "expr": "coherence_node_guard_terminate_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"} - coherence_node_guard_terminate_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"} offset $__interval",
     "legendFormat": "Guardian Terminations"
    }
   ]
  },
  {
   "title": "Send Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "coherence_node_send_queue_size{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\", member=\"$MemberName\"}",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}