{
 "title": "Coherence Members Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor_Coherence_Cluster_Size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor_Coherence_Cluster_Size{cluster=~\"$ClusterName\"}, version)"
   },
   {
    "name": "Services",
    "label": "Services",
    "query": "label_values(vendor_Coherence_Service_RequestMaxDuration{cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "Caches",
    "label": "Caches",
    "query": "label_values(vendor_Coherence_Cache_Size{cluster=~\"$ClusterName\"}, name) "
   },
   { "name": "TopLimit", "label": "Top N Limit", "query": "1,3,10,15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Members Summary - $ClusterName</h3></center>"
  },
  {
   "title": "Current Cluster Members",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\"}) by (member, node_id, site, machine, role)"
    },
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Max{cluster=~\"$ClusterName\"}) by (member, node_id, site, machine, role)"
    },
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\"}) by (member, node_id, site, machine, role) / sum(vendor_Coherence_Memory_HeapAfterGC_Max{cluster=~\"$ClusterName\"}) by (member, nodeId, site, machine, role)  "
    }
   ]
  },
  {
   "title": "Top $TopLimit Total GC Time  - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the highest Total GC Time over the current time range.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk($TopLimit, sum(delta(vendor_Coherence_GC_CollectionTime{cluster=~\"$ClusterName\"}[$__range])) by (member))"
    }
   ]
  },
  {
   "title": "Top $TopLimit Total GC Count  - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the highest Total GC Count over the current time range.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk($TopLimit, sum(delta(vendor_Coherence_GC_CollectionCount{cluster=~\"$ClusterName\"}[$__range] )) by (member))"
    }
   ]
  },
  {
   "title": "Memory Usage % After GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\"}) by(member) / sum(vendor_Coherence_Memory_HeapMemoryUsage_max{cluster=~\"$ClusterName\"}) by (member) * 100",
     "legendFormat": "Member: {{member}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage After GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_Coherence_Memory_HeapAfterGC_Used{cluster=~\"$ClusterName\"}) by (member)",
     "legendFormat": "Member: {{member}}"
    }
   ]
  },
  {
   "title": "Total Collection Count by Member",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_GC_CollectionCount{cluster=~\"$ClusterName\"} - vendor_Coherence_GC_CollectionCount{cluster=~\"$ClusterName\"} offset $__interval ",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Total Garbage Collection Time by Member",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_GC_CollectionTime{cluster=~\"$ClusterName\"} - vendor_Coherence_GC_CollectionTime{cluster=~\"$ClusterName\"}  offset $__interval ",
     "legendFormat": "{{member}} "
    }
   ]
  },
  {
   "title": "Publisher Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Node_PublisherSuccessRate{cluster=~\"$ClusterName\"}",
     "legendFormat": "Member: {{member}}"
    }
   ]
  },
  {
   "title": "Receiver Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vendor_Coherence_Node_ReceiverSuccessRate{cluster=~\"$ClusterName\"}",
     "legendFormat": "Member: {{member}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "HTTP Requests for Microprofile based HTTP servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_requests_count_total{cluster=~\"$ClusterName\"} - vendor_requests_count_total{cluster=~\"$ClusterName\"} offset $__interval) by(member)",
     "legendFormat": "Member: {{member}}"
    }
   ]
  },
  {
   "title": "Total gRPC Requests by Member",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vendor_grpc_requests_count_total{cluster=~\"$ClusterName\"} - vendor_grpc_requests_count_total{cluster=~\"$ClusterName\"} offset $__interval",
     "legendFormat": "{{member}}"
    }
   ]
  }
 ]
}