{
 "title": "Coherence Proxy Server Detail Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(coherence_cluster_size, cluster)"
    }
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": {
     "query": "label_values(coherence_cluster_size{cluster=\"${ClusterName:raw}\"}, version)"
    }
   },
   {
    "name": "ServiceName",
    "label": "Service Name",
    "query": {
     "query": "label_values(coherence_connection_manager_total_messages_sent{cluster=\"${ClusterName:raw}\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>Proxy Servers Details - $ServiceName</h3></center>"
   }
  },
  {
   "title": "Proxy Server Members for $ServiceName",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coherence_connection_manager_connection_count{cluster=\"${ClusterName:raw}\",name='$ServiceName'}) by (member, host_url)"
    },
    {
     "expr": "sum(coherence_connection_manager_total_messages_received{cluster=\"${ClusterName:raw}\",name='$ServiceName'}) by (member, host_url)"
    },
    {
     "expr": "sum(coherence_connection_manager_total_messages_sent{cluster=\"${ClusterName:raw}\",name='$ServiceName'}) by (member, host_url)"
    },
    {
     "expr": "sum(coherence_connection_manager_total_bytes_received {cluster=\"${ClusterName:raw}\",name='$ServiceName'}) by (member, host_url)"
    },
    {
     "expr": "sum(coherence_connection_manager_total_bytes_sent{cluster=\"${ClusterName:raw}\",name='$ServiceName'}) by (member, host)"
    },
    {
     "expr": "sum(coherence_connection_manager_outgoing_byte_backlog{cluster=\"${ClusterName:raw}\",name='$ServiceName'}) by (member, host)"
    },
    {
     "expr": "sum(coherence_connection_manager_unauthorized_connection_attempts{cluster=\"${ClusterName:raw}\",name='$ServiceName'}) by (member, host_url)"
    }
   ]
  },
  {
   "title": "Current Proxy Server Connections for $ServiceName",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(coherence_connection_connection_time_millis{cluster=\"${ClusterName:raw}\",name='$ServiceName'}) by (remote_address, remote_port, member, node_id)"
    }
   ]
  },
  {
   "title": "Outgoing Byte Backlog",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "coherence_connection_manager_outgoing_byte_backlog{cluster=\"${ClusterName:raw}\", name='$ServiceName', protocol=~\"tcp\"} > 0",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Outgoing Message Backlog",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "coherence_connection_manager_outgoing_message_backlog{cluster=\"${ClusterName:raw}\", name='$ServiceName'} > 0",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Total Bytes Sent/ sec - $ServiceName",
   "type": "timeseries",
   "description": "Total bytes sent (bytes/sec) of all Proxy Server members for $ServiceName.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "coherence_connection_manager_total_bytes_sent{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\", name='$ServiceName'} - coherence_connection_manager_total_bytes_sent{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\", name='$ServiceName'} offset $__interval > 0",
     "legendFormat": "{{member}} Sent"
    }
   ]
  },
  {
   "title": "Total Bytes Received/ sec - $ServiceName",
   "type": "timeseries",
   "description": "Total bytes received (bytes/sec) of all Proxy Server members for $ServiceName.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "coherence_connection_manager_total_bytes_received{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"}  - coherence_connection_manager_total_bytes_received{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"} offset $__interval > 0",
     "legendFormat": "{{member}} Received"
    }
   ]
  }
 ]
}