{
 "title": "Coherence Proxy Servers Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(coherence_cluster_size, cluster)"
    }
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": {
     "query": "label_values(coherence_cluster_size{cluster=\"${ClusterName:raw}\"}, version)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>Proxy Servers Summary - $ClusterName</h3></center>"
   }
  },
  {
   "title": "Proxy Service List - Coherence*Extend",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(coherence_connection_manager_connection_count{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"}) by (name)"
    },
    {
     "expr": "sum(coherence_connection_manager_connection_count{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"}) by (name)"
    },
    {
     "expr": "sum(coherence_connection_manager_total_messages_received{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"}) by (name)"
    },
    {
     "expr": "sum(coherence_connection_manager_total_messages_sent{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"}) by (name)"
    },
    {
     "expr": "sum(coherence_connection_manager_total_bytes_received{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"}) by (name)"
    },
    {
     "expr": "sum(coherence_connection_manager_total_bytes_sent{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"}) by (name)"
    },
    {
     "expr": "sum(coherence_connection_manager_outgoing_byte_backlog{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"}) by (name)"
    },
    {
     "expr": "sum(coherence_connection_manager_unauthorized_connection_attempts{cluster=\"${ClusterName:raw}\"}) by (name) "
    }
   ]
  },
  {
   "title": "Total Bytes Sent/ sec per Service",
   "type": "timeseries",
   "description": "Total bytes sent (bytes/sec) of all Proxy Server members.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "coherence_connection_manager_total_bytes_sent{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"} - coherence_connection_manager_total_bytes_sent{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"} offset $__interval > 0",
     "legendFormat": "{{name}} Sent"
    }
   ]
  },
  {
   "title": "Total Bytes Received/ sec per Service",
   "type": "timeseries",
   "description": "Total bytes received (bytes/sec) of all Proxy Server members.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "coherence_connection_manager_total_bytes_received{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"} - coherence_connection_manager_total_bytes_received{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"} offset $__interval > 0",
     "legendFormat": "{{name}} Received"
    }
   ]
  },
  {
   "title": "Total Proxy Connections",
   "type": "timeseries",
   "description": "Total Proxy Connections Across All Services",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coherence_connection_manager_connection_count{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"}) ",
     "legendFormat": "Total Connections"
    }
   ]
  },
  {
   "title": "Total Proxy Connections Per Service",
   "type": "timeseries",
   "description": "Total Proxy connections per service",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coherence_connection_manager_connection_count{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Outgoing Byte Backlog",
   "type": "timeseries",
   "description": "Total Outgoing Byte Backlog per Service",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "coherence_connection_manager_outgoing_byte_backlog{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Outgoing Message Backlog",
   "type": "timeseries",
   "description": "Total Outgoing Message Backlog per Service",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "coherence_connection_manager_outgoing_message_backlog{cluster=\"${ClusterName:raw}\",protocol=~\"tcp\"}",
     "legendFormat": "{{name}} "
    }
   ]
  }
 ]
}