{
 "title": "Coherence Services Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(coherence_cluster_size,namespace)"
    }
   },
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(coherence_cluster_size{namespace=~\"${Namespace:.*}\"}, cluster)"
    }
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": {
     "query": "label_values(coherence_cluster_size{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}, version) "
    }
   },
   {
    "name": "Services",
    "label": "Services",
    "query": {
     "query": "label_values(coherence_service_request_max_duration{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}, name)"
    }
   },
   {
    "name": "Caches",
    "label": "Caches",
    "query": {
     "query": "label_values(coherence_cache_size{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}, name) "
    }
   },
   { "name": "TopLimit", "label": "Top N Limit", "query": "1,3,5,10,15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>Services Summary - Version: $CoherenceVersion</h3></center>"
   }
  },
  {
   "title": "Storage Service List",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(coherence_partition_assignment_service_node_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) by (coherence_service) "
    },
    {
     "expr": "avg(coherence_partition_assignment_ha_status_code{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) by (coherence_service)"
    }
   ]
  },
  {
   "title": "Non-Storage Service List",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(coherence_service_member_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",type!~\"DistributedCache|FederatedCache|ReplicatedCache|PagedTopic\"}) by (name, type) "
    }
   ]
  },
  {
   "title": "Service Task Count - All Services",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(coherence_service_task_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) - sum(coherence_service_task_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"} offset $__interval) > 0",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Request/Task Timeouts - All Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(coherence_service_request_timeout_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) - sum(coherence_service_request_timeout_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"} offset $__interval) > 0",
     "legendFormat": "Request Timeouts"
    },
    {
     "expr": "sum(coherence_service_task_timeout_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) - sum(coherence_service_task_timeout_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"} offset $__interval) > 0",
     "legendFormat": "Task Timeouts"
    },
    {
     "expr": "sum(coherence_service_task_hung_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}) - sum(coherence_service_task_hung_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"} offset $__interval) > 0",
     "legendFormat": "Hung Tasks"
    }
   ]
  },
  {
   "title": "Services With Endangered Partitions",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(coherence_service_partitions_endangered{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",type=~\"DistributedCache|FederatedCache|PagedTopic\"}) by (name) > 0"
    }
   ]
  },
  {
   "title": "Services With Vulnerable Partitions",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(coherence_service_partitions_vulnerable{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",type=~\"DistributedCache|FederatedCache|PagedTopic\"}) by (name) > 0"
    }
   ]
  },
  {
   "title": "Services With Unbalanced Partitions",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(coherence_service_partitions_unbalanced{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",type=~\"DistributedCache|FederatedCache|PagedTopic\"}) by (name) > 0"
    }
   ]
  },
  {
   "title": "Top $TopLimit Services - Task Count  - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Services  that have the greatest change in the Task Count over the current time range.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " topk($TopLimit,sum(delta(coherence_service_task_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}[$__range])) by (name, member)) > 0"
    }
   ]
  },
  {
   "title": "Current Top $TopLimit Services - Task Backlog - Current Range",
   "type": "table",
   "description": "The Current top  $TopLimit Services  that have the greatest task backlog.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " topk($TopLimit,sum(coherence_service_task_backlog{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"})  by (name, member)) > 0"
    }
   ]
  }
 ]
}