{
 "title": "Coherence Topics Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(vendor:coherence_cluster_size, cluster)"
    }
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": {
     "query": "label_values(vendor:coherence_cluster_size{cluster=\"${ClusterName:raw}\"}, version)"
    }
   },
   {
    "name": "Services",
    "label": "Services",
    "query": {
     "query": "label_values(vendor:coherence_service_request_max_duration{cluster=\"${ClusterName:raw}\"}, name)"
    }
   },
   {
    "name": "Caches",
    "label": "Caches",
    "query": {
     "query": "label_values(vendor:coherence_cache_size{cluster=\"${ClusterName:raw}\"}, name) "
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>Topics Summary - $ClusterName</h3></center>"
   }
  },
  {
   "title": "Total Published Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vendor:coherence_paged_topic_published_count{cluster=\"${ClusterName:raw}\"})"
    }
   ]
  },
  {
   "title": "Total Active Subscribers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(\nvendor:coherence_paged_topic_subscriber_backlog{cluster=\"${ClusterName:raw}\"}) by (id))"
    }
   ]
  },
  {
   "title": "Total Active Subscriber Groups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(\nvendor:coherence_paged_topic_subscriber_group_polled_count{cluster=\"${ClusterName:raw}\"}) by (name))"
    }
   ]
  },
  {
   "title": "Total Active Subscriber Receives",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vendor:coherence_paged_topic_subscriber_received_count{cluster=\"${ClusterName:raw}\"})"
    }
   ]
  },
  {
   "title": "Total Active Subscriber Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\nvendor:coherence_paged_topic_subscriber_receive_errors{cluster=\"${ClusterName:raw}\"})"
    }
   ]
  },
  {
   "title": "Total Active Subscriber Backlog",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\nvendor:coherence_paged_topic_subscriber_backlog{cluster=\"${ClusterName:raw}\"})"
    }
   ]
  },
  {
   "title": "Topic List",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_paged_topic_published_count{cluster=\"${ClusterName:raw}\"} ) by (coherence_service, name)"
    }
   ]
  },
  {
   "title": "Publishing Rate (All Topics)",
   "type": "timeseries",
   "description": "Shows a graph of topic publish rate for all topics",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_paged_topic_published_count{cluster=\"${ClusterName:raw}\"}) - sum (vendor:coherence_paged_topic_published_count{cluster=\"${ClusterName:raw}\"} offset $__interval) > 0",
     "legendFormat": "Publish Count"
    }
   ]
  },
  {
   "title": "Subscriber Receive Rate (All Topics)",
   "type": "timeseries",
   "description": "Shows a graph of topic subscriber receive rates for all topics",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_paged_topic_subscriber_received_count{cluster=\"${ClusterName:raw}\"}) - sum (vendor:coherence_paged_topic_subscriber_received_count{cluster=\"${ClusterName:raw}\"} offset $__interval) > 0",
     "legendFormat": "Receive Count"
    }
   ]
  }
 ]
}