{
 "title": "Coherence Subscriber Group Details Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(coherence_cluster_size,namespace)"
    }
   },
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(coherence_cluster_size{namespace=~\"${Namespace:.*}\"}, cluster)"
    }
   },
   {
    "name": "ServiceName",
    "label": "Service Name",
    "query": {
     "query": "label_values(coherence_paged_topic_published_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\"}, coherence_service)"
    }
   },
   {
    "name": "TopicName",
    "label": "Topic Name",
    "query": {
     "query": "label_values(coherence_paged_topic_published_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",coherence_service='$ServiceName'}, name)"
    }
   },
   {
    "name": "SubscriberGroup",
    "label": "Subscriber Group",
    "query": {
     "query": "label_values(coherence_paged_topic_subscriber_group_channels_polled_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",coherence_service='$ServiceName',topic=\"$TopicName\"}, name)"
    }
   },
   {
    "name": "NodeId",
    "query": {
     "query": "label_values(coherence_paged_topic_subscriber_group_channels_polled_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",coherence_service='$ServiceName',topic=\"$TopicName\", name=\"$SubscriberGroup\"}, node_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>Subscriber Group Details - $ServiceName / $TopicName / $SubscriberGroup</h3></center>"
   }
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " count(count(coherence_paged_topic_subscriber_group_channels_polled_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", name=\"$SubscriberGroup\"}) by (channel))"
    }
   ]
  },
  {
   "title": "Polls (All Members)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coherence_paged_topic_subscriber_group_polled_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", name=\"$SubscriberGroup\"})"
    }
   ]
  },
  {
   "title": "Subscriber Group Members",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(coherence_paged_topic_subscriber_group_polled_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", name=\"$SubscriberGroup\"}) by (node_id, member)"
    }
   ]
  },
  {
   "title": "Poll Rate",
   "type": "timeseries",
   "description": "Shows a graph of topic subscriber receive rates for $TopicName",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(coherence_paged_topic_subscriber_group_polled_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\",name=\"$SubscriberGroup\"}) - sum (coherence_paged_topic_subscriber_group_polled_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\",name=\"$SubscriberGroup\"} offset $__interval) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "<center><h3>Subscriber Group Channels Details</h3></center>\n<center>Note: Select Node Id variable</center>"
   }
  },
  {
   "title": "Details for Node Id $NodeId",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "repeat": "NodeId",
   "targets": [
    {
     "expr": "sum(coherence_paged_topic_subscriber_group_channels_polled_count{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", name=\"$SubscriberGroup\",node_id=\"$NodeId\"}) by (channel)"
    },
    {
     "expr": "sum(coherence_paged_topic_subscriber_group_channels_polled_rate{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", name=\"$SubscriberGroup\",rate=\"mean\",node_id=\"$NodeId\"}) by (channel)"
    },
    {
     "expr": "sum(coherence_paged_topic_subscriber_group_channels_polled_rate{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", name=\"$SubscriberGroup\",rate=\"1min\",node_id=\"$NodeId\"}) by (channel)"
    },
    {
     "expr": "sum(coherence_paged_topic_subscriber_group_channels_polled_rate{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", name=\"$SubscriberGroup\",rate=\"5min\",node_id=\"$NodeId\"}) by (channel)"
    },
    {
     "expr": "sum(coherence_paged_topic_subscriber_group_channels_polled_rate{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", name=\"$SubscriberGroup\",rate=\"15min\",node_id=\"$NodeId\"}) by (channel)"
    },
    {
     "expr": "sum(coherence_paged_topic_subscriber_group_channels_owning_subscriber_id{namespace=~\"${Namespace:.*}\",cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", name=\"$SubscriberGroup\",node_id=\"$NodeId\"}) by (channel)"
    }
   ]
  }
 ]
}