{
 "title": "Coherence Subscriber Details Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(vendor:coherence_cluster_size, cluster)"
    }
   },
   {
    "name": "ServiceName",
    "label": "Service Name",
    "query": {
     "query": "label_values(vendor:coherence_paged_topic_published_count{cluster=\"${ClusterName:raw}\"}, coherence_service)"
    }
   },
   {
    "name": "TopicName",
    "label": "Topic Name",
    "query": {
     "query": "label_values(vendor:coherence_paged_topic_published_count{cluster=\"${ClusterName:raw}\",coherence_service='$ServiceName'}, name)"
    }
   },
   {
    "name": "Subscriber",
    "query": {
     "query": "label_values(vendor:coherence_paged_topic_subscriber_receive_completions{cluster=\"${ClusterName:raw}\",coherence_service='$ServiceName',topic=\"$TopicName\"}, id)"
    }
   },
   {
    "name": "NodeId",
    "query": {
     "query": "label_values(vendor:coherence_paged_topic_subscriber_receive_completions{cluster=\"${ClusterName:raw}\",coherence_service='$ServiceName',topic=\"$TopicName\",id=\"$Subscriber\"}, node_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h3>Subscriber Details - \n  $ServiceName / $TopicName / $Subscriber (Node Id: ${NodeId})</h3></center>"
   }
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " count(count(vendor:coherence_paged_topic_subscriber_channels_receive_completions{cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", id=\"$Subscriber\"}) by (channel))"
    }
   ]
  },
  {
   "title": "Receives",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vendor:coherence_paged_topic_subscriber_received_count{cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", id=\"$Subscriber\"})"
    }
   ]
  },
  {
   "title": "Polls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vendor:coherence_paged_topic_subscriber_polls{cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", id=\"$Subscriber\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\nvendor:coherence_paged_topic_subscriber_receive_errors{cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName\", id=\"$Subscriber\"})"
    }
   ]
  },
  {
   "title": "Disconnections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\nvendor:coherence_paged_topic_subscriber_disconnections{cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", id=\"$Subscriber\"})"
    }
   ]
  },
  {
   "title": "Backlog",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\nvendor:coherence_paged_topic_subscriber_backlog{cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", id=\"$Subscriber\"})"
    }
   ]
  },
  {
   "title": "Channel Receives",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_paged_topic_subscriber_channels_receive_completions_count{cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", id=\"$Subscriber\"}) by (channel)"
    },
    {
     "expr": "sum(vendor:coherence_paged_topic_subscriber_channels_receive_completions{cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", id=\"$Subscriber\",rate=\"mean\"}) by (channel)"
    },
    {
     "expr": "sum(vendor:coherence_paged_topic_subscriber_channels_receive_completions{cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", id=\"$Subscriber\",rate=\"1min\"}) by (channel)"
    },
    {
     "expr": "sum(vendor:coherence_paged_topic_subscriber_channels_receive_completions{cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", id=\"$Subscriber\", rate=\"5min\"}) by (channel)"
    },
    {
     "expr": "sum(vendor:coherence_paged_topic_subscriber_channels_receive_completions{cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", id=\"$Subscriber\", rate=\"15min\"}) by (channel)"
    },
    {
     "expr": "sum(vendor:coherence_paged_topic_subscriber_channels_owned_code{cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", id=\"$Subscriber\"}) by (channel)"
    }
   ]
  },
  {
   "title": "Receive Rate",
   "type": "timeseries",
   "description": "Shows a graph of topic subscriber receive rates for the current subscriber",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_paged_topic_subscriber_received_count{cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", id=\"$Subscriber\"}) - sum (vendor:coherence_paged_topic_subscriber_received_count{cluster=\"${ClusterName:raw}\",coherence_service=\"${ServiceName}\", topic=\"${TopicName}\", id=\"$Subscriber\"} offset $__interval) > 0",
     "legendFormat": "Receive Count"
    }
   ]
  }
 ]
}