{
 "title": "Coherence Proxy Servers Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor:coherence_cluster_size{cluster=~\"$ClusterName\"}, version)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Proxy Servers Summary - $ClusterName</h3></center>"
  },
  {
   "title": "Proxy Service List - Coherence*Extend",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "count(vendor:coherence_connection_manager_connection_count{cluster=~\"$ClusterName\",protocol=~\"tcp\"}) by (name)"
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_connection_count{cluster=~\"$ClusterName\",protocol=~\"tcp\"}) by (name)"
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_total_messages_received{cluster=~\"$ClusterName\",protocol=~\"tcp\"}) by (name)"
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_total_messages_sent{cluster=~\"$ClusterName\",protocol=~\"tcp\"}) by (name)"
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_total_bytes_received{cluster=~\"$ClusterName\",protocol=~\"tcp\"}) by (name)"
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_total_bytes_sent{cluster=~\"$ClusterName\",protocol=~\"tcp\"}) by (name)"
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_outgoing_byte_backlog{cluster=~\"$ClusterName\",protocol=~\"tcp\"}) by (name)"
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_unauthorized_connection_attempts{cluster=~\"$ClusterName\"}) by (name) "
    }
   ]
  },
  {
   "title": "Total Bytes Sent/ sec per Service",
   "type": "graph",
   "description": "Total bytes sent (bytes/sec) of all Proxy Server members.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_connection_manager_total_bytes_sent{cluster=~\"$ClusterName\",protocol=~\"tcp\"} - vendor:coherence_connection_manager_total_bytes_sent{cluster=~\"$ClusterName\",protocol=~\"tcp\"} offset $__interval ",
     "legendFormat": "{{name}} Sent"
    }
   ]
  },
  {
   "title": "Total Bytes Received/ sec per Service",
   "type": "graph",
   "description": "Total bytes received (bytes/sec) of all Proxy Server members.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_connection_manager_total_bytes_received{cluster=~\"$ClusterName\",protocol=~\"tcp\"} - vendor:coherence_connection_manager_total_bytes_received{cluster=~\"$ClusterName\",protocol=~\"tcp\"} offset $__interval ",
     "legendFormat": "{{name}} Received"
    }
   ]
  },
  {
   "title": "Total Proxy Connections",
   "type": "graph",
   "description": "Total Proxy Connections Across All Services",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_connection_manager_connection_count{cluster=~\"$ClusterName\",protocol=~\"tcp\"}) ",
     "legendFormat": "Total Connections"
    }
   ]
  },
  {
   "title": "Total Proxy Connections Per Service",
   "type": "graph",
   "description": "Total Proxy connections per service",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_connection_manager_connection_count{cluster=~\"$ClusterName\",protocol=~\"tcp\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Outgoing Byte Backlog",
   "type": "graph",
   "description": "Total Outgoing Byte Backlog per Service",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_connection_manager_outgoing_byte_backlog{cluster=~\"$ClusterName\",protocol=~\"tcp\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Outgoing Message Backlog",
   "type": "graph",
   "description": "Total Outgoing Message Backlog per Service",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_connection_manager_outgoing_message_backlog{cluster=~\"$ClusterName\",protocol=~\"tcp\"}",
     "legendFormat": "{{name}} "
    }
   ]
  }
 ]
}