{
 "title": "Elastic Data Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor:coherence_cluster_size{cluster=~\"$ClusterName\"}, version)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Elastic Data Summary - $ClusterName</h3></center>"
  },
  {
   "title": "RAM Journal Files Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_journal_file_count{cluster=~\"$ClusterName\",name=~\"RamJournalRM\"})"
    }
   ]
  },
  {
   "title": "Total RAM Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_journal_total_data_size{cluster=~\"$ClusterName\",name=~\"RamJournalRM\"})"
    }
   ]
  },
  {
   "title": "Flash Journal Files Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_journal_file_count{cluster=~\"$ClusterName\",name=~\"FlashJournalRM\"})"
    }
   ]
  },
  {
   "title": "Total Flash Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_journal_total_data_size{cluster=~\"$ClusterName\",name=~\"FlashJournalRM\"})"
    }
   ]
  },
  {
   "title": "RAM Journal Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_journal_total_data_size{cluster=~\"$ClusterName\",name=~\"RamJournalRM\"}) by (name)",
     "legendFormat": "Total Used RAM"
    }
   ]
  },
  {
   "title": "Flash Journal Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_journal_total_data_size{cluster=~\"$ClusterName\",name=~\"FlashJournalRM\"}) by (name)",
     "legendFormat": "Total Used Flash"
    }
   ]
  },
  {
   "title": "RAM Journal Compactions - All Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vendor:coherence_journal_compaction_count{cluster=~\"$ClusterName\",name=~\"RamJournalRM\"}[1m])) by (name)",
     "legendFormat": "Compaction Count"
    },
    {
     "expr": "sum(idelta(vendor:coherence_journal_exhaustive_compaction_count{cluster=~\"$ClusterName\",name=~\"RamJournalRM\"}[1m])) by (name)",
     "legendFormat": "Exhaustive Compaction Count"
    }
   ]
  },
  {
   "title": "Flash Journal Compactions - All Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vendor:coherence_journal_compaction_count{cluster=~\"$ClusterName\",name=~\"FlashJournalRM\"}[1m])) by (name)",
     "legendFormat": "Compaction Count"
    },
    {
     "expr": "sum(idelta(vendor:coherence_journal_exhaustive_compaction_count{cluster=~\"$ClusterName\",name=~\"FlashJournalRM\"}[1m])) by (name)",
     "legendFormat": "Exhaustive Compaction Count"
    }
   ]
  }
 ]
}