{
 "title": "Services Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor:coherence_cluster_size{cluster=~\"$ClusterName\"}, version) "
   },
   {
    "name": "Services",
    "label": "Services",
    "query": "label_values(vendor:coherence_service_request_max_duration{cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "Caches",
    "label": "Caches",
    "query": "label_values(vendor:coherence_cache_size{cluster=~\"$ClusterName\"}, name) "
   },
   { "name": "TopLimit", "label": "Top N Limit", "query": "1,3,5,10,15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Services Summary - Version: $CoherenceVersion</h3></center>"
  },
  {
   "title": "Storage Service List",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "avg(vendor:coherence_partition_assignment_service_node_count{cluster=~\"$ClusterName\"}) by (coherence_service) "
    },
    {
     "expr": "avg(vendor:coherence_partition_assignment_ha_status_code{cluster=~\"$ClusterName\"}) by (coherence_service)"
    }
   ]
  },
  {
   "title": "Non-Storage Service List",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "count(vendor:coherence_service_member_count{cluster=~\"$ClusterName\",type!~\"DistributedCache|FederatedCache|ReplicatedCache\"}) by (name, type) "
    }
   ]
  },
  {
   "title": "Service Task Count (Stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vendor:coherence_service_task_count{cluster=~\"$ClusterName\"}[1m])) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Services With Endangered Partitions",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(vendor:coherence_service_partitions_endangered{cluster=~\"$ClusterName\",type=~\"DistributedCache|FederatedCache\"}) by (name) > 0"
    }
   ]
  },
  {
   "title": "Services With Vulnerable Partitions",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "avg(vendor:coherence_service_partitions_vulnerable{cluster=~\"$ClusterName\",type=~\"DistributedCache|FederatedCache\"}) by (name) > 0"
    }
   ]
  },
  {
   "title": "Services With Unbalanced Partitions",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "avg(vendor:coherence_service_partitions_unbalanced{cluster=~\"$ClusterName\",type=~\"DistributedCache|FederatedCache\"}) by (name) > 0"
    }
   ]
  },
  {
   "title": "Top $TopLimit Services - Task Count  - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Services  that have the greatest change in the Task Count over the current time range.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": " topk($TopLimit,sum(delta(vendor:coherence_service_task_count{cluster=~\"$ClusterName\"}[$__range])) by (name, member)) > 0"
    }
   ]
  },
  {
   "title": "Current Top $TopLimit Services - Task Backlog - Current Range",
   "type": "table",
   "description": "The Current top  $TopLimit Services  that have the greatest task backlog.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": " topk($TopLimit,sum(vendor:coherence_service_task_backlog{cluster=~\"$ClusterName\"})  by (name, member)) > 0"
    }
   ]
  }
 ]
}