clusterSize:

imagePullSecrets: [sample-coherence-secret]

role: WebServer

clusterName:

wka:

image: "${docker.push.tag.prefix}${project.artifactId}:${project.version}"

imagePullPolicy:

service:
  enabled: true
  type: "ClusterIP"
  domain: "cluster.local"
  loadBalancerIP:
  annotations:
  httpPort:
