apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  network:
    dnsConfig:
      nameServers:
        - "ns-one"
        - "ns-two"
      searches:
        - "s-one"
        - "s-two"
      options:
        - name: "o1"
          value: "v1"
        - name: "o2"
          value: "v2"
  roles:
    - role: data
    - role: proxy
      network:
        dnsConfig:
          nameServers:
            - "ns-three"
            - "ns-four"
          searches:
            - "s-three"
            - "s-four"
          options:
            - name: "o3"
              value: "v3"
            - name: "o4"
              value: "v4"
    - role: web
      network:
        dnsConfig:
          nameServers:
            - "ns-three"
            - "ns-four"
          searches:
            - "s-three"
            - "s-four"
          options:
            - name: "o1"
              value: "v11"
            - name: "o4"
              value: "v4"
