apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  network:
    hostname: "foo.com"
  roles:
    - role: data
    - role: proxy
      network:
        hostname: "bar.com"
