apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      network:
        hostAliases:
          - ip: "10.10.10.100"
            hostnames:
              - "foo1.com"
              - "foo2.com"
          - ip: "10.10.10.200"
            hostnames:
              - "bar1.com"
              - "bar2.com"
    - role: proxy
      network:
        hostAliases:
          - ip: "10.10.10.300"
            hostnames:
              - "foo3.com"
              - "foo4.com"
          - ip: "10.10.10.400"
            hostnames:
              - "bar3.com"
              - "bar4.com"
