apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  jvm:
    memory:
      heapSize: 1g
  roles:
    - role: data
    - role: proxy
      jvm:
        memory:
          heapSize: 500m
