apiVersion: coherence.oracle.com/v1
kind: CoherenceJob
metadata:
  labels:
    app.kubernetes.io/name: coherence-operator
    app.kubernetes.io/managed-by: kustomize
  name: coherencejob-sample
spec:
  replicas: 1

