# -------------------------------------------------------------
# This is the Cluster Roles required by the Coherence Operator
# to self-manage its CRDs and Web-Hooks.
# -------------------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-webhook-install-role
$patch: delete
