apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../default

patches:
  - path: single-namespace-patch.yaml
    target:
      kind: Deployment
      name: controller-manager
  - path: node-viewer-role.yaml
  - path: node_viewer_role_binding.yaml
