#
# This patch will remove the ClusterRoleBinding to allow the
# Operator to read Node labels.
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-viewer-rolebinding
$patch: delete
