#
# Copyright (c) 2020, 2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
# Federation Example
# Secondary cluster with 'storage` role in an Active/Active topology
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: secondary-cluster-storage
spec:
  cluster: secondary-cluster
  role: storage
  jvm:
    memory:
      heapSize: 512m
    args:
      - "-Dwith.http=false"
      - "-Dwith.data=false"
      - "-Dcoherence.clusterport=40000"
      - "-Dprimary.cluster=primary-cluster"
      - "-Dprimary.cluster.port=40000"
      - "-Dprimary.cluster.host=primary-cluster-storage-wka"
      - "-Dsecondary.cluster=secondary-cluster"
      - "-Dsecondary.cluster.port=40000"
      - "-Dsecondary.cluster.host=secondary-cluster-storage-wka"
  ports:
    - name: federation
      port: 40000
    - name: metrics
      port: 9612
      serviceMonitor:
        enabled: true
  coherence:
    cacheConfig: storage-cache-config.xml
    overrideConfig: tangosol-coherence-override.xml
    metrics:
      enabled: true
      port: 9612
  image: lsho/federation-example:1.0.0
  imagePullPolicy: Always
  replicas: 2
