///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Prerequisites

Everything needed to install and run the Coherence Operator is listed below:

== Prerequisites

* Access to a Kubernetes v1.11.3+ cluster.
* Access to Oracle Coherence Docker images.

=== Image Pull Secrets

In order for the Coherence Operator to be able to install Coherence clusters it needs to be able to pull Coherence
Docker images. These images are not available in public Docker repositories and will typically Kubernetes will need
authentication to be able to pull them. This is achived by creating pull secrets.
Pull secrets are not global and hence secrets will be required in the namespace(s) that Coherence
clusters will be installed into.

