///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Installing With Helm

The simplest way to install the Coherence Operator is to use the Helm chart.
This will ensure that all of the correct resources are created in Kubernetes.

== Add the Coherence Helm Repository

Add the `coherence` helm repository using the following commands:

[source,bash]
----
helm repo add coherence https://oracle.github.io/coherence-operator/charts

helm repo update
----

== Install the Coherence Operator Helm chart

Once the Coherence Helm repo is configured the Coherence Operator can be installed using a normal Helm install command:

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --name coherence-operator \
    coherence/coherence-operator
----

where `<namespace>` is the namespace that the Coherence Operator will be installed into and the namespace where it will
manage `CoherenceClusters`

=== Uninstall the Coherence Operator Helm chart

To uninstall the operator:
[source,bash]
----
helm delete --purge coherence-operator
----
