///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Installing Manually

It is possible to install the Coherence Operator by crating the required yaml manually and installing it into Kubernetes.

== RBAC
In Kubernetes clusters with RBAC enabled the Coherence Operator requires certain RBAC resources to be created.

[source,bash]
----
cd examples/scripts
sh create_role.sh
----

The example RBAC script creates a `ServiceAccount` with the name `coherence-operator` if a different name is required
then the name in the `example/scripts/example-rbac.yaml` should be modified.

The shell script above will use default values for the role name, role binding name and install into the `default`
namespace. If the default values need to be changed or the operator is to be installed into a namespace other than
`default` the script can be run with the following environment variables:

[source,bash]
----
export ROLE_NAME=<role-name>
export ROLE_BINDING_NAME=<role-binding-name>
export NAMESPACE=<namespace>
sh example/create_role.sh
----


== Deployment
Create a `Deployment` for the Coherence Operator using the example script.

[source,bash]
----
kubectl -n <namespace> create -f example-deployment.yaml
----

where `<namespace>` is the name of the namespace that the operator is to be deployed into.
If RBAC is being used this will also be the same namespace used to create the RBAC roles.
If the `default` namespace is being used the `-n <namespace>` argument can be omitted.


