///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Accessing Pre-Release Versions

Pre-release version of the Coherence Operator are made available from time to time.

== Accessing Pre-Release Versions

WARNING: Pre-release versions of the Coherence Operator are not guaranteed to be bug free and should not be used for
production use. Pre-release versions of the Helm chart and Docker images may be removed and hence made unavailable
without notice. APIs and CRD specifications are not guaranteed to remain stable or backwards compatible  between
pre-release versions.

To access pre-release versions of the Helm chart add the unstable chart repository.

[source,bash]
----
helm repo add coherence-unstable https://oracle.github.io/coherence-operator/charts-unstable

helm repo update
----


To list all of the available Coherence Operator chart versions:
[source,bash]
----
helm search coherence-operator -l
----
The `-l` parameter shows all versions as opposed to just the latest versions if it was omitted.


A specific pre-release version of the Helm chart can be installed using the `--version` argument,
for example to use version `2.0.0-1909130555`:
[source,bash]
----
helm install coherence-unstable/coherence-operator \
    --version 2.0.0-1909130555 \    <1>
    --namespace <namespace> \       <2>
    --name coherence-operator
----

<1> The `--version` argument is used to specify the exact version of the chart
<2> The optional `--namespace` parameter to specify which namespace to install the operator into, if omitted then
Helm will install into whichever is currently the default namespace for your Kubernetes configuration.

NOTE: When using pre-release versions of the Helm chart it is always advisable to install a specific version otherwise
Helm will try to work out the latest version in the pre-release repo and as pre-release version numbers are not strictly
sem-ver compliant this may be unreliable.

=== Accessing Pre-Release Coherence Operator Docker Images

NOTE: Not all pre-release images are pushed to public repositories such as Docker Hub.
Consequently when installing those versions of the Coherence Operator credentials and Kubernetes pull secrets will be required.

For example to access an image in the `iad.ocir.io/odx-stateservice` repository you would need to have your own credentials
for that repository so that a secret can be created.

[source,bash]
----
kubectl -n <namespace> \                                     <1>
  create secret docker-registry coherence-operator-secret \  <2>
  --docker-server=$DOCKER_REPO \                             <3>
  --docker-username=$DOCKER_USERNAME \                       <4>
  --docker-password=$DOCKER_PASSWORD \                       <5>
  --docker-email=$DOCKER_EMAIL                               <6>
----

<1> Replace <namespace> with the Kubernetes namespace that the Coherence Operator will be installed into.
<2> In this example the name of the secret to be created is `coherence-operator-secret`
<3> Replace `$DOCKER_REPO` with the name of the Docker repository that the images are to be pulled from.
<4> Replace `$DOCKER_USERNAME` with your username for that repository.
<5> Replace `$DOCKER_PASSWORD` with your password for that repository.
<6> Replace `$DOCKER_EMAIL` with your email (or even a fake email).

See the https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/[Kubernetes documentation]
on pull secrets for more details.

Once a secret has been created in the namespace the Coherence Operator can be installed with an extra value parameter
to specify the secret to use:

[source,bash]
----
helm install coherence-unstable/coherence-operator \
    --version 2.0.0-1909130555 \
    --namespace <namespace> \
    --set imagePullSecrets=coherence-operator-secret \  <1>
    --name coherence-operator
----

<1> Set the pull secret to use to the same name that was created above.

