---
apiVersion: v1
kind: Service
metadata:
  name: storage-metrics
  labels:
    coherence.oracle.com/cluster: test-cluster
    coherence.oracle.com/deployment: storage
    coherence.oracle.com/component: metrics-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 9612
    targetPort: metrics
  selector:
    coherence.oracle.com/cluster: test-cluster
    coherence.oracle.com/deployment: storage
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: storage-metrics
  labels:
    coherence.oracle.com/cluster: test-cluster
    coherence.oracle.com/deployment: storage
    coherence.oracle.com/component: service-monitor
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      coherence.oracle.com/cluster: test-cluster
      coherence.oracle.com/deployment: storage
      coherence.oracle.com/component: metrics-service
