apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../default

components:
  - ../../components/pull-secrets

patches:
  - path: always-pull-patch.yaml
    target:
      kind: Deployment
      name: controller-manager
