///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////
== Example Coherence Server Image

The `examples/no-operator/server-image/` directory contains a simple Maven project that builds an image containing a very simple Coherence application.
This application is nothing more than a cache configuration file that has an Extend proxy along with Coherence metrics and management over REST. We will use this image in the various examples we cover here. When we run the image it will start a simple storage enabled Coherence server.

The server image Maven project, in the `server-image/` directory, uses the
https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin[JIB Maven plugin]
to build an image we can use in these examples. JIB is simple to use and configure and creates reasonably secure images based on distroless Java base images. These images contain the core Linux runtime and a JVM, there are no command line shells or other utilities to introduce security concerns. The down-side is that you cannot exec into a running container, but with the introduction of ephemeral containers in Kubernetes, this is not such an issue.

To create the server image run the following command from the `server-image/` directory:
[source,bash]
----
mvn clean compile jib:dockerBuild
----
The command above will create an image named `simple-coherence:1.0.0` which we use in some of the Non-Operator examples.


