///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Overview

== Overview

The Coherence Operator allows full control over the configuration of the JVM used to run the Coherence application.
The `jvm` section of the `Coherence` CRD spec has a number of fields to easily configure specific aspects of the
JVM as well as a catch-all `jvm.args` list that allows any arbitrary argument to be passed to the JVM.

Whilst every configuration setting could, in theory, be set only by specifying JVM arguments in the `jvm.args`
field of the `Coherence` CRD, the other configuration fields provide simpler means to set configuration
without having to remember specific JVM argument names or system property names to set.
You are, of course, free to use whichever approach best suits your requirements;
but obviously it is better to choose one approach and be consistent.

=== Guides to JVM Settings

[PILLARS]
====
[CARD]
.Classpath
[link=docs/jvm/020_classpath.adoc]
--
Default classpath settings and options for setting a custom classpath.
--

[CARD]
.JVM Arguments
[link=docs/jvm/030_jvm_args.adoc]
--
Adding arbitrary JVM arguments and system properties.
--

[CARD]
.Garbage Collection
[link=docs/jvm/040_gc.adoc]
--
Configuring the garbage collector.
--

[CARD]
.Heap & Memory Settings
[link=docs/jvm/050_memory.adoc]
--
Configuring the heap size and other memory settings.
--
====

[PILLARS]
====
[CARD]
.Debugger
[link=docs/jvm/070_debugger.adoc]
--
Using debugger settings.
--

[CARD]
.Use Container Limits
[link=docs/jvm/090_container_limits.adoc]
--
Configuring the JVM to respect container resource limits.
--
====
