///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2025, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Garbage Collector Settings
:description: Coherence Operator Documentation - Garbage Collector Settings
:keywords: oracle coherence, kubernetes, operator, documentation, Garbage Collector

== Garbage Collector Settings

The `Coherence` CRD has fields in the `jvm.gc` section to allow certain garbage collection parameters to be set.
These include GC logging, setting the collector to use and arbitrary GC arguments.

[IMPORTANT]
====
If running Kubernetes on ARM processors and using Coherence images built on Java 8 for ARM,
note that the G1 garbage collector in that version of Java on ARM is marked as experimental.

By default, the Operator configures the Coherence JVM to use G1.
This will cause errors on Arm64 Java 8 JMS unless the JVM option `-XX:+UnlockExperimentalVMOptions` is
added in the Coherence resource spec.
Alternatively specify a different garbage collector, ideally on a version of Java this old, use CMS.
====

=== Enable GC Logging

To enable GC logging set the `jvm.gc.logging` field to `true`.
For example:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    gc:
      logging: true
----

Setting the field to true adds the following JVM arguments to the JVM in the `coherence` container:
----
-verbose:gc
-XX:+PrintGCDetails
-XX:+PrintGCTimeStamps
-XX:+PrintHeapAtGC
-XX:+PrintTenuringDistribution
-XX:+PrintGCApplicationStoppedTime
-XX:+PrintGCApplicationConcurrentTime
----

If different GC logging arguments are required then the relevant JVM arguments can be added to either the
`jvm.args` field or the `jvm.gc.args` field.

=== Set the Garbage Collector

The garbage collector to use can be set using the `jvm.gc.collector` field.
This field can be set to either `G1`, `CMS` or `Parallel`
(the field is case-insensitive, invalid values will be silently ignored).

The default collector set, if none has been specified, will be whatever is the default for the JVM being used.

|====
| Parameter  | JVM Argument Set
| `G1`       | `-XX:+UseG1GC`
| `CMS`      | `-XX:+UseConcMarkSweepGC`
| `Parallel` | `-XX:+UseParallelGC`
| `Serial`   | `-XX:+UseSerialGC`
| `ZGC`      | `-XX:+UseZGC`
|====

For example:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    gc:
      collector: "ZGC"
----
The example above will add `-XX:+UseZGC` to the command line.

[NOTE]
====
The JVM only allows a single `-XX:Use****` option that sets the garbage collector to use, so the collector should not be
specified in both the `spec.jvm.gc.collector` field, and in the `spec.jvm.args` field.
====

=== Adding Arbitrary GC Args

Any arbitrary GC argument can be added to the `jvm.gc.args` field.
These arguments will be passed verbatim to the JVM command line.

For example:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    gc:
      args:
        - "-XX:MaxGCPauseMillis=200"
----
In the example above the `-XX:MaxGCPauseMillis=200` JVM argument will be added to the command line.

NOTE: The `jvm.gc.args` field will add the provided arguments to the end of the command line exactly as they
are in the args list. This field provides the same functionality as <<docs/jvm/030_jvm_args.adoc,JVM Args>>
but sometimes it might be useful to be able to separate the two gorups of arguments in the CRD spec.

