///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2025 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Heap & Memory Settings
:description: Coherence Operator Documentation - Heap & Memory Settings
:keywords: oracle coherence, kubernetes, operator, documentation, Heap, Memory, Settings

== Heap & Memory Settings

The JVM has a number of arguments that set the sizes of different memory regions; the most commonly set is the heap
size but there are a number of others. The `Coherence` CRD spec has fields that allow some of these to sizes to be
set.

The `Coherence` CRD also has settings to control the behaviour of the JVM if an out of memory error occurs.
For example, killing the container, creating a heap dump etc.

=== Max RAM

The JVM has an option `-XX:MaxRAM=N` the maximum amount of memory used by the JVM to `n`, where `n` is expressed in
terms of megabytes (for example, `100m`) or gigabytes (for example `2g`).

When using resource limited containers it is useful to set the max RAM option to avoid the JVM exceeding the
container limits.

The `Coherence` CRD allows the max RAM option to be set using the `jvm.memory.maxRAM` field, for example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    memory:
      maxRAM: 10g
----

=== Heap Size as a Percentage of Container Memory

There are three JVM options that can be used to control the JVM heap as a percentage of the available memory.
These options can be useful when controlling memory as a percentage of container memory in combination
with resource limits on containers.

|===
|JVM Option |Description

|`-XX:InitialRAMPercentage=N`
|Sets the initial amount of memory that the JVM will use for the Java heap before applying ergonomics heuristics as a
percentage of the maximum amount determined as described in the -XX:MaxRAM option. The default value is 1.5625 percent.

|'-XX:MaxRAMPercentage=N'
|Sets the maximum amount of memory that the JVM may use for the Java heap before applying ergonomics heuristics as a
percentage of the maximum amount determined as described in the `-XX:MaxRAM` option.
The default value is 25 percent.

Specifying this option disables automatic use of compressed oops if the combined result of this and other options
influencing the maximum amount of memory is larger than the range of memory addressable by compressed oops.


|'-XX:MinRAMPercentage=N'
|Sets the maximum amount of memory that the JVM may use for the Java heap before applying ergonomics heuristics as a
percentage of the maximum amount determined as described in the -XX:MaxRAM option for small heaps.
A small heap is a heap of approximately 125 MB.
The default value is 50 percent.
|===

Where `N` is a decimal value between 0 and 100. For example, 12.3456.

When running in a container, and the `-XX:+UseContainerSupport` is set (which it is by default for the Coherence
container), both the default heap size for containers, the `-XX:InitialRAMPercentage` option, the `-XX:MaxRAMPercentage`
option, and the `-XX:MaxRAMPercentage` option, will be based on the available container memory.

NOTE: Some JVMs may not support these options.

The `Coherence` CRD allows these options to be set with the `jvm.memory.initialRAMPercentage`, `jvm.memory.minRAMPercentage`,
and `jvm.memory.maxRAMPercentage` fields.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    memory:
      initialRAMPercentage: 10
      minRAMPercentage: 5.75
      maxRAMPercentage: 75
----

==== Set Heap Percentages From a Single Value

Typically, with Coherence storage members the initial and maximum heap values will be set to the same value so that the
JVM runs with a fixed size heap. The `Coherence` CRD provides the `jvm.memory.percentage` field for this use-case.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    memory:
      percentage: 10  # <1>
----
<1> In this case the `percentage` field has been set to `10`, so the options passed to the JVM will be
`-XX:InitialRAMPercentage=10 -XX:MinRAMPercentage=10 -XX:MaxRAMPercentage=10` meaning the heap size
will be fixed at 10% of max RAM.

NOTE: Setting the `jvm.memory.percentage` field will cause individual RAM percentage fields to be ignored.

NOTE: The JVM documentation states that _"If you set a value for `-Xms`, the `-XX:InitialRAMPercentage`,
`-XX:MinRAMPercentage` and `-XX:MaxRAMPercentage` options will be ignored"_. So if the `Coherence` CRD fields
detailed below for explictly setting the heap size as a bytes value are used then we can assume that the RAM
percentage fields detailed here will be ignored by the JVM. The Coherence Operator will pass both the percentage
and explicit values to the JVM.

NOTE: Due to CRDs not supporting decimal fields the RAM percentage fields are of type resource.Quantity,
see the Kubernetes https://godoc.org/k8s.io/apimachinery/pkg/api/resource#Quantity[Quantity] API docs for details
of the different number formats allowed.

=== Set Heap Size Explicitly

There are two JVM options that can be used to control the JVM heap as an explicit size in bytes value.
These options can be useful when controlling memory of container memory in combination with resource limits on containers.

|===
|JVM Option |Description

| `-XX:InitialHeapSize=<size>`
| Set initial heap size

| `-XX:MaxHeapSize=<size>`
| Set maximum heap size

|===

The `<size>` parameter is a numeric integer followed by a suffix to the size value: "k" or "K" to indicate kilobytes,
"m" or "M" to indicate megabytes, "g" or "G" to indicate gigabytes, or, "t" or "T" to indicate terabytes.

For example:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    memory:
      initialHeapSize: 5g  # <1>
      maxHeapSize: 10g     # <2>
----
<1> The initial heap size to `5g`, passing the `-XX:InitialHeapSize=5g` option to the JVM.
<2> The max heap size to `10g`, passing the `-XX:MaxHeapSize=10g` option to the JVM.

NOTE: Setting the `jvm.memory.heapSize` field will cause individual `jvm.memory.initialHeapSize` and
`jvm.memory.maxHeapSize` fields to be ignored.

==== Set Initial and Max Heap Size With a Single Value

Typically, with Coherence storage members the initial and maximum heap values will be set to the same value so that the
JVM runs with a fixed size heap. The `Coherence` CRD provides the `jvm.memory.heapSize` field for this use-case.

To set the JVM both the initial amd max heap sizes to the same value, set the `jvm.memory.heapSize` field.
The value of the field can be any value that can be used with the JVM `-XX:InitialHeapSize` and `-XX:MaxHeapSize`
(or `-Xmx` and `-Xms`) arguments.
The value of the `jvm.memory.heapSize` field will be used to set both the `-XX:InitialHeapSize`, and the
`-XX:MaxHeapSize` arguments to the same value, so the heap will be a fixed size.

For example:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    memory:
      heapSize: 10g  # <1>
----
<1> Setting `jvm.memory.heapSize` to `10g` will effectively pass `-XX:InitialHeapSize=10g -XX:MaxHeapSize=10g` to the JVM.


=== Direct Memory Size (NIO Memory)

Direct memory size is used to limit on memory that can be reserved for all Direct Byte Buffers.
If a value is set for this option, the sum of all Direct Byte Buffer sizes cannot exceed the limit.
After the limit is reached, a new Direct Byte Buffer can be allocated only when enough old buffers are freed to provide
enough space to allocate the new buffer.

By default, the VM limits the amount of heap memory used for Direct Byte Buffers to approximately 85% of the maximum heap size.

To set a value for the direct memory size use the `jvm.memory.directMemorySize` field. This wil set the value of the
`-XX:MaxDirectMemorySize` JVM option.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    memory:
      directMemorySize: 10g  # <1>
----
<1> The direct memory size is set to `10g` which will pass `-XX:MaxDirectMemorySize=10g` to the JVM.


=== Metaspace Size

Metaspace is memory the VM uses to store class metadata.
Class metadata are the runtime representation of java classes within a JVM process - basically any information the JVM
needs to work with a Java class. That includes, but is not limited to, runtime representation of data from the JVM
class file format.

To set the size of the metaspace use the `jvm.memory.metaspaceSize` field in the `Coherence` CRD.
Setting this field sets both the `-XX:MetaspaceSize` and `-XX:MaxMetaspaceSize` JVM options to this value giving a
fixed size metaspace.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    memory:
      metaspaceSize: 100m  # <1>
----
<1> Set the metaspace size to `100m` which will pass `-XX:MetaspaceSize=100m -XX:MaxMetaspaceSize=100m`
to the JVM.


=== Stack Size

Thread stacks are memory areas allocated for each Java thread for their internal use.
This is where the thread stores its local execution state.
The current default size for a linux JVM is 1MB.

To set the stack size use the `jvm.memory.stackSize` field in the `Coherence` CRD.
Setting this value sets the `-Xss` JVM option.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    memory:
      stackSize: 500k  # <1>
----
<1> The stack size will be set to `500k`, passing `-Xss500k` to the JVM.


=== Out Of Memory Behaviour

The `Coherence` CRD allows two optional behaviours to be specified if the JVM throws an out of memory error.

The `jvm.memory.onOutOfMemory.heapDump` is a bool field that when set to true will pass the
`-XX:+HeapDumpOnOutOfMemoryError` option to the JVM. The default value of the field when not specified is `true`,
hence to turn off heap dumps on OOM set the specifically field to be `false`.

The `jvm.memory.onOutOfMemory.exit` is a bool field that when set to true will pass the
`-XX:+ExitOnOutOfMemoryError` option to the JVM. The default value of the field when not specified is `true`,
hence to turn off killing the JVM on OOM set the specifically field to be `false`.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    memory:
      onOutOfMemory:
        heapDump: true   # <1>
        exit: true       # <2>
----
<1> The JVM will create a heap dump on OOM
<2> The JVM will exit on OOM


=== Native Memory Tracking

The Native Memory Tracking (NMT) is a Java VM feature that tracks internal memory usage for a JVM.
The `Coherence` CRD allows native memory tracking to be configured using the `jvm.memory.nativeMemoryTracking` field.
Setting this field sets the `-XX:NativeMemoryTracking` JVM option. There are three valid values, `off`, `summary` or `detail`.
If not specified the default value used by the operator is `summary`

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    memory:
      nativeMemoryTracking: detail # <1>
----
<1> Native memory tracking is set to `detail` which will pass the `-XX:NativeMemoryTracking=detail` option to the JVM.
