///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Container Resource Limits

== Respect Container Resource Limits

The JVM can be configured to respect container limits set, for example cpu and memory limits.
This can be important if container limits have been set for the container in the `resources` section as a JVM that
does not respect these limits can cause the `Pod` to be killed.
This is done by adding the `-XX:+UseContainerSupport` JVM option.
It is possible to control this using the `jvm.useContainerLimits` field in the `Coherence` CRD spec.
If the field is not set, the operator adds the `-XX:+UseContainerSupport` option by default.

For example:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  jvm:
    useContainerLimits: false   # <1>
----
<1> The `useContainerLimits` field is set to false, so the `-XX:+UseContainerSupport` will not be passed to the JVM.

See the <<other/100_resources.adoc,Resource Limits>> documentation on how to specify resource limits
for the Coherence container.
