#
# Copyright (c) 2020, 2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
# Example 2
# Adds a separate proxy role
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: example-cluster-storage
spec:
  cluster: example-cluster
  image: deployment-example:1.0.0
  imagePullPolicy: Always
  replicas: 3
  coherence:
    cacheConfig: storage-cache-config.xml
    metrics:
      enabled: true
  jvm:
    memory:
      heapSize: 512m
  ports:
    - name: metrics
      serviceMonitor:
        enabled: true
---
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: example-cluster-proxy
spec:
  cluster: example-cluster
  replicas: 1
  image: deployment-example:1.0.0
  imagePullPolicy: Always
  coherence:
    cacheConfig: proxy-cache-config.xml
    storageEnabled: false
    metrics:
      enabled: true
  jvm:
    memory:
      heapSize: 512m
  ports:
    - name: metrics
      serviceMonitor:
        enabled: true
    - name: proxy
      port: 20000
