#
# Copyright (c) 2020, 2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
# Example 1
# Initial cluster with one role of 'storage`
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: example-cluster-storage
spec:
  cluster: example-cluster
  replicas: 3
  image: deployment-example:1.0.0
  imagePullPolicy: Always
  jvm:
    memory:
      heapSize: 512m
  coherence:
    cacheConfig: storage-cache-config.xml
    metrics:
      enabled: true
  ports:
    - name: metrics
      serviceMonitor:
        enabled: true
