///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2025 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Operator K8s Webhooks
:description: Coherence Operator Documentation - Operator K8s Webhooks
:keywords: oracle coherence, kubernetes, operator, K8s Webhooks, webhooks

== Coherence Operator Kubernetes Web-Hooks

The Coherence Operator uses Kubernetes admission control webhooks to validate and provide default values for
Coherence resources
(see the https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/[Kubernetes documentation]
for more details on web-hooks).

The Coherence Operator webhooks will validate a `Coherence` resources when it is created or updated contain.
For example, the `replicas` count is not negative. If a `Coherence` resource is invalid it will be rejected before it
gets stored into Kubernetes.

=== Webhook Scope
Webhooks in Kubernetes are a cluster resource, not a namespaced scoped resource, so consequently there is typically only
a single webhook installed for a given resource type. If the Coherence Operator is installed as a cluster scoped operator
then this is not a problem but if multiple Coherence Operators are deployed then they could all attempt to install the
webhooks and update or overwrite a previous configuration. This might not be an issue if all of the operators deployed
in a Kubernetes cluster are the same version but different versions could cause issues.

== Webhook Certificates

Kubernetes requires webhooks to expose an API over https and consequently this requires certificates to be created.
By default, the Coherence Operator will create a self-signed CA certificate and key for use with its webhooks.
Alternatively it is possible to use an external certificate manager such as the commonly used
https://github.com/jetstack/cert-manager[Cert Manager].
Configuring and using Cert Manager is beyond the scope of this documentation.
