///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Coherence Operator guides
:keywords: oracle coherence, kubernetes, operator, guides

== Getting Started

[PILLARS]
====
[CARD]
.Quickstart
[link=install/01_introduction.adoc]
--
Installing and running the Coherence Operator.
--

[CARD]
.Install
[link=guides/01_overview.adoc]
--
Follow step-by-step guides to using the Coherence Operator to manage Coherence clusters.
--
====

== More Guides

[PILLARS]
====

[CARD]
.ReST Management API
[link=guides/03_management.adoc]
--
Managing Coherence clusters with management over ReST.
--

[CARD]
.Coherence Metrics
[link=guides/04_metrics.adoc]
--
Publishing metrics from Coherence clusters.
--

[CARD]
.Clusters
[link=clusters/01_introduction.adoc]
--
Managing Coherence clusters.
--

[CARD]
.Developer
[link=developer/01_introduction.adoc]
--
Developer guide for building the Coherence Operator.
--
====
