///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Create Coherence Clusters

Creating a Coherence cluster using the Coherence Operator is as simple as creating any other Kubernetes resource.

== Create CoherenceCluster Resources

The Coherence Operator uses the Kubernetes customer resource (CRD) named `CoherenceCluster` to define the `spec` for a
Coherence Cluster.
All the fields in the `CoherenceCluster` CRD are optional and a simple Coherence cluster can be created using `yaml` as
follows:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster  
----

The `metadata.name` field defines the cluster name.

Using this `yaml` configuration, you can create a Coherence Cluster with three storage enabled members. The cluster created is inaccessible as there are no ports exposed outside of Kubernetes. The cluster is accessible by other `Pods` in the same namespace.

== Coherence Roles

You can configure the role of a cluster in the `CoherenceCluster` spec. A cluster can have zero to many roles defined in the spec. 

For example, a Coherence application that has a number of storage enabled members and storage disabled Coherence*Extend proxy members, the cluster must have two roles, `storage` and `proxy`.

Some clusters can just have a storage role with some complex Coherence applications while some cluster can have many roles and even different roles of storage enabled for different caches or services within the same cluster.





