///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2020 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= CoherenceCluster CRD Overview

Creating a Coherence cluster using the Coherence Operator is as simple as creating any other Kubernetes resource.

== CoherenceCluster CRD Overview

The Coherence Operator uses a Kubernetes custom resource definition, (CRD) named `CoherenceCluster` to define the
configuration for a Coherence cluster.
All of the fields in the `CoherenceCluster` CRD are optional and a Coherence cluster can be created with a simple yaml
file:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster  # <1>
----

<1> The `metadata.name` field will be used as the Coherence cluster name.

The yaml above will create a Coherence cluster with three storage enabled members. 
There is not much that can actually be achived with this cluster because no ports are exposed outside of Kubernetes
so the cluster is inaccessible. It could be possibly be accessed by other `Pods` in the same Kubernetes cluster but
in most use cases additional configuration would be required.

== Coherence Roles

A role is what is actually configured in the `CoherenceCluster` spec. In a traditional Coherence application that may have
had a number of storage enabled members and a number of storage disable Coherence*Extend proxy members this cluster would
have effectively had two roles, "storage" and "proxy".
Some clusters may simply have just a storage role and some complex Coherence applications and clusters may have many roles
and even different roles storage enabled for different caches/services within the same cluster.

A role in a `CoherenceCluster` is either configured as a single implicit `role` or one or more explicit `roles`.

[source,yaml]
.Single Implicit Role
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster
spec:               # <1>
  replicas: 6
----

<1> The configuration for the `role` (in this case just the `replicas` field) is added directly to the `spec` section
of the `CoherenceCluster`.

[source,yaml]
.Single Explicit Role
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster
spec:
  roles:
  - role: data # <1>
    replicas: 6
----

<1> The configuration for a single explicit `role` named `data` is added to the `roles` list.
of the `CoherenceCluster`.

[source,yaml]
.Multiple Explicit Roles
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster
spec:
  roles:
  - role: data   # <1>
    replicas: 6
  - role: proxy   # <2>
    replicas: 3
----

<1> The first role in the `roles` list is named `data` with a `replicas` value of `6`
<2> The second role in the `roles` list is named `proxy` with a `replicas` value of `3`


== The Coherence Role Specification

The specification for a `role` in the `CoherenceCluster` CRD (both implicit or expilict) has the following top level
fields that may be configured:

[source,yaml]
----
  role:                      # <1>
  replicas:                  # <2>
  application: {}            # <3>
  coherence: {}              # <4>
  jvm: {}                    # <5>
  scaling: {}                # <6>
  ports: []                  # <7>
  logging: {}                # <8>
  volumes: []                # <9>
  volumeClaimTemplates: []   # <10>
  volumeMounts: []           # <11>
  env: []                    # <12>
  annotations: {}            # <13>
  labels: []                 # <14>
  nodeSelector: {}           # <15>
  tolerations: []            # <16>
  affinity: {}               # <17>
  resources: {}              # <18>
  readinessProbe: {}         # <19>
  livenessProbe: {}          # <20>
  startQuorum: []            # <21>
----

<1> The <<clusters/030_roles.adoc,`role`>> field sets the name of the role, if omitted the default name of `storage`
will be used. If configuring multiple roles in a `CoherenceCluster` each role must have a unique name.

<2> The <<clusters/040_replicas.adoc,`replicas`>> field sets the number of replicas (`Pods`) that will be created for
the role. If not specified the default value is `3`.

<3> The <<clusters/070_applications.adoc,`application`>> section contains fields for configuring custom application code.

<4> The <<clusters/050_coherence.adoc,`coherence`>> section contains fields for configuring Coherence specific settings.

<5> The <<clusters/080_jvm.adoc,`jvm`>> section contains fields for configuring how the JVM behaves.

<6> The <<clusters/085_safe_scaling.adoc,`scaling`>> section contains fields for configuring how the number of replicas
in a role is safely scaled up and down.

<7> The <<clusters/090_ports_and_services.adoc,`ports`>> section contains fields for configuring how ports are exposed
via services.

<8> The <<clusters/100_logging.adoc,`logging`>> section contains fields for configuring logging.

<9> The <<clusters/110_volumes.adoc,`volumes`>> section contains fields for configuring additional volumes to add to
the `Pods` for a role.

<10> The <<clusters/110_volumes.adoc,`volumeClaimTemplates`>> section contains fields for configuring additional PVCs
to add to the `Pods` for a role.

<11> The <<clusters/110_volumes.adoc,`volumeMounts`>> section contains fields for configuring additional volume mounts
to add to the `Pods` for a role.

<12> The <<clusters/115_environment_variables.adoc,`env`>> section contains extra environment variables to add to the
Coherence container.

<13> The <<clusters/120_annotations.adoc,`annotations`>> map contains extra annotations to add to the `Pods` for the
role.

<14> The <<clusters/125_labels.adoc,`labels`>> map contains extra labels to add to the `Pods` for the role.

<15> The <<clusters/130_pod_scheduling.adoc,`nodeSelector`>> map contains node selectors to determine how Kubernetes
schedules the `Pods` in the role.

<16> The <<clusters/130_pod_scheduling.adoc,`tolerations`>> array contains taints and tolerations to determine how
Kubernetes schedules the `Pods` in the role.

<17> The <<clusters/130_pod_scheduling.adoc,`affinity`>> contains `Pod` affinity fields to determine how Kubernetes
schedules the `Pods` in the role.

<18> The <<clusters/140_resource_constraints.adoc,`resources`>> contains configures resource limits for the Coherence
containers.

<19> The <<clusters/150_readiness_liveness.adoc,`readinessProbe>>` section configures the readiness probe for the
Coherence containers.

<20> The <<clusters/150_readiness_liveness.adoc,`livenessProbe`>> section configures the liveness probe for the
Coherence containers.

<21> The <<clusters/035_role_startup_ordering.adoc, `startQuorum`>> section configures the start-up dependencies for a role,
that is the roles that must be started before this role can start.
