///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Create Coherence Clusters

Creating a Coherence cluster using the Coherence Operator is as simple as creating any other Kubernetes resource.

== Create CoherenceCluster Resources

The Coherence Operator uses a Kubernetes `CustomResourceDefinition` named `CoherenceCluster` to define the `spec` for a
Coherence cluster.
All of the fields of the `CoherenceCluster` crd are optional so a Coherence cluster can be created with yaml as
simple as the following:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster  <1>
----

<1> The `metadata.name` field will be used as the Coherence cluster name.

The yaml above will create a Coherence cluster with three storage enabled members. 
There is not much that can actually be achived with this cluster because no ports are exposed outside of Kubernetes
so the cluster is inaccessible. It could be accessed by other `Pods` in the same

== Coherence Roles

A role is what is actually configured in the `CoherenceCluster` spec. In a traditional Coherence application that may have
had a number of storage enabled members and a number of storage disable Coherence*Extend proxy members this cluster would
have effectively had two roles, "storage" and "proxy".
Some clusters may simply have just a storage role and some complex Coherence applications and clusters may have many roles
and even different roles storage enabled for different caches/services within the same cluster.


== Kubernetes Resource Relationships When Creating Coherence Clusters

When a `CoherenceCluster` is deployed into Kubernetes the Coherence Operator will create a number of other resources in Kubernetes.

A `CoherenceCluster` is made up of one or more roles.
In theory a `CoherenceCluster` could have zero roles but this would not by typical.
A role maps to zero or more `Pods` that will all share the same specification and hence typically take on the same
business role within an application.

In Kubernetes a Coherence role is represented by a `CoherenceRole` and a `CoherenceInternal` crd although it is not expected that
these crds are modified directly, they are purely used to allow roles in the same cluster to be managed as independent
entities by the Coherence Operator.

When a resource of type `CoherenceCluster` is created in Kubernetes the Coherence Operator will create the other resources.

A `Service` will be created for every `CoherenceCluster` to be used for Coherence WKA (cluster membership discovery).
Every `Pod` that is created as part of this cluster will have a label `coherenceCluster=<cluster-name>` and the WKA `Service`
uses this label to identify all of the `Pods` in the same Coherence cluster. The `Pods` then use the `Service` as their WKA address.

A `CoherenceRole` resource will be created for each role in the `CoherenceCluster` spec that has a replica count greater than zero.
The name of the `CoherenceRole` will be in the form `<cluster-name>-<role-name>`

Each `CoherenceRole` will have a related `CoherenceInternal` resource. The name of the `CoherenceInternal` will be the same
as the `CoherenceRole` resource.

Each `CoherenceRole` will have a related `StatefulSet` with corresponding `Pods` and headless `Service` required by
the `StatefulSet`. The name of the `StatefulSet` will be the same as the `CoherenceRole`

For each port that a role in a `CoherenceCluster` is configured to expose a corresponding `Service` will be created for that port.
The name of the `Service` will be `<cluster-name>-<role-name>-<port-name>` (although this can be overridden when specifying the port
in the `CoherenceCLuster` spec for that role and port).





