///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Create Coherence Clusters

Creating a Coherence cluster using the Coherence Operator is as simple as creating any other Kubernetes resource.

== Create Coherence Clusters

The Coherence Operator uses a Kubernetes `CustomResourceDefinition` to define the spec for a Coherence cluster.

All of the fields of the `CoherenceCluster` crd are optional so a Coherence cluster can be created with yaml as
simple as the following:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster  <1>
----

<1> The `metadata.name` field will be used as the Coherence cluster name.

The yaml above will create a Coherence cluster with three storage enabled members. 
There is not much that can actually be achived with this cluster because no ports are exposed outside of Kubernetes
so the cluster is inaccessible. 

== Coherence Roles
