///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2020 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Configure Coherence

== Configure Coherence

The `coherence` section of the `role` spec in a `CoherenceCluster` contains the following fields and sections that may
be configured:

[source,yaml]
----
coherence:
  cacheConfig: coherence-cache-config.xml          # <1>
  overrideConfig: tangosol-coherence-override.xml  # <2>
  logLevel: 5                                      # <3>
  storageEnabled: true                             # <4>
  imageSpec: {}                                    # <5>
  management: {}                                   # <6>
  metrics: {}                                      # <7>
  persistence: {}                                  # <8>
  snapshot: {}                                     # <9>
  excludeFromWKA: false                            # <10>
----

<1> The `cacheConfig` field sets the name of the Coherence cache configuration file to use.
See <<clusters/052_coherence_config_files.adoc,Coherence Config Files>> for more details.
<2> The `overrideConfig` field sets the name of the Coherence operational override configuration file to use.
See <<clusters/052_coherence_config_files.adoc,Coherence Config Files>> for more details.
<3> The `logLevel` field sets the log level that Coherence should use.
See <<clusters/100_logging.adoc,Logging Configuration>> for more details.
<4> The `storageEnabled` field sets whether the role is storage enabled or not.
See <<clusters/054_coherence_storage_enabled.adoc,Storage Enabled or Disabled Roles>> for more details.
<5> The `imageSpec` section configures the Coherence image details such as image name, pull policy etc.
See <<clusters/056_coherence_image.adoc,Setting the Coherence Image>> for more details.
<6> The `management` configures how Coherence management over REST behaves, whether it is enabled, etc.
See <<clusters/058_coherence_management.adoc,Coherence Management Over REST>> for more details.
<7> The `metrics` configures how Coherence metrics behaves, whether it is enabled, etc.
See <<clusters/060_coherence_metrics.adoc,Coherence Metrics>> for more details.
<8> The `persistence` configures how Coherence management over REST behaves, whether it is enabled, etc.
See <<clusters/062_coherence_persistence.adoc,Coherence Persistence>> for more details.
<9> The `snapshot` configures how Coherence management over REST behaves, whether it is enabled, etc.
See <<clusters/064_coherence_snapshots.adoc,Coherence Snapshots>> for more details.
<10> The `excludeFromWKA` field configures whether the `Pods` for this role form part of the Coherence WKA list for the cluster,
see the <<about/05_cluster_discovery.adoc, Cluster Discovery>> documentation page for more details.