///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Coherence Config Files

The different configuration files commonly used by Coherence can be specified for a role in the role's spec.

== Coherence Config Files

There are three Coherence configuration files that can be set in a role's specification:

* The <<cache-config,Coherence Cache Configuration>> file
* The <<override-file,Coherence Operational Override>> file
* The <<pof-config,POF Configuration>> file


[#cache-config]
== Setting the Coherence Cache Configuration File

The Coherence cache configuration file for a role in a `CoherenceCluster` is set using the `cacheConfig` field of a role spec.
The value of this field will end up being passed to the Coherence JVM as the `coherence.cache.config` System property and
will hence set the value of the cache configuration file used as described in the Coherence documentation.

=== Set the Cache Configuration for an Implicit Role

When using the implicit role configuration the `cacheConfig` value is set directly in the `CoherenceCluster` `spec` section.
For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  cacheConfig: application-cache-config.xml  <1>
----

<1> In this case a cluster will be created with a single implicit role named `storage` where the `coherence.cache.config`
System property and hence the cache configuration file used will be `application-cache-config.xml`


=== Set the Cache Configuration for Explicit Role

When using the explicit role configuration the `cacheConfig` value is set for each role in the `CoherenceCluster` `spec`
`roles` list.

For example to create cluster with two explicit roles, `data` and `proxy`:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      cacheConfig: data-cache-config.xml  <1>
    - role: proxy
      cacheConfig: proxy-cache-config.xml  <2>
----

<1> The `data` role will use the `data-cache-config.xml` cache configuration file
<2> The `proxy` role will use the `proxy-cache-config.xml` cache configuration file


=== Set the Cache Configuration for Explicit Roles with a Default

When using the explicit role configuration a value for `cacheConfig` value can be set in the `CoherenceCluster` `spec`
section that will be used as the default `cacheConfig` value for any `role` in the `roles` list that does not explicitly
specify a value.

For example to create cluster with three explicit roles, `data` and `proxy` and `web`:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  cacheConfig: application-cache-config.xml  <1>
  roles:
    - role: data
    - role: proxy
    - role: web
      cacheConfig: web-cache-config.xml  <2>
----

<1> The default `cacheConfig` value is set to `application-cache-config.xml`. The `data` and `proxy` roles do not have
a `cacheConfig` value so will use this default value and will each have use the `application-cache-config.xml` file
<2> The `web` role has an explicit `cacheConfig` value of `web-cache-config.xml` so will use the `web-cache-config.xml`
cache configuration file


[#override-file]
== Setting the Coherence Operational Override File



[#pof-config]
== Setting the POF Configuration File
