///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Coherence Metrics


== Coherence Metrics

Since version 12.2.1.4 Coherence has had functionality to expose metrics via a http endpoint.
This endpoint is disabled by default in Coherence clusters but can be enabled and configured by setting the relevant 
fields in the `CoherenceCluster` resource.


== Enabling Coherence Metrics

Coherence metrics can be enabled or disabled by setting the `coherence.metrics.enabled` field.

[NOTE]
====
Enabling metrics will add a number of `.jar` files to the classpath of the Coherence JVM.
In Coherence 12.2.1.4 those `.jar` file are:

[source]
----
org.glassfish.hk2.external:aopalliance-repackaged:jar:2.4.0-b34
org.glassfish.hk2:hk2-api:jar:2.4.0-b34
org.glassfish.hk2:hk2-locator:jar:2.4.0-b34
org.glassfish.hk2:hk2-utils:jar:2.4.0-b34
org.glassfish.hk2.external:javax.inject:jar:2.4.0-b34
com.fasterxml.jackson.core:jackson-annotations:jar:2.9.10
com.fasterxml.jackson.core:jackson-core:jar:2.9.10
com.fasterxml.jackson.core:jackson-databind:jar:2.9.10.1
com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.9.10
com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.9.10
com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.10
javax.annotation:javax.annotation-api:jar:1.2
javax.validation:validation-api:jar:1.1.0.Final
javax.ws.rs:javax.ws.rs-api:jar:2.0.1
org.glassfish.jersey.core:jersey-client:jar:2.22.4
org.glassfish.jersey.core:jersey-common:jar:2.22.4
org.glassfish.jersey.ext:jersey-entity-filtering:jar:2.22.4
org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.22.4
org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.22.4
org.glassfish.jersey.core:jersey-server:jar:2.22.4
org.glassfish.hk2:osgi-resource-locator:jar:1.0.1
----

If adding additional application `.jar` files care should be taken that there are no version conflicts.

If conflicts are an issue there are alternative approaches available to exposing the metrics.

The list above is subject to change in later Coherence patches and version.
====


=== Enabling Metrics for the Implicit Role

When configuring a single implicit role in a `CoherenceCluster` metrics can be enabled by setting
the `coherence.metrics.enabled` to `true` in the `CoherenceCluster` `spec` section.
For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    metrics:
      enabled: true  # <1>
----

<1> Metrics will be enabled and the http endpoint will bind to port `9612` in the container.
The port is not exposed in a `Service`.


=== Enabling Metrics for Explicit Roles

When configuring a explicit roles in the `roles` list of a `CoherenceCluster` metrics can be
enabled or disabled by setting the `coherence.metrics.enabled` for each role.
For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      coherence:
        metrics:
          enabled: true   # <1>
    - role: proxy
      coherence:
        metrics:
          enabled: false  # <2>
----

<1> The `data` role has the metrics enabled.
<2> The `proxy` role has the metrics disabled.


=== Enabling Metrics for Explicit Roles with a Default

When configuring a explicit roles in the `roles` list of a `CoherenceCluster` a default value for the
`coherence.metrics.enabled` field can be set in the `CoherenceCluster` `spec` section that will apply to
all roles in the `roles` list unless overridden for a specific role.
For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    metrics:
      enabled: true       # <1>
  roles:
    - role: data          # <2>
    - role: proxy
      coherence:
        metrics:
          enabled: false  # <3>
----

<1> The default value for enabling metrics is `true` which will apply to all roles in the `roles` list
unless the field is specifically overridden.

<2> The `data` role does not specify a value for the `coherence.metrics.enabled` field so it will use the default
value of `true` so metrics will be enabled.

<3> The `proxy` role overrides the default value for the `coherence.metrics.enabled` field and sets it to `false`
so metrics will be disabled.



=== Exposing Metrics via a Service

Enabling metrics only enables the http server so that the endpoint is available in the container.
If external access to the API is required via a service then the port needs to be exposed just like any other
additional ports as described in <<clusters/090_ports_and_services.adoc,Expose Ports and Services>>.

For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    metrics:
      enabled: true   # <1>
  ports:
    - name: metrics   # <2>
      port: 9612
----

<1> metrics will be enabled and the default port value will be used so that the http endpoint will bind
to port `9612` in the container.

<2> An additional port named `metrics` is added to the `ports` array which will cause the metrics port to be
exposed on a service. The port specified is `9612` as that is the default port that metrics will bind to.


=== Expose metrics on a Different Port

The default port in the container that metrics uses is 9612. It is possible to change ths port using the
`coherence.metrics.port` field.

For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    metrics:
      enabled: true
      port: 9000        # <1>
  ports:
    - name: metrics
      port: 9000        # <2>
----

<1> metrics is enabled and configured to bind to port `9000` in the container.

<2> The corresponding `port` value of `9000` must be used when exposing the port on a `Service`.

[#ssl]
=== Configuring metrics With SSL

It is possible to configure metrics endpoint to use SSL to secure the communication between server and
client. The SSL configuration is in the `coherence.metrics.ssl` section of the spec.
See <<metrics/020_manegement_over_rest.adoc,metrics>> for a more in depth guide to configuring SSL.

For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    metrics:
      enabled: true
      ssl:
        enabled: true                            # <1>
        keyStore: metrics-keys.jks            # <2>
        keyStoreType: JKS                        # <3>
        keyStorePasswordFile: store-pass.txt     # <4>
        keyPasswordFile: key-pass.txt            # <5>
        keyStoreProvider:                        # <6>
        keyStoreAlgorithm: SunX509               # <7>
        trustStore: metrics-trust.jks         # <8>
        trustStoreType: JKS                      # <9>
        trustStorePasswordFile: trust-pass.txt   # <10>
        trustStoreProvider:                      # <11>
        trustStoreAlgorithm: SunX509             # <12>
        requireClientCert: true                  # <13>
        secrets: metrics-secret               # <14>
----

<1> The `enabled` field when set to `true` enables SSL for metrics or when set to `false` disables SSL
<2> The `keyStore` field sets the name of the Java key store file that should be used to obtain the server's key
<3> The optional `keyStoreType` field sets the type of the key store file, the default value is `JKS`
<4> The optional `keyStorePasswordFile` sets the name of the text file containing the key store password
<5> The optional `keyPasswordFile` sets the name of the text file containing the password of the key in the key store
<6> The optional `keyStoreProvider` sets the provider name for the key store 
<7> The optional `keyStoreAlgorithm` sets the algorithm name for the key store, the default value is `SunX509` 
<8> The `trustStore` field sets the name of the Java trust store file that should be used to obtain the server's key
<9> The optional `trustStoreType` field sets the type of the trust store file, the default value is `JKS`
<10> The optional `trustStorePasswordFile` sets the name of the text file containing the trust store password
<11> The optional `trustStoreProvider` sets the provider name for the trust store
<12> The optional `trustStoreAlgorithm` sets the algorithm name for the trust store, the default value is `SunX509`
<13> The optional `requireClientCert` field if set to `true` enables two-way SSL where the client must also provide
a valid certificate
<14> The optional `secrets` field sets the name of the Kubernetes `Secret` to use to obtain the key store, truct store
and password files from.

