///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Coherence Persistence


== Coherence Persistence

Coherence persistence is a set of tools and technologies that manage the persistence and recovery of Coherence
distributed caches. Cached data is persisted so that it can be quickly recovered after a catastrophic failure or
after a cluster restart due to planned maintenance. See the main
https://docs.oracle.com/en/middleware/fusion-middleware/coherence/12.2.1.4/administer/persisting-caches.html#GUID-3DC46E44-21E4-4DC4-9D12-231DE57FE7A1[Coherence documentation]

The Coherence Operator supports configuring Coherence Persistence in two parts, snapshots and continuous persistence.
Snapshots is the process of saving the state of caches to a named snapshot as a set of files on disc.
This cache state can later be restored by reloading a named snapshot from disc - like a backup/restore operation.
Continuous persistence is where  Coherence continually writes the sate of caches to disc. When a Coherence cluster is
stopped and restarted, either on purpose or due to a failue, the data on disc is automatically reloaded and the cache
state is restored.

Ideally, the storage used for persistence and snapshots is fast local storage such as SSD. When using stand-alone
Coherence it is a simple process to manage local storage but when using Coherence in containers, and especially inside
Kubernetes, managing storage is a more complex task when that storage needs to be persisted longer than the lifetime of
the containers and re-attached to the containers if they are restarted.
The Coherence Operator aims to make using Coherence persistence in Kubernetes simpler by allowing the more common
use-cases to be easily configured.

Each role in a `CoherenceCluster` resource maps to a Kubernetes `StatefulSet`. One of the advantages of `StatefulSets`
is that they allow easy management of `PersistentVolumeClaims` which are ideal for use as storage for Coherence
persistence as they have a lifetime outside of the `Pods` are are reattached to the `StatefulSet` `Pods` when they are
restarted.


== Managing Coherence Snapshots using Persistent Volumes

When managing Coherence clusters using the Coherence Operator the simples configuration is to write snapshots to a
volume mapped to a `PersistentVolumeClaim` and to let the `StatefulSet` manage the `PVCs`.

Snapshots are configured in the `coherence.snapshots` section of the role specification in the `CoherenceCluster` CRD.

[source,yaml]
----
coherence:
  snapshots:
    enabled: true            # <1>
      persistentVolumeClaim: # <2>
        # PVC spec...
----

<1> Snapshots should be enabled by setting the `coherence.snapshots.enabled` field to true.
<2> The `persistentVolumeClaim` section allows the `PVC` used for snapshot files to be configured.

The default value for `coherence.snapshots.enabled` is `false` so no snapshot location will be configured for Coherence
caches to use.

If `snapshots.enabled` is either undefined or false it is still possible to use Coherence snapshot functionality but in
this case snapshot files will be written to storage inside the Coherence container and will be lost if the container is
shutdown.

For example, if a Kubernetes cluster has a custom `StorageClass` named `fast` defined below:

[source,yaml]
----
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd
----

Then a `CoherenceCluster` can be created with snapshots enabled and configured to use the `fast` storage class:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    snapshots:
      enabled: true
        persistentVolumeClaim:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: fast
          resources:
            requests:
              storage: 1Gi
----

The content of the `persistentVolumeClaim` is any valid yaml for defining a `PersistentVolumeClaimSpec` that would be
allowed when configuring the `spec` section of a PVC in the `volumeClaimTemplates` section of a `StatefulSet` as
described in the https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#persistentvolumeclaimspec-v1-core[Kubernetes API documentation].


=== Snapshots using Persistent Volumes for a Single Implicit Role

When configuring a `CoherenceCluster` with a single implicit role the `coherence.snapshots` configuration is added
directly to the `spec` section of the `CoherenceCluster`.
For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    snapshots:                              # <1>
      enabled: true
        persistentVolumeClaim:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: fast
          resources:
            requests:
              storage: 1Gi
----

<1> The implicit `storage` role has `snapshots` enabled and configured to use a PVC with custom `StorageClass`.

=== Snapshots using Persistent Volumes for Explicit Roles

When configuring a `CoherenceCluster` with one or more explicit roles the `coherence.snapshots` configuration is added
directly to the configuration of each role in the `roles` list of the `CoherenceCluster`.
For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data                               # <1>
      coherence:
        snapshots:
          enabled: true
            persistentVolumeClaim:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: fast
              resources:
                requests:
                  storage: 1Gi
    - role: proxy                              # <2>
      coherence:
        snapshots:
          enabled: false
----

<1> The `data` role has `snapshots` enabled and configured to use a PVC with custom `StorageClass`.
<2> The `proxy` role has `snapshots` explicitly disabled.


=== Snapshots using Persistent Volumes for Explicit Roles with Defaults

When configuring a explicit roles in the `roles` list of a `CoherenceCluster` default values for the
`coherence.snapshots` configuration can be set in the `CoherenceCluster` `spec` section that will apply to
all roles in the `roles` list unless overridden for a specific role.
For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    snapshots:                                 # <1>
      enabled: true
        persistentVolumeClaim:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: fast
          resources:
            requests:
              storage: 1Gi
  roles:
    - role: data                               # <2>
    - role: proxy                              # <3>
      coherence:
        snapshots:
          enabled: false
----

<1> The default `snapshots` configuration is to enable snapshots using a PVC with custom `StorageClass`.
<2> The `data` role does not specify an explict `snapshots` configuration so it will use the defaults.
<3> The `proxy` role has `snapshots` explicitly disabled.


== Managing Coherence Snapshots using Standard Volumes

Although `PersistentVolumeClaims` are the recommended way to manage storage for Coherence snapshots the Coherence
Operator also supports using standard Kubernetes `Volumes` as a storage mechanism.

WARNING: When using standard Kubernetes `Volumes` for snapshot storage it is important to ensure that
`CoherenceClusters` are configured and managed in such a way that the same `Volumes` are reattached to `Pods` if
clusters are restarted or if individual `Pods` are restarted or rescheduled by Kubernetes. If this is not done
then snapshot data can be lost. There are many ways to accomplish this using particular `Volume` types or controlling
`Pod` scheduling but this configuration is beyond the scope of this document and the relevant Kubernetes or storage
provider documentation should be consulted.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    snapshots:
      enabled: true
        volume:          # <1>
          hostPath:
            path: /data
----

<1> Snapshots storage is configured to use a `hostPath` volume mapped to the `/data` directory on the host

As with configuring snapshots to use `PersistentVolumeClaims` configuring them to use `Volumes` can be done at
different levels in the `CoherenceCluster` spec depending on whether there is a single implicit role, multiple
explicit roles and default values to apply to explicit roles.



== Managing Coherence Persistence using Persistent Volumes

When managing Coherence clusters using the Coherence Operator the simples configuration is to write persistence files
to a volume mapped to a `PersistentVolumeClaim` and to let the `StatefulSet` manage the `PVCs`.

Persistence is configured in the `coherence.persistence` section of the role specification in the `CoherenceCluster` CRD.

[source,yaml]
----
coherence:
  persistence:
    enabled: true            # <1>
      persistentVolumeClaim: # <2>
        # PVC spec...
----

<1> Persistence should be enabled by setting the `coherence.persistence.enabled` field to true.
<2> The `persistentVolumeClaim` section allows the `PVC` used for snapshot files to be configured.

The default value for `coherence.persistence.enabled` is `false` so no snapshot location will be configured for Coherence
caches to use.

For example, if a Kubernetes cluster has a custom `StorageClass` named `fast` defined below:

[source,yaml]
----
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd
----

Then a `CoherenceCluster` can be created with persistence enabled and configured to use the `fast` storage class:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    persistence:
      enabled: true
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: fast
        resources:
          requests:
            storage: 1Gi
----

The content of the `persistentVolumeClaim` is any valid yaml for defining a `PersistentVolumeClaimSpec` that would be
allowed when configuring the `spec` section of a PVC in the `volumeClaimTemplates` section of a `StatefulSet` as
described in the https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#persistentvolumeclaimspec-v1-core[Kubernetes API documentation].


=== Persistence using Persistent Volumes for a Single Implicit Role

When configuring a `CoherenceCluster` with a single implicit role the `coherence.persistence` configuration is added
directly to the `spec` section of the `CoherenceCluster`.
For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    persistence:                              # <1>
      enabled: true
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: fast
        resources:
          requests:
            storage: 1Gi
----

<1> The implicit `storage` role has `persistence` enabled and configured to use a PVC with custom `StorageClass`.


=== Persistence using Persistent Volumes for Explicit Roles

When configuring a `CoherenceCluster` with one or more explicit roles the `coherence.persistence` configuration is added
directly to the configuration of each role in the `roles` list of the `CoherenceCluster`.
For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data                               # <1>
      coherence:
        persistence:
          enabled: true
          persistentVolumeClaim:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: fast
            resources:
              requests:
                storage: 1Gi
    - role: proxy                              # <2>
      coherence:
        persistence:
          enabled: false
----

<1> The `data` role has `persistence` enabled and configured to use a PVC with custom `StorageClass`.
<2> The `proxy` role has `persistence` explicitly disabled.


=== Persistence using Persistent Volumes for Explicit Roles with Defaults

When configuring a explicit roles in the `roles` list of a `CoherenceCluster` default values for the
`coherence.persistence` configuration can be set in the `CoherenceCluster` `spec` section that will apply to
all roles in the `roles` list unless overridden for a specific role.
For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    persistence:                               # <1>
      enabled: true
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: fast
        resources:
          requests:
            storage: 1Gi
  roles:
    - role: data                               # <2>
    - role: proxy                              # <3>
      coherence:
        persistence:
          enabled: false
----

<1> The default `persistence` configuration is to enable persistence using a PVC with custom `StorageClass`.
<2> The `data` role does not specify an explict `persistence` configuration so it will use the defaults.
<3> The `proxy` role has `persistence` explicitly disabled.


== Managing Coherence Persistence using Standard Volumes

Although `PersistentVolumeClaims` are the recommended way to manage storage for Coherence persistence the Coherence
Operator also supports using standard Kubernetes `Volumes` as a storage mechanism.

WARNING: When using standard Kubernetes `Volumes` for snapshot storage it is important to ensure that
`CoherenceClusters` are configured and managed in such a way that the same `Volumes` are reattached to `Pods` if
clusters are restarted or if individual `Pods` are restarted or rescheduled by Kubernetes. If this is not done
then snapshot data can be lost. There are many ways to accomplish this using particular `Volume` types or controlling
`Pod` scheduling but this configuration is beyond the scope of this document and the relevant Kubernetes or storage
provider documentation should be consulted.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    persistence:
      enabled: true
      volume:          # <1>
        hostPath:
          path: /data
----

<1> Snapshots storage is configured to use a `hostPath` volume mapped to the `/data` directory on the host

As with configuring persistence to use `PersistentVolumeClaims` configuring them to use `Volumes` can be done at
different levels in the `CoherenceCluster` spec depending on whether there is a single implicit role, multiple
explicit roles and default values to apply to explicit roles.

