///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Configure Applications

Whilst the Coherence Operator can manage plain Coherence clusters typically custom application code and configuration
files would be added to a Coherence JVM's classpath.

== Configure Applications

Different application code and configuration can be added to different roles in a `CoherenceCluster` by specifying
the application's configuration in the `application` section of a role spec. There are a number of different fields
that can be configured for an application described below. All of the configuration described below is optional.

See the in-depth guide on <<app-deployment/010_overview.adoc,Coherence application deployments>> for more details on
creating and deploying `CoherenceClusters` with custom application code.

[source,yaml]
.Application Spec
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    image: acme/orders-data:1.0.0
    imagePullPolicy: Always
    appDir: "/app"
    libDir: "/lib"
    configDir: "/conf"
    main: io.acme.Server
    args:
      - "foo"
      - "bar"
----

* <<app-image,Setting the Application Image>> - The application's image that is used to provide application
`.jar` files and configuration files to add to the JVM classpath.
* <<pull-policy,Setting the Application Image Pull Policy>> - The pull policy that Kubernetes will use to pull
the application's image
* <<app-dir,Setting the Application Directory>> - The name of the folder in the application's image containing
application artifacts. This will be the working directory for the Coherence container.
* <<app-lib,Setting the Application Lib Directory>> - The name of the folder in the application's image containing
`.jar` files to add to the JVM class path
* <<app-conf,Setting the Application Config Directory>> - The name of the folder in the application's image containing
configuration files that will be add to the JVM classpath
* <<app-main,Setting the Application Main Class>> - The application's custom main main Class to use if running a
class other than Coherence `DefaultCacheServer`
* <<app-args,Setting the Application Main Class Arguments>> - The arguments to pass to the application's main `Class`


////
----- Application Image -------------------------------------------------------------------------------------------
////
'''
[#app-image]
== Setting the Application Image

The application image is the Docker image containing the `.jar` files and configuration files of the Coherence application
that should be deployed in the Coherence cluster. For more information see the
<<app-deployments/010_overview.adoc,Coherence application deployments>> guide.

Whilst the Coherence Operator makes it simple to deploy and manage a Coherence cluster in Kubernetes in the majority of
use cases there will be a requirement for application code to be deployed and run in the Coherence JVMs. This application
code and any application configuration files are supplied as a separate image. This image is loaded as an init-container
by the Coherence `Pods` and the relevant `.jar` files and configuration files from this image are added to the Coherence
JVM's classpath.

As well as setting the image name it is also sometimes useful to set the application image's <<pull-policy,image pull policy>>.

If the image being configured is from a registry requiring authentication see the section
on <<clusters/200_private_repos.adoc,pulling from private registries>>.

=== Setting the Application Image for the Implicit Role

When using the implicit role configuration the application image to use is set directly in the `CoherenceCluster` `spec`
`application.image` field.

For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    image: acme/orders-data:1.0.0  # <1>
----

<1> The `acme/orders-data:1.0.0` will be used to add additional `.jar` files and configuration files to the classpath of
the Coherence container in the implicit `storage` role's `Pods`


=== Setting the Application Image for Explicit Roles

When using the explicit roles in a `CoherenceCluster` `roles` list the application image to use is set for each role.

For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      application:
        image: acme/orders-data:1.0.0   # <1>
    - role: proxy
      application:
        image: acme/orders-proxy/1.0.0  # <2>
----

<1> The `data` role `Pods` will use the application image `acme/orders-data:1.0.0`
<2> The `proxy` role `Pods` will use the application image `acme/orders-proxy/1.0.0`


===  Setting the Application Image for Explicit Roles with a Default

When using the explicit roles in a `CoherenceCluster` `roles` list the application image to use can be set in the
`CoherenceCluster` `spec` section and will apply to all roles unless specifically overridden for a `role` in the
`roles` list.

For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    image: acme/orders-data:1.0.0  # <1>
  roles:
    - role: data
    - role: proxy
----

<1> The `data` and the `proxy` roles will both use the application image `acme/orders-data:1.0.0`


[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    image: acme/orders-data:1.0.0           # <1>
  roles:
    - role: data
    - role: proxy
    - role: web
      application:
        image: acme/orders-front-end/1.0.0  # <2>
----

<1> The `data` and the `proxy` roles will both use the application image `acme/orders-data:1.0.0`
<2> The `web` role will use the application image `acme/orders-web/1.0.0`



////
----- Application image pull policy -------------------------------------------------------------------------------
////
'''
[#pull-policy]
== Setting the Application Image Pull Policy

The image pull policy controls when (and if) Kubernetes will pull the application image onto the node where the Coherence
`Pods` are being schedules.
See https://kubernetes.io/docs/concepts/containers/images/#updating-images[Kubernetes imagePullPolicy] for more information.

NOTE: The Kubernetes default pull policy is `IfNotPresent` unless the image tag is `:latest` in which case the default
policy is `Always`. The `IfNotPresent` policy causes the Kubelet to skip pulling an image if it already exists.
Note that you should avoid using the `:latest` tag, see
https://kubernetes.io/docs/concepts/configuration/overview/#container-images[Kubernetes Best Practices for Configuration]
for more information.

The application image's pull policy is set using the `imagePullPolicy` field in the `spec.application` section.


=== Setting the Image Pull Policy for the Implicit Role

To set the `imagePullPolicy` for the implicit role:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    image: acme/orders-data:1.0.0
    imagePullPolicy: Always # <1>
----

<1> The image pull policy for the implicit role above has been set to `Always`


=== Setting the Image Pull Policy for Explicit Roles

To set the `imagePullPolicy` for the explicit roles in the `roles` list:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      application:
        image: acme/orders-data:1.0.0
        imagePullPolicy: Always        # <1>
    - role: proxy
      application:
        image: acme/orders-proxy/1.0.0
        imagePullPolicy: IfNotPresent  # <2>
----

<1> The image pull policy for the `data` role has been set to `Always`
<2> The image pull policy for the `proxy` role above has been set to `IfNotPresent`


=== Setting the Image Pull Policy for Explicit Roles with Default

To set the `imagePullPolicy` for the explicit roles with a default value:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    imagePullPolicy: Always                 # <1>
  roles:
    - role: data
      application:
        image: acme/orders-data:1.0.0
    - role: proxy
      application:
        image: acme/orders-proxy/1.0.1
    - role: web
      application:
        image: acme/orders-front-end/1.0.1
        imagePullPolicy: IfNotPresent       # <2>
----

<1> The default image pull policy is set to `Always`. The `data` and `proxy` roles will use the default value because
they do not specifically set the value in their specs.
<2> The image pull policy for the `web` role above has been set to `IfNotPresent`


////
----- Application lib directory -----------------------------------------------------------------------------------
////
'''
[#app-lib]
== Setting the Application Lib Directory

A typical Coherence application may also require additional dependencies (usually `.jar` files) that need to be added
to the classpath.
The applications's lib directory is a directory in the application's image that contains these additional `.jar` files.
The Coherence Operator will add the files to the classpath with the wildcard setting (e.g. `-cp /lib/*`) it does not add
each file in the lib directory individually to the classpath. This means that the contents of the lib directory are
added to the classpath using the rules that the JVM uses to process wild card classpath entries.

=== Setting the Application Lib Directory for the Implicit Role

When configuring a `CoherenceCluster` with a single implicit role the application's lib directory is specified in the
`application.libDir` field.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    libDir: app-lib  # <1>
----

<1> The application image contains a directory named `/app-lib` that contains the `.jar` files to add to the JVM
classpath.

=== Setting the Application Lib Directory for Explicit Roles

When creating a `CoherenceCluster` with explicit roles in the `roles` list the `application.libDir` field can be set
specifically for each role:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      application:
        libDir: app-lib    # <1>
    - role: proxy
      application:
        libDir: proxy-lib  # <2>
----

<1> The application image contains a directory named `/app-lib` that contains the `.jar` files to add to the JVM
classpath in all of the `Pods` for the `data` role.
<2> The application image contains a directory named `/proxy-lib` that contains the `.jar` files to add to the JVM
classpath in all of the `Pods` for the `proxy` role.


=== Setting the Application Lib Directory for Explicit Roles with a Default

When creating a `CoherenceCluster` with explicit roles in the `roles` list the `application.libDir` field can be set
at the `spec` level as a default that applies to all of the roles in the `roles` list unless specifically overridden
for an individual role:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    libDir: app-lib        # <1>
  roles:
    - role: data           # <2>
    - role: proxy
      application:
        libDir: proxy-lib  # <3>
----

<1> The default value for the `libDir` field is `app-lib/`.
<2> The `data` role does not specify a value for `libDir` so it will use the default. The application image should
contain a directory named `/app-lib` that contains the `.jar` files to add to the JVM classpath in all of the `Pods`
for the `data` role.
<3> The `proxy` role has an explicit value set for the `libDir` field. The application image should a directory named
`/proxy-lib` that contains the `.jar` files to add to the JVM classpath in all of the `Pods` for the `proxy` role.


////
----- Application config directory --------------------------------------------------------------------------------
////
'''
[#app-conf]
== Setting the Application Config Directory

A Coherence application may require additional files added to the classpath such as configuration files and other
resources. These additional files can be placed into the config directory of the application's image and this directory
added to the classpath of the Coherence JVM. Just the directory is added to the classpath (e.g. `-cp /conf`) the contents
themselves are not added.

=== Setting the Application Config Directory for the Implicit Role

When configuring a `CoherenceCluster` with a single implicit role the application's configuration directory is specified
in the `application.configDir` field.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    configDir: app-conf  # <1>
----

<1> The application image contains a directory named `/app-conf` that contains any configuration files to add to the JVM
classpath.

=== Setting the Application Config Directory for Explicit Roles

When creating a `CoherenceCluster` with explicit roles in the `roles` list the `application.configDir` field can be set
specifically for each role:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      application:
        configDir: app-conf    # <1>
    - role: proxy
      application:
        configDir: proxy-conf  # <2>
----

<1> The application image contains a directory named `/app-conf` that contains the configuration files to add to the JVM
classpath in all of the `Pods` for the `data` role.
<2> The application image contains a directory named `/proxy-conf` that contains the configuration files to add to the
JVM classpath in all of the `Pods` for the `proxy` role.


=== Setting the Application Config Directory for Explicit Roles with a Default

When creating a `CoherenceCluster` with explicit roles in the `roles` list the `application.configDir` field can be set
at the `spec` level as a default that applies to all of the roles in the `roles` list unless specifically overridden
for an individual role:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    configDir: app-conf       # <1>
  roles:
    - role: data              # <2>
    - role: proxy
      application:
        configDir: proxy-conf # <3>
----

<1> The default value for the `configDir` field is `app-conf/`.
<2> The `data` role does not specify a value for `configDir` so it will use the default. The application image should
contain a directory named `/app-conf` that contains the configuration files to add to the JVM classpath in all of the
`Pods` for the `data` role.
<3> The `proxy` role has an explicit value set for the `configDir` field. The application image should a directory named
`/proxy-conf` that contains the configuration files to add to the JVM classpath in all of the `Pods` for the `proxy`
role.


////
----- Application working directory -------------------------------------------------------------------------------
////
'''
[#app-dir]
== Setting the Application Directory

Sometimes an application may have more than just `.jar` files or configuration files in the `conf` folder.
An application may have a number of artifacts that it needs to access from a working directory so for this use case
an application directory can be specified that will effectively become the working directory for the Coherence JVM
in the `Pods`. The application directory may be a parent directory of the lib or configuration directory or they may
be separate directory trees.

=== Setting the Application Directory for the Implicit Role

When configuring a `CoherenceCluster` with a single implicit role the application's working directory is specified
in the `application.appDir` field.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    appDir: app  # <1>
----

<1> The application image contains a directory named `/app` that will effectively become the working directory for
the Coherence JVM in the `Pods` for the role.

=== Setting the Application Directory for Explicit Roles

When creating a `CoherenceCluster` with explicit roles in the `roles` list the `application.appDir` field can be set
specifically for each role:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      application:
        appDir: data-app   # <1>
    - role: proxy
      application:
        appDir: proxy-app  # <2>
----

<1> The application image contains a directory named `/data-app` that will effectively become the working directory for
the Coherence JVM in the `Pods` for the `data` role.
<2> The application image contains a directory named `/proxy-app` that will effectively become the working directory for
the Coherence JVM in the `Pods` for the `proxy` role.


=== Setting the Application Directory for Explicit Roles with a Default

When creating a `CoherenceCluster` with explicit roles in the `roles` list the `application.appDir` field can be set
at the `spec` level as a default that applies to all of the roles in the `roles` list unless specifically overridden
for an individual role:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    appDir: app           # <1>
  roles:
    - role: data          # <2>
    - role: proxy
      application:
        appDir: proxy-app # <3>
----

<1> The default value for the `appDir` field is `/app`.
<2> The `data` role does not specify a value for `appDir` so it will use the default. The application image should
contain a directory named `/app` will effectively become the working directory for the Coherence JVM in the `Pods` for
the `data` role.
<3> The `proxy` role has an explicit value set for the `appDir` field. The application image should a directory named
`/proxy-app` will effectively become the working directory for the Coherence JVM in the `Pods` for the `proxy` role



////
----- Application main --------------------------------------------------------------------------------------------
////
'''
[#app-main]
== Setting the Application Main

By default Coherence containers will run the `main` method in the `com.tangosol.coherence.DefaultCacheServer`
class. Sometimes an application requires a different class as the main class (or even a main that is not a class at all,
for example when running a Node JS application on top of the Graal VM the `main` could be a Javascript file).
The main to be used can be configured for each role in a `CoherenceCluster`.

=== Setting the Application Main Class for the Implicit Role

When configuring a `CoherenceCluster` with a single implicit role the application's working directory is specified
in the `application.main` field.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    libDir: lib          # <1>
    main: com.acme.Main  # <2>
----

<1> The application image should contain a directory named `/lib` that will contain the `.jar` files containing the
application classes and dependencies.
<2> One of those classes will be `com.acme.Main` which will be executed as the main class when starting the JVMs for
the `data` role.


=== Setting the Application Main Class for Explicit Roles

When creating a `CoherenceCluster` with explicit roles in the `roles` list the `application.main` field can be set
specifically for each role:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      application:
        libDir: lib           # <1>
        main: com.acme.Main   # <2>
    - role: proxy
      application:
        libDir: lib
        main: com.acme.Proxy  # <3>
----

<1> The application image should contain a directory named `/lib` that will contain the `.jar` files containing the
application classes and dependencies.
<2> One of those classes will be `com.acme.Main` which will be executed as the main class when starting the JVMs for
the `data` role.
<3> The `proxy` role will use the `com.acme.Proxy` class as the main class


=== Setting the Application Main Class for Explicit Roles with a Default

When creating a `CoherenceCluster` with explicit roles in the `roles` list the `application.main` field can be set
at the `spec` level as a default that applies to all of the roles in the `roles` list unless specifically overridden
for an individual role:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    libDir: lib               # <1>
    main: com.acme.Main       # <2>
  roles:
    - role: data              # <3>
    - role: proxy
      application:
        main: com.acme.Proxy  # <4>
----

<1> The application image should contain a directory named `/lib` that will contain the `.jar` files containing the
application classes and dependencies.
<2> One of those classes will be `com.acme.Main` which will be executed as the main class for all roles that do not
specifically specify a `main`.
<3> The `data` role does not specify a `main` field so the Coherence JVM in the `Pods` for the `data` role will all use
the `com.acme.Main` class as the main class.
<4> The `proxy` role will specifies a `main` class to use so all Coherence JVMs in the `Pods` for the `proxy` role
will use the `com.acme.Proxy` class as the main class.


////
----- Application main arguments ----------------------------------------------------------------------------------
////
'''
[#app-args]
== Setting the Application Main Arguments

Some applications that specify a custom `main` may also require command line arguments to be passed to the `main`,
These additional arguments can also be configured for the roles in a `CoherenceCluster`. Application arguments are
specified as a string array.

=== Setting the Application Main Arguments for the Implicit Role

When configuring a `CoherenceCluster` with a single implicit role the application's working directory is specified
in the `application.main` field.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    libDir: lib          # <1>
    main: com.acme.Main  # <2>
    args:                # <3>
      - "argOne"
      - "argTwo"
----

<1> The application image should contain a directory named `/lib` that will contain the `.jar` files containing the
application classes and dependencies.
<2> One of those classes will be `com.acme.Main` which will be executed as the main class when starting the JVMs for
the `data` role.
<3> The arguments `"argOne"` and `"argTwo"` will be passed to the `com.acme.Main` class `main()` method.


=== Setting the Application Main Arguments for Explicit Roles

When creating a `CoherenceCluster` with explicit roles in the `roles` list the `application.args` field can be set
specifically for each role:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      application:
        libDir: lib           # <1>
        main: com.acme.Main   # <2>
        args:                 # <3>
          - "argOne"
          - "argTwo"
    - role: proxy
      application:
        libDir: lib
        main: com.acme.Main
        args:                 # <4>
          - "argThree"
          - "argFour"
----

<1> The application image should contain a directory named `/lib` that will contain the `.jar` files containing the
application classes and dependencies.
<2> One of those classes will be `com.acme.Main` which will be executed as the main class when starting the JVMs for
the `data` role.
<3> The arguments `"argOne"` and `"argTwo"` will be passed to the `com.acme.Main` class `main()` method in `Pods` for
the `data` role.
<4> The `proxy` role specifies different arguments. The arguments `"argThree"` and `"argFour"` will be passed to the
`com.acme.Main` class `main()` method in `Pods` for the `proxy` role.

=== Setting the Application Main Arguments for Explicit Roles with a Default

When creating a `CoherenceCluster` with explicit roles in the `roles` list the `application.main` field can be set
at the `spec` level as a default that applies to all of the roles in the `roles` list unless specifically overridden
for an individual role:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    libDir: lib               # <1>
    main: com.acme.Main       # <2>
    args:                     # <3>
      - "argOne"
      - "argTwo"
  roles:
    - role: data              # <4>
    - role: proxy
      application:
        args:                 # <5>
          - "argThree"
          - "argFour"
    - role: web
      application:
        args: []              # <6>
----

<1> The application image should contain a directory named `/lib` that will contain the `.jar` files containing the
application classes and dependencies.
<2> One of those classes will be `com.acme.Main` which will be executed as the main class for all roles that do not
specifically specify a `main`.
<3> The default args are `"argOne"` and `"argTwo"`
<4> The `data` role does not specify an `args` field so the Coherence JVM in the `Pods` for the `data` role will all use
the default arguments of `"argOne"` and `"argTwo"`
<5> The `proxy` role specifies different arguments. The arguments `"argThree"` and `"argFour"` will be passed to the
`com.acme.Main` class `main()` method in `Pods` for the `proxy` role.
<6> The `web` role specifies an empty array for the `args` field so no arguments will be passed to its main class.