///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Configure Applications

Whilst the Coherence Operator can manage plain Coherence clusters typically custom application code and configuration
files would be added to a Coherence JVM's classpath.

== Configure Applications

Different application code and configuration can be added to different roles in a `CoherenceCluster` by specifying
the application's configuration in the `application` section of a role spec. There are a number of different fields
that can be configured for an application described below. All of the configuration described below is optional.

[source,yaml]
.Application Spec
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    image: acme/orders-data:1.0.0
    imagePullPolicy: Always
    appDir: "/app"
    libDir: "/lib"
    configDir: "/conf"
    main: io.acme.Server
    args:
      - "foo"
      - "bar"
----

* <<app-image,Setting the Application Image>> - The application's image that is used to provide application
`.jar` files and configuration files to add to the JVM classpath.
* <<pull-policy,Setting the Application Image Pull Policy>> - The pull policy that Kubernetes will use to pull
the application's image
* <<app-dir,Setting the Application Directory>> - The name of the folder in the application's image containing
application artifacts. This will be the working directory for the Coherence container.
* <<app-lib,Setting the Application Lib Directory>> - The name of the folder in the application's image containing
`.jar` files to add to the JVM class path
* <<app-conf,Setting the Application Config Directory>> - The name of the folder in the application's image containing
configuration files that will be add to the JVM classpath
* <<app-main,Setting the Application Main Class>> - The application's custom main main Class to use if running a
class other than Coherence `DefaultCacheServer`
* <<app-args,Setting the Application Main Class Arguments>> - The arguments to pass to the application's main `Class`


[#app-image]
== Setting the Application Image

The application image is the Docker image containing the `.jar` files and configuration files of the Coherence application
that should be deployed in the Coherence cluster. For more information see the
<<guides/030_applications.adoc,Deploying Coherence Applications>> guide.

Whilst the Coherence Operator makes it simple to deploy and manage a Coherence cluster in Kubernetes in the majority of
use cases there will be a requirement for application code to be deployed and run in the Coherence JVMs. This application
code and any application configuration files are supplied as a separate image. This image is loaded as an init-container
by the Coherence `Pods` and the relevant `.jar` files and configuration files from this image are added to the Coherence
JVM's classpath.

As well as setting the image name it is also sometimes useful to set the application image's  <<pull-policy,image pull policy>>.

If the image being configured is from a registry requiring authentication see the section
on <<clusters/200_private_repos.adoc,pulling from private registries>>.

=== Setting the Application Image for the Implicit Role

When using the implicit role configuration the application image to use is set directly in the `CoherenceCluster` `spec`
`application.image` field.

For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    image: acme/orders-data:1.0.0  <1>
----

<1> The `acme/orders-data:1.0.0` will be used to add additional `.jar` files and configuration files to the classpath of
the Coherence container in the implicit `storage` role's `Pods`


=== Setting the Application Image for Explicit Roles

When using the explicit roles in a `CoherenceCluster` `roles` list the application image to use is set for each role.

For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      application:
        image: acme/orders-data:1.0.0  <1>
    - role: proxy
      application:
        image: acme/orders-proxy/1.0.0  <2>
----

<1> The `data` role `Pods` will use the application image `acme/orders-data:1.0.0`
<2> The `proxy` role `Pods` will use the application image `acme/orders-proxy/1.0.0`


===  Setting the Application Image for Explicit Roles with a Default

When using the explicit roles in a `CoherenceCluster` `roles` list the application image to use can be set in the
`CoherenceCluster` `spec` section and will apply to all roles unless specifically overridden for a `role` in the
`roles` list.

For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    image: acme/orders-data:1.0.0  <1>
  roles:
    - role: data
    - role: proxy
----

<1> The `data` and the `proxy` roles will both use the application image `acme/orders-data:1.0.0`


[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    image: acme/orders-data:1.0.0  <1>
  roles:
    - role: data
    - role: proxy
    - role: web
      application:
        image: acme/orders-front-end/1.0.0  <2>
----

<1> The `data` and the `proxy` roles will both use the application image `acme/orders-data:1.0.0`
<2> The `web` role will use the application image `acme/orders-web/1.0.0`


[#pull-policy]
== Setting the Application Image Pull Policy

The image pull policy controls when (and if) Kubernetes will pull the application image onto the node where the Coherence
`Pods` are being schedules.
See https://kubernetes.io/docs/concepts/containers/images/#updating-images[Kubernetes imagePullPolicy] for more information.

NOTE: The Kubernetes default pull policy is `IfNotPresent` unless the image tag is `:latest` in which case the default
policy is `Always`. The `IfNotPresent` policy causes the Kubelet to skip pulling an image if it already exists.
Note that you should avoid using the `:latest` tag, see
https://kubernetes.io/docs/concepts/configuration/overview/#container-images[Kubernetes Best Practices for Configuration]
for more information.

The application image's pull policy is set using the `imagePullPolicy` field in the `spec.application` section.


=== Setting the Image Pull Policy for the Implicit Role

To set the `imagePullPolicy` for the implicit role:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    image: acme/orders-data:1.0.0
    imagePullPolicy: Always <1>
----

<1> The image pull policy for the implicit role above has been set to `Always`


=== Setting the Image Pull Policy for Explicit Roles

To set the `imagePullPolicy` for the explicit roles in the `roles` list:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      application:
        image: acme/orders-data:1.0.0
        imagePullPolicy: Always <1>
    - role: proxy
      application:
        image: acme/orders-proxy/1.0.0
        imagePullPolicy: IfNotPresent <2>
----

<1> The image pull policy for the `data` role has been set to `Always`
<2> The image pull policy for the `proxy` role above has been set to `IfNotPresent`


=== Setting the Image Pull Policy for Explicit Roles with Default

To set the `imagePullPolicy` for the explicit roles with a default value:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    imagePullPolicy: Always <1>
  roles:
    - role: data
      application:
        image: acme/orders-data:1.0.0
    - role: proxy
      application:
        image: acme/orders-proxy/1.0.1
    - role: web
      application:
        image: acme/orders-front-end/1.0.1
        imagePullPolicy: IfNotPresent <2>
----

<1> The default image pull policy is set to `Always`. The `data` and `proxy` roles will use the default value because
they do not specifically set the value in their specs.
<2> The image pull policy for the `web` role above has been set to `IfNotPresent`


[#app-dir]
== Setting the Application Directory


=== Setting the Application Directory for the Implicit Role
=== Setting the Application Directory for Explicit Roles
=== Setting the Application Directory for Explicit Roles with a Default


[#app-lib]
== Setting the Application Lib Directory

A typical Coherence application may also require additional dependencies (usually `.jar` files) that need to be added
to the classpath.
The applications's lib directory is a directory in the application's image that contains these additional `.jar` files.
The Coherence Operator will add the files to the classpath with the wildcard setting (e.g. `-cp /lib/*`) it does not add
each file in the lib directory individually to the classpath. This means that the contents of the lib directory are
added to the classpath using the rules that the JVM uses to process wild card classpath entries.

=== Setting the Application Lib Directory for the Implicit Role
=== Setting the Application Lib Directory for Explicit Roles
=== Setting the Application Lib Directory for Explicit Roles with a Default


[#app-conf]
== Setting the Application Config Directory

A Coherence application may require additional files added to the classpath such as configuration files and other
resources. These additional files can be placed into the config directory of the application's image and this directory
added to the classpath of the Coherence JVM. Just the directory is added to the classpath (e.g. `-cp /conf`) the contents
themselves are not added.

=== Setting the Application Config Directory for the Implicit Role
=== Setting the Application Config Directory for Explicit Roles
=== Setting the Application Config Directory for Explicit Roles with a Default


[#app-main]
== Setting the Application Main Class

By default the Coherence container will run the `main` method in the `com.tangosol.coherence.DefaultCacheServer`
class. Sometimes an application requires a different class as the main class and this can be configured for roles
in a `CoherenceCluster`.

=== Setting the Application Main Class for the Implicit Role
=== Setting the Application Main Class for Explicit Roles
=== Setting the Application Main Class for Explicit Roles with a Default


[#app-args]
== Setting the Application Main Class Arguments

If a custom main class is being used it is sometimes required to pass arguments to that class's `main` method.
These additional arguments can be configured alongside the main class.

=== Setting the Application Main Class Arguments for the Implicit Role
=== Setting the Application Main Class Arguments for Explicit Roles
=== Setting the Application Main Class Arguments for Explicit Roles with a Default
