///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Configure Safe Scaling

== Configure Safe Scaling

The Coherence Operator contains functionality to allow it to safely scale a role within a Coherence cluster without
losing data. Scaling can be configured in the `scaling` section of the `CoherenceCluster` CRD.

A role in a `CoherenceCluster` can be scaled by changing the replica count in the role's spec or by using the
`kubectl scale` command.


=== Scaling Policy

The Coherence Operator uses a scaling policy to determine how the `StatefulSet` that makes up a role withing a
cluster is scaled.
Scaling policy has the following values:

[cols=2*,options=header]
|===
|Value
|Description

|`ParallelUpSafeDown`
|This is the default scaling policy.
With this policy when scaling up `Pods` are added in parallel (the same as using the `Parallel` `podManagementPolicy`
in a https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#statefulsetspec-v1-apps[StatefulSet]) and
when scaling down `Pods` are removed one at a time (the same as the `OrderedReady` `podManagementPolicy` for a
StatefulSet). When scaling down a check is done to ensure that the members of the role have a safe StatusHA value
before a `Pod` is removed (i.e. none of the Coherence cache services have an endangered status).
This policy offers faster scaling up and start-up because pods are added in parallel as data should not be lost when
adding members, but offers safe, albeit slower,  scaling down as `Pods` are removed one by one.

|`Parallel`
|With this policy when scaling up `Pods` are added in parallel (the same as using the `Parallel` `podManagementPolicy`
in a https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#statefulsetspec-v1-apps[StatefulSet]).
With this policy no StatusHA check is performed either when scaling up or when scaling down.
This policy allows faster start and scaling times but at the cost of no data safety; it is ideal for roles that are
storage disabled.

|`Safe`
|With this policy when scaling up and down `Pods` are removed one at a time (the same as the `OrderedReady`
`podManagementPolicy` for a StatefulSet). When scaling down a check is done to ensure that the members of the role have
a safe StatusHA value before a `Pod` is removed (i.e. none of the Coherence cache services have an endangered status).
This policy is slow to start, scale up and scale down.

...
|===


The scaling policy is set in the `scaling.policy` section of the configuration of a role.

=== Configure Scaling Policy for a Single Implicit Role

When creating a `CoherenceCluster` with a single implicit role the scaling policy can be defined at the `spec` level.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  scaling:
    policy: Safe # <1>
----

<1> The implicit role will have a scaling policy of `Safe`


=== Configure Scaling Policy for Explicit Roles

When creating a `CoherenceCluster` with explicit roles in the `roles` list scaling policy can be defined for each role,
for example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      scaling:
        policy: ParallelUpSafeDown # <1>
    - role: proxy
      scaling:
        policy: Parallel           # <2>
----

<1> The `data` role will have the scaling policy `ParallelUpSafeDown`
<2> The `proxy` role will have the scaling policy `Parallel`


=== Configure Pod Labels for Explicit Roles With Defaults

When creating a `CoherenceCluster` with explicit roles in the `roles` list scaling policy can be defined as defaults
applied to all roles unless specifically overridden for a role.

For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  scaling:
    policy: Parallel               # <1>
  roles:
    - role: data
      scaling:
        policy: ParallelUpSafeDown # <2>
    - role: proxy                  # <3>
    - role: web                    # <4>
----

<1> Thedefault scaling policy is `Parallel` that will apply to all roles unless specifically overridden.
<2> The `data` role overrides the default and specifies a scaling policy of `ParallelUpSafeDown`
<3> The `proxy` role does not specify a scaling policy so will use the defautl of `Parallel`
<4> The `web` role does not specify a scaling policy so will use the defautl of `Parallel`

