///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Environment Variables

It is possible to pass arbitrary environment variables to the `Pods` that are created for a Coherence cluster.

== Environment Variables

Environment variables can be configured in a `CoherenceCluster` and will be passed through to the Coherence `Pods`
created for the roles in the cluster. Environment variables are configured in the `env` field of the spec. The format
for setting environment variables is exactly the same as when configuring them in a
https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/[Kubernetes `Container`].

=== Environment Variables in the Implicit Role

If configuring a single implicit role environment variables are set in the `spec.env` section; for example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  env:
    - name: FOO        # <1>
      value: "foo-val"
    - name: BAR        # <2>
      value: "bar-val"
----

<1> The `FOO` environment variable with a value of `foo-val` will be passed to the `coherence` container in the `Pods`
created for the implicit role.
<2> The `BAR` environment variable with a value of `bar-val` will be passed to the `coherence` container in the `Pods`
created for the implicit role.


=== Environment Variables in Explicit Roles

When configuring one or more explicit roles in the `roles` section of the spec environment variables can be configured
for each role.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      env:
        - name: FOO        # <1>
          value: "foo-val"
    - role: proxy
      env:
        - name: BAR        # <2>
          value: "bar-val"
----

<1> All `Pods` created for the `data` role will have the `FOO` environment variable set to `foo-val`
<2> All `Pods` created for the `proxy` role will have the `BAR` environment variable set to `bar-val`


=== Environment Variables in Explicit Roles With Defaults

When configuring one or more explicit roles it is also possible to configure environment variables at the
defaults level. These environment variables will be shared by all `Pods` in all roles unless specifically
overridden for a role. An environment variable is only overridden in a role by declaring a role level
environment variable with the same name. When creating the `Pods` configuration the Coherence Operator will
merge the list of default environment variables with the role's list of environment variables. Where an
environment variable in a role has the same key as an environment variable in the defaults section the
value in the role will take precedence.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  env:
    - name: FOO
      value: "foo-val"
  roles:
    - role: data           # <1>
    - role: proxy          # <2>
      env:
        - name: BAR
          value: "bar-val"
    - role: web            # <3>
      env:
        - name: FOO
          value: "foo-web"
        - name: BAR
          value: "bar-web"
----

<1> The `data` role does not have any environment variables configured so it will just inherit the `FOO=foo-val`
environment variable from the defaults.
<2> The `proxy` role has the `BAR=bar-val` environment variables configured and will also inherit the `FOO=foo-val`
environment variable from the defaults.
<3> The `web` role has will override the `FOO` environment variable from the default with `FOO=foo-web`. It also
has its own `BAR=bar-web` environment variable.
