///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Configure Pod Annotations

Annotations can be added to the `Pods` of a role in a `CoherenceCluster`.

== Configure Pod Annotations

Custom https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/[annotations]
can be added to the spec of a role which will then be added to all `Pods` for that role created by
the Coherence Operator.

=== Configure Pod Annotations for the Implicit Role

When creating a `CoherenceCluster` with a single implicit role annotations can be defined at the `spec` level.
Annotations are defined as a map of string key value pairs, for example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  annotations:
    acme.com/layer: back  # <1>
----

<1> The implicit role will have the annotation `acme.com/layer : back`

This will result in a `StatefulSet` for the role with the annotation added to the `PodSpec`.

[source,yaml]
.StatefulSet snippet
----
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-cluster-storage
spec:
  replicas: 3
  selector:
    matchLabels:
      coherenceDeployment: test-cluster-storage
      component: coherencePod
  serviceName: test-cluster-storage
  template:
    metadata:
      annotations:
        acme.com/layer: back  # <1>
----

<1> The annotation `acme.com/layer: back` has been applied to the `StatefulSet` `Pod` template.


=== Configure Pod Annotations for Explicit Roles

When creating a `CoherenceCluster` with explicit roles in the `roles` list annotations can be defined for each role, for example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      annotations:
        acme.com/layer: back  # <1>
    - role: proxy
      annotations:
        acme.com/layer: front  # <2>
----

<1> The `data` role will have the annotation `acme.com/layer: back`
<2> The `proxy` role will have the annotation `acme.com/layer: front`


=== Configure Pod Annotations for Explicit Roles With Defaults

When creating a `CoherenceCluster` with explicit roles in the `roles` list annotations can be defined as defaults
applied to all roles and also for each role. Where annotations exist with the same key in both the defaults and
the role then the annotation in the role will take precedence.

For example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  annotations:
    acme.com/layer: back         # <1>
    acme.com/app:   orders
  roles:
    - role: data                 # <2>
    - role: proxy                # <3>
      annotations:
        acme.com/state: none
    - role: web                  # <4>
      annotations:
        acme.com/three: none
        acme.com/layer: front
----

<1> There are two default annotations `acme.com/layer : back` and `acme.com/app : orders` that will apply to all `Pods`
in all roles unless specifically overridden.
<2> The `data` role has no other annotations defined so will just have the default annotations `acme.com/layer : back`
and `acme.com/app : orders`
<3> The `proxy` role specified an annotation `acme.com/state : none` so will have this annotation as well as the
default annotations `acme.com/layer : back` and `acme.com/app : orders`
<4> The `web` role specifies the `acme.com/three: none` annotation and also overrides the `acme.com/layer` annotation
with the value `front` so it will have three annotations, `acme.com/three: none` , `acme.com/layer : front`
and `acme.com/app : orders`


