///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Kubernetes Service Account

== Configure the Kubernetes Service Account

In Kubernetes clusters that have RBAC enabled it may be a requirement to set the
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/[service account]
that will be used by the `Pods` created for a `CoherenceCluster`

The service account name is set for the `CoherenceCluster` as a whole and will be applied to all `Pods`.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  serviceAccountName: foo    <1>
----

<1> All `Pods` in the `test-cluster` will use the service account `foo`



