///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Using Private Image Registries


== Using Private Image Registries

Sometimes the images used by a Coherence cluster need to be pulled from a private image registry that requires credentials.
The Coherence Operator supports supplying credentials in the `CoherenceCluster` configuration.
The Kubernetes documentation on https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry[ using a private registries]
gives a number of options for supplying credentials.

== Use ImagePullSecrets

Kubernetes supports configuring pods to use `imagePullSecrets` for pulling images. If possible, this is the preferable
and most portable route.
See the https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod[kubernetes docs]
for this.
Once secrets have been created in the namespace that the `CoherenceCluster` is to be installed in then the secret name
can be specified in the `CoherenceCluster` `spec`. It is possible to specify multiple secrets in the case where the different
images being used are pulled from different registries.


[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  imagePullSecrets:
    - name: coherence-secret  <1>
----

<1> The `coherence-secret` will be used for pulling images from the registry associated to the secret


The `imagePullSecrets` field is a list of values in the same format that they would be specified in Kubernetes `Pod`
specs, so multiple secrets can be specified for different authenticated registries in the case where the Coherence
cluster will use images from different authenticated registries..

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  imagePullSecrets:     <1>
    - name: coherence-secret
    - name: ocr-secret
----

<1> The `imagePullSecrets` list specifies two secrets to use `coherence-secret` and `ocr-secret`

Image pull secrets are only specified for the `CoherenceCluster` as a whole as there is no benefit to being able to
specify different secrets for different roles within a cluster.