///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Network Configuration

== Logging Configuration

When configuring a `Pod` in Kubernetes there are a number of settings related to networking and DNS and these can also
be configured for roles in a `CoherenceCluster`.



[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  network:
    hostname: "foo.com"                  # <1>
    hostNetwork: false                   # <2>
    hostAliases:
      - ip: "10.10.10.100"               # <3>
        hostnames:
          - "a.foo.com"
          - "b.foo.com"
    dnsPolicy: "ClusterFirstWithHostNet" # <4>
    dnsConfig:                           # <5>
      nameservers:
        - "dns.foo.com"
        - "dns.bar.com"
      searches:
        - foo.com"
        - "bar.com"
      options:
        - name: "option-name"
          value: "option-value
----

<1> the `network.hostname` field specifies the hostname of the Pod If not specified, the pod's hostname will be set
to a system-defined value as per the Kubernetes defaults.

<2> the `hostNetwork` field setw whether host networking is requested for Pods in a role . If set to true Pods will use
the host's network namespace. If this option is set, the ports that will be used must be specified. If set to `true`
care must be taken not to schedule multiple Pods for a role onto the same Kubernetes node. Default to false.

<3> the `hostAliases` field adds host aliases to the Pods in a roles.
See the Kubernetes documentation on
https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/[Adding entries to Pod /etc/hosts with HostAliases]

<4> the `dnsPolicy` field sets the DNS policy for the pod. Defaults to "ClusterFirst". Valid values are
'ClusterFirstWithHostNet', 'ClusterFirst', 'Default' or 'None'. DNS parameters given in DNSConfig will be merged with
the policy selected with DNSPolicy. To have DNS options set along with hostNetwork, you have to specify DNS policy
explicitly to 'ClusterFirstWithHostNet'.
See the Kubernetes documentation on
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/[DNS for Services and Pods]

<5> the `dnsConfig` section sets other DNS configuration that will be applied to Pods for a role.
See the Kubernetes documentation on
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/[DNS for Services and Pods]

