{
 "title": "Caches Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor:coherence_cluster_size{cluster=~\"$ClusterName\"}, version)"
   },
   {
    "name": "Services",
    "label": "Services",
    "query": "label_values(vendor:coherence_service_request_max_duration{cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "Caches",
    "label": "Caches",
    "query": "label_values(vendor:coherence_cache_size{cluster=~\"$ClusterName\"}, name) "
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Caches Summary - $ClusterName</h3></center>"
  },
  {
   "title": "Cache List",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_units_bytes{cluster=~\"$ClusterName\",tier=\"back\"}) by (coherence_service, name)"
    },
    {
     "expr": "sum(vendor:coherence_cache_size{cluster=~\"$ClusterName\",tier=\"back\"}) by (coherence_service, name)"
    }
   ]
  },
  {
   "title": "Cache Data Memory Usage",
   "type": "graph",
   "description": "Shows a graph of cache related memory used.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_units_bytes{cluster=~\"$ClusterName\",tier=\"back\"})",
     "legendFormat": "Cache Memory"
    },
    {
     "expr": "sum(vendor:coherence_storage_manager_index_total_units{cluster=~\"$ClusterName\"})",
     "legendFormat": "Index Memory"
    }
   ]
  },
  {
   "title": "Cache Index Size",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_storage_manager_index_total_units{cluster=~\"$ClusterName\"}) by (coherence_service, cache )"
    }
   ]
  }
 ]
}