{
 "title": "Cache Details Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "ServiceName",
    "label": "Service Name",
    "query": "label_values(vendor:coherence_service_member_count{cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "CacheName",
    "label": "Cache Name",
    "query": "label_values(vendor:coherence_cache_units_bytes{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Cache Details - $ServiceName / $CacheName</h3></center>"
  },
  {
   "title": "Cache Size",
   "type": "singlestat",
   "description": "The size of number of entries in the cache.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_size{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\",name=~\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "Cache Memory",
   "type": "singlestat",
   "description": "Indicates memory utilized by the cache entries. \nNote: If the unit-calculator is not BINARY or the service is not a DistributedCache service, then the details may be incorrect.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_units_bytes{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\",name=~\"$CacheName\"}) "
    }
   ]
  },
  {
   "title": "Index Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_storage_manager_index_total_units{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\",cache=~\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "Total Non-Optimized Queries",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_storage_manager_non_optimized_query_count{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\",cache=~\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "Total Non-Optimized Query Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_storage_manager_non_optimized_query_total_millis{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\",cache=~\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "Max Query Duration",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(vendor:coherence_storage_manager_max_query_duration_millis{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\",cache=~\"$CacheName\"})"
    }
   ]
  },
  {
   "title": "Cache And Index Memory for $CacheName",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_units_bytes{cluster=~\"$ClusterName\",tier=\"back\",name=~\"$CacheName\"})",
     "legendFormat": "Cache Memory"
    },
    {
     "expr": "sum(vendor:coherence_storage_manager_index_total_units{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", cache=~\"$CacheName\"})",
     "legendFormat": "Index Memory"
    }
   ]
  },
  {
   "title": "Back Cache and Access Counts for Cache $CacheName",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_size{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_units_bytes{cluster=~\"$ClusterName\",tier=\"back\",name=~\"$CacheName\"}) by(member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_total_gets{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_total_puts{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_hits{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_prunes{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_misses{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_hits{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"back\"}) by (member) / (sum(vendor:coherence_cache_hits{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"back\"}) by (member) + sum(vendor:coherence_cache_misses{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"back\"}) by (member) ) "
    }
   ]
  },
  {
   "title": "Back Cache and Access Times for Cache $CacheName",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_total_gets_millis{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_total_puts_millis{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_hits_millis{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_prunes_millis{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_misses_millis{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"back\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_storage_max_query_duration_millis{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", cache=~\"$CacheName\"}) by (member)"
    }
   ]
  },
  {
   "title": "Cache Storage Details for Cache $CacheName",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_storage_listener_registrations{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_storage_eviction_count{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_storage_non_optimized_query_count{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_storage_optimized_query_count{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_storage_index_total_units{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_storage_manager_non_optimized_query_total_millis{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_storage_manager_max_query_duration_millis{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_storage_manager_eviction_count{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_storage_manager_locks_pending{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", cache=~\"$CacheName\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_storage_manager_locks_granted{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", cache=~\"$CacheName\"}) by (member)"
    }
   ]
  },
  {
   "title": "Front Cache and Access Counts for Cache $CacheName",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_size{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"front\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_total_gets{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"front\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_total_puts{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"front\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_hits{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"front\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_misses{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"front\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_cache_hits{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"front\"}) by (member) / (sum(vendor:coherence_cache_hits{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"front\"}) by (member) + sum(vendor:coherence_cache_misses{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\", name=~\"$CacheName\", tier=\"front\"}) by (member) ) "
    }
   ]
  }
 ]
}