{
 "title": "Coherence Dashboard Main",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor:coherence_cluster_size{cluster=~\"$ClusterName\"}, version)"
   },
   {
    "name": "Services",
    "label": "Services",
    "query": "label_values(vendor:coherence_service_request_max_duration{cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "Caches",
    "label": "Caches",
    "query": "label_values(vendor:coherence_cache_size{cluster=~\"$ClusterName\"}, name) "
   },
   { "name": "TopLimit", "label": "Top N Limit", "query": "1,3,5,10,15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Cluster Overview - $CoherenceVersion</h3></center>"
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    { "title": "Current Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 } },
    { "title": "Recent Alert State Changes", "type": "alertlist", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 } }
   ]
  },
  {
   "title": "Cluster Overview - $ClusterName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Cluster Members",
   "type": "singlestat",
   "description": "Shows the number of cluster members.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vendor:coherence_cluster_size{cluster=~\"$ClusterName\"})  "
    }
   ]
  },
  {
   "title": "Recent Departures",
   "type": "singlestat",
   "description": "Recent member departures.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(delta(vendor:coherence_cluster_members_departure_count{cluster=~\"$ClusterName\"}[5m])) >= 0"
    }
   ]
  },
  {
   "title": "Endangered Services",
   "type": "singlestat",
   "description": "The number of services with endangered partitions.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vendor:coherence_partition_assignment_ha_status_code{cluster=~\"$ClusterName\"} <= 1)"
    }
   ]
  },
  {
   "title": "Used Cluster Heap",
   "type": "singlestat",
   "description": "Total used cluster heap across all members.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_platform_memory_heap_memory_usage_used{cluster=~\"$ClusterName\"})"
    }
   ]
  },
  {
   "title": "Total Cluster Heap",
   "type": "singlestat",
   "description": "Total available cluster heap across all members.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_platform_memory_heap_memory_usage_max{cluster=~\"$ClusterName\"})"
    }
   ]
  },
  {
   "title": "Total Heap Memory Usage %",
   "type": "singlestat",
   "description": "Percentage of heap memory used across all members.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_platform_memory_heap_memory_usage_used{cluster=~\"$ClusterName\"}) / sum(vendor:coherence_platform_memory_heap_memory_usage_max{cluster=~\"$ClusterName\"}) * 100  "
    }
   ]
  },
  {
   "title": "Cluster Memory Details",
   "type": "graph",
   "description": "Total and used cluster memory across all members.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_platform_memory_heap_memory_usage_used{cluster=~\"$ClusterName\"})",
     "legendFormat": "Used Cluster Memory"
    },
    {
     "expr": "sum(vendor:coherence_platform_memory_heap_memory_usage_max{cluster=~\"$ClusterName\"})",
     "legendFormat": "Total Cluster Memory"
    }
   ]
  },
  {
   "title": "Current Load Averages",
   "type": "graph",
   "description": "Show the current load average across all machines.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(vendor:coherence_platform_os_system_load_average{cluster=~\"$ClusterName\"}) by (machine)",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Top $TopLimit Machines -  Physical Memory",
   "type": "table",
   "description": "The top  $TopLimit Members that have the lowest physical memory % available.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "bottomk($TopLimit, avg(vendor:coherence_platform_os_free_physical_memory_size{cluster=~\"$ClusterName\"}/ vendor:coherence_platform_os_total_physical_memory_size{cluster=~\"$ClusterName\"}) by (machine))"
    }
   ]
  },
  {
   "title": "Top $TopLimit Loaded Members  - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the highest CPU Load % over the current time range.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "topk($TopLimit, sum(avg_over_time(vendor:coherence_platform_os_process_cpu_load{cluster=~\"$ClusterName\"}[$__range] )) by (member))"
    }
   ]
  },
  {
   "title": "Top $TopLimit Members - Heap Used % - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the highest heap memory % used over the current time range.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "topk($TopLimit, avg(avg_over_time(vendor:coherence_platform_memory_heap_memory_usage_used{cluster=~\"$ClusterName\"}[$__range]) / avg_over_time(vendor:coherence_platform_memory_heap_memory_usage_max{cluster=~\"$ClusterName\"}[$__range])) by (member))"
    }
   ]
  },
  {
   "title": "Top $TopLimit Members - Task Count -  Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the greatest change in the Task Count over the current time range.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": " topk($TopLimit,sum(delta(vendor:coherence_service_task_count{cluster=~\"$ClusterName\"}[$__range])) by (member)) > 0"
    }
   ]
  },
  {
   "title": "Top $TopLimit Services - Task Count - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Services  that have the greatest change in the Task Count over the current time range.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": " topk($TopLimit,sum(delta(vendor:coherence_service_task_count{cluster=~\"$ClusterName\"}[$__range])) by (name)) > 0"
    }
   ]
  },
  {
   "title": "Task Backlog By Member",
   "type": "graph",
   "description": "Total task backlog per member.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_service_task_backlog{cluster=~\"$ClusterName\"}) by (member)",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Task Backlog By Service",
   "type": "graph",
   "description": "Total task backlog by service.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_service_task_backlog{cluster=~\"$ClusterName\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Proxy Outgoing Byte Backlog by Service",
   "type": "graph",
   "description": "Total Proxy Outgoing Byte Backlog by Service",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_extend_proxy_outgoing_byte_backlog{cluster=~\"$ClusterName\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current Suspect Services - Unbalanced Partitions",
   "type": "table",
   "description": "Services that  have unbalanced partitions.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "avg(vendor:coherence_service_partitions_unbalanced{cluster=~\"$ClusterName\", type=~\"DistributedCache|FederatedCache\"}) by(name) > 0"
    }
   ]
  },
  {
   "title": "Top $TopLimit Members - Network -  Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the greatest change in sent and received messages over the current time range.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "topk($TopLimit, sum(vendor:coherence_node_packets_sent{cluster=~\"$ClusterName\"} + vendor:coherence_node_packets_received{cluster=~\"$ClusterName\"}  - vendor:coherence_node_packets_sent{cluster=~\"$ClusterName\"} offset $__range -   vendor:coherence_node_packets_received{cluster=~\"$ClusterName\"} offset $__range) by (member))"
    }
   ]
  },
  {
   "title": "Current Top  $TopLimit Cache Max Query Times",
   "type": "table",
   "description": "The current top $TopLimit caches, services and member with the highest Max Query Time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "topk($TopLimit, sum(vendor:coherence_storage_max_query_duration_milis{cluster=~\"$ClusterName\"}) by (member, service, cache)) > 0"
    }
   ]
  },
  {
   "title": "Current Top $TopLimit Non-Optimized Queries",
   "type": "table",
   "description": "The current top $TopLimit nodes with the highest number of Non-Optimized Queries.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "topk($TopLimit, sum(vendor:coherence_storage_non_optimized_query_count{cluster=~\"$ClusterName\"}) by (member, service, cache))> 0"
    }
   ]
  },
  {
   "title": "Guardian Recoveries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vendor:coherence_node_guard_recover_count{cluster=~\"$ClusterName\"}[1m])) by (member) > 0",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Guardian Terminations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vendor:coherence_node_guard_terminate_count{cluster=~\"$ClusterName\"}[1m])) by (member) > 0",
     "legendFormat": "{{member}}"
    }
   ]
  }
 ]
}