{
 "title": "Federation Details Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "Destination",
    "label": "Destination",
    "query": "label_values(vendor:coherence_federation_destination_total_bytes_sent {cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "ServiceName",
    "label": "Service Name",
    "query": "label_values(vendor:coherence_federation_destination_total_bytes_sent {cluster=~\"$ClusterName\",name=~\"$Destination\"}, coherence_service)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Federation Details - $ServiceName, Destiniation - $Destination</h3></center>"
  },
  {
   "title": "Destinations",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_federation_destination_total_bytes_sent {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"})by (coherence_service, name, participant_type, node_id)"
    },
    {
     "expr": "sum(vendor:coherence_federation_destination_total_entries_sent {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"})by (coherence_service, name, participant_type, node_id)"
    },
    {
     "expr": "sum(vendor:coherence_federation_destination_total_msg_sent {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"})by (coherence_service, name, participant_type, nodeId)"
    },
    {
     "expr": "sum(vendor:coherence_federation_destination_total_records_sent {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"})by (coherence_service, name, participant_type, node_id)"
    },
    {
     "expr": "sum(vendor:coherence_federation_destination_replicate_all_total_time_millis{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"})by (coherence_service, name, participant_type, node_id)"
    },
    {
     "expr": "avg(vendor:coherence_federation_destination_status{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"})by (coherence_service, name, participant_type, node_id)"
    }
   ]
  },
  {
   "title": "Data Sent  per Member",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vendor:coherence_federation_destination_total_bytes_sent {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"}[1m])) by (node_id)",
     "legendFormat": "Node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Entries Sent per Member",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vendor:coherence_federation_destination_total_entries_sent {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"}[1m])) by (node_id)",
     "legendFormat": "Node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Entries Sent per Member",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vendor:coherence_federation_destination_total_records_sent {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"}[1m])) by (node_id)",
     "legendFormat": "Node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Errors and Un-Acked Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vendor:coherence_federation_destination_total_error_responses{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"}[1m])) by (node_id)",
     "legendFormat": "Error Responses Node: {{node_id}}"
    },
    {
     "expr": "sum(vendor:coherence_federation_destination_total_msg_unacked{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"}) by (node_id)",
     "legendFormat": "Message Unacked Node: {{node_id}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "content": "<center><h3>Federation Details - $ServiceName, Origin - $Destination</h3></center>"
  },
  {
   "title": "Origins",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_federation_origin_total_bytes_received {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"})by (coherence_service, name, nodeId)"
    },
    {
     "expr": "sum(vendor:coherence_federation_origin_total_entries_received {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"})by (coherence_service, name, nodeId)"
    },
    {
     "expr": "sum(vendor:coherence_federation_origin_total_records_received {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"})by (coherence_service, name, nodeId)"
    },
    {
     "expr": "sum(vendor:coherence_federation_origin_total_msg_received {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"})by (coherence_service, name, nodeId)"
    }
   ]
  },
  {
   "title": "Origins Member Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_federation_origin_total_bytes_received {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"})by (coherence_service, name, node_id, member)"
    },
    {
     "expr": "sum(vendor:coherence_federation_origin_total_msg_unacked {cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"})by (coherence_service, name, node_id, member)"
    }
   ]
  },
  {
   "title": "Origins Un-Acked Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_federation_destination_total_msg_unacked{cluster=~\"$ClusterName\",name=~\"$Destination\",coherence_service=~\"$ServiceName\"}) by (node_id)",
     "legendFormat": "Message Unacked Node: {{node_id}}"
    }
   ]
  }
 ]
}