{
 "title": "HTTP Servers Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ClusterName", "label": "Cluster Name", "query": "label_values(cluster)" },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(coherence_cluster_size{cluster=~\"$ClusterName\"}, tag_version)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>HTTP Servers Summary - $ClusterName</h3></center>"
  },
  {
   "title": "HTTP Servers List",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "count(coherence_extend_proxy_request_count_total{cluster=~\"$ClusterName\",tag_protocol=~\"http\"}) by (name) "
    },
    {
     "expr": "sum(coherence_extend_proxy_request_count_total{cluster=~\"$ClusterName\",tag_protocol=~\"http\"}) by (name) "
    },
    {
     "expr": "sum(coherence_extend_proxy_error_count_total{cluster=~\"$ClusterName\",tag_protocol=~\"http\"}) by (name) "
    },
    {
     "expr": "sum(coherence_extend_proxy_average_request_time{cluster=~\"$ClusterName\",tag_protocol=~\"http\"}) by (name) "
    }
   ]
  },
  {
   "title": "HTTP Requests/ sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(coherence_extend_proxy_request_count_total{cluster=~\"$ClusterName\",tag_protocol=~\"http\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(coherence_extend_proxy_response_1xx_count{cluster=~\"$ClusterName\",tag_protocol=~\"http\"}[1m])) by (name)",
     "legendFormat": "{{name}} 100-199"
    },
    {
     "expr": "sum(idelta(coherence_extend_proxy_response_2xx_count{cluster=~\"$ClusterName\",tag_protocol=~\"http\"}[1m])) by (name)",
     "legendFormat": "{{name}} 200-299"
    },
    {
     "expr": "sum(idelta(coherence_extend_proxy_response_3xx_count{cluster=~\"$ClusterName\",tag_protocol=~\"http\"}[1m])) by (name)",
     "legendFormat": "{{name}} 300-399"
    },
    {
     "expr": "sum(idelta(coherence_extend_proxy_response_4xx_count{cluster=~\"$ClusterName\",tag_protocol=~\"http\"}[1m])) by (name)",
     "legendFormat": "{{name}} 400-499"
    },
    {
     "expr": "sum(idelta(coherence_extend_proxy_response_5xx_count{cluster=~\"$ClusterName\",tag_protocol=~\"http\"}[1m])) by (name)",
     "legendFormat": "{{name}} 500-599"
    }
   ]
  }
 ]
}