{
 "title": "Member Details Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "MemberName",
    "label": "Member Name",
    "query": "label_values(vendor:coherence_service_member_count{cluster=~\"$ClusterName\"}, member)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Member Details - $MemberName</h3></center>"
  },
  { "title": "Current  Details - $MemberName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Used Heap",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "vendor:coherence_platform_memory_heap_memory_usage_used{cluster=~\"$ClusterName\",member=~\"$MemberName\"}  "
    }
   ]
  },
  {
   "title": "Max Heap",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "vendor:coherence_platform_memory_heap_memory_usage_max{cluster=~\"$ClusterName\",member=~\"$MemberName\"}  "
    }
   ]
  },
  {
   "title": "Heap Used %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "vendor:coherence_platform_memory_heap_memory_usage_used{cluster=~\"$ClusterName\",member=~\"$MemberName\"} / vendor:coherence_platform_memory_heap_memory_usage_max{cluster=~\"$ClusterName\",member=~\"$MemberName\"}  "
    }
   ]
  },
  {
   "title": "Publisher Success",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "vendor:coherence_node_publisher_success_rate{cluster=~\"$ClusterName\",member=~\"$MemberName\"} "
    }
   ]
  },
  {
   "title": "Receiver Success",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "vendor:coherence_node_receiver_success_rate{cluster=~\"$ClusterName\",member=~\"$MemberName\"} "
    }
   ]
  },
  {
   "title": "Current Services Running on $MemberName",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {},
    {
     "expr": "sum(vendor:coherence_service_thread_count{cluster=~\"$ClusterName\",member=~\"$MemberName\"}) by (name) > 0"
    },
    {
     "expr": "sum(vendor:coherence_service_thread_idle_count{cluster=~\"$ClusterName\",member=~\"$MemberName\"}) by (name) > 0"
    },
    {
     "expr": "(sum(vendor:coherence_service_thread_count{cluster=~\"$ClusterName\",member=~\"$MemberName\"}) by (name) - sum(vendor:coherence_service_thread_idle_count{cluster=~\"$ClusterName\",member=~\"$MemberName\"}) by (name)) / (sum(vendor:coherence_service_thread_count{cluster=~\"$ClusterName\",member=~\"$MemberName\"}) by (name)) "
    }
   ]
  },
  {
   "title": "Guardian Recoveries and Terminations",
   "type": "graph",
   "description": "The Guardian Recovery and Terminations over the current time range.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "idelta(vendor:coherence_node_guard_recover_count{cluster=~\"$ClusterName\", member=~\"$MemberName\"}[1m])  ",
     "legendFormat": "Guardian Recoveries"
    },
    {
     "expr": "idelta(vendor:coherence_node_guard_terminate_count{cluster=~\"$ClusterName\", member=~\"$MemberName\"}[1m])",
     "legendFormat": "Guardian Terminations"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "content": "<center><h3>Member Network Details</h3></center>"
  },
  {
   "title": "Packet  Anomalies",
   "type": "graph",
   "description": "Any packet anomalies such as packets resent/repeated, etc.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "idelta(vendor:coherence_node_packets_resent{cluster=~\"$ClusterName\", member=~\"$MemberName\"}[1m])",
     "legendFormat": "Resent"
    },
    {
     "expr": "idelta(vendor:coherence_node_packets_repeated{cluster=~\"$ClusterName\", member=~\"$MemberName\"}[1m])",
     "legendFormat": "Repeated"
    },
    {
     "expr": "idelta(vendor:coherence_node_nack_sent{cluster=~\"$ClusterName\", member=~\"$MemberName\"}[1m])",
     "legendFormat": "Nacks"
    },
    {
     "expr": "idelta(vendor:coherence_node_packets_resent_early{cluster=~\"$ClusterName\", member=~\"$MemberName\"}[1m])",
     "legendFormat": "Resent Early"
    },
    {
     "expr": "idelta(vendor:coherence_node_packets_resent_excess{cluster=~\"$ClusterName\", member=~\"$MemberName\"} [1m])",
     "legendFormat": "Resent Excess"
    }
   ]
  },
  {
   "title": "Network Anomalies",
   "type": "graph",
   "description": "Any network anomalies such as TCP ring failures or traffic jams.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "idelta(vendor:coherence_node_tcp_ring_failures{cluster=~\"$ClusterName\", member=~\"$MemberName\"} [1m])",
     "legendFormat": "TCP Ring Failures"
    },
    {
     "expr": "idelta(vendor:coherence_node_traffic_jam_count{cluster=~\"$ClusterName\", member=~\"$MemberName\"} [1m])",
     "legendFormat": "Traffic Jam Count"
    }
   ]
  },
  {
   "title": "Packet Send Rate / Second",
   "type": "graph",
   "description": "The rate at which packets are being sent from this member.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(vendor:coherence_node_packets_sent{cluster=~\"$ClusterName\", member=~\"$MemberName\"}[1m])  ",
     "legendFormat": "Packet Sent"
    }
   ]
  },
  {
   "title": "Packet Receive Rate / Second",
   "type": "graph",
   "description": "The rate at which packets are being received by this member.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(vendor:coherence_node_packets_received{cluster=~\"$ClusterName\", member=~\"$MemberName\"}[1m])",
     "legendFormat": "Packets Received"
    }
   ]
  },
  {
   "title": "Publisher Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_node_publisher_success_rate{cluster=~\"$ClusterName\", member=~\"$MemberName\"}"
    }
   ]
  },
  {
   "title": "Receiver Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_node_receiver_success_rate{cluster=~\"$ClusterName\", member=~\"$MemberName\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
   "content": "<center><h3>Memory and Garbage Collection</h3></center>"
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_platform_memory_heap_memory_usage_max{cluster=~\"$ClusterName\", member=~\"$MemberName\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "vendor:coherence_platform_memory_heap_memory_usage_used{cluster=~\"$ClusterName\", member=~\"$MemberName\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_platform_memory_non_heap_memory_usage_used{cluster=~\"$ClusterName\", member=~\"$MemberName\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor:coherence_platform_memory_non_heap_memory_usage_committed{cluster=~\"$ClusterName\", member=~\"$MemberName\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "graph",
   "description": "The  Garbage Collection Count (by type) over the current time range.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "idelta(vendor:coherence_platform_gc_collection_count{subType=\"GarbageCollector\", cluster=~\"$ClusterName\", member=~\"$MemberName\"}[1m]) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "idelta(vendor:coherence_platform_gc_collection_time{subType=\"GarbageCollector\", cluster=~\"$ClusterName\", member=~\"$MemberName\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}