{
 "title": "Proxy Server Detail Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor:coherence_cluster_size{cluster=~\"$ClusterName\"}, version)"
   },
   {
    "name": "ServiceName",
    "label": "Service Name",
    "query": "label_values(vendor:coherence_connection_manager_total_messages_sent{cluster=~\"$ClusterName\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Proxy Servers Details - $ServiceName</h3></center>"
  },
  {
   "title": "Proxy Server Members for $ServiceName",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_connection_manager_connection_count{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member, host_url)"
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_total_messages_received{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member, host_url)"
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_total_messages_sent{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member, host_url)"
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_total_bytes_received {cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member, host_url)"
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_total_bytes_sent{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member, host)"
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_outgoing_byte_backlog{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member, host)"
    },
    {
     "expr": "sum(vendor:coherence_connection_manager_unauthorized_connection_attempts{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member, host_url)"
    }
   ]
  },
  {
   "title": "Current Proxy Server Connections for $ServiceName",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(vendor:coherence_connection_connection_time_millis{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (remote_address, remote_port, member, node_id)"
    }
   ]
  },
  {
   "title": "Outgoing Byte Backlog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_connection_manager_outgoing_byte_backlog{cluster=~\"$ClusterName\", name=~\"$ServiceName\", protocol=~\"tcp\"} > 0",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Outgoing Message Backlog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_connection_manager_outgoing_message_backlog{cluster=~\"$ClusterName\", name=~\"$ServiceName\"} > 0",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Total Bytes Sent/ sec - $ServiceName",
   "type": "graph",
   "description": "Total bytes sent (bytes/sec) of all Proxy Server members for $ServiceName.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vendor:coherence_connection_manager_total_bytes_sent{cluster=~\"$ClusterName\",protocol=~\"tcp\", name=~\"$ServiceName\"}[1m])) by (member)",
     "legendFormat": "{{member}} Sent"
    }
   ]
  },
  {
   "title": "Total Bytes Received/ sec - $ServiceName",
   "type": "graph",
   "description": "Total bytes received (bytes/sec) of all Proxy Server members for $ServiceName.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vendor:coherence_connection_manager_total_bytes_received{cluster=~\"$ClusterName\",protocol=~\"tcp\"}[1m])) by (member)",
     "legendFormat": "{{member}} Received"
    }
   ]
  }
 ]
}