{
 "title": "Service Details Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "ServiceName",
    "label": "Service Name",
    "query": "label_values(vendor:coherence_service_member_count{cluster=~\"$ClusterName\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Service Details - $ServiceName</h3></center>"
  },
  {
   "title": "Member Service Threads",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_service_task_average_duration{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_service_request_average_duration{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_service_thread_count{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_service_thread_idle_count{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member)"
    },
    {
     "expr": "(sum(vendor:coherence_service_thread_count{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member) -sum(vendor:coherence_service_thread_idle_count{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member)) / (sum(vendor:coherence_service_thread_count{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member))"
    }
   ]
  },
  {
   "title": "Thread Utilization %",
   "type": "graph",
   "description": "Thread utilization across all members.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(vendor:coherence_service_thread_count{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member) -sum(vendor:coherence_service_thread_idle_count{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member)) / (sum(vendor:coherence_service_thread_count{cluster=~\"$ClusterName\",name=~\"$ServiceName\"}) by (member))",
     "legendFormat": " {{member}}"
    }
   ]
  },
  {
   "title": "Task Rate",
   "type": "graph",
   "description": "The rate of tasks for this service across all members.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(vendor:coherence_service_task_count{cluster=~\"$ClusterName\", name=~\"$ServiceName\"}[1m]) ",
     "legendFormat": " {{member}}"
    }
   ]
  },
  {
   "title": "Task Backlog",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_service_task_backlog{cluster=~\"$ClusterName\", name=~\"$ServiceName\"} > 0",
     "legendFormat": " {{member}}"
    }
   ]
  },
  {
   "title": "Request Pending Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_service_request_pending_count{cluster=~\"$ClusterName\", name=~\"$ServiceName\"}  ",
     "legendFormat": " {{member}}"
    }
   ]
  },
  {
   "title": "Request Pending Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_service_request_pending_duration{cluster=~\"$ClusterName\", name=~\"$ServiceName\"}  ",
     "legendFormat": " {{member}}"
    }
   ]
  },
  {
   "title": "Task Average Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_service_task_average_duration{cluster=~\"$ClusterName\", name=~\"$ServiceName\"}",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_service_request_average_duration{cluster=~\"$ClusterName\", name=~\"$ServiceName\"}",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 },
   "content": "<center><h3>Storage Details</h3></center>"
  },
  {
   "title": "Endangered Partitions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(vendor:coherence_service_partitions_endangered{cluster=~\"$ClusterName\",name=~\"$ServiceName\"})"
    }
   ]
  },
  {
   "title": "Vulnerable Partitions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(vendor:coherence_service_partitions_vulnerable{cluster=~\"$ClusterName\",name=~\"$ServiceName\"})  "
    }
   ]
  },
  {
   "title": "Unbalanced Partitions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(vendor:coherence_service_partitions_unbalanced{cluster=~\"$ClusterName\",name=~\"$ServiceName\"})"
    }
   ]
  },
  {
   "title": "Cache Memory",
   "type": "singlestat",
   "description": "Indicates memory utilized by the cache entries. \nNote: If the unit-calculator is not BINARY or the service is not a DistributedCache service, then the details may be incorrect.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 43 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_units_bytes{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\"}) "
    }
   ]
  },
  {
   "title": "Index Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 43 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vendor:coherence_storage_manager_index_total_units{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\"})"
    }
   ]
  },
  {
   "title": "Cache Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(vendor:coherence_cache_units_bytes{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\"}) by (name))"
    }
   ]
  },
  {
   "title": "Partition Status Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(vendor:coherence_service_partitions_endangered{cluster=~\"$ClusterName\", name=~\"$ServiceName\"})   ",
     "legendFormat": "Endangered  Partitions:"
    },
    {
     "expr": "avg(vendor:coherence_service_partitions_vulnerable{cluster=~\"$ClusterName\", name=~\"$ServiceName\"})  ",
     "legendFormat": "Vulnerable Partitions:"
    },
    {
     "expr": "avg(vendor:coherence_service_partitions_unbalanced{cluster=~\"$ClusterName\", name=~\"$ServiceName\"})",
     "legendFormat": "Unbalanced Partitions:"
    }
   ]
  },
  {
   "title": "Owned Primary and Backup Partitions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(vendor:coherence_service_owned_partitions_primary{cluster=~\"$ClusterName\", name=~\"$ServiceName\"})   ",
     "legendFormat": "Primary  Partitions:"
    },
    {
     "expr": "avg(vendor:coherence_service_owned_partitions_backup{cluster=~\"$ClusterName\", name=~\"$ServiceName\"})  ",
     "legendFormat": "Backup Partitions:"
    }
   ]
  },
  {
   "title": "Caches for Service $ServiceName",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_cache_units_bytes{cluster=~\"$ClusterName\",coherence_service=~\"$ServiceName\"}) by (name)  "
    },
    {
     "expr": "sum(vendor:coherence_cache_size{cluster=~\"$ClusterName\", coherence_service=~\"$ServiceName\"}) by (name)"
    },
    {
     "expr": "sum(vendor:coherence_cache_total_gets{cluster=~\"$ClusterName\", coherence_service=~\"$ServiceName\"}) by (name)"
    },
    {
     "expr": "sum(vendor:coherence_cache_total_puts{cluster=~\"$ClusterName\", coherence_service=~\"$ServiceName\"}) by (name)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 64 },
   "content": "<center><h3>Persistence Details</h3></center>"
  },
  {
   "title": "Persistence Details across Members",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_service_persistence_active_space_used{cluster=~\"$ClusterName\", name=~\"$ServiceName\"}) by (member)"
    },
    {
     "expr": "sum(vendor:coherence_service_persistence_latency_average{cluster=~\"$ClusterName\", name=~\"$ServiceName\"}) by (member) > 0"
    },
    {
     "expr": "sum(vendor:coherence_service_persistence_latency_max{cluster=~\"$ClusterName\", name=~\"$ServiceName\"}) by (member)"
    }
   ]
  }
 ]
}