///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2024, 2025 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Dual Stack Networking
:description: Coherence Operator Documentation - Dual Stack Networking
:keywords: oracle coherence, kubernetes, operator, networking, dual stack

== Dual Stack Networking

This section describes using Coherence and the Operator with a dual stack Kubernetes cluster,
where Pods and Services can have both IPv4 and IPv6 interfaces.

[NOTE]
====
This section only really applies to making Coherence bind to the correct local IP address for inter-cluster communication.
Normally for other Coherence endpoints, such as Extend, gRPC, management, metrics, etc. Coherence will bind to all
local addresses ubless specifically configured otherwise.
This means that in and environment such as dual-stack Kubernetes where a Pod has both an IPv4 and IPv6
address, those Coherence endpoints will be reachable using either the IPv4 or IPv6 address of the Pod.
====

Normally, using Coherence on a dual-stack server can cause issues due to the way that Coherence decides which local IP
address to use for inter-cluster communication. Similar problems can occur on any server that multiple IP addresses.
When Coherence is configured to use well known addressing for cluster discovery, a Coherence JVM will choose a local
address that is either in the WKA list, or is on an interface that can route to the WKA addresses.
In a dual stack environment the problem comes when an interface has both IPv4 and IPv6 addresses and Coherence is
inconsistent about which one to choose.

There are a few simple ways to fix this:

* Set the JVM system property `java.net.preferIPv4Stack=true` or `java.net.preferIPv6Addresses=true` to set the Coherence
JVM to use the desired stack. If application code requires both stacks to be available though, this is not a good option.

* Configure the WKA list to be only IPv4 addresses or IPv6 addresses. Coherence will then choose a matching local address.

* Set the `coherence.localhost` system property (or `COHERENCE_LOCALHOST` environment variable) to the IP address
that Coherence should bind to. In a dual stack environment choose either the IPv4 address or IPv6 address and make sure
that the corresponding addresses are used in the WKA list.

=== Dual Stack Kubernetes Clusters

In a dual-stack Kubernetes cluster, Pods will have both an IPv4 and IPv6 address.
These can be seen by looking at the status section of a Pod spec:

[source,yaml]
----
  podIP: 10.244.3.3
  podIPs:
  - ip: 10.244.3.3
  - ip: fd00:10:244:3::3
----

The status section will have a `podIP` field, which is the Pods primary address.
There is also an array of the dual-stack addresses in the `podIPs` field.
The first address in `podIPs` is always the same as `podIP` and is usually the IPv4 address.

A Service in a dual-stack cluster can have a single IP family or multiple IP families configured in its spec.
The Operator will work out of the box if the default IP families configuration for Services is single stack, either IPv4 or IPv6.
When the WKA Service is created it will only be populated with one type of address, and Coherence will bind to the correct type.

In Kubernetes clusters where the WKA service has multiple IP families by default, there are a few options to fix this:

* Set the JVM system property `java.net.preferIPv4Stack=true` or `java.net.preferIPv6Addresses=true` to set the Coherence
JVM to use the desired stack. If application code requires both stacks to be available though, this is not a good option.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  replicas: 3
  jvm:
    args:
      - "java.net.preferIPv4Stack=true"
----

* The `COHERENCE_LOCALHOST` environment variable can be configured to be the Pods IP address.
Typically, this will be the IPv4 address.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  replicas: 3
  env:
    - name: COHERENCE_LOCALHOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
----

* Since Operator 3.5.4 it is possible to configure the IP family for the WKA Service. The `spec.coherence.wka.ipFamily`
field can be set to either "IPv4" or "IPv6". This will cause Coherence to bind to the relevant IP address type.

For example, the yaml below will cause Coherence to bind to the IPv6 address.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  replicas: 3
  coherence:
    wka:
      ipFamily: IPv6
----

Since Operator 3.5.4 it is also possible to configure the IP families used by the headless service created for the StatefulSet
if this is required.

The yaml below will configure WKA to use only IPv6, the headless Service created for the StatefulSet will be
a dual-stack, IPv4 and IPv6 service.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  replicas: 3
  headlessServiceIpFamilies:
    - IPv4
    - IPv6
  coherence:
    wka:
      ipFamily: IPv6
----

The yaml below will configure both WKA and the headless Service created for the StatefulSet to use a single stack IPv6.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
spec:
  replicas: 3
  headlessServiceIpFamilies:
    - IPv6
  coherence:
    wka:
      ipFamily: IPv6
----

=== Dual Stack Kubernetes Clusters Without Using the Operator

If not using the Coherence Operator to manage clusters the same techniques described above can be used to
manually configure Coherence to work correctly.

The simplest option is to ensure that the headless service used for well known addressing is configured to be single stack.
For example, the yaml below configures the service `storage-sts` to be a single stack IPv6 service.

[source,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: storage-sts
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
----

If for some reason it is not possible to ise a dedicated single stack service for WKA, then the `COHERENCE_LOCALHOST`
environment variable can be set in the Pod to be the Pod IP address.

[source,yaml]
----
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage
spec:
  template:
    spec:
      containers:
        - name: coherence
          env:
            - name: COHERENCE_LOCALHOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
----

