apiVersion: v1
appVersion: 1.5.0
description: Install kube-state-metrics to generate and expose cluster-level metrics
home: https://github.com/kubernetes/kube-state-metrics/
keywords:
- metric
- monitoring
- prometheus
maintainers:
- email: jose@armesto.net
  name: fiunchinho
name: kube-state-metrics
sources:
- https://github.com/kubernetes/kube-state-metrics/
version: 1.1.0
