#  Copyright (c) 2021, Oracle and/or its affiliates.
#  Licensed under the Universal Permissive License v 1.0 as shown at
#  http://oss.oracle.com/licenses/upl.
#
apiVersion: v1
kind: Namespace
metadata:
  name: coherence-example
---
apiVersion: v1
kind: Secret
metadata:
  name: coherence-webhook-server-cert
  namespace: coherence-example
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    control-plane: coherence
  name: coherence-operator-coherence-operator
  namespace: coherence-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    control-plane: coherence
  name: coherence-operator-crd-webhook-install-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: coherence-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - pods
  - pods/exec
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coherence.oracle.com
  resources:
  - coherence
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coherence.oracle.com
  resources:
  - coherence/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    control-plane: coherence
  name: coherence-operator-node-viewer-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    control-plane: coherence
  name: coherence-operator-crd-webhook-install-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coherence-operator-crd-webhook-install-role
subjects:
- kind: ServiceAccount
  name: coherence-operator-coherence-operator
  namespace: coherence-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    control-plane: coherence
  name: coherence-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coherence-operator-manager-role
subjects:
- kind: ServiceAccount
  name: coherence-operator-coherence-operator
  namespace: coherence-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    control-plane: coherence
  name: coherence-operator-node-viewer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coherence-operator-node-viewer-role
subjects:
- kind: ServiceAccount
  name: coherence-operator-coherence-operator
  namespace: coherence-example
---
apiVersion: v1
data:
  COHERENCE_IMAGE: oraclecoherence/coherence-ce:20.12.1
  UTILS_IMAGE:  ghcr.io/oracle/coherence-operator:3.1.5-utils
kind: ConfigMap
metadata:
  name: coherence-operator-env-vars-m9fcm287df
  namespace: coherence-example
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: coherence
  name: coherence-operator-webhook-service
  namespace: coherence-example
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: coherence
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: coherence
  name: coherence-operator-controller-manager
  namespace: coherence-example
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: coherence
  template:
    metadata:
      labels:
        control-plane: coherence
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WEBHOOK_SERVICE
          value: coherence-operator-webhook-service
        - name: WEBHOOK_SECRET
          value: coherence-webhook-server-cert
        envFrom:
        - configMapRef:
            name: coherence-operator-env-vars-m9fcm287df
            optional: true
        image:  ghcr.io/oracle/coherence-operator:3.1.5
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8080
          name: metrics-server
          protocol: TCP
        - containerPort: 8088
          name: health-server
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: metrics-server
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      serviceAccountName: coherence-operator-coherence-operator
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          optional: true
          secretName: coherence-webhook-server-cert
