== Coherence Operator Federation Example

This simple example demostrates the Coherence federation feature.  It shows how to deploy two Coherence clusters that federating data between them using the Coherence Operator. The Coherence federation feature requires Coherence Grid Edition.

You can find the source code in the https://github.com/oracle/coherence-operator/tree/master/examples/federation[Operator GitHub Repo].

* <<pre,Prerequisites>>
* <<build, Build the Example>>
* <<example, Run the Example>>
* <<cleanup, Cleaning Up>>

[#pre]
== Prerequisites

Following the instructions in https://github.com/oracle/coherence-operator/tree/master/examples/deployment[Coherence Operator Deployment Example] for all the prerequisites and installing the Coherence Operator. 

Confirm the operator is running, for example:
[source,bash]
----
kubectl get pods -n coherence-example

NAME                                                     READY   STATUS    RESTARTS   AGE
coherence-operator-controller-manager-74d49cd9f9-sgzjr   1/1     Running   1          27s
----

[#build]
== Build the Example

This example exists in the `examples/federation` directory in the
https://github.com/oracle/coherence-operator[Coherence Operator GitHub repository].  It depends on Coherence version 14.1.1-0-3, but any Coherence version 12.2.1.4 or above will work. To change the Coherence version, just modify the <coherence.version> in the pom.xml. It also demonstrates how to use a secret to store Coherence configuration files, map the secret to a volumn, and add it to the classpath. However, it is not necessary for this example since the configuration files are in the federation-example docker image.  

To build the example, 

[source,bash]
----
cd coherence-operator/examples/federation

./mvnw package jib:dockerBuild
----

This will result in the following Docker image being created which contains the configuration and server-side artifacts, including Coherence jar files, to be use by the deployment.

[source]
----
federation-example:1.0.0
----

[NOTE]
====
If you are running against a remote Kubernetes cluster, you need to tag and
push the Docker image to your repository accessible to that cluster.
You also need to prefix the image name in the `yaml` files below.
====

[#example]
== Run the Example

Ensure you are in the `examples/federation` directory to run the example. This example uses the yaml files `src/main/yaml/primary-cluster.yaml` and `src/main/yaml/secondary-cluster.yaml`, which
define a primary cluster and a secondary cluster with a single role `storage` to store cluster data.

NOTE: If you have pushed your Docker image to a remote repository, ensure you update the above file to prefix the image.

==== 1. Create a secret for Coherence configuration files 

Run the following command to create a secret named storage-config to store the Coherence configuration files:

[source,bash]
----
kubectl create secret generic storage-config -n coherence-example \
    --from-file=src/main/resources/tangosol-coherence-override.xml \
    --from-file=src/main/resources/storage-cache-config.xml \
    --from-file=src/main/resources/storage-pof-config.xml
----

==== 2. Install the Coherence clusters `storage` role
Run the following commands to create the primary and secondary clusters:

[source,bash]
----
kubectl -n coherence-example create -f src/main/yaml/primary-cluster.yaml

coherence.coherence.oracle.com/primary-cluster-storage created
----

[source,bash]
----
kubectl -n coherence-example create -f src/main/yaml/secondary-cluster.yaml

coherence.coherence.oracle.com/secondary-cluster-storage created
----


==== 3. List the created Coherence clusters
Run the following command to list the clusters:

[source,bash]
----
kubectl -n coherence-example get coherence

NAME                        CLUSTER             ROLE      REPLICAS   READY   PHASE
primary-cluster-storage     primary-cluster     storage   2          2       Ready
secondary-cluster-storage   secondary-cluster   storage   2          2       Ready
----

To see the Coherence cache configuration file loaded from the secret volumn we defined, run the following command:

[source,bash]
----
kubectl logs -n coherence-example primary-cluster-storage-0 | grep "Loaded cache"

... Oracle Coherence GE 14.1.1.0.3 <Info> (thread=main, member=n/a): Loaded cache configuration from "file:/config/storage-cache-config.xml"
----

==== 4. View the running pods

Run the following command to view the Pods:
[source,bash]
----
kubectl -n coherence-example get pods
----

[source,bash]
----
NAME                                                    READY   STATUS    RESTARTS   AGE
coherence-operator-controller-manager-bfcd76786-bzm6h   1/1     Running   6          1h
primary-cluster-storage-0                               1/1     Running   0          1h
primary-cluster-storage-1                               1/1     Running   0          1h
secondary-cluster-storage-0                             1/1     Running   0          1h
secondary-cluster-storage-1                             1/1     Running   0          1h
----

==== 5. Connect to the Coherence Console inside the primary cluster to add data

We will connect via Coherence console to add some data using the following commands:

[source,bash]
----
kubectl exec -it -n coherence-example primary-cluster-storage-0 /coherence-operator/utils/runner console
----

At the prompt type the following to create a cache called `test`:

[source,bash]
----
cache test
----

Use the following to add an entry with "primarykey" and "primaryvalue":

[source,bash]
----
put "primarykey" "primaryvalue"
null
----

Use the following to create 10,000 entries of 100 bytes:
[source,bash]
----
bulkput 10000 100 0 100
----

Lastly issue the command `size` to verify the cache entry count. It should be 10001.

Type `bye` to exit the console.

==== 6. Connect to the Coherence Console inside the secondary cluster to verify that data is federated from primary cluster

We will connect via Coherence console to confirm that the data we added to the primary cluster is federated to the secondary cluster.

[source,bash]
----
kubectl exec -it -n coherence-example secondary-cluster-storage-0 /coherence-operator/utils/runner console
----

At the prompt type the following to set the cache to `test`:

[source,bash]
----
cache test
----

Use the following to get entry with "primarykey":

[source,bash]
----
get "primarykey"
primaryvalue
----

Issue the command `size` to verify the cache entry count. It should be 10001.

Our federation has Active/Active topology. So, the data changes in both primary and secondary clusters are federated between the clusters. Use the following to add an entry with "secondarykey" and "secondaryvalue":
[source,bash]
----
put "secondarykey" "secondaryvalue"
null
----

==== 7. Confirm the primary cluster also received "secondarykey", "secondaryvalue" entry 

Follow the command in the previous section to connect to the Coherence Console inside the primary cluster.

Use the following command to confirm that entry with "secondarykey" is federated to primary cluster:

[source,bash]
----
get "secondarykey"
secondaryvalue
----

[#cleanup]
== Cleaning up

Use the following commands to delete the primary and secondary clusters: 

[source,bash]
----
kubectl -n coherence-example delete -f src/main/yaml/primary-cluster.yaml

kubectl -n coherence-example delete -f src/main/yaml/secondary-cluster.yaml
----

