apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-keystore
spec:
  secretName: coherence-server-certs
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS1
  usages:
    - digital signature
    - key encipherment
    - client auth
    - server auth
  commonName: Coherence Certs
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: password-key
        name: server-keystore-secret
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
