///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Metrics
:keywords: oracle coherence, kubernetes, operator, Metrics

== Metrics

[PILLARS]
====
[CARD]
.Enabling Metrics
[link=metrics/020_metrics.adoc]
--
Deploying Coherence clusters with metrics enabled.
--

[CARD]
.Enabling SSL
[link=metrics/030_ssl.adoc]
--
Enabling SSL for metrics capture.
--

[CARD]
.Using Your Own Prometheus
[link=metrics/040_scraping.adoc]
--
Scraping metrics from your own Prometheus instance.
--

[CARD]
.Grafana Dashboards
[link=metrics/050_dashboards.adoc]
--
Details on the Grafana Dashboards available.
--

====

