///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Publish Metrics

== Publish Metrics

Since version 12.2.1.4 Coherence has had the ability to expose a http endpoint that can be used to scrape metrics.
This would typically be used to expose metrics to something like Prometheus.

NOTE: The metrics endpoint is *disabled* by default in Coherence clusters but can be enabled and configured by
setting the relevant fields in the `Coherence` CRD.

The example below shows how to enable and access Coherence metrics.

Once the metrics port has been exposed, for example via a load balancer or port-forward command, the metrics
endpoint is available at `http://host:port/metrics`.

See the https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/manage/using-coherence-metrics.html[Using Coherence Metrics]
documentation for full details on the available metrics.

NOTE: Note: Use of metrics is available only when using the operator with clusters running Coherence 12.2.1.4 or later version.

=== Deploy Coherence with Metrics Enabled

To deploy a `Coherence` resource with metrics enabled and exposed on a port, the simplest yaml
would look like this:

[source,yaml]
.metrics-cluster.yaml
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: metrics-cluster
spec:
  coherence:
    metrics:
      enabled: true     # <1>
  ports:
    - name: metrics  # <2>
----
<1> Setting the `coherence.metrics.enabled` field to `true` will enable metrics
<2> To expose metrics via a `Service` it is added to the `ports` list.
The `metrics` port is a special case where the `port` number is optional so in this case metrics
will bind to the default port `9612`.
(see <<ports/020_container_ports.adoc,Exposing Ports>> for details)

To expose metrics on a different port the alternative port value can be set in the `coherence.metrics`
section, for example:
[source,yaml]
.metrics-cluster.yaml
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: metrics-cluster
spec:
  coherence:
    metrics:
      enabled: true
      port: 8080      # <1>
  ports:
    - name: metrics
----
<1> metrics will now be exposed on port `8080`


=== Port-forward the Metrics Port

After installing the basic `metrics-cluster.yaml` from the first example above there would be a three member
Coherence cluster installed into Kubernetes.

For example, the cluster can be installed with `kubectl`
[source,bash]
----
kubectl -n coherence-test create -f metrics-cluster.yaml

coherence.coherence.oracle.com/metrics-cluster created
----

The `kubectl` CLI can be used to list `Pods` for the cluster:
[source,bash]
----
kubectl -n coherence-test get pod -l coherenceCluster=metrics-cluster

NAME                   READY   STATUS    RESTARTS   AGE
metrics-cluster-0   1/1     Running   0          36s
metrics-cluster-1   1/1     Running   0          36s
metrics-cluster-2   1/1     Running   0          36s
----

In a test or development environment the simplest way to reach an exposed port is to use the `kubectl port-forward` command.
For example to connect to the first `Pod` in the deployment:
[source,bash]
----
kubectl -n coherence-test port-forward metrics-cluster-0 9612:9612

Forwarding from [::1]:9612 -> 9612
Forwarding from 127.0.0.1:9612 -> 9612
----

=== Access the Metrics Endpoint
Now that a port has been forwarded from localhost to a `Pod` in the cluster the metrics endpoint can be accessed.

Issue the following `curl` command to access the REST endpoint:
[source,bash]
----
curl http://127.0.0.1:9612/metrics
----

== Prometheus Service Monitor

The operator can create a Prometheus `ServiceMonitor` for the metrics port so that Prometheus will automatically
scrape metrics from the `Pods` in a `Coherence` deployment.

[source,yaml]
.metrics-cluster.yaml
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: metrics-cluster
spec:
  coherence:
    metrics:
      enabled: true
  ports:
    - name: metrics
      serviceMonitor:
        enabled: true  # <1>
----
<1> The `serviceMonitor.enabled` field is set to `true` for the `metrics` port.

See <<ports/040_servicemonitors.adoc,Exposing ports and Services - Service Monitors>> documentation for more details.
