///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2021, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Coherence Grafana Dashboards

The Operator has a set of Coherence specific Grafana dashboards that can be imported into a Grafana instance.

== Download the Coherence Dashboards

The Coherence Operator provides a set of dashboards for Coherence that may be imported into Grafana.
There are two ways to obtain the dashboards:

* Clone the Coherence Operator GitHub repo, checkout the branch or tag for the version you want to use and
then obtain the dashboards from the `dashboards/` directory.

* Download the `.tar.gz` dashboards package for the release you want to use.

[source,bash]
----
curl https://oracle.github.io/coherence-operator/dashboards/latest/coherence-dashboards.tar.gz \
    -o coherence-dashboards.tar.gz
tar -zxvf coherence-dashboards.tar.gz
----

The above commands will download the `coherence-dashboards.tar.gz` file and unpack it resulting in a
directory named `dashboards/` in the current working directory. This `dashboards/` directory will contain
the various Coherence dashboard files.


== Import the Dashboards into Grafana.

This example shows you how to import the Grafana dashboards into your own Grafana instance.

The latest Coherence dashboards can be downloaded from the https://github.com/oracle/coherence-operator/raw/gh-pages/dashboards/latest/coherence-dashboards.tar.gz[Coherence Operator GitHub repo]
in a `.tar.gz` file.

e.g.
[source,bash]
----
curl -Lo coherence-dashboards.tar.gz https://github.com/oracle/coherence-operator/raw/gh-pages/dashboards/latest/coherence-dashboards.tar.gz
tar -xvf coherence-dashboards.tar.gz
----

This will result in a directory named `dashboards` containing the different types of Coherence dashboards available.
The Grafana dashboard `.json` files will be in the `dashboards/grafana/` subdirectory

[IMPORTANT]
====
By default, the Coherence dashboards require a datasource in Grafana named `prometheus` (which is case-sensitive).
This datasource usually exists in an out-of-the-box Prometheus Operator installation.
If your Grafana environment does not have this datasource, then there are two choices.

* Create a Prometheus datasource named `prometheus` as described in the https://grafana.com/docs/grafana/latest/datasources/add-a-data-source/[Grafana Add a Datasource] documentation.

* If you have an existing Prometheus datasource with a different name then you will need to edit the dashboard json
files to change all occurrences of `"datasource": "prometheus"` to have the name of your Prometheus datasource.
For example, running the script below in the directory containing the datasource `.json` files to be imported will
change the datasource name from `prometheus` to `Coherence-Prometheus`.
[source,bash]
----
for file in *.json
do
    sed -i '' -e 's/"datasource": "prometheus"/"datasource": "Coherence-Prometheus"/g' $file;
done
----
====

=== Manually Import Grafana Dashboards

The dashboard `.json` files can be manually imported into Grafana using the Grafana UI following the instructions
in the https://grafana.com/docs/grafana/latest/dashboards/export-import/#import-dashboard[Grafana Import Dashboard]
documentation.

=== Bulk Import Grafana Dashboards

At the time of writing, for whatever reason, Grafana does not provide a simple way to bulk import a set of dashboard files.
There are many examples and scripts on available in the community that show how to do this.
The Coherence Operator source contains a script that can be used for this purpose
https://github.com/oracle/coherence-operator/raw/master/hack/grafana-import.sh[grafana-import.sh]

The commands below will download and run the shell script to import the dashboards.
Change the `<GRAFANA-USER>` and `<GRAFANA_PWD>` to the Grafana credentials for your environment.
For example if using the default Prometheus Operator installation they are as specified on the
https://prometheus-operator.dev/docs/prologue/quick-start/#access-grafana[Access Grafana section of the Quick Start] page.
We do not document the credentials here as the default values have been known to change between Prometheus Operator and Grafana versions.

[source,bash]
----
curl -Lo grafana-import.sh https://github.com/oracle/coherence-operator/raw/master/hack/grafana-import.sh
chmod +x grafana-import.sh
./grafana-import.sh -u <GRAFANA-USER> -w <GRAFANA_PWD> -p dashboards/grafana -t localhost:3000
----

Coherence clusters can now be created as described in the <<metrics/020_metrics.adoc,Publish Metrics>>
page, and metrics will eventually appear in Prometheus and Grafana. It can sometimes take a minute or so for
Prometheus to start scraping metrics and for them to appear in Grafana.
