///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2025, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Import the Grafana Dashboards
:description: Coherence Operator Documentation - Import the Grafana Dashboards
:keywords: oracle coherence, kubernetes, operator, metrics, grafana, dashboards, import


== Importing the Coherence Dashboards

The Coherence Operator provides a set of dashboards for Coherence that may be imported into Grafana.
The Coherence dashboards are explained in detail on the <<docs/metrics/040_dashboards.adoc,Coherence Grafana Dashboards>> page.

There are two ways to obtain the dashboards:

1 - Download the `.tar.gz` dashboards package for the release you want to use.

[source,bash]
----
curl https://github.com/oracle/coherence-operator/releases/download/v3.5.4/coherence-dashboards.tar.gz \
    -Lo coherence-dashboards.tar.gz
tar -zxvf coherence-dashboards.tar.gz
----

The above commands will download the `coherence-dashboards.tar.gz` file and unpack it resulting in a
directory named `dashboards/` in the current working directory. This `dashboards/` directory will contain
the various Coherence dashboard files.


2 - Clone the Coherence Operator GitHub repo, checkout the branch or tag for the version you want to use and
then obtain the dashboards from the `dashboards/` directory.

NOTE: The dashboards have been built using Grafana `10.0.13` and as such this is the minimum version required for this release.
If you have an older Grafana installation, you can use previous versions of the dashboard.s

== Import the Dashboards into Grafana.

This section shows you how to import the Grafana dashboards into your own Grafana instance.
Once you have obtained the dashboards using one of the methods above, the Grafana dashboard `.json` files will be in the `dashboards/grafana/` subdirectory

[IMPORTANT]
====
By default, the Coherence dashboards require a datasource in Grafana named `prometheus` (which is case-sensitive).
This datasource usually exists in an out-of-the-box Prometheus Operator installation.
If your Grafana environment does not have this datasource, then there are two choices.

* Create a Prometheus datasource named `prometheus` as described in the https://grafana.com/docs/grafana/latest/datasources/add-a-data-source/[Grafana Add a Datasource] documentation and make this the default datasource.

* If you have an existing Prometheus datasource with a different name then you will need to edit the dashboard json
files to change all occurrences of `"datasource": "prometheus"` to have the name of your Prometheus datasource.
For example, running the script below in the directory containing the datasource `.json` files to be imported will
change the datasource name from `prometheus` to `Coherence-Prometheus`.
[source,bash]
----
for file in *.json
do
    sed -i '' -e 's/"datasource": "prometheus"/"datasource": "Coherence-Prometheus"/g' $file;
done
----

The above sed command works for MacOS, but if you are running on Linux you need to remove the `''` after the `-i`.

====

=== Manually Import Grafana Dashboards

The dashboard `.json` files can be manually imported into Grafana using the Grafana UI following the instructions
in the
https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/import-dashboards/[Grafana Import Dashboards]
documentation.

=== Bulk Import Grafana Dashboards

At the time of writing, for whatever reason, Grafana does not provide a simple way to bulk import a set of dashboard files.
There are many examples and scripts on available in the community that show how to do this.
The Coherence Operator source contains a script that can be used for this purpose
https://github.com/oracle/coherence-operator/raw/main/hack/grafana/grafana-import.sh[grafana-import.sh]

NOTE: The `grafana-import.sh` script requires the https://stedolan.github.io/jq/[JQ] utility to parse json.

The commands below will download and run the shell script to import the dashboards.
Change the `<GRAFANA-USER>` and `<GRAFANA_PWD>` to the Grafana credentials for your environment.
For example if using the default Prometheus Operator installation they are as specified on the
https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/access-ui.md[Access Grafana section of the Quick Start] page.
We do not document the credentials here as the default values have been known to change between Prometheus Operator and Grafana versions.

[source,bash]
----
curl -Lo grafana-import.sh https://github.com/oracle/coherence-operator/raw/main/hack/grafana/grafana-import.sh
chmod +x grafana-import.sh
----
[source,bash]
----
./grafana-import.sh -u <GRAFANA-USER> -w <GRAFANA_PWD> -d dashboards/grafana -t localhost:3000
----
Note: the command above assumes you can reach Grafana on `localhost:3000` (for example, if you have a kubectl port forward process
running to forward localhost:3000 to the Grafana service in Kubernetes). You may need to change the host and port to match however
you are exposing your Grafana instance.

Coherence clusters can now be created as described in the <<docs/metrics/020_metrics.adoc,Publish Metrics>>
page, and metrics will eventually appear in Prometheus and Grafana. It can sometimes take a minute or so for
Prometheus to start scraping metrics and for them to appear in Grafana.
