///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Overview

== Overview

Almost every application deployed into a Kubernetes cluster needs to communicate with other processes to provide services
to other processes or consume services to other processes. This is achieved by exposing ports on containers in `Pods` and
optionally exposing those same ports using `Services` and ingress.
The `CoherenceDeployment` spec makes it simple to add ports to the Coherence container and configure `Services` to
expose those ports.

Each additional port configured is exposed via its own `Service`.

If the configuration of `Services` for ports provided by the `CoherenceDeployment` spec is not sufficient or cannot
provide the required `Service` configuration then it is always possible to just create your own `Services` in Kubernetes.

=== Guides to Adding and Exposing Ports


[PILLARS]
====
[CARD]
.Adding Ports
[link=expose_ports_and_services/020_container_ports.adoc]
--
Adding additional container ports to the Coherence container.
--

[CARD]
.Expose Ports via Services
[link=expose_ports_and_services/030_services.adoc]
--
Configuring Services used to expose ports.
--

[CARD]
.Prometheus ServiceMonitors
[link=expose_ports_and_services/040_servicemonitors.adoc]
--
Adding Prometheus ServiceMonitors to expose ports to be scraped for metrics.
--
====

