///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Introduction

== Introduction

Almost every application deployed into a Kubernetes cluster needs to communicate with other processes to provide services
to other processes or consume services to other processes. This is achieved by exposing ports on containers in `Pods` and
optionally exposing those same ports using `Services` and ingress.
The `CoherenceDeployment` spec makes it simple to add ports to the Coherence container and configure `Services` to
expose those ports.

If the configuration of `Services` for ports provided by the `CoherenceDeployment` spec is not sufficient or cannot
provide the required `Service` configuration then it is alway possible to just create your own `Services` in Kubernetes.

