///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Coherence Operator documentation
:keywords: oracle coherence, kubernetes, operator, documentation

== Get going

[PILLARS]
====
[CARD]
.Quick Start
[icon=settings,link=guides/020_quickstart.adoc]
--
Quick start guide to running your first Coherence cluster using the Coherence Operator.
--

[CARD]
.Install
[icon=settings,link=install/01_introduction.adoc]
--
Installing and running the Coherence Operator.
--

[CARD]
.Guides
[icon=explore,link=guides/010_overview.adoc]
--
Follow step-by-step guides to using the Coherence Operator to manage Coherence clusters.
--
====


== In Depth

[PILLARS]
====

[CARD]
.Coherence Clusters
[icon=widgets,link=clusters/01_introduction.adoc]
--
In depth CoherenceCluster CRD documentation.
--

[CARD]
.Developer
[icon=build,link=developer/01_introduction.adoc]
--
Developer guide for building the Coherence Operator.
--
====
