///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2020 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Coherence Operator documentation
:keywords: oracle coherence, kubernetes, operator, documentation

== Get Going

[PILLARS]
====
[CARD]
.Quick Start
[icon=fa-rocket,link=about/03_quickstart.adoc]
--
Quick start guide to running your first Coherence cluster using the Coherence Operator.
--

[CARD]
.Install
[icon=fa-save,link=install/01_installation.adoc]
--
Installing and running the Coherence Operator.
--

[CARD]
.Build and Deploy Applications
[icon=cloud_upload,link=deploy_applications/010_overview.adoc]
--
Deploying Coherence Applications using the Coherence Operator.
--

====


== In Depth

[PILLARS]
====

[CARD]
.Metrics
[icon=av_timer,link=metrics/010_overview.adoc]
--
Enabling and working with Metrics in the Coherence Operator.
--

[CARD]
.Management and Diagnostics
[icon="fa-stethoscope",link=management/010_overview.adoc]
--
Management and Diagnostics in the Coherence Operator.
--

[CARD]
.Logging
[icon=find_in_page,link=logging/010_overview.adoc]
--
Viewing and managing log files within using the Coherence Operator.
--

[CARD]
.CoherenceDeployment CRD Reference
[icon=widgets,link=about/04_coherencedepoyment.adoc]
--
CoherenceDeployment CRD reference guide.
--

====
