///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Coherence Operator documentation
:keywords: oracle coherence, kubernetes, operator, documentation

== Get Going

[PILLARS]
====
[CARD]
.Quick Start
[icon=fa-rocket,link=about/04_quickstart.adoc]
--
Quick start guide to running your first Coherence cluster using the Coherence Operator.
--

[CARD]
.Install
[icon=settings,link=install/01_introduction.adoc]
--
Installing and running the Coherence Operator.
--

[CARD]
.Application Deployments
[icon=extension,link=app-deployments/010_overview.adoc]
--
Deploying Coherence Applications using the Coherence Operator.
--

[CARD]
.Examples
[icon=list,link=examples/010_overview.adoc]
--
Step-by-step examples with code for various tasks with the Coherence Operator.
--

====


== In Depth

[PILLARS]
====

[CARD]
.Coherence Clusters
[icon=widgets,link=clusters/01_introduction.adoc]
--
In depth CoherenceCluster CRD documentation.
--

[CARD]
.Developer
[icon=build,link=developer/01_introduction.adoc]
--
Developer guide for building the Coherence Operator.
--

[CARD]
.Metrics
[icon=av_timer,link=metrics/010_overview.adoc]
--
Enabling and working with Metrics in the Coherence Operator.
--

[CARD]
.Logging
[icon=donut_large,link=logging/010_overview.adoc]
--
Viewing and managing log files within using the Coherence Operator.
--

[CARD]
.Management Over ReST
[icon=cloud,link=management/010_overview.adoc]
--
Enabling and using Management Over ReST in the Coherence Operator.


--
[CARD]
.Diagnostic Tools
[icon=favorite_outline,link=diagnostics/010_overview.adoc]
--
Tools to Diagnose issues with Coherence Clusters in the Coherence Operator.
--

====
