///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Coherence Operator Concepts

== What is the Coherence Operator
The Coherence Operator is a https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Kubernetes Operator] that
is used to manage https://docs.oracle.com/middleware/12213/coherence/[Oracle Coherence] clusters in Kubernetes.
The Coherence Operator takes on the tasks of that human Dev Ops resource might carry out when managing Coherence clusters,
such as configuration, installation, safe scaling, management and metrics.

The Coherence Operator is a Go based application built using the https://github.com/operator-framework/operator-sdk[Operator SDK].
It is distributed as a Docker image and Helm chart for easy installation and configuration.


== Coherence Clusters
Traditionally a Coherence cluster is a number of distributed JVMs that communicate to form a single coherent cluster. 
In Kubernetes this concept still applies but can now be though of as a number of Pods that form a single cluster. 
Inside each `Pod` is a JVM running Coherence, or some custom application using Coherence.

The Coherence Operator uses a Kubernetes Custom Resource Definition to represent a Coherence cluster
(and the roles withing it, see below). Every field in the `CoherenceCluster` crd `Spec` is optional so a cluster
can be defined by yaml as simple as this:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster # <1>
----

<1> The `metadata.name` field in the `CoherenceCluster` will be used as the Coherence cluster name and would obviously
be unique in a given k8s namespace.

The Coherence Operator will use default values for fields that have not been entered, so the above yaml will create
a Coherence cluster made up of a `StatefulSet` with a replica count of 3, so there will be three storage enabled
Coherence `Pods`.
   


== Coherence Roles
A Coherence cluster can be made up of a number of Pods that perform different roles. All of the Pods in a given role
share the same configuration. At a bare minimum a cluster would have at least one role where Pods are storage enabled.

Each role in a Coherence cluster has a name and configuration. A cluster can have zero or many roles defined in the 
`CoherenceCluster` crd `Spec`. It is possible to define common configuration shared by all roles to save duplicating
configuration multiple times in the yaml.

The Coherence Operator will create a `StatefulSet` for each role defined in the `CoherenceCluster` crd yaml.
This separation allows roles to be managed and scaled independently from each other.


As described above the minimal yaml to define a CoherenceCluster is:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster
----

Although there are no roles described in this yaml the Coherence Operator will create a default role with the name
`storage` and give it a replica count of three. 

There are two ways to describe the specification of a role in a `CoherenceCluster` crd depending on whether the cluster
created will have a single role or multiple roles.

The same configuration to create a single role three member cluster as the minimal yaml could be specified more fully 
as follows:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster
spec:
  role: storage # <1>
  replicas: 3   # <2>
----   

<1> The `role` field specifies the name of the role, in this case `storage`.
<2> The `replicas` field defines the number of Pods that will be started for this role, in this case three.


If a cluster will have multiple roles they are defined in the `spec.roles` list; so again the same cluster could be
defined more fully as:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster
spec:
  roles:             # <1>
    - role: storage
      replicas: 3
----

<1> This time the role is defined in the `roles` section of the yaml. The `roles` section is a list of one or more role
specifications.

Multiple roles can be defined by adding more roles with distinct names to the `roles` list; for example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster
spec:
  roles:
    - role: storage  # <1>
      replicas: 3    # <2>
    - role: web      # <3>
      replicas: 2    # <4>
----

<1> In this case there are two roles defined, the first names `storage`,
<2> with three replicas
<3> and the second named `web`
<4> with two replicas.

This will result in a Coherence cluster with a total of five members.
The Coherence Operator would create two `StatefulSets`, one for `storage` with three `Pods` and one for `web` with two `Pods`.
