///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Coherence Operator Concepts

== What is Coherence Operator?
Coherence Operator is a https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Kubernetes Operator] that
is used to manage https://docs.oracle.com/middleware/12213/coherence/[Oracle Coherence] clusters in Kubernetes.
The Coherence Operator (the "operator") takes a place in the DevOps toolkit when managing Coherence Clusters, such as configuration, installation, safe scaling, management and metrics.

The Coherence Operator is a Go based application built using the https://github.com/operator-framework/operator-sdk[Operator SDK].
It is distributed as a Docker image and Helm chart for easy installation and configuration.


== Coherence Clusters
A Coherence Cluster is a number of distributed Java Virtual Machines (JVMs) that communicate to form a single coherent cluster. 
In Kubernetes, this concept can be related to a number of Pods that form a single cluster. 
In each Pod, there is a JVM running Coherence or some custom application using Coherence.

The operator uses the Kubernetes Custom Resource Definition (CRD) to represent a Coherence Cluster and the roles within it. Every field in the `CoherenceCluster` CRD `Spec` is optional and a simple cluster can be defined in a `yaml` file as:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster
----

Provide a unique cluster name in the `metadata.name` field of the `CoherenceCluster`. The name must be unique in a given Kubernetes namespace.

The operator uses default values for the fields that have not been entered and the `yaml` creates a `StatefulSet` Coherence Cluster that has three replicas, which means that there are three storage enabled Coherence Pods.
   

== Coherence Roles
A Coherence Cluster can be made up of a number of Pods that perform different roles. All of the Pods in a given role
share the same configuration. A cluster has at least one role in which Pods are storage enabled.

Each role in a Coherence Cluster has a name and configuration. A cluster can have zero or many roles defined in the 
`CoherenceCluster` CRD `Spec`. You can define the common configuration shared by all roles in the `yaml` file instead of duplicating the configuration multiple times in the `yaml`.

The operator creates a `StatefulSet` for each role defined in the `CoherenceCluster` CRD `yaml`.
This separation allows roles to be managed and scaled independently from each other.

Even if there are no roles described in the `yaml`, the operator creates a default role with the name
`storage` and gives a replica count to three. 

There are two ways to describe the specification of a role in a `CoherenceCluster` CRD depending on whether the cluster
created will have a single role or multiple roles.

The `yaml` configuration to create a cluster with single role and three member:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster
spec:
  role: storage  
  replicas: 3    
----   

The `role` specifies the name of the role, in this case `storage`.
The `replicas` defines the number of Pods that are started for this role, in this case three.


If a cluster must have multiple roles, it is defined in the `spec.roles` list and the `yaml` configuration is as follows:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster
spec:
  roles:              
    - role: storage
      replicas: 3
----

The `roles` section in the `yaml` defines the list of one or more role specifications.

You can define multiple roles by adding more roles with distinct names to the `roles` list, for example:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster
spec:
  roles:
    - role: storage   
      replicas: 3     
    - role: web       
      replicas: 2     
----

In the example, there are two roles defined, the first named `storage` with three replicas, and the second named `web` with two replicas. A Coherence Cluster is created with a total of five members. The operator creates two `StatefulSets`, one for `storage` with three Pods and one for `web` with two Pods.
