///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2020 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Coherence Operator Introduction

== What is the Coherence Operator?
The Coherence Operator is a https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Kubernetes Operator] that
is used to manage https://coherence.java.net[Oracle Coherence] clusters in Kubernetes.
The Coherence Operator takes on the tasks of that human Dev Ops resource might carry out when managing Coherence clusters,
such as configuration, installation, safe scaling, management and metrics.

The Coherence Operator is a Go based application built using the https://github.com/operator-framework/operator-sdk[Operator SDK].
It is distributed as a Docker image and Helm chart for easy installation and configuration.


== Coherence Clusters
A Coherence cluster is a number of distributed Java Virtual Machines (JVMs) that communicate to form a single coherent cluster.
In Kubernetes, this concept can be related to a number of Pods that form a single cluster. 
In each `Pod` is a JVM running a Coherence `DefaultCacheServer`, or a custom application using Coherence.

The operator uses a Kubernetes Custom Resource Definition (CRD) to represent a group of members in a Coherence cluster.
Typically, a deployment would be used to configure one or more members of a specific role in a cluster.
Every field in the `CoherenceDeployment` CRD `Spec` is optional, so a simple cluster can be defined in  yaml as:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceDeployment
metadata:
  name: my-cluster # <1>
----

<1> In this case the `metadata.name` field in the `CoherenceDeployment` yaml will be used as the Coherence cluster name.

The operator will use default values for fields that have not been entered, so the above yaml will create
a Coherence deployment using a `StatefulSet` with a replica count of three, which means that will be three storage
enabled Coherence `Pods`.
