///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Coherence Operator Introduction

== What is the Coherence Operator?
The Coherence Operator is a https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Kubernetes Operator] that
is used to manage https://coherence.java.net[Oracle Coherence] clusters in Kubernetes.
The Coherence Operator takes on the tasks of that human Dev Ops resource might carry out when managing Coherence clusters,
such as configuration, installation, safe scaling, management and metrics.

The Coherence Operator is a Go based application built using the https://github.com/operator-framework/operator-sdk[Operator SDK].
It is distributed as a Docker image and Helm chart for easy installation and configuration.


== Coherence Clusters
A Coherence cluster is a number of distributed Java Virtual Machines (JVMs) that communicate to form a single coherent cluster.
In Kubernetes, this concept can be related to a number of Pods that form a single cluster. 
In each `Pod` is a JVM running a Coherence `DefaultCacheServer`, or a custom application using Coherence.

The operator uses a Kubernetes Custom Resource Definition (CRD) to represent a group of members in a Coherence cluster.
Typically, a deployment would be used to configure one or more members of a specific role in a cluster.
Every field in the `Coherence` CRD `Spec` is optional, so a simple cluster can be defined in  yaml as:

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: my-cluster # <1>
----

<1> In this case the `metadata.name` field in the `Coherence` resource yaml will be used as the Coherence cluster name.

The operator will use default values for fields that have not been entered, so the above yaml will create
a Coherence deployment using a `StatefulSet` with a replica count of three, which means that will be three storage
enabled Coherence `Pods`.

See the <<about/04_coherence_spec.adoc,Coherence CRD spec>> page for details of all the fields in the CRD.
