///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Kubernetes on your Desktop
:description: Running Kubernetes on your desktop.
:keywords: kubernetes

For development and testing of the Coherence Operator it's often convenient to run Kubernetes on your desktop.

Some ways to do this are:

* https://docs.docker.com/docker-for-mac/kubernetes/[Kubernetes support in Docker for Desktop]
* https://kind.sigs.k8s.io[Kind]
* https://kubernetes.io/docs/getting-started-guides/minikube/[Kubernetes Minikube]

== Docker for Desktop.

=== Install

Install
https://docs.docker.com/docker-for-mac/install/[Docker for Mac] or
https://docs.docker.com/docker-for-windows/install/[Docker for Windows].

Starting with version 18.06 Docker for Desktop includes Kubernetes support.

=== Enable Kubernetes Support

Enable
https://docs.docker.com/docker-for-mac/#kubernetes[Kubernetes Support for Mac]
or
https://docs.docker.com/docker-for-windows/#kubernetes[Kubernetes Support for Windows].

Once Kubernetes installation is complete, make sure you have your context
set correctly to use docker-for-desktop.

[source,bash]
.Make sure K8s context is set to docker-for-desktop
----
kubectl config get-contexts
kubectl config use-context docker-for-desktop
kubectl cluster-info
kubectl version --short
kubectl get nodes
----


== Kind

Install Kind as described in the https://kind.sigs.k8s.io/docs/user/quick-start/[Kind Quick Start]

* To create a Kubernetes three node cluster in Kind you need a configuration file

[source,yaml]
.kind-config.yaml
----
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
----

* Then create a Kind Kubernetes cluster with the following command

[source,bash]
----
kind create cluster --config kind-config.yaml
----

* After a short while (depending on how long images take to download) there should be a Kubernetes cluster with a master
and three worker nodes running in Docker containers.

[source,bash]
----
docker ps
d790d6b779ff  kindest/node:v1.15.3   "/usr/local/bin/entr…"   23 hours ago  Up 23 hours                                         kind-worker2
a096c8bf0c1a  kindest/node:v1.15.3   "/usr/local/bin/entr…"   23 hours ago  Up 23 hours                                         kind-worker3
4c01d94c29b7  kindest/node:v1.15.3   "/usr/local/bin/entr…"   23 hours ago  Up 23 hours   56603/tcp, 127.0.0.1:56603->6443/tcp  kind-control-plane
8f62284be151  kindest/node:v1.15.3   "/usr/local/bin/entr…"   23 hours ago  Up 23 hours                                         kind-worker
----

* As described in the Kind documentation now export `KUBECONFIG` for the Kind cluster

[source,bash]
----
export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
----

* To be able to use this cluster with the Operator Helm chart Helm will need to be initialised.

[source,bash]
----
helm init
----

The Kind cluster has RBAC enabled so Helm's Tiller will now need to be patched with a role:

[source,bash]
----
kubectl create serviceaccount \
  --namespace kube-system tiller

kubectl create clusterrolebinding tiller-cluster-rule \
  --clusterrole=cluster-admin --serviceaccount=kube-system:tiller

kubectl patch deploy --namespace kube-system \
  tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
----

=== A Word About Kind and Docker Images

If trying to use Kind to run the Coherence Operator using locally built images these images need to be added to the
Kubernetes cluster using the Kind CLI because the local images will obviously not be in a repository that the nodes
can pull from. Although a Kind cluster is running in Docker it does not appear to have access to any local Docker images
so all images either need to be pull-able or loaded via the Kind CLI.

For example if the Operator has been built with `make all` there will be the following local images

[source,bash]
----
docker images --format "table {{.Repository}}\t{{.Tag}}"

REPOSITORY                                                     TAG
iad.ocir.io/odx-stateservice/test/oracle/coherence-operator    2.0.0-ci
iad.ocir.io/odx-stateservice/test/oracle/operator-test-image   2.0.0-ci
iad.ocir.io/odx-stateservice/test/oracle/coherence-operator    2.0.0-ci-utils
----

These images can be added to the Kind cluster with the commands:

[source,bash]
----
kind load docker-image iad.ocir.io/odx-stateservice/test/oracle/coherence-operator:2.0.0-ci
kind load docker-image iad.ocir.io/odx-stateservice/test/oracle/coherence-operator:2.0.0-ci-utils
kind load docker-image iad.ocir.io/odx-stateservice/test/oracle/operator-test-image:2.0.0-ci
----

