///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Quick Start

This guide is a simple set of steps to install the Coherence Operator and then use that
to install a simple Coherence cluster.

== Prerequisites

Ensure that the <<install/01_installation.adoc,Coherence Operator prerequisites>> are available.

== 1. Install the Coherence Operator

=== 1.1 Add the Coherence Operator Helm repository

[source,bash]
----
helm repo add coherence https://oracle.github.io/coherence-operator/charts

helm repo update
----

=== 1.2. Install the Coherence Operator Helm chart

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --name <release-name> \
    coherence/coherence-operator
----

NOTE: Use the same namespace that the operator was installed into,
e.g. if the namespace is `coherence` the command would be
`helm install --namespace coherence  --name operator coherence/coherence-operator`

See the <<install/01_introduction.adoc, full install guide>> for more details.

== 2. Install a Coherence Cluster

Ensure that the Coherence images can be pulled by the Kubernetes cluster
see <<04_obtain_coherence_images.adoc,Obtain Coherence Images>>
By default a `CoherenceCluster` will use images from Oracle Container Registry.
If a different registry is used the image name will need to be specified in the `CoherenceCluster` yaml,
see <<clusters/056_coherence_image.adoc,Setting the Coherence Image>> for documentation on how to
specify a different Coherence image to the default.


=== 2.1 Install a Coherence cluster using the minimal required configuration.

The minimal required yaml to create a `CoherenceCluster` resource is shown below.


[source,yaml]
.my-cluster.yaml
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster # <1>
----

The only required field is `metadata.name` which will be used as the Coherence cluster name, in this case `my-cluster`

```
kubectl -n <namespace> apply -f my-cluster.yaml
```

NOTE: Use the same namespace that the operator was installed into,
e.g. if the namespace is `coherence` the command would be
`kubectl -n coherence create -f my-cluster.yaml`


=== 2.2 List the Coherence Resources

After installing the `my-cluster.yaml` above here should be a single `coherencecluster` resource  named `my-cluster`
and a single `coherencerole` resource named `my-cluster-storage` created in the Coherence Operator namespace.

```
kubectl -n <namespace> get coherencecluster
```

NOTE: Use the same namespace that the operator was installed into, e.g. if the namespace is `coherence` the command
would be `kubectl -n coherence get coherence`

```
NAME                                                    AGE
coherencerole.coherence.oracle.com/my-cluster-storage   19s

NAME                                               AGE
coherencecluster.coherence.oracle.com/my-cluster   19s
```

See the <<clusters/020_k8s_resources.adoc,in-depth documentation>> on the Kubernetes resources created by the
Coherence Operator.

=== 2.3 List all of the `Pods` for the Coherence cluster.

The Coherence Operator applies a `coherenceCluster` label to all
of the `Pods` so this label can be used with the `kubectl` command to find `Pods` for a Coherence cluster.

```
kubectl -n <namespace> get pod -l coherenceCluster=my-cluster
```

NOTE: Use the same namespace that the operator was installed into,
e.g. if the namespace is `coherence` the command would be
`kubectl -n coherence get pod -l coherenceCluster=my-cluster`

```
NAME                   READY   STATUS    RESTARTS   AGE
my-cluster-storage-0   1/1     Running   0          2m58s
my-cluster-storage-1   1/1     Running   0          2m58s
my-cluster-storage-2   1/1     Running   0          2m58s
```

The default cluster size is three so there should be three `Pods`

== 3. Scale the Coherence Cluster

=== 3.1 Use kubectl to Scale Up

Using the `kubectl scale` command a specific `CoherenceRole` can be scaled up or down.

```
kubectl -n <namespace> scale coherencerole/storage --replicas=6
```

NOTE: Use the same namespace that the operator was installed into,
e.g. if the namespace is `coherence` the command would be
`kubectl -n coherence scale coherencerole/my-cluster-storage --replicas=6`

=== 3.2 List all of the `Pods` fo the Coherence cluster

```
kubectl -n <namespace> get pod -l coherenceCluster=my-cluster
```

NOTE: Use the same namespace that the operator was installed into,
e.g. if the namespace is `coherence` the command would be
`kubectl -n coherence get pod -l coherenceCluster=my-cluster`

```
NAME                   READY   STATUS    RESTARTS   AGE
my-cluster-storage-0   1/1     Running   0          4m23s
my-cluster-storage-1   1/1     Running   0          4m23s
my-cluster-storage-2   1/1     Running   0          4m23s
my-cluster-storage-3   1/1     Running   0          1m19s
my-cluster-storage-4   1/1     Running   0          1m19s
my-cluster-storage-5   1/1     Running   0          1m19s
```

There should eventually be six running `Pods`.
