///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Quick Start

This guide is a simple set of steps to install the Coherence Operator and then use that
to install a simple Coherence cluster.

== Prerequisites

Ensure that the <<install/01_installation.adoc,Coherence Operator prerequisites>> are available.

== 1. Install the Coherence Operator

=== 1.1 Add the Coherence Operator Helm repository

[source,bash]
----
helm repo add coherence https://oracle.github.io/coherence-operator/charts

helm repo update
----

=== 1.2. Install the Coherence Operator Helm chart

[source,bash]
.helm v3 install command
----
helm install  \
    --namespace <namespace> \
    <release-name> \
    coherence/coherence-operator
----

e.g. if the Kubernetes namespace is `coherence-test` the command would be:
[source,bash]
.helm v3 install command
----
helm install --namespace coherence-test  operator coherence/coherence-operator
----
or with Helm v2
[source,bash]
----
helm install --namespace coherence-test  --name operator coherence/coherence-operator
----



See the <<installation/01_installation.adoc, full install guide>> for more details.

== 2. Install a Coherence Deployment

Ensure that the Coherence images can be pulled by the Kubernetes cluster,
see <<installation/04_obtain_coherence_images.adoc,Obtain Coherence Images>>.
By default, a `CoherenceDeployment` will use the OSS Coherence CE image from Docker Hub.
If a different image is to be used the image name will need to be specified in the `CoherenceDeployment` yaml,
see <<deploy_applications/010_overview.adoc,Setting the Application Image>> for documentation on how to
specify a different images to use.


=== 2.1 Install a Coherence deployment using the minimal required configuration.

The minimal required yaml to create a `CoherenceDeployment` resource is shown below.

[source,yaml]
.my-deployment.yaml
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceDeployment
metadata:
  name: my-deployment # <1>
----

The only required field is `metadata.name` which will be used as the Coherence cluster name, in this case `my-deployment`

[source,bash]
----
kubectl -n <namespace> apply -f my-deployment.yaml
----

NOTE: Use the same namespace that the operator was installed into,
e.g. if the namespace is `coherence-test` the command would be
`kubectl -n coherence-test create -f my-deployment.yaml`


=== 2.2 List the Coherence Resources

After installing the `my-deployment.yaml` above here should be a single `CoherenceDeployment` resource  named `my-deployment` in the Coherence Operator namespace.

[source,bash]
----
kubectl -n <namespace> get coherencedeployment
----
or alternatively using the `CoherenceDeployment` CRD a short name of `cd`
[source,bash]
----
kubectl -n <namespace> get cd
----

e.g. if the namespace is `coherence-test` the command would be `kubectl -n coherence-test get coherencedeployment`

[source,bash]
----
NAME                                                  AGE
coherencedeployment.coherence.oracle.com/my-deployment   19s
----

=== 2.3 List all of the `Pods` for the CoherenceDeployment.

The Coherence Operator applies a `coherenceDeployment` label to all `Pods` so this label can be used with the `kubectl` command to find `Pods` for a `CoherenceDeployment`.

[source,bash]
----
kubectl -n <namespace> get pod -l coherenceDeployment=my-deployment
----

e.g. if the namespace is `coherence` the command would be:
`kubectl -n coherence get pod -l coherenceDeployment=my-deployment`

[source,bash]
----
NAME              READY   STATUS    RESTARTS   AGE
my-deployment-0   1/1     Running   0          2m58s
my-deployment-1   1/1     Running   0          2m58s
my-deployment-2   1/1     Running   0          2m58s
----


=== 2.3 List all of the `Pods` for the Coherence cluster.

The Coherence Operator applies a `coherenceCluster` label to all `Pods` so this label can be used with the `kubectl` command to find `Pods` for a Coherence cluster, which may be made up of multiple `CoherenceDeployments`.

[source,bash]
----
kubectl -n <namespace> get pod -l coherenceCluster=my-cluster
----

e.g. If there is a cluster named `my-cluster` made up of two two `CoherenceDeployments` in a namespace
`coherence-test`, one named `storage` and one named `front-end`
then the `kubectl` command to list all Pods for the cluster would be:
[source,bash]
----
kubectl -n coherence-test get pod -l coherenceCluster=my-cluster
----
The result of which might look something like this

[source,bash]
----
NAME          READY   STATUS    RESTARTS   AGE
storage-0     1/1     Running   0          2m58s
storage-1     1/1     Running   0          2m58s
storage-2     1/1     Running   0          2m58s
front-end-0   1/1     Running   0          2m58s
front-end-1   1/1     Running   0          2m58s
front-end-2   1/1     Running   0          2m58s
----

== 3. Scale the Coherence Cluster

=== 3.1 Use kubectl to Scale Up

Using the `kubectl scale` command a specific `CoherenceDeployment` can be scaled up or down.

[source,bash]
----
kubectl -n <namespace> scale coherencedeployment/my-deployment --replicas=6
----

e.g. if the namespace is `coherence-test` the command would be:
`kubectl -n coherence scale coherencedeployment/my-deployment --replicas=6`
