///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2021, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////

NOTE: *** This document must not be manually edited. ***
This document has been generated from the comments in the pkg/api classes.
Any changes should be made by editing the corresponding struct comments.

///////////////////////////////////////////////////////////////////////////////

= Coherence Operator API Docs

A reference guide to the Coherence Operator CRD types.

== Coherence Operator API Docs
This is a reference for the Coherence Operator API types.
These are all the types and fields that are used in the Coherence CRD. 

TIP: This document was generated from comments in the Go structs in the pkg/api/ directory.

=== Table of Contents
* <<CoherenceResourceSpec,CoherenceResourceSpec>>
* <<ApplicationSpec,ApplicationSpec>>
* <<CloudNativeBuildPackSpec,CloudNativeBuildPackSpec>>
* <<CoherenceSpec,CoherenceSpec>>
* <<CoherenceTracingSpec,CoherenceTracingSpec>>
* <<CoherenceWKASpec,CoherenceWKASpec>>
* <<ConfigMapVolumeSpec,ConfigMapVolumeSpec>>
* <<ImageSpec,ImageSpec>>
* <<JVMSpec,JVMSpec>>
* <<JvmDebugSpec,JvmDebugSpec>>
* <<JvmGarbageCollectorSpec,JvmGarbageCollectorSpec>>
* <<JvmJmxmpSpec,JvmJmxmpSpec>>
* <<JvmMemorySpec,JvmMemorySpec>>
* <<JvmOutOfMemorySpec,JvmOutOfMemorySpec>>
* <<LocalObjectReference,LocalObjectReference>>
* <<NamedPortSpec,NamedPortSpec>>
* <<NetworkSpec,NetworkSpec>>
* <<PersistenceSpec,PersistenceSpec>>
* <<PersistentStorageSpec,PersistentStorageSpec>>
* <<PodDNSConfig,PodDNSConfig>>
* <<PortSpecWithSSL,PortSpecWithSSL>>
* <<Probe,Probe>>
* <<ProbeHandler,ProbeHandler>>
* <<ReadinessProbeSpec,ReadinessProbeSpec>>
* <<Resource,Resource>>
* <<Resources,Resources>>
* <<SSLSpec,SSLSpec>>
* <<ScalingSpec,ScalingSpec>>
* <<SecretVolumeSpec,SecretVolumeSpec>>
* <<ServiceMonitorSpec,ServiceMonitorSpec>>
* <<ServiceSpec,ServiceSpec>>
* <<StartQuorum,StartQuorum>>
* <<StartQuorumStatus,StartQuorumStatus>>
* <<Coherence,Coherence>>
* <<CoherenceList,CoherenceList>>
* <<CoherenceResourceStatus,CoherenceResourceStatus>>

=== CoherenceResourceSpec

CoherenceResourceSpec defines the specification of a Coherence resource. A Coherence resource is typically one or more Pods that perform the same functionality, for example storage members.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| image | The name of the image. More info: https://kubernetes.io/docs/concepts/containers/images m| &#42;string | false
m| imagePullPolicy | Image pull policy. One of Always, Never, IfNotPresent. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#pullpolicy-v1-core[corev1.PullPolicy] | false
m| imagePullSecrets | ImagePullSecrets is an optional list of references to secrets in the same namespace to use for pulling any of the images used by this PodSpec. If specified, these secrets will be passed to individual puller implementations for them to use. For example, in the case of docker, only DockerConfig type secrets are honored. More info: https://kubernetes.io/docs/concepts/containers/images#specifying-imagepullsecrets-on-a-pod m| []<<LocalObjectReference,LocalObjectReference>> | false
m| replicas | The desired number of cluster members of this deployment. This is a pointer to distinguish between explicit zero and not specified. If not specified a default value of 3 will be used. This field cannot be negative. m| &#42;int32 | false
m| cluster | The optional name of the Coherence cluster that this Coherence resource belongs to. If this value is set the Pods controlled by this Coherence resource will form a cluster with other Pods controlled by Coherence resources with the same cluster name. If not set the Coherence resource's name will be used as the cluster name. m| &#42;string | false
m| role | The name of the role that this deployment represents in a Coherence cluster. This value will be used to set the Coherence role property for all members of this role m| string | false
m| coherence | The optional settings specific to Coherence functionality. m| &#42;<<CoherenceSpec,CoherenceSpec>> | false
m| application | The optional application specific settings. m| &#42;<<ApplicationSpec,ApplicationSpec>> | false
m| jvm | The JVM specific options m| &#42;<<JVMSpec,JVMSpec>> | false
m| ports | Ports specifies additional port mappings for the Pod and additional Services for those ports. m| []<<NamedPortSpec,NamedPortSpec>> | false
m| scaling | The configuration to control safe scaling. m| &#42;<<ScalingSpec,ScalingSpec>> | false
m| suspendProbe | The configuration of the probe used to signal that services must be suspended before a deployment is stopped. m| &#42;<<Probe,Probe>> | false
m| suspendServicesOnShutdown | A flag controlling whether storage enabled cache services in this deployment will be suspended before the deployment is shutdown or scaled to zero. The action of suspending storage enabled services when the whole deployment is being stopped ensures that cache services with persistence enabled will shutdown cleanly without the possibility of Coherence trying to recover and re-balance partitions as Pods are stopped. The default value if not specified is true. m| &#42;bool | false
m| startQuorum | StartQuorum controls the start-up order of this Coherence resource in relation to other Coherence resources. m| []<<StartQuorum,StartQuorum>> | false
m| env | Env is additional environment variable mappings that will be passed to the Coherence container in the Pod. To specify extra variables add them as name value pairs the same as they would be added to a Pod containers spec. m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#envvar-v1-core[corev1.EnvVar] | false
m| labels | The extra labels to add to the all of the Pods in this deployments. Labels here will add to or override those defined for the cluster. More info: http://kubernetes.io/docs/user-guide/labels m| map[string]string | false
m| annotations | Annotations are free-form yaml that will be added to the store release as annotations Any annotations should be placed BELOW this annotations: key. For example if we wanted to include annotations for Prometheus it would look like this: +
 +
annotations: +
  prometheus.io/scrape: \"true\" + +
  prometheus.io/port: \"2408\" + m| map[string]string | false
m| initContainers | List of additional initialization containers to add to the deployment's Pod. More info: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/ m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#container-v1-core[corev1.Container] | false
m| sideCars | List of additional side-car containers to add to the deployment's Pod. m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#container-v1-core[corev1.Container] | false
m| configMapVolumes | A list of ConfigMaps to add as volumes. Each entry in the list will be added as a ConfigMap Volume to the deployment's Pods and as a VolumeMount to all of the containers and init-containers in the Pod. +
see: <<misc_pod_settings/050_configmap_volumes.adoc,Add ConfigMap Volumes>> m| []<<ConfigMapVolumeSpec,ConfigMapVolumeSpec>> | false
m| secretVolumes | A list of Secrets to add as volumes. Each entry in the list will be added as a Secret Volume to the deployment's Pods and as a VolumeMount to all of the containers and init-containers in the Pod. +
see: <<misc_pod_settings/020_secret_volumes.adoc,Add Secret Volumes>> m| []<<SecretVolumeSpec,SecretVolumeSpec>> | false
m| volumes | Volumes defines extra volume mappings that will be added to the Coherence Pod. +
  The content of this yaml should match the normal k8s volumes section of a Pod definition + +
  as described in https://kubernetes.io/docs/concepts/storage/volumes/ + m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#volume-v1-core[corev1.Volume] | false
m| volumeClaimTemplates | VolumeClaimTemplates defines extra PVC mappings that will be added to the Coherence Pod. +
  The content of this yaml should match the normal k8s volumeClaimTemplates section of a Pod definition + +
  as described in https://kubernetes.io/docs/concepts/storage/persistent-volumes/ + m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#persistentvolumeclaim-v1-core[corev1.PersistentVolumeClaim] | false
m| volumeMounts | VolumeMounts defines extra volume mounts to map to the additional volumes or PVCs declared above +
  in store.volumes and store.volumeClaimTemplates + m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#volumemount-v1-core[corev1.VolumeMount] | false
m| healthPort | The port that the health check endpoint will bind to. m| &#42;int32 | false
m| readinessProbe | The readiness probe config to be used for the Pods in this deployment. ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ m| &#42;<<ReadinessProbeSpec,ReadinessProbeSpec>> | false
m| livenessProbe | The liveness probe config to be used for the Pods in this deployment. ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ m| &#42;<<ReadinessProbeSpec,ReadinessProbeSpec>> | false
m| resources | Resources is the optional resource requests and limits for the containers +
 ref: http://kubernetes.io/docs/user-guide/compute-resources/ + +
 +
By default the cpu requests is set to zero and the cpu limit set to 32. This is because it appears that K8s defaults cpu to one and since Java 10 the JVM now correctly picks up cgroup cpu limits then the JVM will only see one cpu. By setting resources.requests.cpu=0 and resources.limits.cpu=32 it ensures that the JVM will see the either the number of cpus on the host if this is <= 32 or the JVM will see 32 cpus if the host has > 32 cpus. The limit is set to zero so that there is no hard-limit applied. +
 +
No default memory limits are applied. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#resourcerequirements-v1-core[corev1.ResourceRequirements] | false
m| affinity | Affinity controls Pod scheduling preferences. +
  ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity + m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#affinity-v1-core[corev1.Affinity] | false
m| nodeSelector | NodeSelector is the Node labels for pod assignment +
  ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector + m| map[string]string | false
m| tolerations | Tolerations is for nodes that have taints on them. +
  Useful if you want to dedicate nodes to just run the coherence container + +
For example: +
  tolerations: + +
  - key: \"key\" + +
    operator: \"Equal\" + +
    value: \"value\" + +
    effect: \"NoSchedule\" + +
 +
  ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/ + m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#toleration-v1-core[corev1.Toleration] | false
m| securityContext | SecurityContext is the PodSecurityContext that will be added to all of the Pods in this deployment. See: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#podsecuritycontext-v1-core[corev1.PodSecurityContext] | false
m| shareProcessNamespace | Share a single process namespace between all of the containers in a pod. When this is set containers will be able to view and signal processes from other containers in the same pod, and the first process in each container will not be assigned PID 1. HostPID and ShareProcessNamespace cannot both be set. Optional: Default to false. m| &#42;bool | false
m| hostIPC | Use the host's ipc namespace. Optional: Default to false. m| &#42;bool | false
m| network | Configure various networks and DNS settings for Pods in this rolw. m| &#42;<<NetworkSpec,NetworkSpec>> | false
m| coherenceUtils | The configuration for the Coherence utils image m| &#42;<<ImageSpec,ImageSpec>> | false
m| serviceAccountName | The name to use for the service account to use when RBAC is enabled The role bindings must already have been created as this chart does not create them it just sets the serviceAccountName value in the Pod spec. m| string | false
m| automountServiceAccountToken | Whether or not to auto-mount the Kubernetes API credentials for a service account m| &#42;bool | false
m| operatorRequestTimeout | The timeout to apply to REST requests made back to the Operator from Coherence Pods. These requests are typically to obtain site and rack information for the Pod. m| &#42;int32 | false
|===

<<Table of Contents,Back to TOC>>

=== ApplicationSpec

The specification of the application deployed into the Coherence.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| type | The application type to execute. This field would be set if using the Coherence Graal image and running a none-Java application. For example if the application was a Node application this field would be set to \"node\". The default is to run a plain Java application. m| &#42;string | false
m| main | Class is the Coherence container main class.  The default value is com.tangosol.net.DefaultCacheServer. If the application type is non-Java this would be the name of the corresponding language specific runnable, for example if the application type is \"node\" the main may be a Javascript file. m| &#42;string | false
m| args | Args is the optional arguments to pass to the main class. m| []string | false
m| workingDir | The application folder in the custom artifacts Docker image containing application artifacts. This will effectively become the working directory of the Coherence container. If not set the application directory default value is \"/app\". m| &#42;string | false
m| cloudNativeBuildPack | Optional settings that may be configured if using a Cloud Native Buildpack Image. For example an image build with the Spring Boot Maven/Gradle plugin. See: https://github.com/paketo-buildpacks/spring-boot and https://buildpacks.io/ m| &#42;<<CloudNativeBuildPackSpec,CloudNativeBuildPackSpec>> | false
m| springBootFatJar | SpringBootFatJar is the full path name to the Spring Boot fat jar if the application image has been built by just adding a Spring Boot fat jar to the image. If this field is set then the application will be run by executing this jar. For example, if this field is \"/app/libs/foo.jar\" the command line will be \"java -jar app/libs/foo.jar\" m| &#42;string | false
|===

<<Table of Contents,Back to TOC>>

=== CloudNativeBuildPackSpec

The configuration when using a Cloud Native Buildpack Image. For example an image build with the Spring Boot Maven/Gradle plugin. See: https://github.com/paketo-buildpacks/spring-boot and https://buildpacks.io/

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| enabled | Enable or disable buildpack detection. The operator will automatically detect Cloud Native Buildpack images but if this auto-detection fails to work correctly for a specific image then this field can be set to true to signify that the image is a buildpack image or false to signify that it is not a buildpack image. m| &#42;bool | false
m| launcher | &#160; m| &#42;string | false
|===

<<Table of Contents,Back to TOC>>

=== CoherenceSpec

This section of the CRD configures settings specific to Coherence. +
see: <<coherence_settings/010_overview.adoc,Coherence Configuration>>

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| cacheConfig | CacheConfig is the name of the cache configuration file to use +
see: <<coherence_settings/030_cache_config.adoc,Configure Cache Config File>> m| &#42;string | false
m| overrideConfig | OverrideConfig is name of the Coherence operational configuration override file, the default is tangosol-coherence-override.xml +
see: <<coherence_settings/040_override_file.adoc,Configure Operational Config File>> m| &#42;string | false
m| storageEnabled | A boolean flag indicating whether members of this deployment are storage enabled. This value will set the corresponding coherence.distributed.localstorage System property. If not specified the default value is true. This flag is also used to configure the ScalingPolicy value if a value is not specified. If the StorageEnabled field is not specified or is true the scaling will be safe, if StorageEnabled is set to false scaling will be parallel. +
see: <<coherence_settings/050_storage_enabled.adoc,Configure Storage Enabled>> m| &#42;bool | false
m| persistence | Persistence values configure the on-disc data persistence settings. The bool Enabled enables or disabled on disc persistence of data. +
see: <<coherence_settings/080_persistence.adoc,Configure Persistence>> m| &#42;<<PersistenceSpec,PersistenceSpec>> | false
m| logLevel | The Coherence log level, default being 5 (info level). +
see: <<coherence_settings/060_log_level.adoc,Configure Coherence log level>> m| &#42;int32 | false
m| management | Management configures Coherence management over REST Note: Coherence management over REST will is available in Coherence version >= 12.2.1.4. +
see: <<management_and_diagnostics/010_overview.adoc,Management & Diagnostics>> m| &#42;<<PortSpecWithSSL,PortSpecWithSSL>> | false
m| metrics | Metrics configures Coherence metrics publishing Note: Coherence metrics publishing will is available in Coherence version >= 12.2.1.4. +
see: <<metrics/010_overview.adoc,Metrics>> m| &#42;<<PortSpecWithSSL,PortSpecWithSSL>> | false
m| tracing | Tracing is used to configure Coherence distributed tracing functionality. m| &#42;<<CoherenceTracingSpec,CoherenceTracingSpec>> | false
m| allowEndangeredForStatusHA | AllowEndangeredForStatusHA is a list of Coherence partitioned cache service names that are allowed to be in an endangered state when testing for StatusHA. Instances where a StatusHA check is performed include the readiness probe and when scaling a deployment. This field would not typically be used except in cases where a cache service is configured with a backup count greater than zero but it does not matter if caches in those services loose data due to member departure. Normally, such cache services would have a backup count of zero, which would automatically excluded them from the StatusHA check. m| []string | false
m| excludeFromWKA | Exclude members of this deployment from being part of the cluster's WKA list. +
see: <<coherence_settings/070_wka.adoc,Well Known Addressing>> m| &#42;bool | false
m| wka | Specify an existing Coherence deployment to be used for WKA. If an existing deployment is to be used for WKA the ExcludeFromWKA is implicitly set to true. +
see: <<coherence_settings/070_wka.adoc,Well Known Addressing>> m| &#42;<<CoherenceWKASpec,CoherenceWKASpec>> | false
m| skipVersionCheck | Certain features rely on a version check prior to starting the server, e.g. metrics requires >= 12.2.1.4. The version check relies on the ability of the start script to find coherence.jar but if due to how the image has been built this check is failing then setting this flag to true will skip version checking and assume that the latest coherence.jar is being used. m| &#42;bool | false
|===

<<Table of Contents,Back to TOC>>

=== CoherenceTracingSpec

CoherenceTracingSpec configures Coherence tracing.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| ratio | Ratio is the tracing sampling-ratio, which controls the likelihood of a tracing span being collected. For instance, a value of 1.0 will result in all tracing spans being collected, while a value of 0.1 will result in roughly 1 out of every 10 tracing spans being collected. +
 +
A value of 0 indicates that tracing spans should only be collected if they are already in the context of another tracing span.  With such a configuration, Coherence will not initiate tracing on its own, and it is up to the application to start an outer tracing span, from which Coherence will then collect inner tracing spans. +
 +
A value of -1 disables tracing completely. +
 +
The Coherence default is -1 if not overridden. For values other than -1, numbers between 0 and 1 are acceptable. +
 +
NOTE: This field is a k8s resource.Quantity value as CRDs do not support decimal numbers. See https://godoc.org/k8s.io/apimachinery/pkg/api/resource#Quantity for the different formats of number that may be entered. m| &#42;resource.Quantity | false
|===

<<Table of Contents,Back to TOC>>

=== CoherenceWKASpec



[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| deployment | The name of the existing Coherence deployment to use for WKA. m| string | true
m| namespace | The optional namespace of the existing Coherence deployment to use for WKA if different from this deployment's namespace. m| string | false
|===

<<Table of Contents,Back to TOC>>

=== ConfigMapVolumeSpec

Represents a ConfigMap that will be added to the deployment's Pods as an additional Volume and as a VolumeMount in the containers. +
see: <<misc_pod_settings/050_configmap_volumes.adoc,Add ConfigMap Volumes>>

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| name | The name of the ConfigMap to mount. This will also be used as the name of the Volume added to the Pod if the VolumeName field is not set. m| string | true
m| mountPath | Path within the container at which the volume should be mounted.  Must not contain ':'. m| string | true
m| volumeName | The optional name to use for the Volume added to the Pod. If not set, the ConfigMap name will be used as the VolumeName. m| string | false
m| readOnly | Mounted read-only if true, read-write otherwise (false or unspecified). Defaults to false. m| bool | false
m| subPath | Path within the volume from which the container's volume should be mounted. Defaults to \"\" (volume's root). m| string | false
m| mountPropagation | mountPropagation determines how mounts are propagated from the host to container and the other way around. When not set, MountPropagationNone is used. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#mountpropagationmode-v1-core[corev1.MountPropagationMode] | false
m| subPathExpr | Expanded path within the volume from which the container's volume should be mounted. Behaves similarly to SubPath but environment variable references $(VAR_NAME) are expanded using the container's environment. Defaults to \"\" (volume's root). SubPathExpr and SubPath are mutually exclusive. m| string | false
m| items | If unspecified, each key-value pair in the Data field of the referenced ConfigMap will be projected into the volume as a file whose name is the key and content is the value. If specified, the listed keys will be projected into the specified paths, and unlisted keys will not be present. If a key is specified which is not present in the ConfigMap, the volume setup will error unless it is marked optional. Paths must be relative and may not contain the '..' path or start with '..'. m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#keytopath-v1-core[corev1.KeyToPath] | false
m| defaultMode | Optional: mode bits to use on created files by default. Must be a value between 0 and 0777. Defaults to 0644. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set. m| &#42;int32 | false
m| optional | Specify whether the ConfigMap or its keys must be defined m| &#42;bool | false
|===

<<Table of Contents,Back to TOC>>

=== ImageSpec

ImageSpec defines the settings for a Docker image

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| image | The image name. More info: https://kubernetes.io/docs/concepts/containers/images m| &#42;string | false
m| imagePullPolicy | Image pull policy. One of Always, Never, IfNotPresent. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#pullpolicy-v1-core[corev1.PullPolicy] | false
|===

<<Table of Contents,Back to TOC>>

=== JVMSpec

The JVM configuration.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| classpath | Classpath specifies additional items to add to the classpath of the JVM. m| []string | false
m| args | Args specifies the options (System properties, -XX: args etc) to pass to the JVM. m| []string | false
m| debug | The settings for enabling debug mode in the JVM. m| &#42;<<JvmDebugSpec,JvmDebugSpec>> | false
m| useContainerLimits | If set to true Adds the  -XX:+UseContainerSupport JVM option to ensure that the JVM respects any container resource limits. The default value is true m| &#42;bool | false
m| gc | Set JVM garbage collector options. m| &#42;<<JvmGarbageCollectorSpec,JvmGarbageCollectorSpec>> | false
m| diagnosticsVolume | &#160; m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#volumesource-v1-core[corev1.VolumeSource] | false
m| memory | Configure the JVM memory options. m| &#42;<<JvmMemorySpec,JvmMemorySpec>> | false
m| jmxmp | Configure JMX using JMXMP. m| &#42;<<JvmJmxmpSpec,JvmJmxmpSpec>> | false
m| useJibClasspath | A flag indicating whether to automatically add the default classpath for images created by the JIB tool https://github.com/GoogleContainerTools/jib If true then the /app/lib/* /app/classes and /app/resources entries are added to the JVM classpath. The default value fif not specified is true. m| &#42;bool | false
|===

<<Table of Contents,Back to TOC>>

=== JvmDebugSpec

The JVM Debug specific configuration.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| enabled | Enabled is a flag to enable or disable running the JVM in debug mode. Default is disabled. m| &#42;bool | false
m| suspend | A boolean true if the target VM is to be suspended immediately before the main class is loaded; false otherwise. The default value is false. m| &#42;bool | false
m| attach | Attach specifies the address of the debugger that the JVM should attempt to connect back to instead of listening on a port. m| &#42;string | false
m| port | The port that the debugger will listen on; the default is 5005. m| &#42;int32 | false
|===

<<Table of Contents,Back to TOC>>

=== JvmGarbageCollectorSpec

Options for managing the JVM garbage collector.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| collector | The name of the JVM garbage collector to use. G1 - adds the -XX:+UseG1GC option CMS - adds the -XX:+UseConcMarkSweepGC option Parallel - adds the -XX:+UseParallelGC Default - use the JVMs default collector The field value is case insensitive If not set G1 is used. If set to a value other than those above then the default collector for the JVM will be used. m| &#42;string | false
m| args | Args specifies the GC options to pass to the JVM. m| []string | false
m| logging | Enable the following GC logging args  -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintHeapAtGC -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime Default is true m| &#42;bool | false
|===

<<Table of Contents,Back to TOC>>

=== JvmJmxmpSpec

Options for configuring JMX using JMXMP.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| enabled | If set to true the JMXMP support will be enabled. Default is false m| &#42;bool | false
m| port | The port tht the JMXMP MBeanServer should bind to. If not set the default port is 9099 m| &#42;int32 | false
|===

<<Table of Contents,Back to TOC>>

=== JvmMemorySpec

Options for managing the JVM memory.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| heapSize | HeapSize sets both the initial and max heap size values for the JVM. This will set both the -XX:InitialHeapSize and -XX:MaxHeapSize JVM options to the same value (the equivalent of setting -Xms and -Xmx to the same value). +
 +
The format should be the same as that used when specifying these JVM options. +
 +
If not set the JVM defaults are used. m| &#42;string | false
m| initialHeapSize | InitialHeapSize sets the initial heap size value for the JVM. This will set the -XX:InitialHeapSize JVM option (the equivalent of setting -Xms). +
 +
The format should be the same as that used when specifying this JVM options. +
 +
NOTE: If the HeapSize field is set it will override this field. m| &#42;string | false
m| maxHeapSize | MaxHeapSize sets the maximum heap size value for the JVM. This will set the -XX:MaxHeapSize JVM option (the equivalent of setting -Xmx). +
 +
The format should be the same as that used when specifying this JVM options. +
 +
NOTE: If the HeapSize field is set it will override this field. m| &#42;string | false
m| maxRAM | Sets the JVM option `-XX:MaxRAM=N` which sets the maximum amount of memory used by the JVM to `n`, where `n` is expressed in terms of megabytes (for example, `100m`) or gigabytes (for example `2g`). m| &#42;string | false
m| percentage | Percentage sets the initial and maximum and minimum heap percentage sizes to the same value, This will set the -XX:InitialRAMPercentage -XX:MinRAMPercentage and -XX:MaxRAMPercentage JVM options to the same value. +
 +
The JVM will ignore this option if any of the HeapSize, InitialHeapSize or MaxHeapSize options have been set. +
 +
Valid values are decimal numbers between 0 and 100. +
 +
NOTE: This field is a k8s resource.Quantity value as CRDs do not support decimal numbers. See https://godoc.org/k8s.io/apimachinery/pkg/api/resource#Quantity for the different formats of number that may be entered. +
 +
NOTE: This field maps to the -XX:InitialRAMPercentage -XX:MinRAMPercentage and -XX:MaxRAMPercentage JVM options and will be incompatible with some JVMs that do not have this option (e.g. Java 8). m| &#42;resource.Quantity | false
m| initialRAMPercentage | Set initial heap size as a percentage of total memory. +
 +
The JVM will ignore this option if any of the HeapSize, InitialHeapSize or MaxHeapSize options have been set. +
 +
Valid values are decimal numbers between 0 and 100. +
 +
NOTE: If the Percentage field is set it will override this field. +
 +
NOTE: This field is a k8s resource.Quantity value as CRDs do not support decimal numbers. See https://godoc.org/k8s.io/apimachinery/pkg/api/resource#Quantity for the different formats of number that may be entered. +
 +
NOTE: This field maps to the -XX:InitialRAMPercentage JVM option and will be incompatible with some JVMs that do not have this option (e.g. Java 8). m| &#42;resource.Quantity | false
m| maxRAMPercentage | Set maximum heap size as a percentage of total memory. +
 +
The JVM will ignore this option if any of the HeapSize, InitialHeapSize or MaxHeapSize options have been set. +
 +
Valid values are decimal numbers between 0 and 100. +
 +
NOTE: If the Percentage field is set it will override this field. +
 +
NOTE: This field is a k8s resource.Quantity value as CRDs do not support decimal numbers. See https://godoc.org/k8s.io/apimachinery/pkg/api/resource#Quantity for the different formats of number that may be entered. +
 +
NOTE: This field maps to the -XX:MaxRAMPercentage JVM option and will be incompatible with some JVMs that do not have this option (e.g. Java 8). m| &#42;resource.Quantity | false
m| minRAMPercentage | Set the minimal JVM Heap size as a percentage of the total memory. +
 +
This option will be ignored if HeapSize is set. +
 +
Valid values are decimal numbers between 0 and 100. +
 +
NOTE: This field is a k8s resource.Quantity value as CRDs do not support decimal numbers. See https://godoc.org/k8s.io/apimachinery/pkg/api/resource#Quantity for the different formats of number that may be entered. +
 +
NOTE: This field maps the the -XX:MinRAMPercentage JVM option and will be incompatible with some JVMs that do not have this option (e.g. Java 8). m| &#42;resource.Quantity | false
m| stackSize | StackSize is the stack size value to pass to the JVM. The format should be the same as that used for Java's -Xss JVM option. If not set the JVM defaults are used. m| &#42;string | false
m| metaspaceSize | MetaspaceSize is the min/max metaspace size to pass to the JVM. This sets the -XX:MetaspaceSize and -XX:MaxMetaspaceSize=size JVM options. If not set the JVM defaults are used. m| &#42;string | false
m| directMemorySize | DirectMemorySize sets the maximum total size (in bytes) of the New I/O (the java.nio package) direct-buffer allocations. This value sets the -XX:MaxDirectMemorySize JVM option. If not set the JVM defaults are used. m| &#42;string | false
m| nativeMemoryTracking | Adds the -XX:NativeMemoryTracking=mode  JVM options where mode is on of \"off\", \"summary\" or \"detail\", the default is \"summary\" If not set to \"off\" also add -XX:+PrintNMTStatistics m| &#42;string | false
m| onOutOfMemory | Configure the JVM behaviour when an OutOfMemoryError occurs. m| &#42;<<JvmOutOfMemorySpec,JvmOutOfMemorySpec>> | false
|===

<<Table of Contents,Back to TOC>>

=== JvmOutOfMemorySpec

Options for managing the JVM behaviour when an OutOfMemoryError occurs.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| exit | If set to true the JVM will exit when an OOM error occurs. Default is true m| &#42;bool | false
m| heapDump | If set to true adds the -XX:+HeapDumpOnOutOfMemoryError JVM option to cause a heap dump to be created when an OOM error occurs. Default is true m| &#42;bool | false
|===

<<Table of Contents,Back to TOC>>

=== LocalObjectReference

LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| name | Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names m| string | true
|===

<<Table of Contents,Back to TOC>>

=== NamedPortSpec



[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| name | Name specifies the name of the port. m| string | true
m| port | Port specifies the port used. m| int32 | false
m| protocol | Protocol for container port. Must be UDP or TCP. Defaults to \"TCP\" m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#protocol-v1-core[corev1.Protocol] | false
m| nodePort | The port on each node on which this service is exposed when type=NodePort or LoadBalancer. Usually assigned by the system. If specified, it will be allocated to the service if unused or else creation of the service will fail. If set, this field must be in the range 30000 - 32767 inclusive. Default is to auto-allocate a port if the ServiceType of this Service requires one. More info: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport m| &#42;int32 | false
m| hostPort | Number of port to expose on the host. If specified, this must be a valid port number, 0 < x < 65536. If HostNetwork is specified, this must match ContainerPort. Most containers do not need this. m| &#42;int32 | false
m| hostIP | What host IP to bind the external port to. m| &#42;string | false
m| service | Service configures the Kubernetes Service used to expose the port. m| &#42;<<ServiceSpec,ServiceSpec>> | false
m| serviceMonitor | The specification of a Prometheus ServiceMonitor resource that will be created for the Service being exposed for this port. m| &#42;<<ServiceMonitorSpec,ServiceMonitorSpec>> | false
|===

<<Table of Contents,Back to TOC>>

=== NetworkSpec

NetworkSpec configures various networking and DNS settings for Pods in a deployment.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| dnsConfig | Specifies the DNS parameters of a pod. Parameters specified here will be merged to the generated DNS configuration based on DNSPolicy. m| &#42;<<PodDNSConfig,PodDNSConfig>> | false
m| dnsPolicy | Set DNS policy for the pod. Defaults to \"ClusterFirst\". Valid values are 'ClusterFirstWithHostNet', 'ClusterFirst', 'Default' or 'None'. DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy. To have DNS options set along with hostNetwork, you have to specify DNS policy explicitly to 'ClusterFirstWithHostNet'. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#dnspolicy-v1-core[corev1.DNSPolicy] | false
m| hostAliases | HostAliases is an optional list of hosts and IPs that will be injected into the pod's hosts file if specified. This is only valid for non-hostNetwork pods. m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#hostalias-v1-core[corev1.HostAlias] | false
m| hostNetwork | Host networking requested for this pod. Use the host's network namespace. If this option is set, the ports that will be used must be specified. Default to false. m| &#42;bool | false
m| hostname | Specifies the hostname of the Pod If not specified, the pod's hostname will be set to a system-defined value. m| &#42;string | false
|===

<<Table of Contents,Back to TOC>>

=== PersistenceSpec

The spec for Coherence persistence.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| mode | The persistence mode to use. Valid choices are \"on-demand\", \"active\", \"active-async\". This field will set the coherence.distributed.persistence-mode System property to \"default-\" + Mode. m| &#42;string | false
m| persistentVolumeClaim | PersistentVolumeClaim allows the configuration of a normal k8s persistent volume claim for persistence data. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#persistentvolumeclaimspec-v1-core[corev1.PersistentVolumeClaimSpec] | false
m| volume | Volume allows the configuration of a normal k8s volume mapping for persistence data instead of a persistent volume claim. If a value is defined for store.persistence.volume then no PVC will be created and persistence data will instead be written to this volume. It is up to the deployer to understand the consequences of this and how the guarantees given when using PVCs differ to the storage guarantees for the particular volume type configured here. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#volumesource-v1-core[corev1.VolumeSource] | false
m| snapshots | Snapshot values configure the on-disc persistence data snapshot (backup) settings. These settings enable a different location for persistence snapshot data. If not set then snapshot files will be written to the same volume configured for persistence data in the Persistence section. m| &#42;<<PersistentStorageSpec,PersistentStorageSpec>> | false
|===

<<Table of Contents,Back to TOC>>

=== PersistentStorageSpec

PersistenceStorageSpec defines the persistence settings for the Coherence

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| persistentVolumeClaim | PersistentVolumeClaim allows the configuration of a normal k8s persistent volume claim for persistence data. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#persistentvolumeclaimspec-v1-core[corev1.PersistentVolumeClaimSpec] | false
m| volume | Volume allows the configuration of a normal k8s volume mapping for persistence data instead of a persistent volume claim. If a value is defined for store.persistence.volume then no PVC will be created and persistence data will instead be written to this volume. It is up to the deployer to understand the consequences of this and how the guarantees given when using PVCs differ to the storage guarantees for the particular volume type configured here. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#volumesource-v1-core[corev1.VolumeSource] | false
|===

<<Table of Contents,Back to TOC>>

=== PodDNSConfig

PodDNSConfig defines the DNS parameters of a pod in addition to those generated from DNSPolicy.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| nameservers | A list of DNS name server IP addresses. This will be appended to the base nameservers generated from DNSPolicy. Duplicated nameservers will be removed. m| []string | false
m| searches | A list of DNS search domains for host-name lookup. This will be appended to the base search paths generated from DNSPolicy. Duplicated search paths will be removed. m| []string | false
m| options | A list of DNS resolver options. This will be merged with the base options generated from DNSPolicy. Duplicated entries will be removed. Resolution options given in Options will override those that appear in the base DNSPolicy. m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#poddnsconfigoption-v1-core[corev1.PodDNSConfigOption] | false
|===

<<Table of Contents,Back to TOC>>

=== PortSpecWithSSL

PortSpecWithSSL defines a port with SSL settings for a Coherence component

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| enabled | Enable or disable flag. m| &#42;bool | false
m| port | The port to bind to. m| &#42;int32 | false
m| ssl | SSL configures SSL settings for a Coherence component m| &#42;<<SSLSpec,SSLSpec>> | false
|===

<<Table of Contents,Back to TOC>>

=== Probe

Probe is the handler that will be used to determine how to communicate with a Coherence deployment for operations like StatusHA checking and service suspension. StatusHA checking is primarily used during scaling of a deployment, a deployment must be in a safe Phase HA state before scaling takes place. If StatusHA handler is disabled for a deployment (by specifically setting Enabled to false then no check will take place and a deployment will be assumed to be safe).

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| timeoutSeconds | Number of seconds after which the handler times out (only applies to http and tcp handlers). Defaults to 1 second. Minimum value is 1. m| &#42;int | false
|===

<<Table of Contents,Back to TOC>>

=== ProbeHandler

The definition of a probe handler.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| exec | One and only one of the following should be specified. Exec specifies the action to take. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#execaction-v1-core[corev1.ExecAction] | false
m| httpGet | HTTPGet specifies the http request to perform. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#httpgetaction-v1-core[corev1.HTTPGetAction] | false
m| tcpSocket | TCPSocket specifies an action involving a TCP port. TCP hooks not yet supported m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#tcpsocketaction-v1-core[corev1.TCPSocketAction] | false
|===

<<Table of Contents,Back to TOC>>

=== ReadinessProbeSpec

ReadinessProbeSpec defines the settings for the Coherence Pod readiness probe

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| exec | One and only one of the following should be specified. Exec specifies the action to take. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#execaction-v1-core[corev1.ExecAction] | false
m| httpGet | HTTPGet specifies the http request to perform. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#httpgetaction-v1-core[corev1.HTTPGetAction] | false
m| tcpSocket | TCPSocket specifies an action involving a TCP port. TCP hooks not yet supported m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#tcpsocketaction-v1-core[corev1.TCPSocketAction] | false
m| initialDelaySeconds | Number of seconds after the container has started before liveness probes are initiated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes m| &#42;int32 | false
m| timeoutSeconds | Number of seconds after which the probe times out. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes m| &#42;int32 | false
m| periodSeconds | How often (in seconds) to perform the probe. m| &#42;int32 | false
m| successThreshold | Minimum consecutive successes for the probe to be considered successful after having failed. m| &#42;int32 | false
m| failureThreshold | Minimum consecutive failures for the probe to be considered failed after having succeeded. m| &#42;int32 | false
|===

<<Table of Contents,Back to TOC>>

=== Resource



[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| kind | &#160; m| ResourceType | true
m| name | &#160; m| string | true
m| spec | &#160; m| runtime.Object | true
|===

<<Table of Contents,Back to TOC>>

=== Resources



[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| version | &#160; m| int32 | true
m| items | &#160; m| []<<Resource,Resource>> | true
|===

<<Table of Contents,Back to TOC>>

=== SSLSpec

SSLSpec defines the SSL settings for a Coherence component over REST endpoint.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| enabled | Enabled is a boolean flag indicating whether enables or disables SSL on the Coherence management over REST endpoint, the default is false (disabled). m| &#42;bool | false
m| secrets | Secrets is the name of the k8s secrets containing the Java key stores and password files. +
  This value MUST be provided if SSL is enabled on the Coherence management over ReST endpoint. + m| &#42;string | false
m| keyStore | Keystore is the name of the Java key store file in the k8s secret to use as the SSL keystore +
  when configuring component over REST to use SSL. + m| &#42;string | false
m| keyStorePasswordFile | KeyStorePasswordFile is the name of the file in the k8s secret containing the keystore +
  password when configuring component over REST to use SSL. + m| &#42;string | false
m| keyPasswordFile | KeyStorePasswordFile is the name of the file in the k8s secret containing the key +
  password when configuring component over REST to use SSL. + m| &#42;string | false
m| keyStoreAlgorithm | KeyStoreAlgorithm is the name of the keystore algorithm for the keystore in the k8s secret +
  used when configuring component over REST to use SSL. If not set the default is SunX509 + m| &#42;string | false
m| keyStoreProvider | KeyStoreProvider is the name of the keystore provider for the keystore in the k8s secret +
  used when configuring component over REST to use SSL. + m| &#42;string | false
m| keyStoreType | KeyStoreType is the name of the Java keystore type for the keystore in the k8s secret used +
  when configuring component over REST to use SSL. If not set the default is JKS. + m| &#42;string | false
m| trustStore | TrustStore is the name of the Java trust store file in the k8s secret to use as the SSL +
  trust store when configuring component over REST to use SSL. + m| &#42;string | false
m| trustStorePasswordFile | TrustStorePasswordFile is the name of the file in the k8s secret containing the trust store +
  password when configuring component over REST to use SSL. + m| &#42;string | false
m| trustStoreAlgorithm | TrustStoreAlgorithm is the name of the keystore algorithm for the trust store in the k8s +
  secret used when configuring component over REST to use SSL.  If not set the default is SunX509. + m| &#42;string | false
m| trustStoreProvider | TrustStoreProvider is the name of the keystore provider for the trust store in the k8s +
  secret used when configuring component over REST to use SSL. + m| &#42;string | false
m| trustStoreType | TrustStoreType is the name of the Java keystore type for the trust store in the k8s secret +
  used when configuring component over REST to use SSL. If not set the default is JKS. + m| &#42;string | false
m| requireClientCert | RequireClientCert is a boolean flag indicating whether the client certificate will be +
  authenticated by the server (two-way SSL) when configuring component over REST to use SSL. + +
  If not set the default is false + m| &#42;bool | false
|===

<<Table of Contents,Back to TOC>>

=== ScalingSpec

The configuration to control safe scaling.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| policy | ScalingPolicy describes how the replicas of the deployment will be scaled. The default if not specified is based upon the value of the StorageEnabled field. If StorageEnabled field is not specified or is true the default scaling will be safe, if StorageEnabled is set to false the default scaling will be parallel. m| &#42;ScalingPolicy | false
m| probe | The probe to use to determine whether a deployment is Phase HA. If not set the default handler will be used. In most use-cases the default handler would suffice but in advanced use-cases where the application code has a different concept of Phase HA to just checking Coherence services then a different handler may be specified. m| &#42;<<Probe,Probe>> | false
|===

<<Table of Contents,Back to TOC>>

=== SecretVolumeSpec

Represents a Secret that will be added to the deployment's Pods as an additional Volume and as a VolumeMount in the containers. +
see: <<misc_pod_settings/020_secret_volumes.adoc,Add Secret Volumes>>

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| name | The name of the Secret to mount. This will also be used as the name of the Volume added to the Pod if the VolumeName field is not set. m| string | true
m| mountPath | Path within the container at which the volume should be mounted.  Must not contain ':'. m| string | true
m| volumeName | The optional name to use for the Volume added to the Pod. If not set, the Secret name will be used as the VolumeName. m| string | false
m| readOnly | Mounted read-only if true, read-write otherwise (false or unspecified). Defaults to false. m| bool | false
m| subPath | Path within the volume from which the container's volume should be mounted. Defaults to \"\" (volume's root). m| string | false
m| mountPropagation | mountPropagation determines how mounts are propagated from the host to container and the other way around. When not set, MountPropagationNone is used. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#mountpropagationmode-v1-core[corev1.MountPropagationMode] | false
m| subPathExpr | Expanded path within the volume from which the container's volume should be mounted. Behaves similarly to SubPath but environment variable references $(VAR_NAME) are expanded using the container's environment. Defaults to \"\" (volume's root). SubPathExpr and SubPath are mutually exclusive. m| string | false
m| items | If unspecified, each key-value pair in the Data field of the referenced Secret will be projected into the volume as a file whose name is the key and content is the value. If specified, the listed keys will be projected into the specified paths, and unlisted keys will not be present. If a key is specified which is not present in the Secret, the volume setup will error unless it is marked optional. Paths must be relative and may not contain the '..' path or start with '..'. m| []https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#keytopath-v1-core[corev1.KeyToPath] | false
m| defaultMode | Optional: mode bits to use on created files by default. Must be a value between 0 and 0777. Defaults to 0644. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set. m| &#42;int32 | false
m| optional | Specify whether the Secret or its keys must be defined m| &#42;bool | false
|===

<<Table of Contents,Back to TOC>>

=== ServiceMonitorSpec

The ServiceMonitor spec for a port service.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| enabled | Enabled is a flag to enable or disable creation of a Prometheus ServiceMonitor for a port. If Prometheus ServiceMonitor CR is not installed no ServiceMonitor then even if this flag is true no ServiceMonitor will be created. m| &#42;bool | false
m| labels | Additional labels to add to the ServiceMonitor. More info: http://kubernetes.io/docs/user-guide/labels m| map[string]string | false
m| jobLabel | The label to use to retrieve the job name from. See https://coreos.com/operators/prometheus/docs/latest/api.html#servicemonitorspec m| string | false
m| targetLabels | TargetLabels transfers labels on the Kubernetes Service onto the target. See https://coreos.com/operators/prometheus/docs/latest/api.html#servicemonitorspec m| []string | false
m| podTargetLabels | PodTargetLabels transfers labels on the Kubernetes Pod onto the target. See https://coreos.com/operators/prometheus/docs/latest/api.html#servicemonitorspec m| []string | false
m| sampleLimit | SampleLimit defines per-scrape limit on number of scraped samples that will be accepted. See https://coreos.com/operators/prometheus/docs/latest/api.html#servicemonitorspec m| uint64 | false
m| path | HTTP path to scrape for metrics. See https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint m| string | false
m| scheme | HTTP scheme to use for scraping. See https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint m| string | false
m| params | Optional HTTP URL parameters See https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint m| map[string][]string | false
m| interval | Interval at which metrics should be scraped See https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint m| string | false
m| scrapeTimeout | Timeout after which the scrape is ended See https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint m| string | false
m| tlsConfig | TLS configuration to use when scraping the endpoint See https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint m| &#42;monitoringv1.TLSConfig | false
m| bearerTokenFile | File to read bearer token for scraping targets. See https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint m| string | false
m| bearerTokenSecret | Secret to mount to read bearer token for scraping targets. The secret needs to be in the same namespace as the service monitor and accessible by the Prometheus Operator. See https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#secretkeyselector-v1-core[corev1.SecretKeySelector] | false
m| honorLabels | HonorLabels chooses the metric's labels on collisions with target labels. See https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint m| bool | false
m| honorTimestamps | HonorTimestamps controls whether Prometheus respects the timestamps present in scraped data. See https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint m| &#42;bool | false
m| basicAuth | BasicAuth allow an endpoint to authenticate over basic authentication More info: https://prometheus.io/docs/operating/configuration/#endpoints See https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint m| &#42;monitoringv1.BasicAuth | false
m| metricRelabelings | MetricRelabelings to apply to samples before ingestion. See https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint m| []&#42;monitoringv1.RelabelConfig | false
m| relabelings | Relabelings to apply to samples before scraping. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config See https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint m| []&#42;monitoringv1.RelabelConfig | false
m| proxyURL | ProxyURL eg http://proxyserver:2195 Directs scrapes to proxy through this endpoint. See https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint m| &#42;string | false
|===

<<Table of Contents,Back to TOC>>

=== ServiceSpec



[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| enabled | Enabled controls whether to create the service yaml or not m| &#42;bool | false
m| name | An optional name to use to override the generated service name. m| &#42;string | false
m| port | The service port value m| &#42;int32 | false
m| type | Kind is the K8s service type (typically ClusterIP or LoadBalancer) The default is \"ClusterIP\". m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#servicetype-v1-core[corev1.ServiceType] | false
m| externalIPs | externalIPs is a list of IP addresses for which nodes in the cluster will also accept traffic for this service.  These IPs are not managed by Kubernetes.  The user is responsible for ensuring that traffic arrives at a node with this IP.  A common example is external load-balancers that are not part of the Kubernetes system. m| []string | false
m| clusterIP | clusterIP is the IP address of the service and is usually assigned randomly by the master. If an address is specified manually and is not in use by others, it will be allocated to the service; otherwise, creation of the service will fail. This field can not be changed through updates. Valid values are \"None\", empty string (\"\"), or a valid IP address. \"None\" can be specified for headless services when proxying is not required. Only applies to types ClusterIP, NodePort, and LoadBalancer. Ignored if type is ExternalName. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies m| &#42;string | false
m| loadBalancerIP | LoadBalancerIP is the IP address of the load balancer m| &#42;string | false
m| labels | The extra labels to add to the service. More info: http://kubernetes.io/docs/user-guide/labels m| map[string]string | false
m| annotations | Annotations is free form yaml that will be added to the service annotations m| map[string]string | false
m| sessionAffinity | Supports \"ClientIP\" and \"None\". Used to maintain session affinity. Enable client IP based session affinity. Must be ClientIP or None. Defaults to None. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#serviceaffinity-v1-core[corev1.ServiceAffinity] | false
m| loadBalancerSourceRanges | If specified and supported by the platform, this will restrict traffic through the cloud-provider load-balancer will be restricted to the specified client IPs. This field will be ignored if the cloud-provider does not support the feature.\" More info: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/ m| []string | false
m| externalName | externalName is the external reference that kubedns or equivalent will return as a CNAME record for this service. No proxying will be involved. Must be a valid RFC-1123 hostname (https://tools.ietf.org/html/rfc1123) and requires Kind to be ExternalName. m| &#42;string | false
m| externalTrafficPolicy | externalTrafficPolicy denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints. \"Local\" preserves the client source IP and avoids a second hop for LoadBalancer and Nodeport type services, but risks potentially imbalanced traffic spreading. \"Cluster\" obscures the client source IP and may cause a second hop to another node, but should have good overall load-spreading. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#serviceexternaltrafficpolicytype-v1-core[corev1.ServiceExternalTrafficPolicyType] | false
m| healthCheckNodePort | healthCheckNodePort specifies the healthcheck nodePort for the service. If not specified, HealthCheckNodePort is created by the service api backend with the allocated nodePort. Will use user-specified nodePort value if specified by the client. Only effects when Kind is set to LoadBalancer and ExternalTrafficPolicy is set to Local. m| &#42;int32 | false
m| publishNotReadyAddresses | publishNotReadyAddresses, when set to true, indicates that DNS implementations must publish the notReadyAddresses of subsets for the Endpoints associated with the Service. The default value is false. The primary use case for setting this field is to use a StatefulSet's Headless Service to propagate SRV records for its Pods without respect to their readiness for purpose of peer discovery. m| &#42;bool | false
m| sessionAffinityConfig | sessionAffinityConfig contains the configurations of session affinity. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#sessionaffinityconfig-v1-core[corev1.SessionAffinityConfig] | false
m| ipFamily | ipFamily specifies whether this Service has a preference for a particular IP family (e.g. IPv4 vs. IPv6).  If a specific IP family is requested, the clusterIP field will be allocated from that family, if it is available in the cluster.  If no IP family is requested, the cluster's primary IP family will be used. Other IP fields (loadBalancerIP, loadBalancerSourceRanges, externalIPs) and controllers which allocate external load-balancers should use the same IP family.  Endpoints for this Service will be of this family.  This field is immutable after creation. Assigning a ServiceIPFamily not available in the cluster (e.g. IPv6 in IPv4 only cluster) is an error condition and will fail during clusterIP assignment. m| &#42;https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#ipfamily-v1-core[corev1.IPFamily] | false
|===

<<Table of Contents,Back to TOC>>

=== StartQuorum

StartQuorum defines the order that deployments will be started in a Coherence cluster made up of multiple deployments.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| deployment | The name of deployment that this deployment depends on. m| string | true
m| namespace | The namespace that the deployment that this deployment depends on is installed into. Default to the same namespace as this deployment m| string | false
m| podCount | The number of the Pods that should have been started before this deployments will be started, defaults to all Pods for the deployment. m| int32 | false
|===

<<Table of Contents,Back to TOC>>

=== StartQuorumStatus

StartQuorumStatus tracks the state of a deployment's start quorums.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| deployment | The name of deployment that this deployment depends on. m| string | true
m| namespace | The namespace that the deployment that this deployment depends on is installed into. Default to the same namespace as this deployment m| string | false
m| podCount | The number of the Pods that should have been started before this deployments will be started, defaults to all Pods for the deployment. m| int32 | false
m| ready | Whether this quorum's condition has been met m| bool | true
|===

<<Table of Contents,Back to TOC>>

=== Coherence

Coherence is the Schema for the Coherence API.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#objectmeta-v1-meta[metav1.ObjectMeta] | false
m| spec | &#160; m| <<CoherenceResourceSpec,CoherenceResourceSpec>> | false
m| status | &#160; m| <<CoherenceResourceStatus,CoherenceResourceStatus>> | false
|===

<<Table of Contents,Back to TOC>>

=== CoherenceList

CoherenceList contains a list of Coherence resources.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| metadata | &#160; m| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#listmeta-v1-meta[metav1.ListMeta] | false
m| items | &#160; m| []<<Coherence,Coherence>> | true
|===

<<Table of Contents,Back to TOC>>

=== CoherenceResourceStatus

CoherenceResourceStatus defines the observed state of Coherence resource.

[cols="1,10,1,1"options="header"]
|===
| Field | Description | Type | Required
m| phase | The phase of a Coherence resource is a simple, high-level summary of where the Coherence resource is in its lifecycle. The conditions array, the reason and message fields, and the individual container status arrays contain more detail about the pod's status. There are eight possible phase values: +
 +
Initialized:    The deployment has been accepted by the Kubernetes system. Created:        The deployments secondary resources, (e.g. the StatefulSet, Services etc) have been created. Ready:          The StatefulSet for the deployment has the correct number of replicas and ready replicas. Waiting:        The deployment's start quorum conditions have not yet been met. Scaling:        The number of replicas in the deployment is being scaled up or down. RollingUpgrade: The StatefulSet is performing a rolling upgrade. Stopped:        The replica count has been set to zero. Failed:         An error occurred reconciling the deployment and its secondary resources. m| status.ConditionType | false
m| coherenceCluster | The name of the Coherence cluster that this deployment is part of. m| string | false
m| replicas | Replicas is the desired number of members in the Coherence deployment represented by the Coherence resource. m| int32 | false
m| currentReplicas | CurrentReplicas is the current number of members in the Coherence deployment represented by the Coherence resource. m| int32 | false
m| readyReplicas | ReadyReplicas is the number of number of members in the Coherence deployment represented by the Coherence resource that are in the ready state. m| int32 | false
m| role | The effective role name for this deployment. This will come from the Spec.Role field if set otherwise the deployment name will be used for the role name m| string | false
m| selector | label query over deployments that should match the replicas count. This is same as the label selector but in the string format to avoid introspection by clients. The string will be in the same format as the query-param syntax. More info about label selectors: http://kubernetes.io/docs/user-guide/labels#label-selectors m| string | false
m| conditions | The status conditions. m| status.Conditions | false
|===

<<Table of Contents,Back to TOC>>
