///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Obtain Coherence Images

Coherence images are not available from public registries such as Docker Hub and must be pulled from one of two
private registries.

== Coherence Images from Oracle Container Registry

Get the Coherence Docker image from the Oracle Container Registry:

* In a web browser, navigate to https://container-registry.oracle.com/[Oracle Container Registry] and click Sign In.
* Enter your Oracle credentials or create an account if you don't have one.
* Search for coherence in the Search Oracle Container Registry field.
* Click coherence in the search result list.
* On the Oracle Coherence page, select the language from the drop-down list and click Continue.
* Click Accept on the Oracle Standard Terms and Conditions page.

Once this is done the Oracle Container Registry credentials can be used to create Kubernetes secret to pull the
Coherence image.
See <<clusters/200_private_repos.adoc,Using Private Image Registries>>

== Coherence Images from Docker Store

* In a https://hub.docker.com/_/oracle-coherence-12c

* In a web browser, navigate to https://hub.docker.com/[Docker Hub] and click Sign In.
* Search for the official Oracle Coherence images
* Click on the `Proceed to Checkout` button
* Accept the license agreements by clicking the check boxes.
* Click the `Get Content` button

Once this is done the Docker Hub credentials can be used to create Kubernetes secret to pull the Coherence image.
See <<clusters/200_private_repos.adoc,Using Private Image Registries>>
