///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Coherence Clusters on OpenShift

== Coherence Clusters on OpenShift

Whilst the Coherence Operator will run out of the box on OpenShift some versions of the Coherence Docker
image will not work without configuration changes.

Some earlier versions of the Coherence Docker images that Oracle publishes default to the container user
as `oracle`. When running the Oracle images or layered images that retain the default user as `oracle`
with OpenShift, the `anyuid` security context constraint is required to ensure proper access to the file
system within the Docker image. Later versions of the Coherence images have been modified to work without
needing `anyuid`.


To work with older image versions , the administrator must:

* Ensure the `anyuid` security content is granted
* Ensure that Coherence containers are annotated with `openshift.io/scc: anyuid`

For example, to update the OpenShift policy, use:
[source,bash]
----
oc adm policy add-scc-to-user anyuid -z default
----

and to annotate the Coherence containers, update the `CoherenceCluster` resource to include annotations

For example:
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  annotations:
    openshift.io/scc: anyuid  # <1>
  roles:
    - role: data
      replicas: 6
----

<1> The `openshift.io/scc: anyuid` annotation will be applied to all of the Coherence Pods.

NOTE: For additional information about OpenShift requirements see the
https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html[OpenShift documentation]
