///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Coherence Operator Installation

The Coherence Operator is available as a Docker image `oracle/coherence-operator:{operator-version}` that can
easily be installed into a Kubernetes cluster.

== Prerequisites

* Access to a Kubernetes v1.12.0+ cluster.
* Access to Oracle Coherence Docker images.

NOTE: OpenShift - the Coherence Operator works without modification on OpenShift but some versions
of the Coherence images will not work out of the box.
See the <<installation/06_openshift.adoc,OpensShift>> section of the documentation that explains how to
run Coherence clusters with the Operator on OpenShift.

=== Image Pull Secrets

In order for the Coherence Operator to be able to install Coherence clusters it needs to be able to pull Coherence
Docker images. These images are not available in public Docker repositories and will typically Kubernetes will need
authentication to be able to pull them. This is achived by creating pull secrets.
Pull secrets are not global and hence secrets will be required in the namespace(s) that Coherence
clusters will be installed into.
see <<installation/04_obtain_coherence_images.adoc,Obtain Coherence Images>>

== Installing With Helm

The simplest way to install the Coherence Operator is to use the Helm chart.
This will ensure that all of the correct resources are created in Kubernetes.

=== Add the Coherence Helm Repository

Add the `coherence` helm repository using the following commands:

[source,bash]
----
helm repo add coherence https://oracle.github.io/coherence-operator/charts

helm repo update
----

=== Install the Coherence Operator Helm chart

Once the Coherence Helm repo is configured the Coherence Operator can be installed using a normal Helm install command:

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --name coherence-operator \
    coherence/coherence-operator
----

where `<namespace>` is the namespace that the Coherence Operator will be installed into and the namespace where it will
manage `Coherence` resources

==== Uninstall the Coherence Operator Helm chart

To uninstall the operator:
[source,bash]
----
helm delete --purge coherence-operator
----

