///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2022, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Coherence Operator Installation

The Coherence Operator is available as a Docker image `oracle/coherence-operator:{operator-version}` that can
easily be installed into a Kubernetes cluster.

== Coherence Operator Installation

=== Prerequisites
The prerequisites apply to all installation methods.

* Access to Oracle Coherence Operator images.
* Access to a Kubernetes v1.18.0+ cluster. The Operator test pipeline is run using Kubernetes versions v1.18 upto v1.24
* A Coherence application image using Coherence version 12.2.1.3 or later. Note that some functionality (e.g. metrics) is only
available in Coherence 12.2.1.4 and later.

NOTE: ARM Support: As of version 3.2.0, the Coherence Operator is build as a multi-architecture image that supports running in Kubernetes on both Linux/amd64 and Linux/arm64. The prerequisite is that the Coherence application image used has been built to support ARM.

There are a number of ways to install the Coherence Operator documented below:

* <<manifest,Simple installation using Kubectl>>
* <<helm,Install the Helm chart>>
* <<kubectl,Kubectl with Kustomize>>
* <<tanzu,VMWare Tanzu Package (kapp-controller)>>

=== High Availability

The Coherence Operator runs in HA mode by default. The `Deployment` created by the installation will have a replica count of 3.
In reduced capacity Kubernetes clusters, for example, local laptop development and test, the replica count can be reduced. It is recommended to leave the default of 3 for production environments.
Instructions on how to change the replica count for the different install methods are included below.

The Coherence Operator runs a REST server that the Coherence cluster members will query to discover the site and rack names that should be used by Coherence. If the Coherence Operator is not running when a Coherence Pod starts, then the Coherence member in that Pod will be unable to properly configure its site and rack names, possibly leading to data distribution that is not safely distributed over sites. In production, and in Kubernetes clusters that are spread over multiple availability zones and failure domains, it is important to run the Operator in HA mode.

The Operator yaml files and Helm chart include a default Pod scheduling configuration that uses anti-affinity to distribute the three replicas onto nodes that have different `topology.kubernetes.io/zone` labels. This label is a standard Kubernetes label used to describe the zone the node is running in, and is typically applied by Kubernetes cloud vendors.


=== Notes

NOTE: Installing the Coherence Operator using the methods below will create a number of `ClusterRole` RBAC resources.
Some corporate security policies do not like to give cluster wide roles to third-party products.
To help in this situation the operator can be installed without cluster roles, but with caveats
(see the <<docs/installation/09_RBAC.adoc,RBAC>> documentation) for more details.

NOTE: OpenShift - the Coherence Operator works without modification on OpenShift, but some versions
of the Coherence images will not work out of the box.
See the <<docs/installation/06_openshift.adoc,OpensShift>> section of the documentation that explains how to
run Coherence clusters with the Operator on OpenShift.

NOTE: Whilst Coherence works out of the box on many Kubernetes installations, some Kubernetes
installations may configure iptables in a way that causes Coherence to fail to create clusters.
See the <<docs/installation/08_networking.adoc,O/S Network Configuration>> section of the documentation
for more details if you have well-known-address issues when Pods attempt to form a cluster.

== Coherence Operator Images

The Coherence Operator uses a single images, the Operator also runs as an init-container in the Coherence cluster Pods.

* `{operator-image}` - The Operator image.

If no image is specified in the `Coherence` yaml, then the default Coherence image will also be used,

* `{coherence-image}` - The default Coherence image.

If using a private image registry then these images will all need to be pushed to that registry for the Operator to work. The default Coherence image may be omitted if all Coherence applications will use custom Coherence images.


[#manifest]
== Default Install with Kubectl

If you want the default Coherence Operator installation then the simplest solution is use `kubectl` to apply the manifests from the Operator release.

[source,bash]
----
kubectl apply -f https://github.com/oracle/coherence-operator/releases/download/v3.2.10/coherence-operator.yaml
----

This will create a namespace called `coherence` and install the Operator into it along with all the required `ClusterRole` and `RoleBinding` resources. The `coherence` namespace can be changed by downloading and editing the yaml file.

NOTE: Because the `coherence-operator.yaml` manifest also creates the namespace, the corresponding `kubectl delete` command will _remove the namespace and everything deployed to it_! If you do not want this behaviour you should edit the `coherence-operator.yaml` to remove the namespace section from the start of the file.

Instead of using a hard coded version in the command above you can find the latest Operator version using `curl`:

[source,bash]
----
export VERSION=$(curl -s \
  https://api.github.com/repos/oracle/coherence-operator/releases/latest \
  | grep '"name": "v' \
  | cut -d '"' -f 4 \
  | cut -b 2-10)
----

Then download with:
[source,bash]
----
kubectl apply -f https://github.com/oracle/coherence-operator/releases/download/${VERSION}/coherence-operator.yaml
----

=== Change the Operator Replica Count

When installing with single manifest yaml file, the replica count can be changed by editing the yaml file itself to change the occurrence of `replicas: 3` in the manifest yaml to `replicas: 1`

For example, this could be done using `sed`
[source,bash]
----
sed -i -e 's/replicas: 3/replicas: 1/g' coherence-operator.yaml
----

Or on MacOS, where `sed` is slightly different:
[source,bash]
----
sed -i '' -e 's/replicas: 3/replicas: 1/g' coherence-operator.yaml
----


== Installing With Helm

For more flexibility but the simplest way to install the Coherence Operator is to use the Helm chart.
This ensures that all the correct resources will be created in Kubernetes.

[#helm]
=== Add the Coherence Helm Repository

Add the `coherence` helm repository using the following commands:

[source,bash]
----
helm repo add coherence https://oracle.github.io/coherence-operator/charts

helm repo update
----

NOTE: To avoid confusion, the URL `https://oracle.github.io/coherence-operator/charts` is a Helm repo, it is not a website you open in a browser. You may think we shouldn't have to say this, but you'd be surprised.

=== Install the Coherence Operator Helm chart

Once the Coherence Helm repo has been configured the Coherence Operator can be installed using a normal Helm 3
install command:

[source,bash]
----
helm install  \
    --namespace <namespace> \      <1>
    coherence \                    <2>
    coherence/coherence-operator
----

<1> where `<namespace>` is the namespace that the Coherence Operator will be installed into.
<2> `coherence` is the name of this Helm installation.

=== Change the Operator Replica Count

To change the replica count when installing the Operator using Helm, the `replicas` value can be set.

For example, to change the replica count from 3 to 1, the `--set replicas=1` option can be used.

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --set replicas=1
    coherence \
    coherence/coherence-operator
----

=== Run the Operator as a Non-Root User

The Operator container can be configured with a `securityContext` so that it runs as a non-root user.

This can be done using a values file:

[source,yaml]
.security-values.yaml
----
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
----

Then the `security-values.yaml` values file above can be used in the Helm install command.

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --values security-values.yaml \
    coherence \
    coherence/coherence-operator
----

Alternatively, the `securityContext` values can be set on the command line as `--set` parameters:

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --set securityContext.runAsNonRoot=true \
    --set securityContext.runAsUser=1000 \
    coherence \
    coherence/coherence-operator
----


=== Uninstall the Coherence Operator Helm chart

To uninstall the operator:
[source,bash]
----
helm delete coherence-operator --namespace <namespace>
----

== Operator Scope

The recommended way to install the Coherence Operator is to install a single instance of the operator into a namespace
and where it will then control `Coherence` resources in all namespaces across the Kubernetes cluster.
Alternatively it may be configured to watch a sub-set of namespaces by setting the `WATCH_NAMESPACE` environment variable.
The watch namespace(s) does not have to include the installation namespace.

In theory, it is possible to install multiple instances of the Coherence Operator into different namespaces, where
each instances monitors a different set of namespaces. There are a number of potential issues with this approach, so
it is not recommended.

* Only one CRD can be installed - Different releases of the Operator may use slightly different CRD versions, for example
a new version may introduce extra fields not in the previous version. As the CRD version is `v1` there is no guarantee
which CRD version has actually installed, which could lead to subtle issues.
* The operator creates and installs defaulting and validating web-hooks. A web-hook is associated to a CRD resource so
installing multiple web-hooks for the same resource may lead to issues. If an operator is uninstalled, but the web-hook
configuration remains, then Kubernetes will not accept modifications to resources of that type as it will be
unable to contact the web-hook.

To set the watch namespaces when installing with helm set the `watchNamespaces` value, for example:

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --set watchNamespaces=payments,catalog,customers <1>
    coherence-operator \
    coherence/coherence-operator
----

<1> The `payments`, `catalog` and `customers` namespaces will be watched by the Operator.

== Operator Image

The Helm chart uses a default registry to pull the Operator image from.
If the image needs to be pulled from a different location (for example an internal registry) then the `image` field
in the values file can be set, for example:

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --set image=images.com/coherence-operator:0.1.2 <1>
    coherence-operator \
    coherence/coherence-operator
----

<1> The image used to run the Operator will be `images.com/coherence-operator:0.1.2`.

=== Image Pull Secrets

If the image is to be pulled from a secure repository that requires credentials then the image pull secrets
can be specified.
See the Kubernetes documentation on https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/[Pulling from a Private Registry].

==== Add Pull Secrets Using a Values File

Create a values file that specifies the secrets, for example the `private-repo-values.yaml` file below:

[source,yaml]
.private-repo-values.yaml
----
imagePullSecrets:
- name: registry-secrets
----

Now use that file in the Helm install command:

[source,bash]
----
helm install  \
    --namespace <namespace> \
    -f private-repo-values.yaml <1>
    coherence-operator \
    coherence/coherence-operator
----
<1> the `private-repo-values.yaml` values fle will be used by Helm to inject the settings into the Operator deployment

==== Add Pull Secrets Using --set

Although the `imagePullSecrets` field in the values file is an array of `name` to value pairs it is possible to set
these values with the normal Helm `--set` parameter.

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --set imagePullSecrets[0].name=registry-secrets <1>
    coherence-operator \
    coherence/coherence-operator
----

<1> this creates the same imagePullSecrets as the values file above.

[#kubectl]
== Install with Kubectl and Kustomize

If you want to use yaml directly to install the operator, with something like `kubectl`, you can use the manifest files
published with the GitHub release at this link:
https://github.com/oracle/coherence-operator/releases/download/v3.2.10/coherence-operator-manifests.tar.gz[3.2.10 Manifests]

These manifest files are for use with a tool called Kustomize, which is built into `kubectl`
see the documentation here: https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/

Download the
https://github.com/oracle/coherence-operator/releases/download/v3.2.10/coherence-operator-manifests.tar.gz[3.2.10 Manifests]
from the release page and unpack the file, which should produce a directory called `manifests` with a structure like this:

[source]
----
manifests
    default
        config.yaml
        kustomization.yaml
    manager
        kustomization.yaml
        manager.yaml
        service.yaml
    rbac
        coherence_editor_role.yaml
        coherence_viewer_role.yaml
        kustomization.yaml
        leader_election_role.yaml
        leader_election_role_binding.yaml
        role.yaml
        role_binding.yaml
----

There are two ways to use these manifest files, either install using `kustomize` or generate the yaml and manually
install with `kubectl`.

NOTE: All the commands below are run from a console in the `manifests/` directory from the extracted file above.

=== Install with Kustomize

If you have Kustomize installed (or can install it from https://github.com/kubernetes-sigs/kustomize) you can use
Kustomize to configure the yaml and install.

==== Change the Operator Replica Count

To change the replica count using Kustomize a patch file needs to be applied.
The Operator manifests include a patch file, named `manager/single-replica-patch.yaml`, that changes the replica count from 3 to 1. This patch can be applied with the following Kustomize command.

[source,bash]
----
cd ./manager && kustomize edit add patch \
  --kind Deployment --name controller-manager \
  --path single-replica-patch.yaml
----


==== Set Image Names
If you need to use different iamge names from the defaults `kustomize` can be used to specify different names:

Change the name of the Operator image by running the command below, changing the image name to the registry and image name
that you are using for the Operator, for example if you have the images in a custom registry
[source,bash]
----
cd ./manager && kustomize edit set image controller=myregistry/coherence-operator:3.2.10
----

Change the name of the Operator image by running the command below, changing the image name to the registry and image name
that you are using for the Operator utilities image
[source,bash]
----
cd ./manager && kustomize edit add configmap env-vars --from-literal OPERATOR_IMAGE=myregistry/coherence-operator:3.2.10
----

Change the name of the default Coherence image. If you are always going to be deploying your own application images then this
does not need to change.
[source,bash]
----
cd ./manager && $(GOBIN)/kustomize edit add configmap env-vars --from-literal COHERENCE_IMAGE=$(COHERENCE_IMAGE)
----

Set the namespace to install into, the example below sets the namespace to `coherence-test`:
[source,bash]
----
cd ./default && /kustomize edit set namespace coherence-test
----

==== Install

The Operator requires a `Secret` for its web-hook certificates. This `Secret` needs to exist but can be empty.
The `Secret` must be in the same namespace that the Operator will be deployed to.
For example, if the Operator namespace is `coherence-test`, then the `Secret` can be created with this command:

[source,bash]
----
kubectl -n coherence-test create secret generic coherence-webhook-server-cert
----

The Operator can now be installed by running the following command from the `manifests` directory:
[source,bash]
----
kustomize build ./default | kubectl apply -f -
----

=== Generate Yaml - Install with Kubectl

Instead of using Kustomize to modify and install the Operator we can use `kubectl` to generate the yaml from the manifests.
You can then edit this yaml and manually deploy it with `kubectl`.

Run the following command from the `manifests` directory:
[source,bash]
----
kubectl create --dry-run -k default/ -o yaml > operator.yaml
----

This will create a file in the `manifests` directory called `operator.yaml` that contains all the yaml required
to install the Operator. You can then edit this yaml to change image names or add other settings.

The Operator can be installed using the generated yaml.

For example if the Operator is to be deployed to the `coherence-test` namespace:
[source,bash]
----
kubectl -n coherence-test create secret generic coherence-webhook-server-cert
kubectl -n coherence-test create -f operator.yaml
----


[#tanzu]
== Install as a VMWare Tanzu Package (Carvel kapp-controller)

If using https://tanzucommunityedition.io[VMWare Tanzu] the Coherence Operator can be installed as a package.
Under the covers, Tanzu uses the https://carvel.dev[Carvel] tool set to deploy packages.
The Carvel tools can be used outside Tanzu, so the Coherence Operator repo and package images could also be deployed
using a standalone Carvel https://carvel.dev/kapp-controller/[kapp-controller].

The Coherence Operator release published two images required to deploy the Operator as a Tanzu package.

* `ghcr.io/oracle/coherence-operator-package:{operator-version}` - the Coherence Operator package
* `ghcr.io/oracle/coherence-operator-repo:{operator-version}` - the Coherence Operator repository

=== Install the Coherence Repository

The first step to deploy the Coherence Operator package in Tanzu is to add the repository.
This can be done using the Tanzu CLI.

[source,bash]
----
tanzu package repository add coherence-repo \
    --url ghcr.io/oracle/coherence-operator-repo:3.2.10 \
    --namespace coherence \
    --create-namespace
----

The installed repositories can be listed using the CLI:

[source,bash]
----
tanzu package repository list --namespace coherence
----

which should display something like the following
[source,bash]
----
NAME            REPOSITORY                              TAG  STATUS               DETAILS
coherence-repo  ghcr.io/oracle/coherence-operator-repo  1h   Reconcile succeeded
----

The available packages in the Coherence repository can also be displayed using the CLI

[source,bash]
----
tanzu package available list --namespace coherence
----

which should include the Operator package, `coherence-operator.oracle.github.com` something like the following
[source,bash]
----
NAME                                  DISPLAY-NAME               SHORT-DESCRIPTION                                             LATEST-VERSION
coherence-operator.oracle.github.com  Oracle Coherence Operator  A Kubernetes operator for managing Oracle Coherence clusters  3.2.10
----

=== Install the Coherence Operator Package

Once the Coherence Operator repository has been installed, the `coherence-operator.oracle.github.com` package can be installed, which will install the Coherence Operator itself.

[source,bash]
----
tanzu package install coherence \
    --package-name coherence-operator.oracle.github.com \
    --version 3.2.10 \
    --namespace coherence
----

The Tanzu CLI will display the various steps it is going through to install the package and if all goes well, finally display `Added installed package 'coherence'`
The packages installed in the `coherence` namespace can be displayed using the CLI.

[source,bash]
----
tanzu package installed list --namespace coherence
----

which should display the Coherence Operator package.
[source,bash]
----
NAME       PACKAGE-NAME                          PACKAGE-VERSION  STATUS
coherence  coherence-operator.oracle.github.com  3.2.10            Reconcile succeeded
----

The Operator is now installed and ready to mage Coherence clusters.