///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2021, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Coherence Operator Installation

The Coherence Operator is available as a Docker image `oracle/coherence-operator:{operator-version}` that can
easily be installed into a Kubernetes cluster.

== Coherence Operator Installation

=== Prerequisites
The prerequisites apply to all installation methods.

* Access to Oracle Coherence Operator images.
* Access to a Kubernetes v1.16.0+ cluster. The Operator test pipeline is run using Kubernetes versions v1.16 upto v1.21
* A Coherence application image using Coherence version 12.2.1.3 or later. Note that some functionality (e.g. metrics) is only
available in Coherence 12.2.1.4 and later.

NOTE: ARM Support: As of version 3.2.0, the Coherence Operator is build as a multi-architecture image that supports running in Kubernetes on both Linux/amd64 and Linux/arm64. The prerequisite is that the Coherence application image used has been built to support ARM.

There are a few ways to install the Coherence Operator documented below:

* <<manifest,Simple installation using Kubectl>>
* <<helm,Install the Helm chart>>
* <<kubectl,Kubectl with Kustomize>>

NOTE: Installing the Coherence Operator using the methods above will create a number of `ClusterRole` RBAC resources.
Some corporate security policies do not like to give cluster wide roles to third-party products.
To help in this situation the operator can be installed without cluster roles, but with caveats
(see the <<docs/installation/09_RBAC.adoc,RBAC>> documentation) for more details.

NOTE: OpenShift - the Coherence Operator works without modification on OpenShift, but some versions
of the Coherence images will not work out of the box.
See the <<docs/installation/06_openshift.adoc,OpensShift>> section of the documentation that explains how to
run Coherence clusters with the Operator on OpenShift.

NOTE: Whilst Coherence works out of the box on many Kubernetes installations, some Kubernetes
installations may configure iptables in a way that causes Coherence to fail to create clusters.
See the <<docs/installation/08_networking.adoc,O/S Network Configuration>> section of the documentation
for more details if you have well-known-address issues when Pods attempt to form a cluster.

[WARNING]
====
*Upgrading from version 3.1.0*

Due to a CRD incompatibility that was initially un-noticed in v3.1.0 we deprecated v3.1.0 and recommended that
it not be used.
If you did install v3.1.0 and are upgrading to the latest version you must manually uninstall the
`coherences.coherence.oracle.com` CRD from your Kubernetes cluster before installing the new Operator version.

[source,bash]
----
kubectl delete crd coherences.coherence.oracle.com
----

Note that the CRD name in the 3.1.0 CRD being uninstalled has a plural `coherences` for the first part of the name.
====

[#manifest]
== Default Install with Kubectl

If you want the default Coherence Operator installation then the simplest solution is use `kubectl` to apply the manifests from the Operator release.

[source,bash]
----
kubectl apply -f https://github.com/oracle/coherence-operator/releases/download/v3.2.5/coherence-operator.yaml
----

This will create a namespace called `coherence` and install the Operator into it along with all the required `ClusterRole` and `RoleBinding` resources. The `coherence` namespace can be changed by downloading and editing the yaml file.

NOTE: Because the `coherence-operator.yaml` manifest also creates the namespace, the corresponding `kubectl delete` command will _remove the namespace and everything deployed to it_! If you do not want this behaviour you should edit the `coherence-operator.yaml` to remove the namespace section from the start of the file.

Instead of using a hard coded version in the command above you can find the latest Operator version using `curl`:

[source,bash]
----
export VERSION=$(curl -s \
  https://api.github.com/repos/oracle/coherence-operator/releases/latest \
  | grep '"name": "v' \
  | cut -d '"' -f 4 \
  | cut -b 2-10)
----

Then download with:
[source,bash]
----
kubectl apply -f https://github.com/oracle/coherence-operator/releases/download/${VERSION}/coherence-operator.yaml
----



== Installing With Helm

For more flexibility but the simplest way to install the Coherence Operator is to use the Helm chart.
This ensures that all the correct resources will be created in Kubernetes.

[#helm]
=== Add the Coherence Helm Repository

Add the `coherence` helm repository using the following commands:

[source,bash]
----
helm repo add coherence https://oracle.github.io/coherence-operator/charts

helm repo update
----

NOTE: To avoid confusion, the URL `https://oracle.github.io/coherence-operator/charts` is a Helm repo, it is not a web site you open in a browser. You may think we shouldn't have to say this, but you'd be surprised.

=== Install the Coherence Operator Helm chart

Once the Coherence Helm repo has been configured the Coherence Operator can be installed using a normal Helm 3
install command:

[source,bash]
----
helm install  \
    --namespace <namespace> \      <1>
    coherence \                    <2>
    coherence/coherence-operator
----

<1> where `<namespace>` is the namespace that the Coherence Operator will be installed into.
<2> `coherence` is the name of this Helm installation.


==== Uninstall the Coherence Operator Helm chart

To uninstall the operator:
[source,bash]
----
helm delete coherence-operator --namespace <namespace>
----

== Operator Scope

The recommended way to install the Coherence Operator is to install a single instance of the operator into a namespace
and where it will then control `Coherence` resources in all namespaces across the Kubernetes cluster.
Alternatively it may be configured to watch a sub-set of namespaces by setting the `WATCH_NAMESPACE` environment variable.
The watch namespace(s) does not have to include the installation namespace.

In theory, it is possible to install multiple instances of the Coherence Operator into different namespaces, where
each instances monitors a different set of namespaces. There are a number of potential issues with this approach, so
it is not recommended.

* Only one CRD can be installed - Different releases of the Operator may use slightly different CRD versions, for example
a new version may introduce extra fields not in the previous version. As the CRD version is `v1` there is no guarantee
which CRD version has actually installed, which could lead to subtle issues.
* The operator creates and installs defaulting and validating web-hooks. A web-hook is associated to a CRD resource so
installing multiple web-hooks for the same resource may lead to issues. If an operator is uninstalled, but the web-hook
configuration remains, then Kubernetes will not accept modifications to resources of that type as it will be
unable to contact the web-hook.

To set the watch namespaces when installing with helm set the `watchNamespaces` value, for example:

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --set watchNamespaces=payments,catalog,customers <1>
    coherence-operator \
    coherence/coherence-operator
----

<1> The `payments`, `catalog` and `customers` namespaces will be watched by the Operator.

== Operator Image

The Helm chart uses a default registry to pull the Operator image from.
If the image needs to be pulled from a different location (for example an internal registry) then the `image` field
in the values file can be set, for example:

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --set image=images.com/coherence-operator:0.1.2 <1>
    coherence-operator \
    coherence/coherence-operator
----

<1> The image used to run the Operator will be `images.com/coherence-operator:0.1.2`.

=== Image Pull Secrets

If the image is to be pulled from a secure repository that requires credentials then the image pull secrets
can be specified.
See the Kubernetes documentation on https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/[Pulling from a Private Registry].

==== Add Pull Secrets Using a Values File

Create a values file that specifies the secrets, for example the `private-repo-values.yaml` file below:

[source,yaml]
.private-repo-values.yaml
----
imagePullSecrets:
- name: registry-secrets
----

Now use that file in the Helm install command:

[source,bash]
----
helm install  \
    --namespace <namespace> \
    -f private-repo-values.yaml <1>
    coherence-operator \
    coherence/coherence-operator
----
<1> the `private-repo-values.yaml` values fle will be used by Helm to inject the settings into the Operator deployment

==== Add Pull Secrets Using --Set

Although the `imagePullSecrets` field in the values file is an array of `name` to value pairs it is possible to set
these values with the normal Helm `--set` parameter.

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --set imagePullSecrets[0].name=registry-secrets <1>
    coherence-operator \
    coherence/coherence-operator
----

<1> this creates the same imagePullSecrets as the values file above.

[#kubectl]
== Install with Kubectl and Kustomize

If you want to use yaml directly to install the operator, with something like `kubectl`, you can use the manifest files
published with the GitHub release at this link:
https://github.com/oracle/coherence-operator/releases/download/v3.2.5/coherence-operator-manifests.tar.gz[3.2.5 Manifests]

These manifest files are for use with a tool called Kustomize, which is built into `kubectl`
see the documentation here: https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/

Download the
https://github.com/oracle/coherence-operator/releases/download/v3.2.5/coherence-operator-manifests.tar.gz[3.2.5 Manifests]
from the release page and unpack the file, which should produce a directory called `manifests` with a structure like this:

[source]
----
manifests
    default
        config.yaml
        kustomization.yaml
    manager
        kustomization.yaml
        manager.yaml
        service.yaml
    rbac
        coherence_editor_role.yaml
        coherence_viewer_role.yaml
        kustomization.yaml
        leader_election_role.yaml
        leader_election_role_binding.yaml
        role.yaml
        role_binding.yaml
----

There are two ways to use these manifest files, either install using `kustomize` or generate the yaml and manually
install with `kubectl`.

NOTE: All the commands below are run from a console in the `manifests/` directory from the extracted file above.

=== Install with Kustomize

If you have Kustomize installed (or can install it from https://github.com/kubernetes-sigs/kustomize) you can use
Kustomize to configure the yaml and install.

==== Set Image Names
If you need to use different iamge names from the defaults `kustomize` can be used to specify different names:

Change the name of the Operator image by running the command below, changing the image name to the registry and image name
that you are using for the Operator, for example if you have the images in a custom registry
[source,bash]
----
cd ./manager && kustomize edit set image controller=myregistry/coherence-operator:3.2.5
----

Change the name of the Operator utilities image by running the command below, changing the image name to the registry and image name
that you are using for the Operator utilities image
[source,bash]
----
cd ./manager && kustomize edit add configmap env-vars --from-literal UTILS_IMAGE=myregistry/coherence-operator:3.2.5-utils
----

Change the name of the default Coherence image. If you are always going to be deploying your own application images then this
does not need to change.
[source,bash]
----
cd ./manager && $(GOBIN)/kustomize edit add configmap env-vars --from-literal COHERENCE_IMAGE=$(COHERENCE_IMAGE)
----

Set the namespace to install into, the example below sets the namespace to `coherence-test`:
[source,bash]
----
cd ./default && /kustomize edit set namespace coherence-test
----

==== Install

The Operator requires a `Secret` for its web-hook certificates. This `Secret` needs to exist but can be empty.
The `Secret` must be in the same namespace that the Operator will be deployed to.
For example, if the Operator namespace is `coherence-test`, then the `Secret` can be created with this command:

[source,bash]
----
kubectl -n coherence-test create secret generic coherence-webhook-server-cert
----

The Operator can now be installed by running the following command from the `manifests` directory:
[source,bash]
----
kustomize build ./default | kubectl apply -f -
----

=== Generate Yaml - Install with Kubectl

Instead of using Kustomize to modify and install the Operator we can use `kubectl` to generate the yaml from the manifests.
You can then edit this yaml and manually deploy it with `kubectl`.

Run the following command from the `manifests` directory:
[source,bash]
----
kubectl create --dry-run -k default/ -o yaml > operator.yaml
----

This will create a file in the `manifests` directory called `operator.yaml` that contains all the yaml required
to install the Operator. You can then edit this yaml to change image names or add other settings.

The Operator can be installed using the generated yaml.

For example if the Operator is to be deployed to the `coherence-test` namespace:
[source,bash]
----
kubectl -n coherence-test create secret generic coherence-webhook-server-cert
kubectl -n coherence-test create -f operator.yaml
----
