///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2025 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Accessing Pre-Release Versions
:description: Coherence Operator Documentation - Accessing Pre-Release Versions
:keywords: oracle coherence, kubernetes, operator, documentation, Accessing Pre-Release Versions

Pre-release version of the Coherence Operator are made available from time to time.

== Accessing Pre-Release Versions

WARNING: We cannot guarantee that pre-release versions of the Coherence Operator are bug free and hence they should
not be used in production.
We reserve the right to remove pre-release versions of the Helm chart and Docker images ant any time and without notice.
We cannot guarantee that APIs and CRD specifications will remain stable or backwards compatible between pre-release versions.

To access pre-release versions of the Helm chart add the unstable chart repository.

[source,bash]
----
helm repo add coherence-unstable https://oracle.github.io/coherence-operator/charts-unstable

helm repo update
----


To list all the available Coherence Operator chart versions:
[source,bash]
----
helm search coherence-operator -l
----
The `-l` parameter shows all versions as opposed to just the latest versions if it was omitted.


A specific pre-release version of the Helm chart can be installed using the `--version` argument,
for example to use version `3.0.0-2005140315`:
[source,bash]
----
helm install coherence-unstable/coherence-operator \
    --version 3.0.0-2005140315 \   <1>
    --namespace <namespace> \      <2>
    --name coherence-operator
----

<1> The `--version` argument is used to specify the exact version of the chart
<2> The optional `--namespace` parameter to specify which namespace to install the operator into, if omitted then
Helm will install into whichever is currently the default namespace for your Kubernetes configuration.

NOTE: When using pre-release versions of the Helm chart it is always advisable to install a specific version otherwise
Helm will try to work out the latest version in the pre-release repo and as pre-release version numbers are not strictly
sem-ver compliant this may be unreliable.

