///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Obtain Coherence Images

For most use-cases we expect the developer to provide a suitable Coherence application image to be
run by the operator. For POCs, demos and experimentation the Coherence Operator uses the OSS Coherence CE image as
the image to run when no image has been specified for a `Coherence` resource.
Commercial Coherence images are not available from public image registries and must be pulled from the
middleware section of https://container-registry.oracle.com[Oracle Container Registry.]

== Coherence Images from Oracle Container Registry

Get the Coherence Docker image from the Oracle Container Registry:

* In a web browser, navigate to https://container-registry.oracle.com/[Oracle Container Registry] and click Sign In.
* Enter your Oracle credentials or create an account if you don't have one.
* Search for coherence in the Search Oracle Container Registry field.
* Click coherence in the search result list.
* On the Oracle Coherence page, select the language from the drop-down list and click Continue.
* Click Accept on the Oracle Standard Terms and Conditions page.

Once this is done the Oracle Container Registry credentials can be used to create Kubernetes secret to pull the
Coherence image.

== Use ImagePullSecrets

Kubernetes supports configuring pods to use `imagePullSecrets` for pulling images. If possible, this is the preferable
and most portable route.
See the https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod[kubernetes docs]
for this.

Once secrets have been created in the namespace that the `Coherence` resource is to be installed in then the secret name
can be specified in the `Coherence` CRD `spec`. It is possible to specify multiple secrets in the case where the different
images being used are pulled from different registries.

For example to use the commercial Coherence 14.1.1.0.0 image from OCR specify the image and image pull secrets in
the `Coherence` resource yaml
[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: test-cluster
spec:
  image: container-registry.oracle.com/middleware/coherence:14.1.1.0.0
  imagePullSecrets:
    - name: coherence-secret  # <1>
----

<1> The `coherence-secret` will be used for pulling images from the registry associated to the secret

Also see <<docs/installation/05_private_repos.adoc,Using Private Image Registries>>
