///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2024, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Operator Web-Hooks

== Operator Web-Hooks

The Coherence Operator uses Kubernetes
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/[dynamic admission control]
commonly known as defaulting and validating web-hooks. As the name implies, these are used to provide default values
for some fields in a `Coherence` resource and to also validate `Coherence` resources on creation and update.
The operator creates and configures the two web-hooks when it starts.


=== Webhook Scope

Webhooks in Kubernetes are a cluster resource, not a namespaced scoped resource, so consequently there is typically only
a single webhook installed for a given resource type. If the Coherence Operator has been installed as a cluster scoped
operator then this is not a problem but if multiple Coherence Operators have been deployed then they could all attempt
to install the webhooks and update or overwrite a previous configuration.
This might not be an issue if all the operators deployed in a Kubernetes cluster are the same version but different
versions could cause issues.
This is one of the reasons that it is recommended to install a single cluster scoped Coherence Operator.

== Manage Web-Hook Certificates

A web-hook requires certificates to be able to work in Kubernetes.
By default, the operator will create and manage self-signed certificates for this purpose.
These certificates are created using the Kubernetes certificate
It is possible to use other certificates, either managed by the
https://cert-manager.io/docs/installation/kubernetes/[Kubernetes cert-manager] or managed manually.

The certificates should be stored in a `Secret` named `coherence-webhook-server-cert` in the same namespace that
the operator has installed in. (although this name can be changed if required). This `Secret` must exist, or the operator
wil fail to start. The Operator Helm chart will create this `Secret` when the Operator is managing its own self-signed
certs, otherwise the `Secret` must be created manually or by an external certificate manager.

=== Self-Signed Certificates

This is the default option, the operator will create and manage a set of self-signed certificates.
The Operator will update the `Secret` with its certificates and create the `MutatingWebhookConfiguration` and
`ValidatingWebhookConfiguration` resources configured to use those certificates.

=== Cert Manager (Self-Signed)

Assuming https://cert-manager.io/docs/installation/kubernetes/[Kubernetes Cert Manager] has been installed in the
Kubernetes cluster then to use it for managing the web-hook certificates,
the Operator needs to be installed with the `CERT_TYPE` environment variable set to `cert-manager`.

The Operator will then detect the version of Cert Manager and automatically create the required self-signed `Issuer`
and `Certificate` resources. Cert Manager will detect these and create the `Secret`. This may cause the operator Pod to
re-start until the `Secret` has been created.

==== Install Using Manifest File

If installing the operator using the manifest yaml file first replace the occurrences of `self-signed` in the yaml file with `cert-manager`.

For example:
[source,bash]
----
curl -L https://github.com/oracle/coherence-operator/releases/download/v3.4.3/coherence-operator.yaml \
    -o coherence-operator.yaml
sed -i s/self-signed/cert-manager/g coherence-operator.yaml
kubectl apply -f coherence-operator.yaml
----

[NOTE]
====
On MacOS the `sed` command is slightly different for in-place replacement
and requires an empty string after the `-i` parameter:

[source,bash]
----
sed -i '' s/self-signed/cert-manager/g coherence-operator.yaml
----
====

==== Install Using Helm

To set the certificate manager to use when installing the Helm chart, set the `webhookCertType` value:

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --set webhookCertType=cert-manager <1>
    coherence-operator \
    coherence/coherence-operator
----

<1> The certificate manager will be set to `cert-manager`


=== Manual Certificates

If certificates will be managed some other way (for example by Cert Manager managing real certificates) then the
`CERT_TYPE` environment variable should be set to `manual`.

A `Secret` must exist in the namespace the operator will be installed into containing the CA certificate, certificate
and key files that the operator will use to configure the web-hook. The files must exist with the names expected by the operator.
The default name of the `Secret` expected by the operator is `coherence-webhook-server-cert` but this can be changed.

The certificates in the `Secret` must be valid for the `Service` name that exposes the Coherence web-hook.
The default format of the DNS used for the certificate CN (common name) is `coherence-operator-webhook.<namespace>.svc`
where `<namespace>` is the namespace the operator is installed into.
Additional names may also be configured using the different formats of Kubernetes `Service` DNS names.

For example, if the Operator is installed into a namespace named `coherence` the `Service` DNS names would be:

[source]
----
  - coherence-operator-webhook.coherence
  - coherence-operator-webhook.coherence.svc
  - coherence-operator-webhook.coherence.svc.cluster.local
----

An example of the format of the `Secret` is shown below:

[source,yaml]
.sh
----
apiVersion: v1
kind: Secret
metadata:
  name: coherence-webhook-server-cert
type: Opaque
data:
  ca.crt: ... # <base64 endocde CA certificate file>
  tls.crt: ... # <base64 endocde certificate file>
  tls.key: ... # <base64 endocde private key file>
----

[WARNING]
====
If a `Secret` with the name specified in `webhookCertSecret` does not exist in the namespace the operator
is being installed into then the operator Pod will not start as the `Secret` will be mounted as a volume
in the operator Pod.
====

==== Install Using Manifest File

If installing the operator using the manifest yaml file first replace the occurrences of `self-signed` in the yaml file with `cert-manager`.

For example:
[source,bash]
----
curl -L https://github.com/oracle/coherence-operator/releases/download/v3.3.5/coherence-operator.yaml \
    -o coherence-operator.yaml
sed -i s/self-signed/manual/g coherence-operator.yaml
kubectl apply -f coherence-operator.yaml
----

[NOTE]
====
On MacOS the `sed` command is slightly different for in-place replacement
and requires an empty string after the `-i` parameter:

[source,bash]
----
sed -i '' s/self-signed/cert-manager/g coherence-operator.yaml
----
====

==== Install Using Helm

To configure the operator to use manually managed certificates when installing the Helm chart,
set the `webhookCertType` value.

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --set webhookCertType=manual \ <1>
    coherence-operator \
    coherence/coherence-operator
----

<1> The certificate manager will be set to `manual` and the operator will expect to find a `Secret` named `coherence-webhook-server-cert`


To use manually managed certificates and store the keys and certs in a different secret, set the secret
name using the `webhookCertSecret` value.

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --set webhookCertType=manual \ <1>
    --set webhookCertSecret=operator-certs \ <2>
    coherence-operator \
    coherence/coherence-operator
----

<1> The certificate manager will be set to `manual`
<2> The name of the secret is set to `operator-certs`

The Coherence Operator will now expect to find the keys and certs in a `Secret` named `operator-certs` in
the same namespace that the Operator is deployed into.

[#no-hooks]
=== Install the Operator Without Web-Hooks

It is possible to start the Operator without it registering any web-hooks with the API server.

[CAUTION]
====
Running the Operator without web-hooks is not recommended.
The admission web-hooks validate the `Coherence` resource yaml before it gets into the k8s cluster.
Without the web-hooks, invalid yaml will be accepted by k8s and the Operator will then log errors
when it tries to reconcile invalid yaml. Or worse, the Operator will create an invalid `StatefulSet`
which will then fail to start.
====

==== Install Using Manifest File

If installing using the manifest yaml files, then you need to edit the `coherence-operator.yaml` manifest to add a
command line argument to the Operator.

Update the `controller-manager` deployment and add an argument, edit the section that looks like this:
[source,yaml]
----
        args:
          - operator
          - --enable-leader-election
----

and add the additional `--enable-webhook=false` argument like this:

[source,yaml]
----
        args:
          - operator
          - --enable-leader-election
          - --enable-webhook=false
----


apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager


==== Installing Using Helm

If installing the Operator using Helm, the `webhooks` value can be set to false in the values file or
on the command line.

[source,bash]
----
helm install  \
    --namespace <namespace> \
    --set webhooks=false \
    coherence-operator \
    coherence/coherence-operator
----
