///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= O/S Networking Configuration

== O/S Networking Configuration

=== Operating System Library Requirements

In order for Coherence clusters to form correctly, the `conntrack` library
must be installed.  Most Kubernetes distributions will do this for you.
If you have issues with clusters not forming, then you should check that
`conntrack` is installed using this command (or equivalent):

[source,bash]
----
rpm -qa | grep conntrack
----

You should see output similar to that shown below.  If you do not, then you
should install `conntrack` using your operating system tools.

[source,bash]
----
libnetfilter_conntrack-1.0.6-1.el7_3.x86_64
conntrack-tools-1.4.4-4.el7.x86_64
----


=== Firewall (iptables) Requirements

Some Kubernetes distributions create `iptables` rules that block some
types of traffic that Coherence requires to form clusters.  If you are
not able to form clusters, then you can check for this issue using the
following command:

[source,bash]
----
iptables -t nat -v  -L POST_public_allow -n
----

If you see output similar to the example below:

[source,bash]
----
Chain POST_public_allow (1 references)
pkts bytes target     prot opt in     out     source               destination
164K   11M MASQUERADE  all  --  *      !lo     0.0.0.0/0            0.0.0.0/0
   0     0 MASQUERADE  all  --  *      !lo     0.0.0.0/0            0.0.0.0/0
----

For example, if you see any entries in this chain, then you need to remove them.
You can remove the entries using this command:

[source,bash]
----
iptables -t nat -v -D POST_public_allow 1
----

Note that you will need to run that command for each line. So in the example
above, you would need to run it twice.

After you are done, you can run the previous command again and verify that
the output is now an empty list.

After making this change, restart your domains and the Coherence cluster
should now form correctly.

==== Make iptables Updates Permanent Across Reboots

The recommended way to make `iptables` updates permanent across reboots is
to create a `systemd` service that applies the necessary updates during
the startup process.

Here is an example; you may need to adjust this to suit your own
environment:

* Create a `systemd` service:

[source,bash]
----
echo 'Set up systemd service to fix iptables nat chain at each reboot (so Coherence will work)...'
mkdir -p /etc/systemd/system/
cat > /etc/systemd/system/fix-iptables.service << EOF
[Unit]
Description=Fix iptables
After=firewalld.service
After=docker.service

[Service]
ExecStart=/sbin/fix-iptables.sh

[Install]
WantedBy=multi-user.target
EOF
----

* Create the script to update `iptables`:

[source,bash]
----
cat > /sbin/fix-iptables.sh << EOF
#!/bin/bash
echo 'Fixing iptables rules for Coherence issue...'
TIMES=$((`iptables -t nat -v -L POST_public_allow -n --line-number | wc -l` - 2))
COUNTER=1
while [ $COUNTER -le $TIMES ]; do
  iptables -t nat -v -D POST_public_allow 1
  ((COUNTER++))
done
EOF
----

* Start the service (or just reboot):

[source,bash]
----
echo 'Start the systemd service to fix iptables nat chain...'
systemctl enable --now fix-iptables
----
