apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
  - bases/coherence-operator.clusterserviceversion.yaml
  - ../default
  - ../samples
  - ../scorecard

replacements:
  - source:
      kind: Deployment
      name: controller-manager
      fieldPath: spec.template.spec.containers.0.image
    targets:
      - select:
          kind: ClusterServiceVersion
        fieldPaths:
          - metadata.annotations.containerImage