name: Sync Trivy DB

on:
  workflow_dispatch:
env:
  IMAGE_NAME: ${{ github.repository_owner }}/trivy-db-act
  REGISTRY: ghcr.io

jobs:
  sync-trivy-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Packages Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy Trivy DB
        run: |
          oras cp ghcr.io/aquasecurity/trivy-db:2 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
