///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Application Deployment
:keywords: oracle coherence, kubernetes, operator, Application Deployment

== Coherence Application Deployment

[PILLARS]
====
[CARD]
.Packaging Applications
[link=app-deployment/020_packaging.adoc]
--
Adding application jars/config to a Coherence deployment.
--

[CARD]
.Using Application Roles
[link=app-deployment/030_roles.adoc]
--
Defining and using application roles.
--

[CARD]
.Persistence
[link=app-deployment/060_persistence.adoc]
--
Using Coherence Persistence.
--

[CARD]
.Rolling Upgrades
[link=app-deployment/090_rolling.adoc]
--
Changing an image version for Coherence or applications using rolling upgrade.
--

====
