///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Packaging Applications

Whilst it is simple to deploy a Coherence cluster into Kubernetes in most cases there is also a requirement to add
application code and configuration to the Coherence JVMs class path.

== Introduction

A common scenario for Coherence deployments is to include specific user artefacts such as cache and
operational configuration files as well as user classes.

This can be achieved with Coherence Operator by specifying the application configuration
in the `application` section of the spec or for an individual role.
The `image` field specifies a Docker image from which the configuration and classes
are copied and added to the JVM classpath at runtime.

The `libDir` and `configDir` are optional fields below `application` and are described below:

* `libDir` - contains application classes, default value is `/app/lib`

* `configDir`  - contains cache and operational configuration files, default value is `/app/conf`

The example yaml below instructs the Coherence Operator to attach a Docker image called `acme/orders-data:1.0.0`
at Pod startup and copy the artefacts in the `libDir` and `configDir` to the Pod and add
to the JVM classpath.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  application:
    image: acme/orders-data:1.0.0
----

Since we are using the default directories, we would expect that the Docker image referenced above
would include two directories `/app/lib` and `/app/conf` containing the appropriate files.

The following Dockerfile could be used to create such an image,
assuming the the directories `files/lib` and `files/conf` contain the files to copy.

[source,dockerfile]
----
FROM scratch
COPY files/lib/  /app/lib/
COPY files/conf/ /app/conf/
----

NOTE: Is is recommended to use the `scratch` image in the `FROM` clause to minimize the size of the resultant image.

See the <<clusters/070_applications.adoc,Coherence Applications>> section for
full details on each of the fields in the application section.

=== 1. Prerequisites

. Install the Coherence Operator
. Create any secrets required to pull Docker images
. Create a new `working directory` and change to that directory

==== 2. Create the Dockerfile

In your working directory directory create a file called `Dockerfile` with the following contents:

[source,dockerfile]
----
FROM scratch
COPY files/lib/  /app/lib/
COPY files/conf/ /app/conf/
----

==== 3. Add the required config files

[source,bash]
----
mkdir -p files/lib files/conf
----

Add the following content to a file in `/files/conf` called `storage-cache-config.xml`.

[source,xml]
----
<?xml version='1.0'?>
<cache-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://xmlns.oracle.com/coherence/coherence-cache-config"
              xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-cache-config coherence-cache-config.xsd">

  <caching-scheme-mapping>
    <cache-mapping>
      <cache-name>*</cache-name>
      <scheme-name>server</scheme-name>
    </cache-mapping>
  </caching-scheme-mapping>

  <caching-schemes>
    <distributed-scheme>
      <scheme-name>server</scheme-name>
      <service-name>ExamplePartitionedCache</service-name>
      <backing-map-scheme>
        <local-scheme>
          <high-units>{back-limit-bytes 0B}</high-units>
        </local-scheme>
      </backing-map-scheme>
      <autostart>true</autostart>
    </distributed-scheme>
  </caching-schemes>
</cache-config>
----


==== 4. Build the Docker image

In your `working directory`, issue the following:

[source,bash]
----
docker build -t packaging-example:1.0.0 .

Step 1/3 : FROM scratch
 --->
Step 2/3 : COPY files/lib/  /app/lib/
 ---> c91db5a34f5c
Step 3/3 : COPY files/conf/ /app/conf/
 ---> 7dd0b5f3e37a
Successfully built 7dd0b5f3e37a
Successfully tagged packaging-example:1.0.0
----

NOTE: In this example we have created but not populated the `lib` directory which would be used for application classes.

==== 5. Create the Coherence cluster yaml

Create the file `packaging-cluster.yaml` with the following contents.

[source,yaml]
----
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: packaging-cluster
spec:
  replicas: 3
  coherence:
    cacheConfig: storage-cache-config.xml
  application:
    image: packaging-example:1.0.0
----

NOTE: Add an `imagePullSecrets` entry if required to pull images from a private repository.

==== 6. Install the Coherence Cluster

Issue the following to install the cluster:

[source,bash]
----
kubectl create -n <namespace> -f packaging-cluster.yaml

coherencecluster.coherence.oracle.com/packaging-cluster created

kubectl -n <namespace> get pod -l coherenceCluster=packaging-cluster

NAME                          READY   STATUS    RESTARTS   AGE
packaging-cluster-storage-0   1/1     Running   0          58s
packaging-cluster-storage-1   1/1     Running   0          58s
packaging-cluster-storage-2   1/1     Running   0          58s
----

==== 7. Add Data to the Coherence Cluster via the Console

[source,bash]
----
kubectl exec -it -n <namespace> packaging-cluster-storage-0 bash /scripts/startCoherence.sh console
----

At the prompt, type `cache test` and you will notice the following indicating your
cache configuration file with the service name of `ExamplePartitionedCache` is being loaded.

[source,bash]
----
...
Cache Configuration: test
  SchemeName: server
  AutoStart: true
  ServiceName: ExamplePartitionedCache
..
----

==== 8. Uninstall the Coherence Cluster

[source,bash]
----
kubectl delete -n <namespace> -f packaging-cluster.yaml

coherencecluster.coherence.oracle.com "packaging-cluster" deleted
----